<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-24 06:19+0000
// PO revision date:  2013-03-23 23:19+0000
$lang = array(
	'email' => array(
		'email' => 'Érvénytelen email cím szerepel az email mezőben.',
		'exists' => 'Már létezik ezzel az email címmel regisztrált felhasználó.',
		'length' => 'Az email cím legalább 4 és legfeljebb 64 karakter hosszú lehet.',
		'required' => 'Az email mezőt kötelező kitölteni.',
	) ,
	'name' => array(
		'length' => 'A név mezőben legalább 3 és legfeljebb 100 karakter szerepelhet.',
		'required' => 'A név mező kitöltése kötelező.',
		'standard_text' => 'A felhasználónévben nem engedélyezett karakter szerepel.',
	) ,
	'current_password' => array(
		'length' => 'A jelszónak legalább 8 karakter hosszúnak kell lennie.',
		'login error' => 'Kérjük ellenőrizd, hogy a helyes email címet és jelszót adtad-e meg.',
		'matches' => 'Kérjük, ugyanazt a jelszót adja meg mindkét jelszó mezőben.',
		'required' => 'A jelszó mezőt kötelező kitölteni.',
		'alpha_dash' => 'A jelszó mezőben csak betűk, számok, # és @ jelek, aláhúzás jel és kötőjel szerepelhet.',
		'incorrect' => 'A megadott jelszó érvénytelen. Kérjük ismételd meg a jelszó beírását!',
	) ,
	'new_password' => array(
		'length' => 'A jelszónak legalább 8 karakter hosszúnak kell lennie.',
		'login error' => 'Kérjük ellenőrizd, hogy a helyes email címet és jelszót adtad-e meg.',
		'matches' => 'Kérjük, hogy ugyanazt a jelszót add meg mindkét jelszó mezőben.',
		'required' => 'A jelszó mező kitöltése kötelező.',
	) ,
	'password' => array(
		'length' => 'A jelszó minimum 5  és maximum 16 karakter hosszú lehet.',
		'matches' => 'Kérem, ugyanazt a jelszót adja meg mindkét mezőben.',
		'required' => 'A jelszó mezőt kötelező kitölteni.',
		'riverid' => '%s',
	) ,
	'password_confirm' => array(
		'matches' => 'A két jelszó mezőben megadott jelszónak egyeznie kell.',
	) ,
	'resetemail' => array(
		'email' => 'Érvénytelen e-mail címet adott meg?',
		'invalid' => 'A megadott email cím nem létezik a rendszerben.',
		'required' => 'Az e-mail mező kitöltése kötelező.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Érvénytelen formátumú felhasználótípus.',
		'length' => 'A felhasználó típusa mezőben legalább 5 és maximum 30 karakter szerepelhet.',
		'required' => 'Legalább egy felhasználói típust be kell állítani.',
		'values' => 'Kérjük, hogy válassz az ADMIN vagy a USER felhasználói típusok közül.',
	) ,
	'username' => array(
		'admin' => 'Az admin felhasználótípus nem változtatható meg.',
		'exists' => 'Ez a felhasználónév már foglalt.',
		'length' => 'A felhasználónév legalább 2, maximum 16 karakter hosszú lehet.',
		'required' => 'A felhasználónév mező kitöltése kötelező',
		'superadmin' => 'A szuper admin felhasználótípus módosítása nem lehetséges.',
	) ,
);
