<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-16 06:12+0000
// PO revision date:  2013-03-15 14:32+0000
$lang = array(
	'category_color' => array(
		'length' => 'A szín mező legalább 6 karakter hosszú kell hogy legyen.',
		'required' => 'A szín mező kitöltése szükséges.',
	) ,
	'category_description' => array(
		'required' => 'A leírás mező kitöltése szükséges.',
	) ,
	'category_image' => array(
		'size' => 'A képek feltöltési mérete 50kb-ra van korlátozva.',
		'type' => 'A kép meő nem tartalmaz megfelelő formátumú képet. Az elfogadott formátumok: JPG, PNG és GIF',
		'valid' => 'Az kép mező nem tartalmaz érvényes fájlt.',
	) ,
	'category_title' => array(
		'length' => 'A cím mező legalább 3 karakter kell tartalmazzon és nem lehet hosszabb 80 karakternél.',
		'required' => 'A cím mező kitöltése szükséges.',
	) ,
	'parent_id' => array(
		'already_parent' => 'Nem oszthat alkategóriákra egy kategáriót amely már rendelkezik alkategóriákkal.',
		'exists' => 'A szülő kategória nem létezik.',
		'numeric' => 'A szülő kategória mezőnek számnak kell lennie.',
		'parent_trusted' => 'A szülő kategória nem lehet speciális',
		'required' => 'A szülő kategória mező kitöltése szükséges.',
		'same' => 'A kategória és a szülő kategória nem lehet ugyanaz.',
		'special' => 'Speciális kategóriák nem oszthatók alkategóriákra.',
	) ,
);
