<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:32+0000
$lang = array(
	'error' => 'Adatbázis hiba: %s',
	'table_not_found' => 'A keresett mutató "%s" nem található az adatbázisban. Kérem, ellenőrizze, hogy az Ushahidi megfelelő verzióját használja-e az adatbázishoz',
);
