<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-13 04:56+0000
$lang = array(
	'layer_color' => array(
		'length' => 'A színezett mezőnek legalább 6 karaktert kell tartalmaznia.',
		'required' => 'A színezett mező kitöltése kötelező. ',
	) ,
	'layer_file' => array(
		'type' => 'A fájlmező nem tartalmaz érvényes fájlt. Lehetséges formátumok: .KMZ, .KML.',
		'valid' => 'A fájlmező nem tartalmaz érvényes fájlt.',
	) ,
	'layer_name' => array(
		'length' => 'A névmezőnek legalább 3 legfeljebb 80 karakter hosszúnak kell lennie.',
		'required' => 'A névmező kitöltése kötelező.',
	) ,
	'layer_url' => array(
		'atleast' => 'Vagy egy KML Url vagy egy fájl kötelező. ',
		'both' => 'Nem adhat meg egyszerre KML fájlt és Url-t.',
		'url' => 'Kérem, adjon meg egy érvényes URL-t. Például: http://www.ushahidi.com/layerl.kml',
	) ,
);
