<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-29 06:14+0000
// PO revision date:  2013-03-28 10:31+0000
$lang = array(
	'captcha' => array(
		'default' => 'Kérem, adjon meg érvényes biztonsági kódot.',
		'required' => 'Kérjük add meg a biztonsági kódot.',
	) ,
	'email' => array(
		'email' => 'Az Email mező nem tartalmaz érvényes email címet.',
		'length' => 'Az Email cím legalább 4 és legfeljebb 64 karakter hosszúságú lehet.',
		'required' => 'Az Email mező kitöltése kötelező, ha a jelölőnégyzetet bejelölte.',
	) ,
	'message' => array(
		'required' => 'A Leírás mező kitöltése kötelező.',
	) ,
	'name' => array(
		'length' => 'A Névnek legalább 3 karakter hosszúnak kell lennie.',
		'required' => 'A Név mező kitöltése kötelező.',
	) ,
	'phone' => array(
		'length' => 'A Telefonszám mező érvénytelen.',
	) ,
);
