<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-29 06:14+0000
// PO revision date:  2013-03-28 10:24+0000
$lang = array(
	'admin_footer' => 'Ezt az üzenetet a weboldaladról küldték.',
	'admin_login_url' => 'Adminisztrátor bejelentkezés',
	'admin_new_comment' => array(
		'message' => 'Új fejlemény érkezett a weboldaladra a következő bejelentéshez:',
		'subject' => 'Új fejlemény',
	) ,
	'admin_new_email' => array(
		'message' => 'Új email üzenet érkezett a weboldaladra.',
		'subject' => 'Új email üzenet',
	) ,
	'admin_new_report' => array(
		'message' => 'Új bejelentés érkezett a weboldaladra.',
		'subject' => 'Új bejelentés',
	) ,
	'admin_new_sms' => array(
		'message' => 'Új SMS üzenet érkezett a weboldaladra.',
		'subject' => 'Új SMS üzenet',
	) ,
	'member_new_alert' => array(
		'message' => 'Új riasztás érkezett',
		'subject' => 'Új riasztás!',
	) ,
	'member_new_message' => array(
		'message' => 'Új privát üzenetet kaptál',
		'subject' => 'Új privát üzenet',
		'footer' => 'Válaszoláshoz kérjük kattints ide:',
	) ,
);
