<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-14 06:14+0000
// PO revision date:  2013-04-13 06:14+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'A megjegyzések engedélyezése mezőben érvénytelen értéket adott meg.',
		'required' => 'A megjegyzések engedélyezése mezőt kötelező kitölteni.',
	) ,
	'allow_feed' => array(
		'between' => 'A tartalom mezőben érvénytelen értéket adott meg.',
		'required' => 'A tartalom mező kitöltése kötelező.',
	) ,
	'allow_reports' => array(
		'between' => 'A jelentések engedélyezése mezőben érvénytelen értéket adott meg.',
		'required' => 'A jelentések engedélyezése mezőt kötelező kitölteni.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'A statisztika megosztása mezőben érvénytelen értéket adott meg.',
		'required' => 'A statisztika megosztása mező kitöltése kötelező.',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Az Akismet mezőben érvénytelen értéket adott meg.',
		'length' => 'Az Akismet mezőben érvénytelen értéket adott meg.',
	) ,
	'cache_pages' => array(
		'between' => 'A cache oldalak mező kitöltése kötelez',
		'required' => 'A cache oldalak mező nem érvényes értéket tartalmaz?',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'A gyorsítótár élettartam mezője nem tartalmaz megfelelő értéket',
		'required' => 'A gyorsítótár élettartam mezőjének kitöltése kötelező',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'Úgy tűnik, az Ön szervere nincs beállítva arra, hogy a clean URL-eket kezelje. Meg kell változtatnia a szerver konfigurációját mielőtt engedélyezi a clean URL-eket. További információ arról, hogyan engedélyezze a clean URL-eket ebben <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">a fórum posztban</a> található (angolul).',
		'clean_url_enabled' => 'Ez az opció lehetővé teszi, hogy "clean" URL-ről lehessen elérni az Ushahidit, "index.php" kiterjesztés nélkül a honlapcímben.',
		'enable_clean_url' => 'Clean URL-ek engedélyezése',
		'title' => 'Clean URL-ek',
	) ,
	'clickatell_api' => array(
		'length' => 'A Clickatell API számának legalább 20 karakter hosszúnak kell lennie.',
		'required' => 'A Clickatell API szám megadása kötelező.',
	) ,
	'clickatell_password' => array(
		'length' => 'A Clickatell jelszavának legalább 5 és maximum 50 karakter hosszúnak kell lennie.',
		'required' => 'Clickatell jelszó megadása kötelező.',
	) ,
	'clickatell_username' => array(
		'length' => 'A Clickatell felhasználónév nem lehet hosszabb 50 karakternél.',
		'required' => 'Clickatell felhasználónév megadása kötelező.',
	) ,
	'configure_map' => 'Térkép beállítás',
	'default_location' => 'Alapértelmezett helyszín',
	'default_map_all' => array(
		'alpha_numeric' => 'A szín betöltés mezőben érvénytelen értéket adott meg.',
		'length' => 'A szín mező nem lehet 6 karakternél hosszabb.',
		'required' => 'A szín mező kitöltése kötelező.',
	) ,
	'default_map_view' => 'Alapértelmezett térképnézet',
	'default_zoom_level' => 'Nézet alapértelmezett magassága',
	'download_city_list' => 'Városnevek behúzása a Geonamesről.',
	'email_host' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'numeric' => 'A mail szerver port mezőben csak számok szerepelhetnek.',
	) ,
	'email_password' => array(
		'length' => 'A mail szerver jelszó legalább 5 és maximum 50 karakter hosszú lehet.',
		'required' => 'A mail szerverhez jelszó megadása kötelező.',
	) ,
	'email_port' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'numeric' => 'A mail szerver port mezőben csak számok szerepelhetnek.',
	) ,
	'email_servertype' => array(
		'length' => 'Az mail szerver port mezőben túl hosszú értéket adott meg.',
		'required' => 'Mail szerver típusa mező kitöltése kötelező.',
	) ,
	'email_username' => array(
		'length' => 'A mail szerverhez megadott felhasználónév nem lehet hosszabb 50 karakternél.',
		'required' => 'A mail szerver felhasználónevének megadása kötelező.',
	) ,
	'google_analytics' => array(
		'length' => 'A Google Analyticshez megadott értéknek érvényes Web Property azonosító számot kell tartalmaznia a következő formátumban: UA-XXXXX-XX.',
	) ,
	'items_per_page' => array(
		'required' => 'Az elemem per oldal (Frontend) mező kitöltése szükséges',
	) ,
	'items_per_page_admin' => array(
		'required' => 'Az elemem per oldal (Admin) mező kitöltése szükséges',
	) ,
	'map' => array(
		'zoom' => 'Zoom szint',
	) ,
	'map_provider' => array(
		'choose' => 'Válassz egy térkép szogálatatót',
		'enter_api' => 'Üsd be az API kulcsot',
		'get_api' => 'Szerezz egy API kulcsot',
		'name' => 'Térkép szolgáltató',
	) ,
	'map_settings' => 'Térkép beállításai',
	'select_default_location' => 'Válassz ki az országot',
	'set_location' => 'Klikelj és húzd térképet hogy a pontos helyszínt beállítsad',
	'site' => array(
		'allow_clustering' => 'Klaszter jelentések a térképen',
		'allow_comments' => 'Felhasználók megjegyzésének engedélyezése a felajánlásokhoz',
		'allow_feed' => 'Legyen RSS hírcsatorna a website-on',
		'allow_reports' => 'Felhasználók számára felajánlások beküldésének engedélyezése',
		'api_akismet' => 'Akismet kulcs',
		'cache_pages' => 'Oldal cache',
		'cache_pages_lifetime' => 'Oldal cache élettartama',
		'default_category_colors' => 'Alapszín az összes kategóriára',
		'display_contact_page' => 'A kapcsolati oldal megjelenítése',
		'display_howtohelp_page' => 'a "Segítség" oldal megjelenítése',
		'email_alerts' => 'Riasztás email címe',
		'email_notice' => '<span>hogy emailben értesítést kaphass a történtekről,kérlek állítsd be a postafiókodat.</span>',
		'email_site' => 'Az oldal kapcsolattartójának email címe',
		'google_analytics' => 'Google Analitics',
		'google_analytics_example' => 'Web Property ID - Formato: UA-XXXXX-XX',
		'items_per_page' => 'Elemek per oldal - Front end',
		'items_per_page_admin' => 'Elemek per oldal - Admin',
		'laconica_site' => 'Laconica oldal',
		'language' => 'Az oldal nyelve',
		'message' => 'Az oldal üzenet',
		'name' => 'Az oldal neve',
		'share_site_stats' => 'Statisztikák engedélyezése (a szerveren, ahol ez az oldal fut)',
		'tagline' => 'Oldal tagline-ja',
		'title' => 'Website beállításai',
		'twitter_configuration' => 'Twitter kereső kifejezések',
		'twitter_hashtags' => 'Hashtag-ek - vesszővel elválasztva',
	) ,
	'site_email' => array(
		'email' => 'Az oldal email címe nem éppen érvényes. Valamit elrontottál?',
		'length' => 'Az email cím legalább 4 karakter és rövidebb mint 100 karakter hosszú  legyen',
	) ,
	'site_name' => array(
		'length' => 'Ki kell tölteni a weboldal címe mezőt - legalább 3 karaktert írjál, de ne többet mint 50. ',
		'required' => 'Az oldal címe mező kitöltése kötelező.',
	) ,
	'site_tagline' => array(
		'length' => 'Ki kell tölteni a tagline mezőt - legalább 3 karaktert írjál, de ne többet mint 50. ',
		'required' => 'A tagline mező kitöltése kötelező',
	) ,
	'sms' => array(
		'clickatell_api' => 'A Clickatell API száma',
		'clickatell_check_balance' => 'Nézd meg a Clickatell egyenleged',
		'clickatell_load_balance' => 'Egyenleg betöltése',
		'clickatell_password' => 'A Clikatell jelszó',
		'clickatell_text_1' => 'Jelentkezz be a Clicatell szolgáltatásba úgy, hogy <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">ide kattintasz</a>',
		'clickatell_text_2' => 'Add meg a Clickatell hozzáférési adataidat',
		'clickatell_username' => 'A Clicatell felhasználói neved',
		'flsms_text_1' => 'Add meg a Frontline SMS-ben használatos telefonszámod(telefonszámaidat) a következő mezőkben',
		'option_1' => 'A Frontline SMS használata',
		'option_2' => 'Global SMS gateway használata',
		'title' => 'SMS beállítási opciók',
	) ,
	'sms_no1' => array(
		'numeric' => 'A telefon \'1\' mező csak számokat tartalmazhat.',
	) ,
	'sms_no2' => array(
		'length' => 'A telefon \'2\' mező túl hosszú.',
		'numeric' => 'A telefon \'2\' mező csak számokat tartalmazhat.',
	) ,
	'sms_no3' => array(
		'length' => 'A telefon \'3\' mező túl hosszú.',
		'numeric' => 'A telefon \'3\' mező csak számokat tartalmazhat.',
	) ,
);
