<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-20 06:24+0000
// PO revision date:  2013-11-19 16:10+0000
$lang = array(
	'email' => array(
		'email' => '正しいメールアドレス形式ではありません。',
		'exists' => 'このメールアドレスで、アカウントが存在します。',
		'length' => 'メールアドレスは最低4文字、最高64文字の長さでなければいけません。',
		'required' => 'メールアドレスは入力必須です。',
	) ,
	'name' => array(
		'length' => '氏名は最低3文字、最高100文字の長さでなければいけません。',
		'required' => '氏名は入力必須です。',
		'standard_text' => '氏名に許可されていない文字列が入っています。',
	) ,
	'current_password' => array(
		'matches' => '2つのパスワード行に同じパスワードを入力してください。',
		'required' => 'パスワードが必要です。',
		'alpha_dash' => 'パスワード行は、アルファベット文字、#と@、数字、アンダースコア、ダッシュ記号のみが使えます。',
	) ,
	'new_password' => array(
		'length' => 'パスワード行は、8文字以上が必須です。',
		'required' => 'パスワード行が必須です。',
	) ,
	'password' => array(
		'length' => 'パスワードは5文字以上、16文字以下です。',
		'matches' => '再度同じパスワードを入力してください。',
		'required' => 'パスワードは入力必須です。',
	) ,
	'password_confirm' => array(
		'matches' => 'パスワード確認は、パスワードと同じ物を入力してください。',
	) ,
	'resetemail' => array(
		'email' => '正しいメールアドレス形式ではありません。',
		'invalid' => '入力されたメールアドレスの登録がありません。',
		'required' => 'メールアドレスは入力必須です。',
	) ,
	'roles' => array(
		'alpha_numeric' => 'ルールの形式が不正です。',
		'length' => 'ルールは最低5文字以上、30文字以下でなければいけません。',
		'required' => '最低1つルールを定義する必要あります。',
		'values' => '管理者かユーザーのどちらかのルールを選択する必要があります。',
	) ,
	'username' => array(
		'admin' => '管理者ユーザーのルールは変更する事が出来ません。',
		'exists' => 'ユーザー名はすでに使われています。',
		'length' => 'ユーザー名は最低2文字、最高16文字までです。',
		'required' => 'ユーザー名は入力必須です。',
		'superadmin' => '特権管理者ルールは変更する事が出来ません。',
	) ,
);
