<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:26+0000
$lang = array(
	'captcha' => array(
		'default' => '有効なセキュリティコードを入力してください。',
		'required' => 'セキュリティコードを入力してください。',
	) ,
	'email' => array(
		'email' => '正しいメールアドレス形式ではありません。',
		'length' => 'メールアドレスは最低4文字、最高64文字の長さでなければいけません。',
		'required' => 'チェックボックスにチェックが入っている場合はメールアドレスが必須です。',
	) ,
	'error' => array(
		'required' => 'エラーは入力必須です。',
	) ,
	'subject' => array(
		'length' => 'タイトルは最低3文字以上でなければいけません。',
		'required' => 'タイトルは入力必須です。',
	) ,
	'yourname' => array(
		'length' => '名前は最低3文字以上でなければいけません。',
		'required' => '名前は入力必須です。',
	) ,
);
