<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:41+0000
$lang = array(
	'layer_color' => array(
		'length' => 'カラーフィールドは６文字でなければいけません。',
		'required' => 'カラーフィールドは必須項目です。',
	) ,
	'layer_file' => array(
		'type' => 'ファイル選択で、有効なファイルが選択されていません。有効な拡張子は.KMZ か .KML　のみです。',
		'valid' => 'ファイル選択で、有効なファイルが選択されていません。',
	) ,
	'layer_name' => array(
		'length' => '名前フィールドが、最低3文字以上、80文字以内でなければいけません。',
		'required' => '名前フィールドは必須項目です。',
	) ,
	'layer_url' => array(
		'atleast' => 'KMLのUriかファイルのどちらか必須です。',
		'both' => 'KMLファイルとurlの両方を保持する事は出来ません。',
		'url' => '有効なURLを入力してください。（例. http://www.ushahidi.com/layerl.kml',
	) ,
);
