<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => '有効なセキュリティーコードを入力してください。',
		'required' => 'セキュリティコードを入力してください。',
	) ,
	'email' => array(
		'email' => '有効なメールアドレス形式ではないようです。',
		'length' => 'メールアドレスは４文字以上、64文字以下でなければいけません。',
		'required' => 'チェックボックスにチェックが入っている場合は、メールアドレスは必須です。',
	) ,
	'message' => array(
		'required' => 'コメントは必須です。',
	) ,
	'name' => array(
		'length' => '名前は最低３文字以上でなければいけません。',
		'required' => '名前は必須です。',
	) ,
	'phone' => array(
		'length' => '電話番号が有効ではないようです。',
	) ,
);
