<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:49+0000
$lang = array(
	'latitude' => array(
		'between' => '緯度には正しい緯度が入力されていないようです。',
		'required' => '緯度は必須項目です。地図上でロケーションを選択してください。',
	) ,
	'level_id' => array(
		'numeric' => 'レポーターレベルには正しいレベル値が入っていないようです。',
		'required' => 'レポーターレベルには正しいレベル値が入っていないようです。',
	) ,
	'location_name' => array(
		'length' => 'ロケーション名は最低３文字、最高200文字以内でないといけません。',
		'required' => 'ロケーション名は必須です。',
	) ,
	'longitude' => array(
		'between' => '緯度フィールドに有効な緯度が入っていないようです。',
		'required' => '緯度は必須です。地図上でロケーションを選択してください。',
	) ,
	'reporter_id' => array(
		'numeric' => '無効なレポーターです。',
		'required' => '無効なレポーターです。',
	) ,
);
