<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-07 06:22+0000
// PO revision date:  2013-07-06 18:29+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'コメント許可フィールドに正しい値が入っていないようです。',
		'required' => 'コメント許可フィールドは必須です。',
	) ,
	'allow_feed' => array(
		'between' => 'フィードフィールドに正しい値が入ってないようです。',
		'required' => 'フィードは必須です。',
	) ,
	'allow_reports' => array(
		'between' => 'レポート許可フィールドには正しい値が入っていないようです。',
		'required' => 'レポート許可は必須です。',
	) ,
	'allow_stat_sharing' => array(
		'between' => '統計共有フィールドに正しい値が入っていないようです。',
		'required' => '統計共有は必須です。',
	) ,
	'api' => array(
		'default_record_limit' => 'API越しでレコードを取得するのではディフォルトで無効です。',
		'maximum_record_limit' => 'API越しでレコードを取得出来最大数',
		'maximum_requests_per_ip_address' => 'IPアドレス毎のAPIリクエストの最大数',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Akismetフィールドには正しい値が入ってないようです。',
		'length' => 'Akismetフィールドには正しい値が入ってないようです。',
	) ,
	'banner_image' => array(
		'size' => 'バナー画像の容量が250KB未満であることを確認して下さい。',
	) ,
	'cache_pages' => array(
		'between' => 'キャッシュページは入力必須です。',
		'required' => 'キャッシュページフィールドには正しい値が入ってないようです。',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'キャッシュページの有効期間フィールドには正しい値が入っていないようです。',
		'required' => 'キャッシュページ有効期間は入力必須です。',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'あなたのサーバーはクリーンURLを正しく扱えないようです。この機能を有効する前に、サーバの設定をする必要があります。<a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">このフォームの投稿</a>の詳細を確認してください。',
		'clean_url_enabled' => 'この設定はUshahidiは"index.php"ではなくクリーンURLでアクセス出来るようにします。',
		'enable_clean_url' => 'クリーンURLを有効にする',
		'title' => 'クリーンURL',
	) ,
	'clickatell_api' => array(
		'length' => 'ClickatellのAPI入力番号は20文字以下ではなければいけません。',
		'required' => 'ClickatellのAPI番号は入力必須です。',
	) ,
	'clickatell_password' => array(
		'length' => 'Clickatellパスワードは最低5文字、最大50文字以下の入力する必要があります。',
		'required' => 'Clickatellパスワードは入力必須です。',
	) ,
	'clickatell_username' => array(
		'length' => 'Clickatellのユーザー名は50文字以下でなければいけません。',
		'required' => 'Clickatellのユーザー名は入力必須です。',
	) ,
	'configure_map' => '地図を設定する',
	'default_location' => 'ディフォルトの位置',
	'default_map_all' => array(
		'alpha_numeric' => '色フィードに正しい値が入っていないようです。',
		'length' => '色は6文字以下でなければいけません。',
		'required' => '色は必須です。',
	) ,
	'default_map_view' => 'ディフォルトの地図の見え方',
	'default_zoom_level' => 'ディフォルトのズームのレベル',
	'download_city_list' => 'GeoNamesからの市町村の収集',
	'email_host' => array(
		'length' => 'メールサーバーのポート入力が長過ぎます。',
		'numeric' => 'メールサーバーのポートには数字のみ入力可能です。',
	) ,
	'email_password' => array(
		'length' => 'メールサーバーのパスワードは最少５文字、最大50文字以下でなければいけません。',
		'required' => 'メールサーバーのパスワードは入力必須です。',
	) ,
	'email_port' => array(
		'length' => 'メールサーバーのポートの入力されている値が長過ぎます。',
		'numeric' => 'メールサーバーのポート値は数字のみでなければいけません。',
	) ,
	'email_servertype' => array(
		'length' => 'メールサーバーのポートの入力されている値が長過ぎます。',
		'required' => 'メールサーバーのタイプは必須です。',
	) ,
	'email_username' => array(
		'length' => 'メールサーバーのユーザー名は最大50文字以下でなければいけません。',
		'required' => 'メールサーバのユーザー名は入力必須です。',
	) ,
	'google_analytics' => array(
		'length' => 'Google Analyticsは有効なUA-XXXXX-XXというフォーマットのウェブプロパティIDを入力する必要があります。',
	) ,
	'https' => array(
		'enable_https' => 'HTTPSを使用する',
		'title' => 'HTTPS',
	) ,
	'items_per_page' => array(
		'between' => '表側のページ毎に表示するアイテムのフィールドに正しい値が入っていないようです。',
		'required' => '表側のページ毎に表示するアイテムは入力必須です。',
	) ,
	'items_per_page_admin' => array(
		'between' => '管理側のページ毎に表示するアイテムのフィールドに正しい値が入っていないようです。',
		'required' => '管理側のページ毎に表示するアイテムは入力必須です。',
	) ,
	'map' => array(
		'default_location' => '地図提供者の設定をするのは簡単です。提供者を選択し、APIを取得し、入力するだけです。',
		'zoom' => 'ズームレベル',
	) ,
	'map_provider' => array(
		'choose' => '地図提供者を選択する',
		'enter_api' => 'APIキーを入力する',
		'get_api' => 'APIキーを取得する',
		'info' => '地図提供者の設定をするのは簡単です。提供者を選択し、APIを取得し、入力するだけです。',
		'name' => '地図提供者',
	) ,
	'map_settings' => '地図設定',
	'multiple_countries' => 'このUshahidiは、複数の国にまたがっていますか',
	'select_default_location' => 'デフォルトの国を選択してください。',
	'set_location' => '地図をクリック＆ドラッグして、正しい位置を選択してください。',
	'site' => array(
		'allow_clustering' => '地図上のレポートをひとまとめにする',
		'allow_comments' => 'レポートへのコメント投稿を許可',
		'allow_feed' => 'ウェブサイトのRSSニュースフィードを含める',
		'allow_reports' => 'レポート投稿を許可',
		'api_akismet' => 'Akismetキー',
		'cache_pages' => 'キャッシュページ',
		'cache_pages_lifetime' => 'キャッシュページの有効期間',
		'checkins' => 'チェックイン',
		'copyright_statement' => 'サイトの利用ライセンス',
		'default_category_colors' => 'すべてのカテゴリーのデフォルトの色',
		'delete_banner_image' => 'バナー画像を削除する',
		'display_contact_page' => 'コンタクトページを表示する',
		'display_howtohelp_page' => '"手助けする"ページを表示する',
		'email_alerts' => 'メールアドレスに通告する',
		'email_notice' => '<span>メールでレポートを受け取る場合は、メールアカウント設定をしてください。</span>',
		'email_site' => 'サイトのメールアドレス',
		'google_analytics_example' => 'ウェブプロパティID - フォマット: UA-XXXXX-XX',
		'items_per_page' => 'ページ毎のアイテム - 表側',
		'items_per_page_admin' => 'ページ毎のアイテム - 裏側',
		'kismet_notice' => '自動で<a href="http://akismet.com/" target="_blank">Akismet</a>を使ってスパムコメントを防いでください。<BR /><a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com ユーザーアカウント</a>に無償登録するとフリーのAPIキーを取得する事が出来ます。',
		'laconica_configuration' => 'Laconica証明書',
		'laconica_site' => 'Laconica サイト',
		'language' => 'サイト言語',
		'message' => 'サイトメッセージ',
		'name' => 'サイト名',
		'private_deployment' => 'プライベートサイト',
		'share_site_stats' => '統計を有効にする（Ushahidiサーバに蓄積されます）',
		'tagline' => 'サイトのタグライン',
		'timezone' => 'タイムゾーン',
		'title' => 'サイト設定',
		'twitter_configuration' => 'ツイッター収集タグ',
		'twitter_hashtags' => 'ハッシュタグ - カンマ区切りにしてください',
	) ,
	'site_email' => array(
		'email' => 'サイトのメールアドレスフィールドには正しい値が入っていないようです。',
		'length' => 'サイトのメールアドレスは最低4文字以上、最低100文字以下でなければいけません。',
	) ,
	'site_name' => array(
		'length' => 'サイト名は最低3文字、最大50文字以下でなければいけません。',
		'required' => 'サイト名は入力必須です。',
	) ,
	'site_tagline' => array(
		'length' => 'タグラインは最低3文字以上、最大100文字以下でなければいけません。',
		'required' => 'タグラインは入力必須です。',
	) ,
	'sms' => array(
		'clickatell_api' => 'ClickatellのAPI番号です',
		'clickatell_check_balance' => 'Clickatellのクレジットバランスを確認する',
		'clickatell_load_balance' => 'クレジットバランスを取り込む',
		'clickatell_password' => 'Clickatellパスワード',
		'clickatell_text_1' => '<a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">ここをクリックして</a>Clickatellサーバに登録する',
		'clickatell_text_2' => '以下にClickatellのアクセス情報を入力する',
		'clickatell_username' => 'Clickatellユーザー名',
		'flsms_description' => 'FrontlineSMSは、無料の、そしてオープンソースのソフトウェアです。FrontlineSMSを使用して、携帯電話で多くの人と文章のメッセージをやり取りすることができます。下にある四角形をクリックすると、FrontlineSMS.comから最新版をダウンロードします。',
		'flsms_download' => 'FrontlineSMSをダウンロードし、インストールする',
		'flsms_text_1' => '以下のフィールドにSMSにつながる電話番号を入力してください。',
		'flsms_text_2' => '+や-を入れないで番号を入力してください。',
		'option_1' => 'オプション1: SMSを使う',
		'option_2' => 'オプション2 : グローバルなSMSのゲートウェイを使う',
		'title' => 'SMS設定オプション',
	) ,
	'sms_no1' => array(
		'length' => '電話番号のフィールド１が正しい値が入力されてないようです。',
		'numeric' => '電話番号フィールド１は番号のみ入力可です。',
	) ,
	'sms_no2' => array(
		'length' => '電話番号フィールド２の値は長過ぎます。',
		'numeric' => '電話番号フィールド2は番号のみ入力可です。',
	) ,
	'sms_no3' => array(
		'length' => '電話番号フィールド3の値は長過ぎます。',
		'numeric' => '電話番号フィールド3は番号のみ入力可です。',
	) ,
	'twitter' => array(
		'title' => 'Twitterの設定',
	) ,
	'test_settings' => '設定を試す',
);
