<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-20 03:00+0000
$lang = array(
	'category_color' => array(
		'length' => '颜色值长度应是6个字符',
		'required' => '颜色是必填项',
	) ,
	'category_description' => array(
		'required' => '类别的描述是必填项',
	) ,
	'category_image' => array(
		'size' => '图片文件大小不能超过50K',
		'type' => '图片文件格式不正确，只能上传 .JPG, .PNG 和 .GIF',
		'valid' => '图片文件格式不正确',
	) ,
	'category_title' => array(
		'length' => '标题必须在3至80个字符之间',
		'required' => '标题是必填项',
	) ,
	'parent_id' => array(
		'already_parent' => '要创建的子类别已在父类别中存在',
		'exists' => '父类别不存在',
		'numeric' => '父类别必须是数字',
		'parent_trusted' => '父类别不能是一个有特殊性的类别',
		'required' => '父类别是必填项',
		'same' => '要创建的子类别不能与父类别相同',
		'special' => '有特殊性的类别不能创建子类别',
	) ,
);
