<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:49+0000
$lang = array(
	'latitude' => array(
		'between' => '纬度值无效',
		'required' => '纬度值为必填项。您可以点击地图确定地点',
	) ,
	'level_id' => array(
		'numeric' => '报告者等级无效',
		'required' => '报告者等级无效',
	) ,
	'location_name' => array(
		'length' => '地点名称长度必须在3到200个字符之间',
		'required' => '地点名为必填项',
	) ,
	'longitude' => array(
		'between' => '经度值无效',
		'required' => '经度值为必填项。您可以点击地图确定地点',
	) ,
	'reporter_id' => array(
		'numeric' => '无效的报告者',
		'required' => '无效的报告者',
	) ,
);
