<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:35+0000
// PO revision date:  2014-08-30 19:02+0000
$lang = array(
	'comments_form_error' => '错误！',
	'country_name' => array(
		'single_country' => '您报告的事件地点跨越了本网站部署的国家范围。请确保事件地点是在Uganda国家或地区范围内.',
	) ,
	'custom_field' => array(
		'values' => '请输入为“%s”字段的有效值。',
		'numeric' => '“% s”字段必须为数字。',
		'required' => '“% s”字段是必需的。',
		'not_exist' => '“%s”字段不存在。',
		'permission' => '通过你的账号不能编辑“%s”。',
		'email' => '“%s”字段必须包含一个有效的email地址。',
		'phone' => '“%s”必须包含一个有效的电话号码',
		'date_mmddyyyy' => '“%s”格式必须包含有效地的日期（月／日／年）。',
		'date_ddmmyyyy' => '“%s”格式必须包含有效地的日期（日／月／年）。',
	) ,
	'data_include' => array(
		'between' => '请选择一个有效的项目',
		'numeric' => '请选择一个有效的项目',
	) ,
	'data_active' => array(
		'between' => '请选择"等待核准"或"已核准"这两种状态的报告。',
		'numeric' => '请至少选择一个"等待核准"或"已核准"这两种状态的报告。',
		'required' => '请选择一个"等待核准"或"已核准"这两种状态的报告。',
	) ,
	'data_verified' => array(
		'between' => '请选择"等待验证"或"已验证”这两种状态的报告。',
		'numeric' => '请至少选择一个"等待验证"或"已验证”这两种状态的报告。',
		'required' => '请选择一个"等待验证"或"已验证”这两种状态的报告。',
	) ,
	'data_point' => array(
		'between' => '一个选择有效的事件报告类型进行下载',
		'numeric' => '一个选择有效的事件报告类型进行下载',
		'required' => '一个选择有效的事件报告类型进行下载',
	) ,
	'format' => array(
		'required' => '选择一个下载格式，是CSV或者XML格式。',
		'valid' => '请选择一个有效的格式去下载报告',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => '发件日期无效',
		'range' => '请选择有效的发件日期。不能晚于今天。',
	) ,
	'incident_active' => array(
		'between' => '请为“核准该事件报告”选择一个有效的值',
		'required' => '请为“核准该事件报告”选择一个有效的值',
	) ,
	'incident_ampm' => array(
		'validvalues' => '上午/下午格式不正确',
	) ,
	'incident_category' => array(
		'numeric' => '类别栏格式不正确',
		'required' => '类别为必填项',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => '日期格式不正确',
		'date_mmddyyyy' => '日期格式不正确',
		'required' => '日期为必填项',
	) ,
	'incident_description' => array(
		'required' => '描述为必填项',
	) ,
	'incident_hour' => array(
		'between' => '小时格式不正确',
		'required' => '小时为必填项',
	) ,
	'incident_information' => array(
		'alpha' => '请为“信息准确度”输入一个有效值',
		'length' => '请为“信息准确度”输入一个有效值',
	) ,
	'incident_minute' => array(
		'between' => '分钟格式不正确',
		'required' => '分钟为必填项',
	) ,
	'incident_news' => array(
		'url' => '新闻来源链接格式不正确',
	) ,
	'incident_photo' => array(
		'size' => '请确认您上传的照片大小不大于2MB',
		'type' => '上传照片格式无效。仅接受.JPG、.PNG和.GIF格式的图片',
		'valid' => '上传照片文件无效',
	) ,
	'incident_source' => array(
		'alpha' => '请为“来源可靠度”输入一个有效值',
		'length' => '请为“来源可靠度”输入一个有效值',
	) ,
	'incident_title' => array(
		'length' => '标题的长度须在3到200个字符之间',
		'required' => '标题栏为必填项',
		'csrf' => '可能的CSRF(跨站请求伪造)攻击。你真的要创建/编辑一份报告？',
	) ,
	'incident_verified' => array(
		'between' => '请为“验证此报告”输入一个有效值',
		'required' => '请为“验证此报告”输入一个有效值',
	) ,
	'incident_video' => array(
		'url' => '视频链接中包含无效的URL地址',
	) ,
	'latitude' => array(
		'between' => '纬度值格式错误',
		'required' => '纬度值为必填项。您可以点击地图确定地点',
	) ,
	'locale' => array(
		'alpha_dash' => '地点栏无效',
		'exists' => '此报告已有该语言的翻译版本',
		'length' => '地点格式错误',
		'locale' => '原始报告与翻译报告的语言相同',
		'required' => '语言为必填项',
	) ,
	'location_name' => array(
		'length' => '地点名称长度必须在3到200个字符之间',
		'required' => '地点名为必填项',
	) ,
	'longitude' => array(
		'between' => '经度值格式错误',
		'required' => '经度值为必填项。您可以点击地图确定地点',
	) ,
	'person_email' => array(
		'email' => '邮件地址格式不正确',
		'length' => '邮件地址长度须在4至64个字符之间',
	) ,
	'person_first' => array(
		'length' => '名字长度须在3到100个字符之间',
	) ,
	'person_last' => array(
		'length' => '姓长度须在3到100个字符之间',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => '收件日期格式错误',
		'range' => '请输入有效的收件日期，不得晚于今日',
		'range_greater' => '发送日期不得晚于收件日期',
	) ,
);
