<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-29 06:22+0000
// PO revision date:  2013-06-28 13:24+0000
$lang = array(
	'description' => array(
		'length' => '描述的长度须在3到100个字符之间',
		'required' => '描述为必填项',
	) ,
	'name' => array(
		'alpha_numeric' => '用户名中只能包含字母和数字',
		'length' => '用户名的长度应在3到80个字符之间',
		'nomodify' => '超级管理员角色不能被更改',
		'required' => '姓名为必填项',
	) ,
	'access_level' => array(
		'numeric' => '访问级别必须是0到100之间的数字.',
		'required' => '访问级别必须输入0到100之间的数字.',
	) ,
	'permissions' => array(
		'numeric' => '权限字段必须是0-100之间的数字。',
	) ,
);
