<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-20 03:02+0000
$lang = array(
	'date' => '进入时间',
	'date_added' => '增加日期',
	'last_access' => '最后接入',
	'sharing_color' => array(
		'length' => '颜色值长度应是6个字符',
		'required' => '颜色值为必填项',
	) ,
	'sharing_name' => array(
		'length' => '共享名称格式错误',
		'required' => '共享名称为必填项',
	) ,
	'sharing_url' => array(
		'exists' => '该网站链接已存在',
		'length' => '该网站链接无效',
		'required' => '网站链接为必填项',
		'url' => '网站链接中包含无效的 URL 地址',
	) ,
);
