<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-15 06:12+0000
$lang = array(
	'captcha' => array(
		'default' => 'Ве молиме внесете валиден сигурносен код.',
		'required' => 'Ве молиме внесете го сигурносниот код.',
	) ,
	'email' => array(
		'email' => 'Email полето не изгледа како да содржи валидна email адреса?',
		'length' => 'Email полето мора да биде најмалку 4 а не подолго 64 карактери.',
		'required' => 'Email полето е задолжително ако сте штиклирале.',
	) ,
	'message' => array(
		'required' => 'Полето со коментари е задолжително',
	) ,
	'name' => array(
		'length' => 'Името мора да е барем 3 карактери долго.',
		'required' => 'Полето со име е задолжително.',
	) ,
	'phone' => array(
		'length' => 'Полето за телефон не е валидно',
	) ,
);
