<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-27 16:31+0000
$lang = array(
	'reports_view' => 'Видете извештаи',
	'reports_edit' => 'Создадете/Променете/Избришете Извештаи',
	'reports_approve' => 'Одобри Извештаи',
	'reports_verify' => 'Потврди Извештаи',
	'reports_download' => 'Симни Извештаи',
	'reports_upload' => 'Внеси извештаи',
	'messages' => 'Менаџирај пораки',
	'stats' => 'Прикажи статистика',
	'settings' => 'Промени ги подесувањата',
);
