<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-03 14:16+0000
$lang = array(
	'captcha' => array(
		'default' => 'Por favor ingrese un código de seguridad válido',
		'required' => 'Por favor ingrese el código de seguridad',
		'valid' => 'Has introducido un código de seguridad incorrecto',
	) ,
	'comment_author' => array(
		'length' => 'El campo nombre debe tener al menos 3 caracteres de largo.',
		'required' => 'El campo nombre es obligatorio.',
	) ,
	'comment_description' => array(
		'required' => 'El campo comentarios es obligatorio.',
	) ,
	'comment_email' => array(
		'email' => 'El campo correo electrónico parece no tener una dirección de correo electrónico válida.',
		'length' => 'El campo correo electrónico debe tener al menos 4 y no más de 64 caracteres de largo.',
		'required' => 'El campo correo electrónico es obligatorio si el checkbox está marcado.',
	) ,
);
