<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-03 14:16+0000
$lang = array(
	'captcha' => array(
		'default' => 'Por favor ingrese un código de seguridad válido',
		'valid' => 'Por favor introduce un código de seguridad válido',
		'required' => 'Por favor ingrese el código de seguridad',
	) ,
	'contact_email' => array(
		'email' => 'El campo correo electrónico no contiene una dirección de correo electrónico válida.',
		'length' => 'El campo correo electrónico debe tener al menos 4 y no más de 64 caracteres de largo.',
		'required' => 'El campo correo electrónico es obligatorio si el checkbox está marcado.',
	) ,
	'contact_message' => array(
		'required' => 'El campo mensaje es obligatorio.',
	) ,
	'contact_name' => array(
		'length' => 'El campo nombre tiene que tener al menos 3 caracteres de largo.',
		'required' => 'El campo nombre es obligatorio.',
	) ,
	'contact_subject' => array(
		'length' => 'El campo asunto tiene que tener al menos 3 caracteres de largo.',
		'required' => 'El campo asunto es obligatorio.',
	) ,
	'email_send' => array(
		'failed' => 'Hubo un error al enviar tu mensaje',
	) ,
);
