<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-03 14:05+0000
$lang = array(
	'message' => 'Lo sentimos, estamos en mantenimiento. Por favor intenta de nuevo en algunos minutos. Gracias.',
);
