<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-03 14:09+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'El Parent ID debe ser numérico',
	) ,
	'private_to' => array(
		'required' => 'El campo "A:" es obligatorio',
		'exists' => 'El usuario al que deseas hacer el envío, no existe',
	) ,
	'private_subject' => array(
		'required' => 'El campo "Asunto" es obligatorio.',
		'length' => 'El Asunto debe tener entre 3 y 150 caracteres en total',
	) ,
	'private_message' => array(
		'required' => 'El campo "Mensaje" es obligatorio',
	) ,
);
