<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-09 06:25+0000
// PO revision date:  2013-08-08 23:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'Por favor ingrese un código de seguridad válido',
		'required' => 'Por favor ingrese el código de seguridad',
	) ,
	'email' => array(
		'email' => 'El campo correo electrónico no contiene una dirección de correo electrónico válida',
		'length' => 'El campo correo electrónico debe tener al menos 4 y no más de 64 caracteres de largo.',
		'required' => 'El campo correo electrónico es requerido si el checkbox está seleccionado.',
	) ,
	'error' => array(
		'required' => 'El campo error es obligatorio.',
	) ,
	'subject' => array(
		'length' => 'El campo asunto debe tener al menos 3 caracteres de largo.',
		'required' => 'El campo asunto es obligatorio.',
	) ,
	'yourname' => array(
		'length' => 'El campo nombre debe tener al menos 3 caracteres de largo.',
		'required' => 'El campo nombre es obligatorio.',
	) ,
);
