<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-09 06:25+0000
// PO revision date:  2013-08-09 02:19+0000
$lang = array(
	'config' => 'archivo de configuración',
	'controller' => 'controlador (controller)',
	'driver' => 'controlador (driver)',
	'driver_implements' => 'El driver %s para la biblioteca %s debe implementar la interfaz %s',
	'driver_not_found' => 'El driver %s para la biblioteca %s no puede ser encontrado',
	'errors_disabled' => 'Puede ir a la <a href="%s">página principal</a> o <a href="%s">intentar de nuevo</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'No es posible completar este pedido',
	'helper' => 'ayudante (helper)',
	'invalid_filetype' => 'El tipo de archivo solicitado, .%s, no está permitido por el archivo de configuración',
	'invalid_method' => 'Método inválido %s llamado en %s',
	'invalid_property' => 'La propiedad %s no existe en la clase %s.',
	'library' => 'biblioteca (library)',
	'log_dir_unwritable' => 'El directorio de log no se puede escribir: %s ',
	'model' => 'modelo',
	'no_controller' => 'Ushahidi no pudo encontrar un controlador para ejecutar este pedido: %s',
	'no_default_route' => 'Por favor seleccione una ruta predeterminada en config/routes.php',
	'page_not_found' => 'La página solicitada, %s, no fue encontrada.',
	'report_bug' => '<a href="%s" id="show_bugs">Reporte esto a Ushahidi</a>',
	'resource_not_found' => 'El %s solicitado, %s, no fue encontrado',
	'stack_trace' => 'Stack Trace',
	'stats_footer' => 'Cargado en {execution_time} segundos, utilizando {memory_usage} de memoria. Generado por Ushahidi v%s.',
	'text_direction' => 'izquierda-a-derecha',
	'there_can_be_only_one' => 'Sólo puede haber una instancia de Ushahidi por cada pedido de página',
	'uncaught_exception' => 'Excepción no atrapada %s: %s en el archivo %s en la línea %s',
	'view' => 'vista (view)',
	'view_set_filename' => 'Debe seleccionar el archivo de vistas antes de llamar al render',
);
