<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-10 06:26+0000
// PO revision date:  2013-08-09 21:21+0000
$lang = array(
	'imap_stream_not_opened' => 'No se pudo abrir el stream IMAP',
	'unsupported_service' => 'El servicio de correo electrónico no está soportado',
);
