<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-10 06:26+0000
// PO revision date:  2013-08-09 21:54+0000
$lang = array(
	'layer_color' => array(
		'length' => 'El campo color debe tener al menos 6 caracteres de largo.',
		'required' => 'El campo color es obligatorio.',
	) ,
	'layer_file' => array(
		'type' => 'El campo Archivo parece no contener un archivo válido. Los únicos formatos aceptados son .KMZ y .KML',
		'valid' => 'El campo Archivo parece no contener un archivo válido',
	) ,
	'layer_name' => array(
		'length' => 'El nombre del campo debe tener por lo menos 3 y no mas de 80 caracteres de largo.',
		'required' => 'El campo nombre es obligatorio.',
	) ,
	'layer_url' => array(
		'atleast' => 'Se requiere un archivo o un URL de un KML',
		'both' => 'No se puede especificar un URL y un archivo KML. Utilice solamente uno.',
		'url' => 'Por favor ingrese una URL válida. Ej: http://www.ushahidi.com/layerl.kml',
	) ,
);
