<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-10 06:26+0000
// PO revision date:  2013-08-10 02:27+0000
$lang = array(
	'akismet_cannot_connect' => 'No es posible conectarse al servidor de Akismet',
	'akismet_cannot_retrieve' => 'No es posible recibir una respuesta de Akismet',
	'api_library_not_found' => 'El API: <strong>%s</strong> para la clase <strong>%s</strong> no se encuentra. Verifique la tabla de ruteo del API.',
	'askimet_invalid_apikey' => 'La llave API de Akismet no es válida',
	'clickatell_fopen_error' => 'Error intentando realizar un fopen al enviar.<br>Verifique que PHP soporta OpenSSL y que la versión de PHP es mayor a 5.2',
	'clickatell_message_too_long' => 'El mensaje es demasiado largo. (Largo actual=',
	'clickatell_no_destination_address' => 'Debe especificar una dirección de destino (A)',
	'clickatell_no_sender_address' => 'Debe especificar una dirección de origen (DE)',
	'clickatell_unicode_message_too_long' => 'El mensaje en Unicode es demasiado largo. (Largo actual=',
	'clickatell_unsupported_method' => 'Método de envío no soportado',
	'invalid_api_library' => 'La librería de API %s no es válida. Todas las librerías de API deben ser subclases de %s',
	'upgrade_directory_not_deleted' => 'El directorio <code>%s</code> no puede ser borrado',
	'upgrade_extracting_error' => 'Error cuando se extraía: <code>%s</code>',
	'upgrade_failed' => 'La descarga de la última versión de Ushahidi falló. Código HTTP',
	'upgrade_file_not_copied' => 'El archivo <code>%s</code> no puede ser copiado',
	'upgrade_file_not_deleted' => 'El archivo <code>%s</code> no puede ser borrado',
	'upgrade_title' => 'Programa para la actualización de Ushahidi',
	'upgrade_zip_error' => 'El archivo comprimido descargado <code>%s</code>, no puede ser escrito',
	'riverid_variable_not_available' => '%s no está disponible en la clase RiverID.',
);
