<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-11 06:25+0000
// PO revision date:  2013-08-11 00:10+0000
$lang = array(
	'admin_footer' => 'Este mensaje ha sido enviado desde su página web.',
	'admin_login_url' => 'Acceso Administrador',
	'admin_new_comment' => array(
		'message' => 'Un nuevo comentario ha sido publicado en su página web en respuesta a: ',
		'subject' => 'Nuevo Comentario',
	) ,
	'admin_new_email' => array(
		'message' => 'Un nuevo correo ha sido publicado en su página web',
		'subject' => 'Nuevo mensaje de correo',
	) ,
	'admin_new_report' => array(
		'message' => 'Su sitio ha recibido un nuevo reporte',
		'subject' => 'Nuevo reporte',
	) ,
	'admin_new_sms' => array(
		'message' => 'Un nuevo mensaje de texto ha sido publicado en su página web',
		'subject' => 'Nuevo mensaje de texto',
	) ,
	'member_new_alert' => array(
		'message' => 'Ha recibido una alerta.',
		'subject' => 'Nueva alerta',
	) ,
	'member_new_message' => array(
		'message' => 'Ha recibido un mensaje privado',
		'subject' => 'Nuevo mensaje privado',
		'footer' => 'Para responder diríjase a: ',
	) ,
);
