<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-03 16:09+0000
$lang = array(
	'reports_view' => 'Ver reportes',
	'reports_edit' => 'Crear/Editar/Borrar reportes',
	'reports_approve' => 'Aprobar reportes',
	'reports_verify' => 'Verificar Reportes',
	'reports_comments' => 'Administrar comentario y reportes',
	'reports_download' => 'Descargar reportes',
	'reports_upload' => 'Subir reportes',
	'messages' => 'Administrar mensajes',
	'messages_reporters' => 'Administrar informantes',
	'stats' => 'Ver estadísticas',
	'settings' => 'Modificar configuración',
	'manage' => 'Administrar panel',
	'users' => 'Administrar usuarios',
	'manage_roles' => 'Administrar roles',
	'checkin' => 'Ver verificaciones',
	'checkin_admin' => 'Administrar verificaciones',
	'admin_ui' => 'Acceso administración',
	'member_ui' => 'Acceso a miembros',
	'delete_all_reports' => 'Eliminar todos los reportes',
);
