<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-11 06:25+0000
// PO revision date:  2013-08-11 00:00+0000
$lang = array(
	'date' => 'Fecha de ingreso',
	'date_added' => 'Agregado el',
	'last_access' => 'Último acceso',
	'sharing_color' => array(
		'length' => 'El campo color debe tener 6 caracteres de largo.',
		'required' => 'El campo color es obligatorio.',
	) ,
	'sharing_name' => array(
		'length' => 'El nombre para Compartir no parece ser válido.',
		'required' => 'Un nombre para Compartir es requerido.',
	) ,
	'sharing_url' => array(
		'exists' => 'La dirección URL del sitio ya existe',
		'length' => 'El sitio URL parace no ser válido',
		'required' => 'Dirección URL del sitio es obligatoria',
		'url' => 'El campo URL parece no contener una URL valida ',
	) ,
);
