<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-19 06:15+0000
// PO revision date:  2013-04-18 21:10+0000
$lang = array(
	'config' => 'קובץ הגדרות',
	'controller' => 'בקר (controller)',
	'driver' => 'דרייבר (driver)',
	'driver_implements' => 'יש ליישם את הדרייבר %s עבור הספרייה %s באמצעות הממשק %s',
	'driver_not_found' => 'לא הצלחתי למצוא את הדרייבר %s, עבור הספרייה %s',
	'errors_disabled' => 'באפשרותך לגשת <a href="%s">לדף הבית</a> או <a href="%s">לנסות שוב</a>.',
	'generic_error' => 'לא הצלחתי להשלים את הבקשה',
	'helper' => 'סייען',
	'invalid_filetype' => 'סוג הקובץ המבוקש, .%s, אינו מאושר בקובץ צפיית ההגדרות שלך (view configuration file)',
	'invalid_method' => 'שיטה לא תקינה %s נקראה ב- %s',
	'invalid_property' => 'התכונה (property) %s איננה קיימת במחלקה (class) %s.',
	'library' => 'ספרייה',
	'log_dir_unwritable' => 'לא ניתן לכתוב לתיקיית הלוג (log): %s',
	'model' => 'מודל',
	'no_controller' => 'אושהידי לא הצליח לקבוע מהו הבקר (controller) לצורך ביצוע הבקשה: %s',
	'no_default_route' => 'אנא הגדר נתיב ברירת מחדל ב config/routes.php',
	'page_not_found' => 'הדף שביקשת, %s, לא נמצא.',
	'report_bug' => '<a href="%s" id="show_bugs">דווח על השגיאה הזו לאושהידי</a>',
	'resource_not_found' => 'הבקשה %s, %s, לא אותרה',
	'stats_footer' => 'נטען ב {execution_time} שניות, באמצעות {memory_usage} של זכרון. נוצר על ידי אושהידי v%s.',
	'text_direction' => 'rtl',
	'there_can_be_only_one' => 'יכול להיות רק הרצה אחת של אושהידי לכל בקשת עמוד',
	'uncaught_exception' => 'לא תפסתי %s: %s בקובץ %s בשורה %s',
	'view' => 'צפייה',
	'view_set_filename' => 'עליך להגדיר את קובץ הצפייה (view filename) לפני שקוראים למריץ (render)',
);
