<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:42+0000
$lang = array(
	'akismet_cannot_connect' => 'החיבור לשרת akismet נכשל',
	'akismet_cannot_retrieve' => 'לא ניתן לאחזר תשובה משרת Akismet',
	'api_library_not_found' => 'ספרית ה-API: <strong>%s</strong>, עבור ה-class <strong>%s</strong> לא נמצאה. יש לבדוק את טבלת ניתוב משימות ה-API.',
	'askimet_invalid_apikey' => 'מפתח ה-API עבור Akismet אינו תקין.',
	'clickatell_fopen_error' => 'שגיאה בעת ביצוע fopen sending method! <br> אנא בדוק האם ל- PHP יש תמיכה ב- OpenSSL כמו כן וודא שגירסת ה- PHP אשר מותקנת בשרת היא מעל 5.2',
	'clickatell_message_too_long' => 'הודעה ה- unicode שלך ארוכה מדי! (אורך נוכחי =',
	'clickatell_no_destination_address' => 'אנא ציין את כתובת היעד אל (TO)!',
	'clickatell_no_sender_address' => 'אנא ציין את כתובת המען (FROM)!',
	'clickatell_unicode_message_too_long' => 'הודעה ה- unicode שלך ארוכה מדי! (אורך נוכחי =',
	'clickatell_unsupported_method' => 'שיטת משלוח אשר איננה נתמכת!',
	'invalid_api_library' => 'ספריית ה- API %s איננה תקפה. כל ספריות ה- API צריכות להיות תת מחלקות (subclasses) של %s',
	'upgrade_directory_not_deleted' => 'לא הצלחתי למחוק את התיקייה <code>%s</coded>',
	'upgrade_extracting_error' => 'שגיאה התרחשה בזמן החילוץ מכיווץ של: <code>%s</code>',
	'upgrade_failed' => 'ההורדה של הגירסה הכי עדכנית של אושהידי כשלה. HTTP status code',
	'upgrade_file_not_copied' => 'לא הצלחתי להעתיק את הקובץ <code>%s</coded>',
	'upgrade_file_not_deleted' => 'לא הצלחתי למחוק את הקובץ <code>%s</coded>',
	'upgrade_title' => 'סקריפט עידכון לאושהידי',
	'upgrade_zip_error' => 'קובץ הזיפ של אושהידי, <code>%s</code>, חסום לכתיבה',
);
