<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:44+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'נא להזין קוד אבטחה בתוקף.',
		'required' => 'נא להזין קוד אבטחה.',
	) ,
	'contact_email' => array(
		'email' => 'שדה האימייל אינו מכיל כתובת אימייל תקינה',
		'required' => 'נא להזין כתובת אימייל',
	) ,
	'contact_message' => array(
		'required' => 'שדה ההודעה הינו שדה חובה.',
	) ,
	'contact_subject' => array(
		'length' => 'שדה הנושא חייב להכיל 3 תווים לפחות.',
		'required' => 'שדה הנושא הינו שדה חובה.',
	) ,
);
