<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-14 06:14+0000
// PO revision date:  2013-04-13 06:14+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'האם השדה להפעלת תגובות מכיל ערך תקין?',
		'required' => 'השדה להפעלת תגובות הוא הכרחי.',
	) ,
	'allow_feed' => array(
		'between' => 'האם השדה שמאפשר לכלול פיד מכיל ערך תקין?',
		'required' => 'השדה שמאפשר לכלול פיד הוא הכרחי.',
	) ,
	'allow_reports' => array(
		'between' => 'האם השדה שמאפשר לכלול דיווחים מכיל ערך תקין?',
		'required' => 'השדה שמאפשר לכלול דיווחים הוא הכרחי.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'האם השדה שמאפשר שיתוף סטטיסטיקות מכיל ערך תקין?',
		'required' => 'השדה שמאפשר שיתוף סטטיסטיקות הוא הכרחי.',
	) ,
	'api' => array(
		'default_record_limit' => 'ברירת מחדל למספר הרשומות אשר ישלפו פר בקשת API',
		'maximum_record_limit' => 'המספר המקסימלי של רשומות אשר ישלפו פר בקשת API',
		'maximum_requests_per_ip_address' => 'מספר מקסימלי של בקשות API לכל כתובת IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'האם שדה האקיזמט (Akismet) מכיל ערך תקין?',
		'length' => 'האם שדה האקיזמט (Akismet) מכיל ערך תקין?',
	) ,
	'cache_pages' => array(
		'between' => 'השדה של מטמון (cache) העמוד הוא חובה.',
		'required' => 'האם השדה של מטמון (cache) העמוד מכיל ערך תקין?',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'האם השדה של משך זמן מטמון (cache) העמוד מכיל ערך תקין?',
		'required' => 'השדה של משך זמן מטמון (cache) העמוד הוא חובה.',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'עושה רושם שהשרת שלך איננו מוגדר באופן שמאפשר לו להגיש קישורים נקיים.  יהיה עליך להגדיר את השרת שלך על מנת לאפשר אופציה זו.  עקוב אחר <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">ההוראות בקישור המצורף </a>על מנת לתקן את הבעיה.',
		'clean_url_enabled' => 'האופציה הזו מפעילה קישורים "נקיים" באושהידי. כלומר ללא "index.php" בכתובת האתר.',
		'enable_clean_url' => 'אפשר קישורים נקיים',
		'title' => 'קישורים נקיים',
	) ,
	'clickatell_api' => array(
		'length' => 'על שדה מספר ה-Clickatell API להיות באורך של עד 20 תווים בדיוק.',
		'required' => 'שדה מספר ה-Clickatell API הוא חובה.',
	) ,
	'clickatell_password' => array(
		'length' => 'על שדה סיסמאת ה-Clickatell להיות באורך של 5 עד 50 תווים בדיוק.',
		'required' => 'שדה סיסמאת ה-Clickatell הוא חובה.',
	) ,
	'clickatell_username' => array(
		'length' => 'על שדה שם משתמש ה Clickatell להיות באורך של עד 50 תווים בדיוק.',
		'required' => 'שדה שם משתמש ה-Clickatell הוא חובה.',
	) ,
	'configure_map' => 'הגדר מפה',
	'default_location' => 'מיקום ברירת מחדל',
	'default_map_all' => array(
		'alpha_numeric' => 'האם שדה צבע הפיד מכיל ערך תקין?',
		'length' => 'על שדה הצבע להיות באורך של עד 6 תווים בדיוק.',
		'required' => 'שדה הצבע הוא חובה.',
	) ,
	'default_map_view' => 'ברירת מחדל לתצוגת המפה',
	'default_zoom_level' => 'ברירת מחדל למידת ההגדלה',
	'download_city_list' => 'אחזר ערים מגאו-שמות (Geonames)',
	'email_host' => array(
		'length' => 'שדה הפורט (port) של שרת האימייל ארוך מידי',
		'numeric' => 'על שדה הפורט (port) של שרת האימייל להכיל מספרים בלבד.',
	) ,
	'email_password' => array(
		'length' => 'על שדה סיסמאת שרת הדואר להיות באורך של בין 5 ל- 50 תווים בדיוק.',
		'required' => 'שדה סיסמאת שרת הדואר הוא חובה.',
	) ,
	'email_port' => array(
		'length' => 'שדה הפורט (port) של שרת האימייל ארוך מידי',
		'numeric' => 'על שדה הפורט (port) של שרת האימייל להכיל מספרים בלבד.',
	) ,
	'email_servertype' => array(
		'length' => 'שדה הפורט (port) של שרת האימייל ארוך מידי',
	) ,
	'email_username' => array(
		'length' => 'על שדה שם המשתמש של שרת הדואר להיות באורך של עד 50 תווים בדיוק.',
		'required' => 'שדה שם המשתמש של שרת הדואר הוא חובה.',
	) ,
	'facebook' => array(
		'title' => 'הגדרת אפשרויות הפייסבוק',
		'description' => 'על מנת להשיג את המידע שיש למלא למטה, ראשית יהיה עליך ליצור אפליקציית פייסבוק ב',
	) ,
	'google_analytics' => array(
		'length' => 'חובה על שדה הגוגל אנליטיקס להכיל מספר זיהוי (Web Property ID) מהצורה UA-XXXXX-XX.',
	) ,
	'https' => array(
		'enable_https' => 'הפעל HTTPS',
		'https_disabled' => 'האופציה הזו מאפשרת לגשת לאושהידי באופן לא מאובטח; כלומר <strong>ללא</strong> "https://" בקידומת לכתובת האתר',
		'https_enabled' => 'האופציה הזו מאפשרת לגשת לאושהידי באופן מאובטח; כלומר עם <strong>"https://"</strong> בקידומת לכתובת האתר',
	) ,
	'items_per_page' => array(
		'between' => 'האם השדה של מספר הפריטים פר עמוד (עמוד ראשי) מכיל ערך תקין?',
		'required' => 'השדה של מספר הפריטים פר עמוד (עמוד ראשי) הוא חובה.',
	) ,
	'items_per_page_admin' => array(
		'between' => 'האם השדה של מספר הפריטים פר עמוד (עמוד ניהול) מכיל ערך תקין?',
		'required' => 'השדה של מספר הפריטים פר עמוד (עמוד ניהול) הוא חובה.',
	) ,
	'map' => array(
		'default_location' => 'הגדרת ספק המפות עבור האתר הוא תהליך פשוט. בחר את הספק, השג את מפתח ה API מאתר הספק, והכנס את מפתח ה API',
		'zoom' => 'מידת ההגדלה',
	) ,
	'map_provider' => array(
		'choose' => 'בחר ספק מפות',
		'enter_api' => 'הכנס את מפתח ה- API החדש',
		'get_api' => 'השג מפתח API',
		'info' => 'הגדרת ספק המפות עבור האתר הוא תהליך פשוט. בחר את הספק, השג את מפתח ה API מאתר הספק, והכנס את מפתח ה API',
		'name' => 'ספק המפות',
	) ,
	'map_settings' => 'הגדרות המפה',
	'multiple_countries' => 'האם התקנת האושהידי מתייחסת למספר ארצות',
	'select_default_location' => 'בחר ארץ ברירת מחדל',
	'set_location' => 'הקלק וגרור את המפה כדי לבחור את מיקומך המדוייק',
	'site' => array(
		'allow_clustering' => 'דיווחי אשכולות על המפה',
		'allow_comments' => 'אפשר למשתמש להשאיר תגובות לדיווחים',
		'allow_feed' => 'כלול פיד רסס חדשות (news RSS feed) באתר',
		'allow_reports' => 'אפשר למשתמשים לשלוח דיווחים',
		'api_akismet' => 'מפתח אקיזמט (Akismet)',
		'banner' => 'באנר האתר',
		'blocks_per_row' => 'בלוקים לכל שורה',
		'cache_pages' => 'שמור מטמון עבור עמודים',
		'checkins' => 'צ\'ק-אינים',
		'copyright_statement' => 'הצהרת זכויות היוצרים של האתר',
		'default_category_colors' => 'צבע ברירת המחדל לכל הקטגוריות',
		'delete_banner_image' => 'מחק את תמונת הבאנר של האתר',
		'display_contact_page' => 'הצג עמוד יצירת קשר',
		'display_howtohelp_page' => 'הצג עמוד "כיצד לעזור"',
		'email_alerts' => 'התראות כתובות אימייל',
		'email_notice' => '<span>על מנת לקבל דיווחים דרך האימייל, אנא הגדר את הגדרות חשבון האימייל שלך.</span>',
		'email_site' => 'כתובת האימייל של האתר',
		'google_analytics' => 'גוגל אנליטיקס',
		'google_analytics_example' => 'Web Property ID - פורמט: UA-XXXXX-XX',
		'items_per_page' => 'פריטים לכל עמוד - עמוד ראשי',
		'items_per_page_admin' => 'פריטים לכל עמוד - ממשק הניהול',
		'kismet_notice' => 'מנע תגובות ספאם באמצות שימוש באקיזמט (<a href="http://akismet.com/" target="_blank">Akismet</a> from Automattic). <BR />באפשרותך להשיג מפתח API בחינם על ידי רישום <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com לחשבון משתמש ב-</a>',
		'language' => 'שפת האתר',
		'message' => 'הודעת האתר',
		'name' => 'שם האתר',
		'private_deployment' => 'פריסת אתר פרטית',
		'submit_report_message' => 'הודעת שליחת דיווח',
		'share_site_stats' => 'הפעל סטטיסטיקות (מאוכסנות בשרת של אושהידי)',
		'tagline' => 'כותרת משנה לאתר',
		'timezone' => 'איזור זמן',
		'title' => 'הגדרות האתר',
		'twitter_configuration' => 'מונחי חיפוש בטוויטר',
		'twitter_hashtags' => 'האשתגים (Hashtags) - מופרדים באמצעות פסיקים ',
	) ,
	'site_email' => array(
		'email' => 'האם שדה האימייל של האתר מכיל ערך תקין?',
		'length' => 'על שדה האימייל של האתר להיות באורך של 4 עד 100 תווים בדיוק.',
	) ,
	'site_name' => array(
		'length' => 'על שדה שם האתר להיות באורך של 3 עד 50 תווים בדיוק.',
		'required' => 'שדה שם האתר הוא חובה.',
	) ,
	'site_tagline' => array(
		'length' => 'על שדה כותרת המשנה של האתר להיות באורך של 3 עד 100 תווים בדיוק.',
		'required' => 'שדה כותרת המשנה היא חובה.',
	) ,
	'sms' => array(
		'clickatell_api' => 'מספר ה Clickatell API שלך',
		'clickatell_check_balance' => 'בדוק את מאזן הקרדיט שלך ב Clickatell',
		'clickatell_load_balance' => 'העלה מאזן קרדיט',
		'clickatell_password' => 'סיסמאת ה Clickatell שלך',
		'clickatell_text_1' => 'הירשם לשירות ה Clickatells על ידי <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">לחיצה כאן</a>',
		'clickatell_text_2' => 'הכנס את פרטי הגישה שלך של Clickatell למטה',
		'clickatell_username' => 'שם המשתמש שלך ב Clickatell',
		'flsms_text_1' => 'הכנס מספר(י) טלפון אשר מחוברים עם Frontline SMS בשדה(ות) למטה',
		'flsms_text_2' => 'הכנס את המספר ללא אף סימני פלוסים או מקפים (+/-)',
		'option_1' => 'אופציה 1: השתמש ב Frontline SMS',
		'option_2' => 'אופציה 2: השתמש ב Global SMS Gateway',
		'title' => 'אפשרויות הגדרת SMS',
	) ,
	'sms_no1' => array(
		'length' => 'השדה טלפון 1 ארוך מידי',
		'numeric' => 'על השדה טלפון 1 להכיל מספרים בלבד.',
	) ,
	'sms_no2' => array(
		'length' => 'השדה טלפון 2 ארוך מידי',
		'numeric' => 'על השדה טלפון 2 להכיל מספרים בלבד.',
	) ,
	'sms_no3' => array(
		'length' => 'השדה טלפון 3 ארוך מידי',
		'numeric' => 'על השדה טלפון 3 להכיל מספרים בלבד.',
	) ,
);
