<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:53+0000
$lang = array(
	'approved' => 'מאושר',
	'categories' => 'קטגויות',
	'category_impact' => 'דיווחי קטגוריות לאורך זמן',
	'category_impact_description' => 'בתרשים זה מוצגת כמות הדיווחים לכל קטגוריה לאורך הזמן. יש לגלול משמאל לימין כדי לראות תצוגה השוואתית של הקטגוריות השונות. יש להעביר את הסמן מעל הגרף לפרטים נוספים.',
	'choose_date_range' => 'בחירת טווח תאריכים',
	'countries' => 'מדינות',
	'country' => 'מדינה',
	'country_breakdown' => 'מבקרים לפי מדינות',
	'description' => 'זהו אזור הסטטיסטיקה. ניתן להתרשם באמצעות הקישורים לתתי הקטגוריות למעלה',
	'error' => 'שגיאה',
	'glossary' => 'מילון מונחים',
	'hit_summary' => 'סיכום כניסות',
	'legend' => 'מקרא',
	'pageviews' => 'צפיות',
	'pageviews_description' => 'המספר הכולל של דפים שנצפו על ידי המבקרים באתר',
	'reports' => 'דיווחים',
	'reports_categories' => 'קטגוריות הדיווחים',
	'reports_statistics' => 'סטטיסטיקת הדיווחים',
	'reports_status' => 'מצב הדיווחים',
	'report_punchcard' => 'דיווחים לאורך זמן',
	'report_stats' => 'פילוח דיווחים',
	'stats_not_setup' => 'סטטיסטיקות אינן מוגדרות',
	'time_range_1' => 'חודש אחד',
	'time_range_2' => 'שלושה חודשים',
	'time_range_3' => 'חצי שנה',
	'time_range_all' => 'הכל',
	'unapproved' => 'לא מאושר',
	'unique_visitors' => 'מבקרים ייחודיים',
	'unique_visitors_description' => 'מספר האנשים שהגיעו לאתר, מבקרים ייחודיים נקבעים באמצעות עוגיות (cookies). במקרה והמבקר חסם את האפשרות לשמירת עוגיות במחשבו, המבקר יזוהו באמצעות שיטה פשוטה אשר מתחשבת בכתובת חשבון ה-IP של המשתמש, הדפדפן, רזולוצית המסך, הפלאגינים שלו, מערכת ההפעלה וכדומה.',
	'unverified' => 'לא מאומת',
	'verified' => 'מאומת',
	'visitor_summary' => 'מבקרים באתר',
	'visits' => 'ביקורים',
	'visits_description' => 'ביקור מתאר מבקר ייחודי שנכנס לאתר לאחר יותר מ-30 דקות מאז הפעם האחרונה בה צפה בדף',
);
