<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:49+0000
$lang = array(
	'captcha' => array(
		'default' => 'Bitte gib einen gültigen Sicherheitscode ein.',
		'required' => 'Bitte gib den Sicherheitscode ein.',
	) ,
	'email' => array(
		'email' => 'Das E-Mail-Feld scheint keine gültige E-Mailadresse zu enthalten.',
		'length' => 'Das E-Mail-Feld muss mindestens 4 und höchstens 64 Zeichen lang sein.',
		'required' => 'Das E-Mail-Feld ist erforderlich, wenn das Kästchen angehakt wurde.',
	) ,
	'error' => array(
		'required' => 'Das Fehlerfeld ist notwendig.',
	) ,
	'subject' => array(
		'length' => 'Das Betreffeld muss mindestens 3 Zeichen lang sein.',
		'required' => 'Das Betreff-Feld ist notwendig.',
	) ,
	'yourname' => array(
		'length' => 'Das Namensfeld muss mindestens 3 Zeichen lang sein.',
		'required' => 'Das Namensfeld ist notwendig.',
	) ,
);
