<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:52+0000
$lang = array(
	'captcha' => array(
		'default' => 'Bitte gib einen gültigen Sicherheitscode ein.',
		'valid' => 'Bitte gib einen gültigen Sicherheitscode ein.',
		'required' => 'Bitte gib den Sicherheitscode ein.',
	) ,
	'contact_email' => array(
		'email' => 'Die E-Mail-Adresse scheint ungültig zu sein.',
		'length' => 'Die E-Mail-Adresse muss mindestens 4 und maximal 64 Zeichen lang sein.',
		'required' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
	) ,
	'contact_message' => array(
		'required' => 'Das Feld NACHRICHT muss ausgefüllt werden.',
	) ,
	'contact_name' => array(
		'length' => 'Das Feld NAME muss mindestens 3 Zeichen lang sein.',
		'required' => 'Das Feld NAME muss ausgefüllt werden.',
	) ,
	'contact_subject' => array(
		'length' => 'Das BETREFF Feld muss mindestens 3 Zeichen lang sein.',
		'required' => 'Das BETREFF Feld muss ausgefüllt werden.',
	) ,
	'email_send' => array(
		'failed' => 'Es gab einen Fehler beim Verschicken Deiner Nachricht.',
	) ,
);
