<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:12+0000
$lang = array(
	'message' => 'Entschuldigung, unsere Seite ist derzeit offline und im Wartungsbetrieb. Bitte versuchen Sie es in ein paar Minuten erneut.',
);
