<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:56+0000
$lang = array(
	'captcha' => array(
		'default' => 'Bitte gib einen gültigen Sicherheitscode ein.',
		'required' => 'Bitte gib den Sicherheitscode ein.',
	) ,
	'email' => array(
		'email' => 'Das E-Mail-Feld scheint keine gültige Mailadresse zu enthalten.',
		'length' => 'Das E-Mail-Feld muss zwischen 4 und 64 Zeichen lang sein.',
		'required' => 'Das E-Mail-Feld ist erforderlich, wenn die Box angehakt wurde. ',
	) ,
	'message' => array(
		'required' => 'Das Kommentarfeld ist notwendig.',
	) ,
	'name' => array(
		'length' => 'Das Namensfeld muss min. 3 Zeichen lang sein.',
		'required' => 'Das Namensfeld ist notwendig.',
	) ,
	'phone' => array(
		'length' => 'Das Telefonfeld ist nicht gültig.',
	) ,
);
