<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:48+0000
$lang = array(
	'page_title' => array(
		'required' => 'Bitte gib einen Seitentitel an.',
		'length' => 'Der Seitentitel muss mindestens 3 bis maximal 150 Zeichen lang sein.',
	) ,
	'page_tab' => array(
		'required' => 'Bitte gib einen Seitentab Namen an.',
	) ,
	'page_description' => array(
		'required' => 'Bitte gib eine Seitenbeschreibung an.',
	) ,
);
