<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-08-12 16:09+0000
$lang = array(
	'reports_view' => 'Berichte anzeigen',
	'reports_edit' => 'Berichte erstellen/bearbeiten/löschen',
	'reports_approve' => 'Berichte bestätigen',
	'reports_verify' => 'Berichte beglaubigen',
	'reports_comments' => 'Kommentare zu Berichten verwalten',
	'reports_download' => 'Berichte herunterladen',
	'reports_upload' => 'Berichte hochladen',
	'messages' => 'Berichte verwalten',
	'messages_reporters' => 'Verwalte Berichterstatter',
	'stats' => 'Betrachte Statistiken',
	'settings' => 'Einstellungen verändern',
	'manage' => 'Panel verwalten',
	'users' => 'Benutzer verwalten',
	'manage_roles' => 'Rollenverteilung verwalten',
	'checkin' => 'Kann einchecken',
	'checkin_admin' => 'Checkins verwalten',
	'admin_ui' => 'Zugang Administrationsoberfläche',
	'member_ui' => 'Zugang Benutzeroberfläche',
	'delete_all_reports' => 'Alle Berichte löschen',
);
