<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-08-12 16:11+0000
$lang = array(
	'comments_form_error' => 'Fehler!',
	'country_name' => array(
		'single_country' => 'Diese Installation erstreckt sich nur über ein Land. Bitte stelle sicher, dass  sich der Ort des Berichts nur auf das Land %s bezieht.',
	) ,
	'custom_field' => array(
		'values' => 'Bitte geben Sie einen gültigen Wert für "%s" ein. ',
		'numeric' => 'Das Feld "%s" darf nur Zahlen enthalten.',
		'required' => 'Das Feld "%s" wird benötigt.',
		'not_exist' => 'Das feld "%s" existiert nicht.',
		'permission' => 'Das Feld "%s" kann nicht von ihrem Profil aus bearbeitet werden.',
		'email' => 'Das Feld "%s" muss eine gültige E-Mail Adresse enthalten.',
		'phone' => 'Das Feld "%s" muss eine gültige Telefonnummer enthalten.',
		'date_mmddyyyy' => 'Das Feld "%s" muss ein gültiges Datum enthalten (MM/DD/YYYY).',
		'date_ddmmyyyy' => 'Das Feld "%s" muss ein gültiges Datum enthalten (MM/DD/YYYY).',
	) ,
	'data_include' => array(
		'between' => 'Bitte wähle einen gültigen Eintrag aus für den Download.',
		'numeric' => 'Bitte wähle einen gültigen Eintrag aus für den Download.',
	) ,
	'data_active' => array(
		'between' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides. ',
		'numeric' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides.',
		'required' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides.',
	) ,
	'data_verified' => array(
		'between' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides.',
		'numeric' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides.',
		'required' => 'Bitte wähle "unbestätigte Berichte" oder "bestätigte Berichte" oder Beides.',
	) ,
	'data_point' => array(
		'between' => 'Bitte wähle einen gültigen Bericht aus für den Download',
		'numeric' => 'Bitte wähle einen gültigen Bericht aus für den Download',
		'required' => 'Bitte wähle einen gültigen Bericht aus für den Download',
	) ,
	'format' => array(
		'required' => 'Für das Herunterladen muss zwischen dem CSV oder XML Format ausgewählt werden.',
		'valid' => 'Bitte wähle ein Format zum Herunterladen Deiner Berichte',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Das Feld VON scheint ungültig zu sein.',
		'range' => 'Bitte geben Sie ein VON Datum ein. Es kann nicht größer sein als das heutige',
	) ,
	'incident_active' => array(
		'between' => 'Gib einen gültigen Wert ein, um diesen Bericht zu bestätigen.',
		'required' => 'Gib einen gültigen Wert ein, um diesen Bericht zu bestätigen.',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Das am/pm Feld scheint ungültig zu sein.',
	) ,
	'incident_category' => array(
		'numeric' => 'Das Kategoriefeld scheint keinen gültigen Wert zu beinhalten.',
		'required' => 'Das Kategoriefeld ist ein Pflichtfeld.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Das Datumsfeld scheint keinen gültigen Wert zu beinhalten.',
		'date_mmddyyyy' => 'Das Datumsfeld scheint keinen gültigen Wert zu beinhalten.',
		'required' => 'Das Datumsfeld ist ein Pflichtfeld.',
	) ,
	'incident_description' => array(
		'required' => 'Das Beschreibungsfeld ist notwendig.',
	) ,
	'incident_hour' => array(
		'between' => 'Das Stundenfeld scheint keinen gültigen Wert zu beinhalten.',
		'required' => 'Das Stundenfeld ist ein Pflichtfeld.',
	) ,
	'incident_information' => array(
		'alpha' => 'Bitte gib einen gültigen Wert ein für die Wahrscheinlichkeit der Information.',
		'length' => 'Bitte gib einen gültigen Wert ein für die Wahrscheinlichkeit der Information.',
	) ,
	'incident_minute' => array(
		'between' => 'Das Minutenfeld scheint keinen gültigen Wert zu beinhalten.',
		'required' => 'Das Minutenfeld ist ein Pflichtfeld.',
	) ,
	'incident_news' => array(
		'url' => 'Das Feld für die Nachrichtenquelle scheint keine gültige URL zu beinhalten.',
	) ,
	'incident_photo' => array(
		'size' => 'Foto-Uploads sind in der Grösse begrenzt auf 2MB.',
		'type' => 'Das Fotoformat scheint ungültig zu sein. Akzeptierte Formate sind .JPG, .PNG and .GIF.',
		'valid' => 'Die hochzuladene Datei scheint fehlerhaft zu sein.',
	) ,
	'incident_source' => array(
		'alpha' => 'Bitte gib einen gültigen Wert ein für die Verlässlichkeit der Quelle',
		'length' => 'Bitte gib einen gültigen Wert ein für die Verlässlichkeit der Quelle',
	) ,
	'incident_title' => array(
		'length' => 'Das Titelfeld muss zwischen 3 und 200 Zeichen lang sein.',
		'required' => 'Das Titelfeld ist notwendig.',
		'csrf' => 'Mögliche CSRF Attacke. Möchtest du wirklich einen Bericht erstellen/bearbeiten?',
	) ,
	'incident_verified' => array(
		'between' => 'Bitte gib einen gültigen Wert ein für die Verifizierung des Berichts',
		'required' => 'Bitte gib einen gültigen Wert ein für die Verifizierung des Berichts',
	) ,
	'incident_video' => array(
		'url' => 'Der Video-Link scheint ungültig zu sein.',
	) ,
	'latitude' => array(
		'between' => 'Der Längengrad ist ungültig.',
		'required' => 'Der Längengrad ist notwendig. Bitte klicke auf die Karte um einen auszuwählen.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Das Ortsfeld ist ungültig. ',
		'exists' => 'Der Bericht hat bereits eine Übersetzung.',
		'length' => 'Das Ortsfeld ist ungültig.',
		'locale' => 'Original und Übersetzung haben die gleiche Sprache.',
		'required' => 'Der Ort ist notwendig.',
	) ,
	'location_name' => array(
		'length' => 'Der Ort muss zwischen 3 und 200 Zeichen lang sein.',
		'required' => 'Das Feld Ort ist notwendig.',
	) ,
	'longitude' => array(
		'between' => 'Der Längengrad scheint ungültig zu sein?',
		'required' => 'Der Längengrad ist notwendig. Bitte klicke auf einen Punkt in der Karte.',
	) ,
	'person_email' => array(
		'email' => 'Die E-Mail-Adresse scheint ungültig zu sein.',
		'length' => 'Das Feld muss eine Länge zwischen 4 und 64 Zeichen haben.',
	) ,
	'person_first' => array(
		'length' => 'Das Feld muss eine Länge zwischen 3 und 100 Zeichen haben.',
	) ,
	'person_last' => array(
		'length' => 'Das Feld muss eine Länge zwischen 3 und 100 Zeichen haben.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Das BIS Datum scheint keinen gültigen Wert zu enthalten.',
		'range' => 'Bitte geben Sie ein gültiges BIS-Datum ein. Es kann nicht größer sein als HEUTE.',
		'range_greater' => 'Dein VON Datum kann nicht größer sein als das BIS Datum.',
	) ,
);
