<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-23 19:12+0000
$lang = array(
	'date' => 'Eintrittsdatum',
	'date_added' => 'Datum hinzugefügt',
	'last_access' => 'Letzter Zugriff',
	'sharing_color' => array(
		'length' => 'Das Farbfeld muss 6 Zeichen lang sein (Hex-Code)',
		'required' => 'Die Farbangabe ist notwendig.',
	) ,
	'sharing_name' => array(
		'length' => 'Der SHARING-NAME ist ungültig',
		'required' => 'Ein SHARING Name ist notwendig.',
	) ,
	'sharing_url' => array(
		'exists' => 'Die Seiten URL existiert bereits.',
		'length' => 'Die URL scheint ungültig zu sein.',
		'required' => 'Die Seiten URL ist notwendig.',
		'url' => 'Das URL Feld scheint keine gültige URL zu beinhalten.',
	) ,
);
