<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-07 07:13+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Het e-mail adres wordt niet geaccepteerd, controleer het e-mail adres',
		'email_check' => 'Het e-mail adres is al geconfigureerd om notificaties te ontvangen voor deze locatie',
		'length' => 'Het e-mail adres dient uit tenminste 4 en maximaal 64 tekens te bestaan',
		'required' => 'Je hebt aangegeven e-mail te willen ontvangen, geef een geldig e-mail adres op',
	) ,
	'alert_country' => array(
		'single_country' => 'Deze opstelling bestrijkt maar één land. Zorg dat de plaats van de waarschuwing in het land %s ligt.',
	) ,
	'alert_lat' => array(
		'between' => 'Selecteer een locatie op de kaart',
		'required' => 'Selecteer een locatie op de kaart',
	) ,
	'alert_lon' => array(
		'between' => 'Selecteer een locatie op de kaart',
		'required' => 'Selecteer een locatie op de kaart',
	) ,
	'alert_mobile' => array(
		'length' => 'Het aantal opgegeven cijfers voor het mobiele nummer is ongeldig',
		'mobile_check' => 'Het mobiele nummer is al geconfigureerd om notificaties te ontvangen voor deze locatie',
		'numeric' => 'Het opgegeven mobiele nummer lijkt ongeldig. Gebruik alleen cijfers met landcode.',
		'one_required' => 'Geef een mobiel nummer en/of een e-mail adres op',
		'required' => 'Je hebt aangegeven mobiele notificaties te willen ontvangen, geef een geldig mobiel nummer op',
	) ,
	'alert_radius' => array(
		'in_array' => 'Geef een zoekstraal aan op de kaart',
		'required' => 'Geef een zoekstraal aan op de kaart',
	) ,
	'alert_recipient' => array(
		'required' => 'Je hebt geen ontvanger voor waarschuwingen ingesteld.',
	) ,
	'alerts_subscribed' => 'Je bent ingeschreven voor waarschuwingen met de volgende categoriën',
	'code_already_verified' => 'Deze code is al eerder geverifieerd',
	'code_not_found' => 'De verificatiecode kon niet worden gevonden.Controleer of de gebruikte URL correct is',
	'code_verified' => ' De code is geverifieerd. Je ontvangt nu notificaties wanneer er berichten zijn.',
	'confirm_request' => 'Om je notificaties verzoek te bevestigen ga je naar ',
	'create_more_alerts' => 'Ga naar de notificaties pagina om meer notificaties te maken',
	'email_alert_request_created' => 'Je e-mail notificaties verzoek is aangemaakt. Een verificatie bericht is verzonden naar ',
	'email_code' => 'Vul de per e-mail ontvangen verificatiecode in: ',
	'email_error_head' => 'Je e-mail notificaties verzoek is niet opgeslagen!',
	'email_ok_head' => 'Je e-mail notificaties verzoek is opgeslagen!',
	'error' => 'Het systeem is niet instaat om je bevestiging te verwerken!',
	'mobile_alert_request_created' => 'Je mobiele notificaties verzoek  is aangemaakt. Een verificatie bericht is verzonden naar ',
	'mobile_code' => 'Vul de per SMS ontvangen verificatiecode in: ',
	'mobile_error_head' => 'Je mobiele notificaties verzoek is niet opgeslagen!',
	'mobile_ok_head' => 'Je mobiele notificaties verzoek is opgeslagen',
	'settings_error' => 'De installatie is niet correct ingesteld om notificaties te verwerken. Neem contact op met de beheerder.',
	'unsubscribe' => 'Je ontvangt deze e-mail omdat je hebt aangegeven notificaties te willen ontvangen. Indien je in de toekomst geen notificaties meer wilt ontvangen, ga dan naar ',
	'unsubscribed' => 'Je zult niet langer notificaties ontvangen van ',
	'unsubscribe_failed' => 'Het systeem kan je niet uitschrijven voor notificaties. Controleer of je de juiste URL hebt opgegeven.',
	'verification_email_subject' => 'notificaties - verificatie',
	'verify_code' => 'Je zult geen notificaties ontvangen tot je verzoek bevestigd is.',
);
