<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'Geef een geldige veiligheidscode op',
		'required' => 'Geef een veiligheidscode op',
	) ,
	'email' => array(
		'email' => 'Geef een geldig e-mail adres op',
		'length' => 'Een e-mail adres dient tenminste 4 en maximaal 64 tekens te bevatten',
		'required' => 'Een e-mail adres is verplicht wanneer het vinkje is aangekruisd.',
	) ,
	'error' => array(
		'required' => 'De foutmelding is verplicht.',
	) ,
	'subject' => array(
		'length' => 'Een onderwerp moet tenminste 3 tekens bevatten.',
		'required' => 'Onderwerp is verplicht.',
	) ,
	'yourname' => array(
		'length' => 'Een naam moet tenminste 3 tekens bevatten.',
		'required' => 'Naam is verplicht.',
	) ,
);
