<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:35+0000
$lang = array(
	'date' => 'Datum',
	'feed_name' => array(
		'length' => 'Een feed naam dient tenminste 3 en maximaal 70 tekens te bevatten.',
		'required' => 'Geef de feed een naam.',
	) ,
	'feed_url' => array(
		'required' => 'Geef de feed URL.',
		'url' => 'Geef een geldige URL op, b.v. http://www.ushahidi.com',
	) ,
	'source' => 'Bron',
	'title' => 'Titel',
);
