<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-27 06:19+0000
// PO revision date:  2013-06-26 08:52+0000
$lang = array(
	'captcha' => array(
		'default' => 'Please enter a valid security code',
		'required' => 'Please enter the security code',
	) ,
	'email' => array(
		'email' => 'The Email field does not appear to contain a valid email address?',
		'length' => 'Het e-mailveld dient uit tenminste 4 en tenhoogste 64 tekens te bestaan.',
		'required' => 'Het e-mailveld is verplicht wanneer het vinkje is aangekruisd.',
	) ,
	'message' => array(
		'required' => 'Het commentaarveld is verplicht.',
	) ,
	'name' => array(
		'length' => 'Het naamveld dient tenminste 3 tekens lang te zijn.',
		'required' => 'Het naamveld is verplicht.',
	) ,
	'phone' => array(
		'length' => 'Het telefoonveld is niet geldig.',
	) ,
);
