<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-30 06:24+0000
// PO revision date:  2013-07-29 19:05+0000
$lang = array(
	'approved' => 'Goedgekeurd',
	'categories' => 'Categorieën',
	'category_impact_description' => 'This chart gives you a linear view of the reports by category over time.  Scroll from left to right to see a comparative view of the different categories. Mouse over the graph for more details',
	'choose_date_range' => 'Kies een datumbereik.',
	'countries' => 'Landen',
	'country' => 'Land',
	'description' => 'Hello, this is the statistics section. General description going here soon. For now, browse around using the sub category links above',
	'error' => 'Fout',
	'glossary' => 'Woordenlijst',
	'legend' => 'Legenda',
	'reports' => 'Berichten',
	'reports_categories' => 'Berichtcategorie&euml;n',
	'reports_statistics' => 'Berichtstatistiek',
	'reports_status' => 'Berichtstatus',
	'time_range_1' => '1 maand',
	'time_range_2' => '3 maanden',
	'time_range_3' => '6 maanden',
	'time_range_all' => 'Alle',
	'unique_visitors' => 'Unieke bezoekers',
	'unique_visitors_description' => 'The number of individuals coming to your deployment; Unique Visitors are determined using cookies. In the case that a visitor does not have cookies enabled, they will be identified using a simple heuristic taking into account IP address, resolution, browser, plugins, OS, etc',
	'unverified' => 'Onbevestigd',
	'verified' => 'Bevestigd',
	'visits_description' => 'A visit is a record of a unique visitor coming to the site more than 30 minutes past his/her last pageview',
);
