<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-15 06:14+0000
$lang = array(
	'admin_footer' => 'Ky mesazh &euml;sht&euml; d&euml;rguar nga faqja juaj e web.',
	'admin_login_url' => 'Identifikimi i administratorit',
	'admin_new_comment' => array(
		'message' => 'Nje koment i ri &euml;sht&euml; sh&euml;nuar n&euml; faqen tuaj n&euml; p&euml;rgjigje t&euml;:',
		'subject' => 'Koment i ri',
	) ,
	'admin_new_email' => array(
		'message' => 'Nj&euml; mesazh i ri &euml;sht&euml; d&euml;rguar n&euml; faqen tuaj.',
		'subject' => 'Mesazh i ri',
	) ,
	'admin_new_report' => array(
		'message' => 'Nj&euml; raportim i ri &euml;sht&euml; sh&euml;nuar n&euml; faqen tuaj.',
		'subject' => 'Raportim i ri',
	) ,
	'admin_new_sms' => array(
		'message' => 'Nj&euml; mesazh i ri &euml;sht&euml; d&euml;rguar n&euml; faqen tuaj.',
		'subject' => 'Mesazh i ri',
	) ,
	'member_new_alert' => array(
		'message' => 'Ju keni marr&euml; nj&euml; denoncim t&euml; ri',
		'subject' => 'Denoncim i ri!',
	) ,
	'member_new_message' => array(
		'message' => 'Ju keni marr&euml; nj&euml; mesazh privat',
		'subject' => 'Mesazh privat i ri',
		'footer' => 'P&euml;r t`u p&euml;rgjigjur shkoni tek: ',
	) ,
);
