<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'Будь ласка, введіть правильний код безпеки',
		'required' => 'Будь ласка, введіть код безпеки',
	) ,
	'email' => array(
		'email' => 'Електронну адресу введено неправильно.',
		'length' => 'Довжина електронної адреси повинна бути не менше 4 і не більше 64 символів.',
		'required' => 'Потрібно ввести електронну адресу, або зніміть прапорець.',
	) ,
	'error' => array(
		'required' => 'Введіть опис помилки.',
	) ,
	'subject' => array(
		'length' => 'Довжина теми повинна бути не менше 3 символів.',
		'required' => 'Введіть поле Тема.',
	) ,
	'yourname' => array(
		'length' => 'Довжина імені повинна бути не менше 3 символів.',
		'required' => 'Введіть поле Ім\'я.',
	) ,
);
