<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-26 06:19+0000
// PO revision date:  2013-06-25 18:16+0000
$lang = array(
	'captcha' => array(
		'default' => 'Будь ласка, введіть правильний код безпеки.',
		'required' => 'Будь ласка, введіть код безпеки.',
		'valid' => 'Ви ввели невірний код безпеки.',
	) ,
	'comment_author' => array(
		'length' => 'Поле імені має містити принаймні три символи.',
		'required' => 'Введіть ім\'я.',
	) ,
	'comment_description' => array(
		'required' => 'Введіть текст коментаря.',
	) ,
	'comment_email' => array(
		'email' => 'Поле email містить неправильну електронну адресу.',
		'length' => 'Електронна адреса має містити від 4-х до 64-х символів.',
		'required' => 'Якщо поле email адреси відмічено прапорцем, треба ввести електронну адресу. ',
	) ,
);
