<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 16:58+0000
$lang = array(
	'captcha' => array(
		'default' => 'Будь ласка, введіть правильний код безпеки',
		'valid' => 'Будь ласка, введіть правильний код безпеки.',
		'required' => 'Будь ласка, введіть код безпеки',
	) ,
	'contact_email' => array(
		'email' => 'Поле email містить неправильну електронну адресу.',
		'length' => 'Поле електронної пошти повинно бути довжиною не менше 4 і не більше 64 символів.',
		'required' => 'Потрібно ввести Email адресу або зніміть прапорець.',
	) ,
	'contact_message' => array(
		'required' => 'Поле повідомлення є обов\'язковим.',
	) ,
	'contact_name' => array(
		'length' => 'У полі "Ім\'я" має бути не менше 3-х символів.',
		'required' => 'Поле "Ім\'я" є обов\'язковим.',
	) ,
	'contact_subject' => array(
		'length' => 'У полі теми має бути не менше 3-х символів.',
		'required' => 'Поле теми є обов\'язковим.',
	) ,
	'email_send' => array(
		'failed' => 'Трапилася помилка при надсиланні вашого повідомлення.',
	) ,
);
