<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-07-12 21:31+0000
$lang = array(
	'error' => 'Помилка бази даних: %s',
	'table_not_found' => 'Таблиця "%s" не може бути знайдений в базі даних. Будь ласка, переконайтеся, що ви використовуєте останню версію бази даних для даної версії Ushahidi',
);
