<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 15:28+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Переконайтеся, що ви вже відмітили один елемент',
		'numeric' => 'Переконайтеся, що ви вже відмітили один елемент',
		'categories_required' => 'Звіти повинні бути класифіковані, перш ніж вони можуть бути схвалені',
	) ,
	'action' => array(
		'permission' => 'У вас немає дозволу на виконання цієї дії',
	) ,
	'uploadfile' => array(
		'required' => 'Ви повинні вибрати файл для вивантаження',
		'type' => 'Файл для вивантаження мусить бути у форматі .csv або .xml',
		'valid' => 'Поле файлу вивантаження, здається, не містить правильний файл',
	) ,
);
