<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-03 06:22+0000
// PO revision date:  2013-07-02 11:23+0000
$lang = array(
	'cURL_not_installed' => 'php5-curl is not installed on this system.',
);
