<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-02 06:22+0000
// PO revision date:  2013-07-01 17:45+0000
$lang = array(
	'imap_stream_not_opened' => 'Could not open IMAP stream.',
	'unsupported_service' => 'The email service is not supported.',
);
