<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-03 06:22+0000
// PO revision date:  2013-07-02 21:29+0000
$lang = array(
	'page_title' => array(
		'required' => 'Please enter a Page Title.',
		'length' => 'Page Title must be at least 3 and no more than 150 characters long.',
	) ,
	'page_tab' => array(
		'required' => 'Please enter a Page Tab Name.',
	) ,
	'page_description' => array(
		'required' => 'Please enter a Page Description.',
	) ,
);
