<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-18 06:22+0000
// PO revision date:  2013-09-17 10:19+0000
$lang = array(
	'reports_view' => 'View Reports',
	'reports_edit' => 'Create/Edit/Delete Reports',
	'reports_approve' => 'Approve Reports',
	'reports_verify' => 'Verify Reports',
	'reports_comments' => 'Manage Report Comments',
	'reports_download' => 'Download Reports',
	'reports_upload' => 'Upload Reports',
	'messages' => 'Manage Messages',
	'messages_reporters' => 'Manage Message Reporters',
	'stats' => 'View Stats',
	'settings' => 'Modify Settings',
	'manage' => 'Manage Panel',
	'users' => 'Manage Users',
	'manage_roles' => 'Manage Roles',
	'checkin' => 'Can checkin',
	'checkin_admin' => 'Manage checkins',
	'admin_ui' => 'Access Admin UI',
	'member_ui' => 'Access Members UI',
	'delete_all_reports' => 'Delete all reports',
);
