<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-02 06:22+0000
// PO revision date:  2013-07-01 17:40+0000
$lang = array(
	'date' => 'Ingress date',
	'date_added' => 'Date Added',
	'last_access' => 'Last Access',
	'sharing_color' => array(
		'length' => 'The colour field must be 6 characters long.',
		'required' => 'The colour field is required.',
	) ,
	'sharing_name' => array(
		'length' => 'The Sharing name does not appear to be valid.',
		'required' => 'A Sharing name is required.',
	) ,
	'sharing_url' => array(
		'exists' => 'The site URL already exists.',
		'length' => 'The site URL does not appear to be valid.',
		'required' => 'The site URL is required.',
		'url' => 'The site URL field does not appear to contain a valid URL.',
	) ,
);
