<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-03-06 02:44+0000
$lang = array(
	'captcha' => array(
		'default' => 'សូមបញ្ចូលលេខកូដដែលមាន។',
		'valid' => 'សូមបញ្ចូលលេខកូដដែលមាន។',
		'required' => 'សូមបញ្ចូលលេខកូដសុវត្ថិភាព',
	) ,
	'contact_email' => array(
		'email' => 'ប្រឡោះអ៊ីម៉ែលហាក់ដូចអត់មានអី',
		'length' => 'ប្រឡោះអ៊ីម៉ែលត្រូវតែមានយ៉ាងតិច4 និង​ មិនច្រើនជាង 64តួ',
		'required' => 'តម្រូវការបើប្រអប់បានជ្រើសរើស',
	) ,
	'contact_message' => array(
		'required' => 'ប្រឡោះសារតម្រូវឲ្យមាន',
	) ,
	'contact_name' => array(
		'length' => 'ប្រឡោះឈ្មោះតម្រូវ​ឲ្យមានយ៉ាងតិច3តួ',
		'required' => 'ប្រឡោះឈ្មោះតម្រូវឲ្យមាន',
	) ,
	'contact_subject' => array(
		'length' => 'ប្រឡោះប្រធានបទតម្រូវឲ្យមានយ៉ាងតិច3តួ',
		'required' => 'ប្រឡោះប្រធានបទតម្រូវឲ្យមាន',
	) ,
	'email_send' => array(
		'failed' => 'មានការមិនប្រក្រតីពេលកំពុងផ្ញើសារ',
	) ,
);
