<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-14 06:13+0000
// PO revision date:  2013-03-13 08:19+0000
$lang = array(
	'error' => 'កំហុស​មូលដ្ឋាន​ទិន្នន័យ៖ %s',
	'table_not_found' => 'រក​មិន​ឃើញ​តារាង "%s" នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ។ សូម​ប្រាកដ​ថា​អ្នក​កំពុង​ប្រើ​កំណែ​ថ្មី​បំផុត​របស់​មូលដ្ឋាន​ទិន្នន័យ​សម្រាប់​កំណែ Ushahidi នេះ។',
);
