<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-14 06:13+0000
// PO revision date:  2013-03-13 09:00+0000
$lang = array(
	'layer_color' => array(
		'length' => 'វាល​ពណ៌​ត្រូវតែ​មាន៦តួអក្សរ។',
		'required' => 'បាន​ទាមទារ​វាល​ពណ៌។',
	) ,
	'layer_file' => array(
		'type' => 'វាល​ឯកសារ​មិន​​មាន​​​បង្ហាញ​​ឯកសារ​​ត្រឹមត្រូវ​ឡើយ។ បាន​ព្រម​ទទួល​យក​តែ​ទ្រង់ទ្រាយ .KMZ និង .KML ប៉ុណ្ណោះ។',
		'valid' => 'វាល​ឯកសារ​មិន​មាន​បង្ហាញ​ឯកសារ​ត្រឹមត្រូវ​ឡើយ',
	) ,
	'layer_name' => array(
		'length' => 'វាល​ឈ្មោះ​ត្រូវ​តែ​មាន​យ៉ាងហោចណាស់ ៣ តួអក្សរ និង​មិន​ច្រើន​​ជាង​ ៨០ តួអក្សរ​ឡើយ។',
		'required' => 'បាន​ទាមទារ​វាល​ឈ្មោះ។',
	) ,
	'layer_url' => array(
		'atleast' => 'បាន​ទាមទារ KML URL ឬ​ឯកសារ។',
		'both' => 'អ្នក​មិន​មាន​​​​ឯកសារ KML និង URL ឡើយ។',
		'url' => 'សូម​បញ្ចូល​ URL ត្រឹមត្រូវ ឧ. http://www.ushahidi.com/layerl.kml',
	) ,
);
