<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-03-11 06:14+0000
$lang = array(
	'page_title' => array(
		'required' => 'សូមបញ្ចូលចំណងជើងទំព័រ',
		'length' => 'ប្រឡោះចំណងជើងតម្រូវឲ្យមានយ៉ាងតិច 3 និងមិនច្រើនជាង 150តួ',
	) ,
	'page_tab' => array(
		'required' => 'សូមវាយបញ្ចូលឈ្មោះបន្ទះ',
	) ,
	'page_description' => array(
		'required' => 'សូមបញ្ចូលទំព័រពិពណ៌នា',
	) ,
);
