<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-12 06:12+0000
// PO revision date:  2013-03-11 08:13+0000
$lang = array(
	'latitude' => array(
		'between' => 'វាល​រយៈ​ទទឹង​មិន​បង្ហាញ​ថា​មាន​រយៈ​ទទឹង​ត្រឹមត្រូវ​ទេ។',
		'required' => 'វាល​រយៈ​ទទឹង​ត្រូវ​បាន​ទាមទារ។ សូម​ចុច​តំណ​​លើ​ផែនទី​ដើម្បី​​បង្ហាញ​ទីតាំង។',
	) ,
	'level_id' => array(
		'numeric' => 'វាល​កម្រិត​អ្នក​រាយការណ៍​មិន​បង្ហាញ​ថា​មាន​កម្រិត​ត្រឹមត្រូវ​ទេ។',
		'required' => 'វាល​កម្រិត​អ្នក​រាយការណ៍​មិន​បង្ហាញ​ថា​មាន​កម្រិត​ត្រឹមត្រូវ​ទេ។',
	) ,
	'location_name' => array(
		'length' => 'វាល​ឈ្មោះ​ទីតាំង​​យ៉ាង​ហោច​ណាស់​ត្រូវ​តែ​ ៣ និង​មាន​ប្រវែង​ជាង ២០០ តួអក្សរ។',
		'required' => 'វាល​ឈ្មោះ​ទីតាំ​ង​ត្រូវ​បាន​ទាមទារ។',
	) ,
	'longitude' => array(
		'between' => 'វាល​រយៈ​បណ្ដោយ​មិន​បង្ហាញ​ថា​មាន​រយៈ​បណ្ដោយ​ត្រឹមត្រូវ​ទេ។',
		'required' => 'វាល​រយៈ​បណ្ដោយ​ត្រូវ​បាន​ទាមទារ។ សូម​ចុច​តំណ​លើ​ផែនទី ដើម្បី​បង្ហាញ​ទីតាំង។',
	) ,
	'reporter_id' => array(
		'numeric' => 'អ្នក​រាយការណ៍​មិន​ត្រឹមត្រូវ',
		'required' => 'អ្នក​រាយការណ៍​មិន​ត្រឹមត្រូវ',
	) ,
);
