<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-25 06:11+0000
// PO revision date:  2012-12-24 15:24+0000
$lang = array(
	'captcha' => array(
		'default' => 'Παρακαλώ εισάγετε ένα έγκυρο κωδικό ασφαλείας.',
		'required' => 'Παρακαλώ εισάγετε τον κωδικό ασφαλείας.',
	) ,
	'email' => array(
		'email' => 'Το πεδίο e-mail δεν φαίνεται να περιέχει μια έγκυρη διεύθυνση e-mail;',
		'length' => 'Το πεδίο Email πρέπει να έχει μήκος τουλάχιστον 4 και όχι περισσότερο απο 64 χαρακτήρες',
		'required' => 'Το πεδίο Email είναι υποχρεωτικό εάν η επιλογή είναι επιλεγμένη.',
	) ,
	'error' => array(
		'required' => 'Το πεδίο "σφάλμα" είναι υποχρεωτικό',
	) ,
	'subject' => array(
		'length' => 'Το πεδίο "Θέμα" πρέπει να είναι τουλάχιστον 3 χαρακτήρες.',
		'required' => 'Το πεδίο "Θέμα" είναι υποχρεωτικό',
	) ,
	'yourname' => array(
		'length' => 'Το πεδίο "Όνομα" πρέπει να είναι τουλάχιστον 3 χαρακτήρες.',
		'required' => 'Το πεδίο "Όνομα" είναι υποχρεωτικό',
	) ,
);
