<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-25 06:11+0000
// PO revision date:  2012-12-24 17:59+0000
$lang = array(
	'captcha' => array(
		'default' => 'Παρακαλώ εισάγετε ένα έγκυρο κωδικό ασφαλείας.',
		'required' => 'Παρακαλώ εισάγετε τον κωδικό ασφαλείας.',
	) ,
	'email' => array(
		'email' => 'Το πεδίο διεύθυνση ηλεκτρονικού ταχυδρομείου φαίνεται να μην περιέχει μια έγκυρη διεύθυνση e-mail;',
		'length' => 'Το πεδίο διεύθυνση ηλεκτρονικού ταχυδρομείου πρέπει να έχει μήκος τουλάχιστον 4 και όχι περισσότερο απο 64 χαρακτήρες.',
		'required' => 'Το πεδίο διεύθυνση ηλεκτρονικού ταχυδρομείου είναι υποχρεωτικό εάν το checkbox είναι επιλεγμένο.',
	) ,
	'message' => array(
		'required' => 'Το πεδίο "Σχόλια" είναι υποχρεωτικό.',
	) ,
	'name' => array(
		'length' => 'Το πεδίο "Όνομα" πρέπει να είναι τουλάχιστον 3 χαρακτήρες.',
		'required' => 'Το πεδίο "Όνομα" είναι υποχρεωτικό',
	) ,
	'phone' => array(
		'length' => 'Το πεδίο "Τηλέφωνο" είναι υποχρεωτικό',
	) ,
);
