<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-02-02 20:49+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Παρακαλώ εισάγετε έναν έγκυρο κωδικό ασφαλείας.',
		'required' => 'Παρακαλώ εισάγετε τον κωδικό ασφαλείας.',
	) ,
	'contact_email' => array(
		'email' => 'Το πεδίο Ηλεκτρονική Διεύθυνση δεν περιέχει έγκυρη ηλεκτρονική διεύθυνση.',
		'required' => 'Παρακαλώ εισάγετε μια έγκυρη ηλεκτρονική διεύθυνση.',
	) ,
	'contact_message' => array(
		'required' => 'Το πεδίο Μήνυμα απαιτείται.',
	) ,
	'contact_subject' => array(
		'length' => 'Το πεδίο Θέμα πρέπει να είναι τουλάχιστον 3 χαρακτήρων.',
		'required' => 'Το πεδίο Θέμα απαιτείται.',
	) ,
);
