<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-02-02 19:49+0000
$lang = array(
	'admin_footer' => 'Αυτό το μήνυμα έχει σταλθεί από την ιστοσελίδα σας.',
	'admin_login_url' => 'Σύνδεση διαχειριστή.',
	'admin_new_comment' => array(
		'message' => 'Ένα νέο σχόλιο έχει υποβληθεί στην ιστοσελίδας σας σε απάντηση του:',
		'subject' => 'Νέο σχόλιο',
	) ,
	'admin_new_email' => array(
		'message' => 'Ένα νέο ηλεκτρονικό μήνυμα έχει υποβληθεί στην ιστοσελίδα σας.',
		'subject' => 'Νέο ηλεκτρονικό μήνυμα',
	) ,
	'admin_new_report' => array(
		'message' => 'Μια νέα αναφορά έχει υποβληθεί στην ιστοσελίδα σας.',
		'subject' => 'Νέα αναφορά',
	) ,
	'admin_new_sms' => array(
		'message' => 'Ένα νέο γραπτό μήνυμα έχει υποβληθεί στην ιστοσελίδα σας.',
		'subject' => 'Νέο γραπτό μήνυμα',
	) ,
	'member_new_alert' => array(
		'message' => 'Λάβατε νέα προειδοποιήσει ',
		'subject' => 'Νέα προειδοποιήσει',
	) ,
	'member_new_message' => array(
		'message' => 'Λάβατε ένα προσωπικό μήνυμα',
		'subject' => 'Νέο προσωπικό μήνυμα',
		'footer' => 'Για απάντηση παρακαλώ πηγαίνετε στο:',
	) ,
);
