<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-25 06:11+0000
// PO revision date:  2012-12-24 18:02+0000
$lang = array(
	'page_title' => array(
		'required' => 'Παρακαλώ εισάγετε έναν τίτλο σελίδας.',
		'length' => 'Ο Τίτλος σελίδας θα πρέπει να είναι τουλάχιστον 3 και όχι περισσότερο από 150 χαρακτήρες.',
	) ,
	'page_tab' => array(
		'required' => 'Παρακαλώ εισάγετε ένα όνομα Tab.',
	) ,
	'page_description' => array(
		'required' => 'Παρακαλώ εισάγετε μια περιγραφή σελίδας',
	) ,
);
