<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-18 06:24+0000
// PO revision date:  2013-11-17 23:41+0000
$lang = array(
	'error' => 'Errore nel database: %s',
	'table_not_found' => 'La Tabella "%s" non può essere trovata nel database. Assicurati di stare usando la versione più recente del database per questa versione di Ushahidi.',
);
