<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-18 06:24+0000
// PO revision date:  2013-11-17 23:36+0000
$lang = array(
	'cURL_not_installed' => 'php5-curl non è installato su questo sistema',
);
