<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-03 17:33+0000
$lang = array(
	'akismet_cannot_connect' => 'Non è stato possibile connettersi al server Akismet',
	'akismet_cannot_retrieve' => 'Non è stato possibile ricevere la risposta dal server Akismet.',
	'api_library_not_found' => 'La API Library: : <strong>%s</strong>, per la classe <strong>%s</strong> non è stata trovata. Controlla la tua API task routing table.',
	'askimet_invalid_apikey' => 'La tua chiave API Akismet non è valida',
	'clickatell_fopen_error' => 'Errore nell\'esecuzione di fopen metodo di invio!<br>Verifica se PHP ha un supporto OpenSSL e assicurati che la versione PHP sia maggiore della 5.2',
	'clickatell_message_too_long' => 'Il tuo unicode message è troppo lungo (Lunghezza attuale=',
	'clickatell_no_destination_address' => 'Specifica un indirizzo di destinazione (A)!',
	'clickatell_no_sender_address' => 'Specifica un indirizzo per il mittente (DA)!',
	'clickatell_unicode_message_too_long' => 'Il tuo unicode message è troppo lungo!  (Lunghezza attuale=',
	'clickatell_unsupported_method' => 'Metodo di invio non supportato!',
	'invalid_api_library' => 'La Libreria APi %s non è valida. Tutte le librerie APi devo essere sottoclassi di %s',
	'upgrade_directory_not_deleted' => 'Non è stato possibile cancellare la directory <code>%s</coded>',
	'upgrade_extracting_error' => 'Errore nell\'estrazione: <code>%s</code>',
	'upgrade_failed' => 'Il download dell\'ultima versione di Ushahidi non è andato a buon fine. HTTP status code',
	'upgrade_file_not_copied' => 'Non è stato possibile copiare il File <code>%s</coded>',
	'upgrade_file_not_deleted' => 'Non è stato possibile cancellare il File <code>%s</coded>',
	'upgrade_title' => 'Script per l\'aggiornamento di Ushahidi',
	'upgrade_zip_error' => 'Il file scaricato Ushahidi zip <code>%s</code>, non è scrivibile',
	'riverid_variable_not_available' => '%s non è disponibile nella classe RiverID.',
);
