<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-11 15:43+0000
$lang = array(
	'admin_footer' => 'Questo messaggio ',
	'admin_login_url' => 'Accesso Amministratore',
	'admin_new_comment' => array(
		'message' => 'Un nuovo Commento ',
		'subject' => 'Nuovo Commento',
	) ,
	'admin_new_email' => array(
		'message' => 'Un Nuovo Messaggio Email ',
		'subject' => 'Nuovo Messaggio Email',
	) ,
	'admin_new_report' => array(
		'message' => 'Una nuova segnalazione ',
		'subject' => 'Nuova segnalazione',
	) ,
	'admin_new_sms' => array(
		'message' => 'Un nuovo Messaggio di Testo ',
		'subject' => 'Nuovo Messaggio di Testo',
	) ,
	'member_new_alert' => array(
		'message' => 'Hai Ricevuto un Nuovo Avviso',
		'subject' => 'Nuova Avviso!',
	) ,
	'member_new_message' => array(
		'message' => 'Hai Ricevuto un Messaggio Privato',
		'subject' => 'Nuovo Messaggio Privato',
		'footer' => 'Per rispondere Andare A:',
	) ,
);
