<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-11 15:32+0000
$lang = array(
	'page_title' => array(
		'required' => 'Inserire il Titolo della Pagina',
		'length' => 'Il Titolo della Pagina deve essere lungo tra 3 e 150 caratteri',
	) ,
	'page_tab' => array(
		'required' => 'Inserire il Nome del Tab della Pagina',
	) ,
	'page_description' => array(
		'required' => 'Inserire la Descrizione della Pagina',
	) ,
);
