<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-14 06:10+0000
// PO revision date:  2012-12-13 10:57+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Da li ste upisali ispravan email u polje za unos email adrese?',
		'email_check' => 'Navedena email adresa je vec registrovana da prima obavjestenja o toj lokaciji.',
		'length' => 'Email polje mora imati najmanje 4 a najviše 64 znaka.',
		'required' => 'Email polje je obavezno ukoliko je oznaceno.',
	) ,
	'alert_country' => array(
		'single_country' => 'Ovaj deployment pokriva samo jednu državu. Osigurajte se dali je lokacija na koju upozoravate unutar %s za tu državu.',
	) ,
	'alert_lat' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_lon' => array(
		'between' => 'Niste izabrali validnu lokaciju na mapi.',
		'required' => 'Niste izabrali validnu lokaciju na mapi.',
	) ,
	'alert_mobile' => array(
		'length' => 'Čini se da polje za mobilni telefon ne sadrzi ispravan broj karaktera.',
		'mobile_check' => 'Navedeni broj je već registriran za primanje obavještenja o toj lokaciji.',
		'numeric' => 'Polje za mobitel ne sadrži ispravan broj karaktera. Molimo unesite samo brojeve uključujući i pozivni broj.',
		'one_required' => 'Morate unjeti broj vašeg mobitela ili vašu email adresu.',
		'required' => 'Polje za mobitel je obavezno ukoliko je označeno.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Niste označili ispravan radius na mapi.',
		'required' => 'Niste podesili svoj radius na mapi.',
	) ,
	'alert_recipient' => array(
		'required' => 'Niste naveli primaoca upozorenja.',
	) ,
	'alerts_subscribed' => 'Pretplatili ste se za obavijesti u sljedećim kategorijama',
	'code_already_verified' => 'Ovaj kod je vec verificiran!',
	'code_not_found' => 'Ovaj kod za verifikaciju nije pronađen! Molimo potvrdite da imate tačan URL.',
	'code_verified' => 'Vaš kod je uspješno verificiran. Od sada ćete primati upozorenja o incidentima kako se budu događali.',
	'confirm_request' => 'Za potvrdu zahtjeva za obavijesti, otidjite na',
	'create_more_alerts' => 'Vratite se na stranicu Upozorenja kako biste kreirali dodatna upozorenja',
	'email_alert_request_created' => 'Vaš zahtjev za email obavijestima je kreiran i poruka za verifikaciju je poslana na',
	'email_code' => 'Unesite email kod za potvrdu koji ste primili:',
	'email_error_head' => 'Vaš zahtjev za email obavijesti NIJE spašen!',
	'email_ok_head' => 'Vaš zahtjev za email obavijesti je spašen!',
	'error' => 'Sistem nije bio u mogucnosti da procesira Vas zahtjev za potvrdom!',
	'mobile_alert_request_created' => 'Vasa Mobilna Aplikacija Upozorenja je kreirana i poslata je poruka upozorenja',
	'mobile_code' => 'Unesite SMS kod za potvrdu koji ste primili:',
	'mobile_error_head' => 'Vaš zahtjev za upozorenje preko mobilnog telefona NIJE snimljen!',
	'mobile_ok_head' => 'Vaš Zahtjev za upozorenje preko mobilnog telefona je snimljen!',
	'settings_error' => 'Ovaj deployment nije setovan za ispravno procesiranje upozorenja',
	'unsubscribe' => 'Dobili ste ovu poruku jer ste se prijavili da primate obavjesti. Ukoliko ubuduce ne zelite primati ovakve poruke idite na',
	'unsubscribed' => 'Nećeš iše primati upozorenja od',
	'unsubscribe_failed' => 'Nismo bili u mogucnosti da Vas odjavimo. Molimo Vas potvrdite da Vam je URL ispravan.',
	'verification_email_subject' => 'obavijesti - verifikacija',
	'verify_code' => 'Necete primati obavjesti na navedenoj lokaciji dok ne potvrdite zahtjev',
);
