<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-10-25 21:04+0000
$lang = array(
	'captcha' => array(
		'default' => 'Unesite ispravan sigurnosni kod',
		'required' => 'Unesite sigurnosni kod',
		'valid' => 'Unijeli ste pogrešan sigurnosni kod',
	) ,
	'comment_author' => array(
		'length' => 'Polje ime zahtjeva najmanje 3 znaka',
		'required' => 'Ime je obavezno',
	) ,
	'comment_description' => array(
		'required' => 'Komentari su obavezni',
	) ,
	'comment_email' => array(
		'email' => 'Vaša Email adresa je pogrešno unešena',
		'length' => 'Polje Email zahtjeva najmanje 4 znaka, a najviše 64 znaka.',
		'required' => 'Unesite email adresu ukoliko je kockica oznacena.',
	) ,
);
