<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-14 06:10+0000
// PO revision date:  2012-12-13 10:28+0000
$lang = array(
	'config' => 'konfiguracijska datoteka',
	'controller' => 'kontroler',
	'driver' => 'drajver',
	'driver_implements' => 'Drajver "%s" za "%s" biblioteku mora biti implementiran u "%s" interfejsu.',
	'driver_not_found' => '"%s" drajver za "%s" biblioteku nije pronađen.',
	'errors_disabled' => 'Može te otvoriti <a href="%s">naslovnu stranicu</a> ili <a href="%s">pokušati ponovo</a>',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Nemoguće izvršiti zahtjev.',
	'helper' => 'pomoćnik',
	'invalid_filetype' => 'Traženi tip podatka, .%s, nije dozvoljen u konfiguracijskoj datoteci.',
	'invalid_method' => 'Ne postojeća metoda %s pozvana u %s',
	'invalid_property' => 'Atribut "%s" ne postoji u klasi "%s".',
	'library' => 'biblioteka',
	'log_dir_unwritable' => 'Log direktorij nije zaključan: %s',
	'model' => 'model',
	'no_controller' => 'Ushahidi nije mogao odrediti kontroler za procesiranje upita: "%s"',
	'no_default_route' => 'Molimo podesi te početnu rutu u "config/routes.php"',
	'page_not_found' => 'Stranica koju ste tražili, %s, nije pronađena.',
	'report_bug' => '<a href="%s" id="show_bugs">Prijavi ovaj problem Ushahidi-u</a>',
	'resource_not_found' => 'Upit "%s", "%s", nije mogao biti pronađen.',
	'stack_trace' => 'Prateća Poruka',
	'stats_footer' => 'Učitano za {execution_time} s. , korišteno {memory_usage} memorije. Generisano sa Ushahidi v%s.',
	'text_direction' => 'ltr',
	'there_can_be_only_one' => 'Može biti samo jedna instanca Ushahidi po upitu.',
	'uncaught_exception' => 'Neuhvaćen %s: %s u datoteci %s na liniji %s',
	'view' => 'pogled',
	'view_set_filename' => 'Mora te podesiti naziv "view" datoteke prije početka render-a.',
);
