<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-10-25 16:06+0000
$lang = array(
	'admin_footer' => 'Ova poruka je poslata sa vaše web stranice.',
	'admin_login_url' => 'Prijava Administratora',
	'admin_new_comment' => array(
		'message' => 'Novi komentar je postavljen na vašoj web stranici kao odgovor na:',
		'subject' => 'Novi komentar',
	) ,
	'admin_new_email' => array(
		'message' => 'Nova e-mail poruka je poslana na vašoj web stranici.',
		'subject' => 'Nova e-mail poruka',
	) ,
	'admin_new_report' => array(
		'message' => 'Novi izvještaj je podnešen na vašoj web stranici',
		'subject' => 'Novi izvještaj',
	) ,
	'admin_new_sms' => array(
		'message' => 'Nova tekstualna poruka je podnešena na vašoj web stranici.',
		'subject' => 'Nova tekstualna poruka',
	) ,
	'member_new_alert' => array(
		'message' => 'Primiliste ste novo upozorenje',
		'subject' => 'Novo upozorenje',
	) ,
	'member_new_message' => array(
		'message' => 'Dobili ste privatnu poruku',
		'subject' => 'Nova privatna poruka',
		'footer' => 'Za odgovor molimo idete na:',
	) ,
);
