<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-10-26 07:45+0000
$lang = array(
	'latitude' => array(
		'between' => 'Polje za unos geografske širine ne sadrži validnu vrednost geografske širine.',
		'required' => 'Polje za unos geografske širine se mora popuniti. Molimo vas, kliknite na mapu kako biste odredili tačnu lokaciju.',
	) ,
	'level_id' => array(
		'numeric' => 'Polje za Nivo Izvještavača ne sadrži validni Nivo.',
		'required' => 'Polje za Nivo Izvještavača ne sadrži validni Nivo.',
	) ,
	'location_name' => array(
		'length' => 'Unos u polje za ime lokacije ne sme biti kraće od 3 i duže od 200 karaktera.',
		'required' => 'Polje sa imenom lokacije se mora popuniti.',
	) ,
	'longitude' => array(
		'between' => 'Polje za unos geografske dužine ne sadrži validnu vrednost geografske dužine.',
		'required' => 'Polje za unos geografske dužine se mora popuniti. Molimo vas, kliknite na mapu kako biste odredili tačnu lokaciju.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Ime izvještavača nije validno',
		'required' => 'Ime izvještavača nije validno',
	) ,
);
