<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-10-26 23:11+0000
$lang = array(
	'description' => array(
		'length' => 'Polje opis mora da sadrži najmanje 3 i ne više od 100 karaktera. ',
		'required' => 'Polje Opis je neophodno ispuniti',
	) ,
	'name' => array(
		'alpha_numeric' => 'Polje Ime mora sadržavati slova ili brojeve',
		'length' => 'Polje ime mora da sadrži najmanje 2 i ne više od 30 karaktera.',
		'nomodify' => 'Super Admin uloga se ne može mijenjati.',
		'required' => 'Polje Ime je neophodno ispuniti',
	) ,
	'access_level' => array(
		'numeric' => 'Polje razina pristupa mora biti broj između 0-100.',
		'required' => 'Polje razina pristupa mora biti broj između 0-100.',
	) ,
	'permissions' => array(
		'numeric' => 'Polje dozvole mora biti broj između 0-100.',
	) ,
);
