<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-29 06:22+0000
// PO revision date:  2013-06-28 19:57+0000
$lang = array();
