<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-28 06:18+0000
// PO revision date:  2013-05-27 16:11+0000
$lang = array(
	'error' => 'Duombazės klaida: %s',
	'table_not_found' => 'Lentelė "%s" nerasta duombazei. Prašome įsitikinti kad naudojate naujausia duombazės versiją šiai Ushahidi versijai.',
);
