<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-28 06:18+0000
// PO revision date:  2013-05-27 16:09+0000
$lang = array(
	'imap_stream_not_opened' => 'Neįmanoma atidaryti IMAP srautą.',
	'unsupported_service' => 'Elektroninio pašto tiekėjas nepalaikomas.',
);
