<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-09 11:01+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vui lòng điền vào mã an ninh hợp lệ.',
		'required' => 'Vui lòng điền vào mã an ninh.',
	) ,
	'email' => array(
		'email' => 'Phần thông tin về địa chỉ email không chứa địa chỉ email hợp lệ?',
		'length' => 'Phần khung thông tin email phải chứa ít nhất 4 ký tự và tối đa 64 ký tự về độ dài.',
		'required' => 'Phần khung thông tin email yêu cầu phần lựa chọn phải được đánh dấu chọn.',
	) ,
	'error' => array(
		'required' => 'Phần khung thông tin về lỗi không được để trống.',
	) ,
	'subject' => array(
		'length' => 'Phần khung thông tin chủ đề phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'Phần khung thông tin về chủ đề không được để trống.',
	) ,
	'yourname' => array(
		'length' => 'Phần khung thông tin tên phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'Phần khung thông tin về tên không được để trống.',
	) ,
);
