<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-09 14:39+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vui lòng điền vào mã an ninh hợp lệ.',
		'valid' => 'Vui lòng điền vào mã an ninh hợp lệ.',
		'required' => 'Vui lòng điền vào mã an ninh.',
	) ,
	'contact_email' => array(
		'email' => 'Phần khung thông tin email dường như chứa địa chỉ email không hợp lệ.',
		'length' => 'Phần thông tin email phải chứa ít nhất 4 và không được nhiều hơn 64 ký tự.',
		'required' => 'Phần thông tin email được yêu cầu nếu phần lựa chọn được chọn.',
	) ,
	'contact_message' => array(
		'required' => 'Phần nội dung tin nhắn không được để trống.',
	) ,
	'contact_name' => array(
		'length' => 'Phần khung thông tin tên phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'Phần khung thông tin tên không được để trống.',
	) ,
	'contact_subject' => array(
		'length' => 'Phần khung thông tin chủ đề phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'Phần khung thông tin về chủ đề không được để trống.',
	) ,
	'email_send' => array(
		'failed' => 'Xảy ra lỗi khi gửi đi tin nhắn của bạn.',
	) ,
);
