<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-09 14:57+0000
$lang = array(
	'date' => 'NGÀY THÁNG',
	'feed_name' => array(
		'length' => 'Phần khung thông tin tên feed phải có ít nhất 3 ký tự 
			tối đa 70 ký tự về độ dài.',
		'required' => 'Vui lòng điền vào tên của feed.',
	) ,
	'feed_url' => array(
		'required' => 'Vui lòng điền vào đường dẫn liên kết của feed.',
		'url' => 'Vui lòng điền vào đường dẫn hợp lệ, ví dụ: http://www.ushahidi.com',
	) ,
	'source' => 'NGUỒN',
	'title' => 'Tiêu đề',
);
