<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:24+0000
// PO revision date:  2013-07-09 15:07+0000
$lang = array(
	'imap_stream_not_opened' => 'Không thể mở luồng dữ liệu dạng IMAP.',
	'unsupported_service' => 'Dịch vụ email này không được hỗ trợ.',
);
