<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 13:09+0000
$lang = array(
	'category_color' => array(
		'required' => 'Zahtevano je barvno polje.',
	) ,
);
