<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 18:23+0000
$lang = array(
	'akismet_cannot_connect' => 'Povezava na Akismet server ni mogoča.',
	'askimet_invalid_apikey' => 'Vaš Akismet API ključ ni veljaven.',
	'clickatell_no_destination_address' => 'Prosim določite naslov prejemnika (ZA)!',
	'clickatell_no_sender_address' => 'Prosim določite naslov vira (OD)!',
	'clickatell_unsupported_method' => 'Nepodprta metoda pošiljanja!',
	'invalid_api_library' => 'API knjižnica %s ni veljavna. Vse API knjižnice morajo biti podrazredi %s.',
	'upgrade_directory_not_deleted' => 'Direktori <code>%s</coded> ne mora biti izbrisan.',
	'upgrade_extracting_error' => 'Napaka med ekstrakcijo: <code>%s</code>',
	'upgrade_failed' => 'Prenos zadnje verzije Ushahidi ni uspel. HTTP status code',
	'upgrade_file_not_copied' => 'Datoteka <code>%s</coded> ne mora biti kopirana.',
	'upgrade_file_not_deleted' => 'Datoteka <code>%s</coded> ne mora biti izbrisana.',
	'upgrade_zip_error' => 'Prenesena Ushahidi zip datoteka <code>%s</code>, ne mora biti zapisana.',
	'riverid_variable_not_available' => '%s ni dostopna v RiverID class.',
);
