<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 12:25+0000
$lang = array(
	'message' => 'Oprostite, naša stran je trenutno nedosegljiva zaradi vzdrževanja. Prosimo, poskusite znova čez nekaj minut.',
);
