<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 12:24+0000
$lang = array(
	'captcha' => array(
		'default' => 'Prosim vnesite veljavno varnostno geslo.',
		'required' => 'Prosim vnesite varnostno geslo.',
	) ,
	'email' => array(
		'email' => 'Vnešeni Email naslov ni veljaven. ',
		'length' => 'Email mora vsebovati najmanj 4 in največ 64 znakov.',
		'required' => 'Email naslov je zahtevan v primeru, da je označen checkbox.',
	) ,
	'message' => array(
		'required' => 'Potrebno je izpolniti okno za komentar.',
	) ,
	'name' => array(
		'length' => 'Ime mora vsebovati najmanj 3 znake.',
		'required' => 'Potrebno je izpolniti okno z imenom.',
	) ,
	'phone' => array(
		'length' => 'Vnešena telefonska številka ni veljavna.',
	) ,
);
