<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 12:36+0000
$lang = array(
	'approved' => 'Odobreno',
	'categories' => 'kategorije',
	'category_impact' => 'Vpliv kategorije',
	'choose_date_range' => 'Izberite razpon datumov.',
	'countries' => 'Države',
	'country' => 'Država',
	'error' => 'Napaka',
	'glossary' => 'Slovar',
	'legend' => 'Legenda',
	'pageviews' => 'Pogled strani',
	'pageviews_description' => 'Skupno število strani, ki so si jih ogledali obiskovalci',
	'reports' => 'Poročila',
	'reports_categories' => 'Kategorije poročil',
	'reports_statistics' => 'Statistika poročil',
	'reports_status' => 'Status poročil',
	'time_range_1' => '1 mesec',
	'time_range_2' => '3 mesece',
	'time_range_3' => '6 mesecev',
	'time_range_all' => 'Vse',
	'unapproved' => 'neodobreno',
	'unique_visitors' => 'Posebni obiskovalci',
	'unverified' => 'Nepreverjeno',
	'verified' => 'preverjeno',
	'visitor_summary' => 'Dnevnik obiskovalcev',
	'visits' => 'Obiski',
);
