<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-08 06:14+0000
// PO revision date:  2013-04-07 20:05+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'To doda poročilo k dodatnim kategorijam. Če izberete kategorijo 1 in poročilo že vsebuje kategorijo 2, bo poročilo vsebovalo obe kategoriji; kategorijo 1 in kategorijo 2.',
		'approve' => 'Odobrite ali zavrnite poročilo. Če bo poročilo odobreno bo postalo javno vidno.',
		'email_body' => 'Jedro email sporočila, ki bo bilo poslano.',
		'email_subject' => 'Naslov email sporočila, ki bo poslano.',
		'report_title' => 'To je osnovni naslov, ki se doda poročilu.',
	) ,
	'private_subject' => 'Naslov privatnega sporočila',
	'private_message' => 'Privatno sporočilo',
	'profile_email' => 'Vaš email naslov',
	'profile_username' => 'Vaše uporabniško ime ne mora biti spremenjeno.',
);
