<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-25 12:46+0000
$lang = array(
	'captcha' => array(
		'default' => '정확한 보안문자를 입력해주세요.',
		'required' => '보안문자를 입력해주세요.',
		'valid' => '비밀번호가 맞지 않습니다.',
	) ,
	'comment_author' => array(
		'length' => '이름은 최소 3자 이상이어야 합니다.',
		'required' => '이름을 입력해주세요.',
	) ,
	'comment_description' => array(
		'required' => '코멘트를 입력해주세요.',
	) ,
	'comment_email' => array(
		'email' => '입력한 이메일 주소가 유효하지 않습니다.',
		'length' => '이메일은 최소 4~64자가 입력되어야 합니다.',
		'required' => '체크박스 체크 시 이메일 입력은 필수입니다.',
	) ,
);
