<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-01 23:33+0000
$lang = array(
	'captcha' => array(
		'default' => '정확한 보안문자를 입력해주세요.',
		'valid' => '유효한 보안코드를 입력하세요.',
		'required' => '보안문자를 입력해주세요.',
	) ,
	'contact_email' => array(
		'email' => '입력한 이메일 주소가 유효하지 않습니다.',
		'length' => '이메일은 최소 4~64자가 입력되어야 합니다.',
		'required' => '체크박스 체크 시 이메일 입력은 필수입니다.',
	) ,
	'contact_message' => array(
		'required' => '메시지를 입력해주세요.',
	) ,
	'contact_name' => array(
		'length' => '이름은 최소 3자 이상이어야 합니다.',
		'required' => '이름을 입력해주세요.',
	) ,
	'contact_subject' => array(
		'length' => '제목은 최소 3자 이상이어야 합니다.',
		'required' => '제목을 입력해주세요.',
	) ,
	'email_send' => array(
		'failed' => '메시지 전송 시 오류가 발생했습니다.',
	) ,
);
