<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:40+0000
$lang = array(
	'layer_color' => array(
		'length' => '컬러필드는 6자이상이어야 합니다.',
		'required' => '컬러필드를 입력해주세요.',
	) ,
	'layer_file' => array(
		'type' => '다음의 파일포맷만 사용가능합니다. .KMZ, .KML.',
		'valid' => '허용되지 않은 파일포맷의 경우 나타나지 않습니다.',
	) ,
	'layer_name' => array(
		'length' => '이름은 최소 3자이상 80자이하여야 합니다.',
		'required' => '이름을 입력해주세요.',
	) ,
	'layer_url' => array(
		'atleast' => 'KML Url 또는 File 을 입력해주세요.',
		'both' => 'KML file 과 url을 동시에 사용할 수 없습니다.',
		'url' => '정확한 URL을 입력해주세요. 예. http://www.ushahidi.com/layerl.kml',
	) ,
);
