<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-25 12:41+0000
$lang = array(
	'akismet_cannot_connect' => 'Akismet 서버와 연결할 수 없습니다.',
	'akismet_cannot_retrieve' => 'Akismet 에 반응을 검색할 수 없습니다.',
	'api_library_not_found' => 'API 라이브러리: <strong>%s</strong> 을 위한  <strong>%s</strong> 클래스를 찾을 수 없습니다. API task routing table를 확인해 보세요.',
	'askimet_invalid_apikey' => '유효하지 않은 Akismet API 키입니다.',
	'clickatell_fopen_error' => 'fopen를 보내는 과정에서 오류가 발생하셨습니다. PHP가 OpenSSL를 갖고 있는지 혹은 PHP 버젼이 5.2 보다 높은지 확인해 보세요.',
	'clickatell_message_too_long' => '현재 유니코드 메시지가 너무 깁니다. (현재 길이=',
	'clickatell_no_destination_address' => '목표 주소를 명확히 해주세요(TO)!',
	'clickatell_no_sender_address' => '출처를 명확히 해주세요(FROM)!',
	'clickatell_unicode_message_too_long' => '현재 유니코드 메시지가 너무 깁니다. (현재 길이=',
	'clickatell_unsupported_method' => '지원하지 않는 보내기 형식입니다.',
	'invalid_api_library' => '%s 는 유효하지 않는 API library 입니다. 모든 API library는 %s 의 서브클래스이어야 합니다.',
	'upgrade_directory_not_deleted' => '디렉토리 <code>%s</coded> 는 삭제 할 수 없습니다.',
	'upgrade_extracting_error' => '추출하는 동안 에러 발생 : <code>%s</code>',
	'upgrade_failed' => '최선 버젼의 우샤히디를 다운 받는데 실패하였습니다. HTTP status code',
	'upgrade_file_not_copied' => '파일 <code>%s</coded> 는 복사 할 수 없습니다.',
	'upgrade_file_not_deleted' => '파일 <code>%s</coded> 는 삭제 할 수 없습니다.',
	'upgrade_title' => '유샤히디 업그레이드 스크립트',
	'upgrade_zip_error' => '다운로드된  Ushahidi zip file <code>%s</code>, 쓰기를 할 수 없습니다.',
	'riverid_variable_not_available' => '%s 는 RiverID class에서 사용할 수 없습니다.',
);
