<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:45+0000
$lang = array(
	'admin_footer' => '이 메시지는 귀하의 웹사이트에서 전송되었습니다..',
	'admin_login_url' => '관리자 로그인',
	'admin_new_comment' => array(
		'message' => '새로운 댓글이 등록되었습니다. 답변은 : ',
		'subject' => '새 댓글',
	) ,
	'admin_new_email' => array(
		'message' => '새로운 이메일이 도착하였습니다.',
		'subject' => '새 이메일',
	) ,
	'admin_new_report' => array(
		'message' => '새로운 리포트가 등록되었습니다.',
		'subject' => '새 리포트',
	) ,
	'admin_new_sms' => array(
		'message' => '새로운 문자가 도착하였습니다.',
		'subject' => '새 문자',
	) ,
	'member_new_alert' => array(
		'message' => '새 알람을 받았습니다.',
		'subject' => '새로운 알람!',
	) ,
	'member_new_message' => array(
		'message' => '비공개 메시지를 받았습니다.',
		'subject' => '새 비공개 메시지',
		'footer' => '비공개 메시지 응답은 : ',
	) ,
);
