<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-25 12:29+0000
$lang = array(
	'page_title' => array(
		'required' => '페이지의 제목을 입력해 주세요.',
		'length' => '페이지의 제목은 최소 3자 최대 150자이어야 합니다.',
	) ,
	'page_tab' => array(
		'required' => '페이지 탭에 이름을 입력해 주세요.',
	) ,
	'page_description' => array(
		'required' => '페이지를 설명하는 글을 입력해 주세요.',
	) ,
);
