<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-22 06:10+0000
// PO revision date:  2012-12-21 22:22+0000
$lang = array(
	'incident_id' => array(
		'required' => '체크한 아이템을 다시 한 번 확인해주세요.',
		'numeric' => '체크한 아이템을 다시 한 번 확인해주세요.',
		'categories_required' => '리포트는 승인 전 반드시 카테고리에 속해 있어야 합니다.',
	) ,
	'action' => array(
		'permission' => '이것을 실행하기 위해 허락이 필요없습니다.',
	) ,
	'uploadfile' => array(
		'required' => '업로드하기 위해 파일을 선택하세요',
		'type' => '업로드 파일은 .csv 또는 .xml 형식이어야 합니다',
		'valid' => '파일 업로드 필드에 유효하지 않는 파일이 포함되어 있습니다.',
	) ,
);
