<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-13 06:24+0000
// PO revision date:  2013-07-12 21:27+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Por favor verifica que has seleccionado un ítem',
		'numeric' => 'Por favor verifica que has seleccionado un ítem',
		'categories_required' => 'Los reportes deben ser categorizados antes de ser aprobados',
	) ,
	'action' => array(
		'permission' => 'No tienes permiso para realizar esta acción',
	) ,
	'uploadfile' => array(
		'required' => 'Debes seleccionar un archivo a subir',
		'type' => 'El archivo a subir debe ser del formato .csv o .xml',
		'valid' => 'El campo Archivo a Subir no parece contener un archivo válido',
	) ,
);
