<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-15 05:55+0000
$lang = array(
	'captcha' => array(
		'default' => 'Մուտքագրեք ճիշտ պաշտպանության կոդ:',
		'required' => 'Մուտքագրեք պաշտպանության կոդը:',
	) ,
	'email' => array(
		'email' => 'Էլ-փոստի դաշտում նշված հասցեն ճիշտ չէ:',
		'length' => 'Էլ-փոստի դաշտում կարող եք մուտքագրել առնվազն 4 և առավելագույնը` 64 նիշ:',
		'required' => 'Մուտքագրեք էլ-փոստի հասցեն, կամ հանեք վանդակից համապատասխան նշումը:',
	) ,
	'error' => array(
		'required' => 'Մուտքագրեք սխալի նկարագրությունը:',
	) ,
	'subject' => array(
		'length' => '«Թեմա» դաշտը չի կարող պարունակել 3-ից պակաս նիշ:',
		'required' => 'Մուտքագրեք «Թեմա» դաշտը:',
	) ,
	'yourname' => array(
		'length' => '«Անուն» դաշտը չի կարող պարունակել 3-ից պակաս նիշ:',
		'required' => 'Մուտքագրեք «Անուն» դաշտը:',
	) ,
);
