<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-15 06:03+0000
$lang = array(
	'date' => 'Ամսաթիվ',
	'feed_name' => array(
		'length' => 'Լրահոսի անվանումը պետք է պարունակի առնվազն 3 և առավելագույնը` 70 նիշ:',
		'required' => 'Մուտքագրեք լրահոսի անվանումը',
	) ,
	'feed_url' => array(
		'required' => 'Մուտքագրեք լրահոսի URL-ն:',
		'url' => 'URL-ն ճիշտ մուտքագրեք, օր. http://www.ushahidi.com',
	) ,
	'source' => 'Աղբյուր',
	'title' => 'Վերնագիր',
);
