<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-15 06:10+0000
$lang = array(
	'layer_color' => array(
		'length' => 'Գույնի երկարությունը պետք է լինի 6 նիշ:',
		'required' => 'Նշեք շերտավորման գույնը:',
	) ,
	'layer_file' => array(
		'type' => 'Ֆայլը վնասված է կամ չունի ճիշտ ձևաչափ: Ընդունելի ձևաչափերն են` .KMZ, .KML:',
		'valid' => 'Ֆայլը վնասված է կամ չունի ճիշտ ձևաչափ:',
	) ,
	'layer_name' => array(
		'length' => 'Անվանումը պետք է պարունակի առնվազն 3 և առավելագույնը` 80 նիշ:',
		'required' => 'Մուտքագրեք անվանումը:',
	) ,
	'layer_url' => array(
		'atleast' => 'Նշեք կա՛մ KML/KMZ Url, կա՛մ KML/KMZ ֆայլ:',
		'both' => 'Դուք չեք կարող միաժամանակ նշել և՛ KML/KMZ Url, և՛ KML/KMZ ֆայլ:',
		'url' => 'Մուտքագրեք ճիշտ URL: Օր. http://www.ushahidi.com/layerl.kml',
	) ,
);
