<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-15 06:25+0000
$lang = array(
	'approved' => 'Հաստատված',
	'categories' => 'Կատեգորիաներ',
	'category_impact' => 'Կատեգորիաների ազդեցությունը',
	'category_impact_description' => 'Այս գրաֆիկը հնարավորություն է տալիս նշված ժամանակահատվածում գծայնորեն դիտել ահազանգերը ըստ կատեգորիաների: Տեղաշարժելով ձախից աջ, կարող եք դիտել տարբեր կատեգորիաների համեմատությունը: Տեղաշարժելով մկնիկը գրաֆիկի վրայով, կարող եք դիտել մանրամասները:',
	'choose_date_range' => 'Ընտրեք ժամանակային միջակայքը',
	'countries' => 'Երկրներ',
	'country' => 'Երկիր',
	'country_breakdown' => 'Ըստ երկրների',
	'description' => 'Ողջույն: Սա վիճակագրության բաժինն է: Օգտվեք հղումներից համապատասխան վիճակագրությունը դիտելու համար:',
	'error' => 'Սխալ',
	'glossary' => 'Բառացանկ',
	'hit_summary' => 'Հիթերի վիճակագրություն',
	'legend' => 'Պարզաբանում',
	'pageviews' => 'Էջերի դիտումներ',
	'pageviews_description' => 'Կայքի այցելուների կողմից դիտված էջերի ընդհանուր քանակը:',
	'reports' => 'Ահազանգեր',
	'reports_categories' => 'Ահազանգերի կատեգորիաները',
	'reports_statistics' => 'Ահազանգերի վիճակագրություն',
	'reports_status' => 'Ահազանգերի կարգավիճակը',
	'report_stats' => 'Ահազանգեր',
	'stats_not_setup' => 'Վիճակագրությունը պատրաստ չէ',
	'time_range_1' => '1 ամիս',
	'time_range_2' => '3 ամիս',
	'time_range_3' => '6 ամիս',
	'time_range_all' => 'Բոլորը',
	'unapproved' => 'Չհաստատված',
	'unique_visitors' => 'Ունիկալ Այցելուներ',
	'unique_visitors_description' => 'Կայքի այցելուների քանակը: Ունիկալ Այցելուները որոշվում են cookie-ների միջոցով: Եթե այցելուի մոտ cookie-ներ արգելափակված են, ապա նրանք հաշվառվում են օգտագործելով IP հասցեն, դիտարկիչը, օպերացիոն համակարգը և այլն:',
	'unverified' => 'Չստուգված',
	'verified' => 'Ստուգված',
	'visitor_summary' => 'Այցելությունների վիճակագրություն',
	'visits' => 'Այցելություններ',
	'visits_description' => 'Այցելությունը ունիկալ այցելուի գրանցումն է իր վերջին էջի դիտումից ավելի քան 30 րոպե հետո:',
);
