<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 21:36+0000
$lang = array(
	'captcha' => array(
		'default' => 'Sartu baliozko segurtasun kodea mesedez',
		'required' => 'Sartu segurtasun kodea mesedez',
	) ,
	'email' => array(
		'email' => 'Email eremuak ez du baliozko email helbiderik duenik ematen',
		'length' => 'Email eremuak ezin du 4 hizki baino gutxiago eta 64 baino gehiago eduki',
		'required' => 'Email eremua beharrezkoa da laukitxoa hautatuta badago.',
	) ,
	'error' => array(
		'required' => 'Akatsaren eremua betetzea beharrezkoa da.',
	) ,
	'subject' => array(
		'length' => 'Gaiaren eremuak gutxienez 3 karaktere izan behar ditu.',
		'required' => 'Gaiaren eremua betetzea beharrezkoa da.',
	) ,
	'yourname' => array(
		'length' => 'Izenaren eremuak gutxienez 3 karaktere izan behar ditu.',
		'required' => 'Izenaren eremua betetzea beharrezkoa da.',
	) ,
);
