<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 22:03+0000
$lang = array(
	'date' => 'DATA',
	'feed_name' => array(
		'length' => 'Iturriaren izenak gutxienez 3 eta gehienez ⏎
⇥⇥⇥70 karaktere izan bear ditu.',
		'required' => 'Sar ezazu, mesedez, iturriaren izena.',
	) ,
	'feed_url' => array(
		'required' => 'Sartu mesedez iturriaren URLa.',
		'url' => 'Sar ezazu, mesedez, URL baliagarri bat, adb. http://www.ushahidi.com',
	) ,
	'source' => 'JATORRIA',
	'title' => 'Izenburua',
);
