<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 13:36+0000
$lang = array(
	'field_default' => array(
		'default' => 'Eremuarentzat emandako balio lehenetsia baliogabea da',
		'length' => 'Eremuaren izenak 3 hizki baino gehiago izan behar ditu eta 200 baino gutxiago',
	) ,
	'field_height' => array(
		'between' => '0 eta 50 bitarteko balore bat sartu eremuaren altuerarentzat, mesedez',
	) ,
	'field_isdate' => array(
		'between' => 'Data eremuarentzat balore baliogabea sartu duzu',
		'required' => 'aukeratu Bai edo Ez data eremuetan',
	) ,
	'field_name' => array(
		'length' => 'Eremuaren izenak 3 hizki baino gehiago izan behar ditu eta 100 baino gutxiago',
		'required' => 'Sartu eremuaren izena, mesedez',
		'duplicate' => 'Sartu duzun eremu izena badago formulario honetan, Aukeratu beste bat, mesedez',
	) ,
	'field_required' => array(
		'between' => 'Beharrezko eremuarentzat balore baliogabea sartu duzu',
		'required' => 'aukeratu Bai edo Ez beharrezko eremuetan',
	) ,
	'field_type' => array(
		'numeric' => 'Aukeratu baliozko eremu mota, mesedez',
		'required' => 'Aukeratu eremu mota, mesedez',
	) ,
	'field_width' => array(
		'between' => '0 eta 300 bitarteko balore bat sartu eremuaren zabalerarentzat, mesedez',
	) ,
	'form_description' => array(
		'required' => 'Sartu formularioaren deskribapena, mesedez',
	) ,
	'form_id' => array(
		'default' => 'Lehenetsitako formularioa ezaba ezina da.',
		'numeric' => 'Aukeratu zein formulariotara gehituko den eremu hau.',
		'required' => 'Aukeratu zein formulariotara gehituko den eremu hau.',
	) ,
	'form_title' => array(
		'length' => 'Formularioaren eremuaren izenak 3 hizki baino gehiago izan behar ditu eta 100 baino gutxiago',
		'required' => 'Sartu formularioaren izena, mesedez',
		'exists' => 'Dagoeneko titulu hau duen formularioa badago. Beste bat aukeratu mesedez',
	) ,
);
