<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-22 06:17+0000
// PO revision date:  2013-05-21 15:50+0000
$lang = array(
	'reports_view' => 'Txostenak ikusi',
	'reports_edit' => 'Txostenak sortu/ezabatu/editatu',
	'reports_approve' => 'Txostenak onartu',
	'reports_verify' => 'Txostenak egiaztatu',
	'reports_comments' => 'Kudeatu txostenen iruzkinak',
	'reports_download' => 'Txostenak jaitsi',
	'reports_upload' => 'Txostenak kargatu',
	'messages' => 'Mezuak kudeatu',
	'messages_reporters' => 'Kudeatu mezu bidaltzaileak',
	'stats' => 'Estatistiken txostena',
	'settings' => 'Ezarpenak aldatu',
	'manage' => 'Kudeatzaile panela',
	'users' => 'Kudeatu erabiltzaileak',
	'manage_roles' => 'Kudeatu rolak',
	'checkin' => 'Erregistratu daiteke',
	'checkin_admin' => 'Kudeatu erregistroak',
	'admin_ui' => 'Admin interfaze sarrera',
	'member_ui' => 'Kide interfaze sarrera',
);
