<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-21 06:17+0000
// PO revision date:  2013-05-20 23:03+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'ID nagusia zenbakia izan behar du',
	) ,
	'private_to' => array(
		'required' => 'Izena eremua beharrezkoa da',
		'exists' => 'Mezua bidali nahi diozun erabiltzailea ez da existitzen',
	) ,
	'private_subject' => array(
		'required' => 'Gaiaren eremua beharrezkoa da.',
		'length' => 'Orrialdearen izenburuak gutxienez 3 eta gehienez 150 karaktere izan behar ditu luzeran.',
	) ,
	'private_message' => array(
		'required' => 'Mezu eremua beharrezkoa da',
	) ,
);
