<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-05-24 06:17+0000
// PO revision date:  2013-05-23 12:22+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Email eremuak ez du baliozko helbiderik.',
		'required' => 'Mezu eremua beharrezkoa da.',
	) ,
	'allow_feed' => array(
		'between' => 'Badirudi feed-a sartu eremuan balio egokirik ez duela.',
		'required' => 'Feed-a sartu eremua beharrezkoa da.',
	) ,
	'allow_alerts' => array(
		'between' => 'Badirudi abisuak baimendu eremuak ez duela balio egokirik.',
		'required' => 'Abisuak baimendu eremua beharrezkoa da.',
	) ,
	'allow_reports' => array(
		'between' => 'Badirudi txostenak baimendu eremuak balio egokirik ez duela',
		'required' => 'Txostenak baimendu eremua beharrezkoa da.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Badirudi \'estatistikak elkarbanatu\' eremuak ez du balio egokirik.',
		'required' => 'Estatistitak elkarbanatu eremua nahitaezkoa da.',
	) ,
	'cache_pages' => array(
		'between' => 'Cache orrialdeen eremua',
	) ,
	'cleanurl' => array(
		'enable_clean_url' => 'Aukera eman URLak garbitzeko',
		'title' => 'Garbitu URLak',
	) ,
	'configure_map' => 'Mapa konfiguratu',
	'default_location' => 'Berezko kokapena',
	'default_map_all' => array(
		'alpha_numeric' => 'Badirudi feed-a sartu eremuan balio egokirik ez duela',
		'length' => 'Koloredun eremuak 6 karaktere izan behar ditu.',
		'required' => 'Kolore eremua beharrezkoa da',
	) ,
	'default_map_view' => 'Berezko mapa ikuskera',
	'default_zoom_level' => 'Berezko zoom maila',
	'download_city_list' => 'Eskuratu hiriak Geonames-etik',
	'email_host' => array(
		'length' => 'Mail serbitzariaren portuaren eremua luzeegia da.',
		'numeric' => 'Mail serbitzariaren portuaren eremuak bakarrik zenbakiak eduki beharko lituzke.',
	) ,
	'email_password' => array(
		'required' => 'Mail serbitzariaren pasahitzaren eremua betetzea beharrezkoa da.',
	) ,
	'email_port' => array(
		'length' => 'Mail serbitzariaren portuaren eremua luzeegia da.',
		'numeric' => 'Mail serbitzariaren portuaren eremuak bakarrik zenbakiak eduki beharko lituzke.',
	) ,
	'email_servertype' => array(
		'length' => 'Mail serbitzariaren portuaren eremua luzeegia da. ',
	) ,
	'email_username' => array(
		'length' => 'Mail serbitzariaren erabiltzaile izenaren eremuak 50 karaktere baino gutxiago izan behar ditu.',
		'required' => 'Mail serbitzariaren erabiltzaile izenaren eremua betetzea beharrezkoa da.',
	) ,
	'facebook' => array(
		'title' => 'Facebook Konfigurazio aukerak',
		'app_id' => 'Facebook erabiltzailea',
	) ,
	'https' => array(
		'enable_https' => 'Gaitu HTTPS',
		'title' => 'HTTPS',
	) ,
	'map' => array(
		'zoom' => 'Zoom maila',
	) ,
	'map_provider' => array(
		'choose' => 'Mapa hornitzailea aukeratu',
		'enter_api' => 'API gako berria sartu',
		'get_api' => 'API gakoa lortu',
		'name' => 'Maparen hornitzailea',
	) ,
	'map_timeline' => 'Maparen denbora lerroa',
	'map_settings' => 'Maparen ezarpenak',
	'multiple_countries' => 'Ushahidi instalazio honek herrialde anitz onartzen ditu?',
	'select_default_location' => 'Mesedez, lehenetsitako herria aukeratu',
	'set_location' => 'Klik egin eta arrastatu, mapan zure kokapen zehatza ezartzeko.',
	'site' => array(
		'banner' => 'Lekuko bannerra',
		'blocks_per_row' => 'Blokeak ilarako',
		'cache_pages' => 'Cache orriak',
		'checkins' => 'Gaitu egiaztapenak',
		'default_category_colors' => 'Lehenetsitako koloreak kategori guztientzat',
		'default_category_icons' => 'Lehenetsitako ikonoak kategori guztientzat',
		'delete_banner_image' => 'Banner irudia ezabatu',
		'delete_default_map_all_icon' => 'Lehenetsitako ikonoa ezabatu',
		'display_contact_page' => 'Kontaktu orria erakutsi',
		'display_howtohelp_page' => '"Nola lagundu" orria erakutsi',
		'email_site' => 'Guneko email helbidea',
		'google_analytics' => 'Google Analytics',
		'items_per_page' => 'Elementuak orriko - Front End',
		'items_per_page_admin' => 'Elementuak orriko _ Administrazioa',
		'language' => 'Guneko hizkuntza',
		'manually_approve_users' => 'Erabiltzaileak eskuz onartu',
		'message' => 'Gunearen mezua',
		'name' => 'Gunearen izena',
		'private_deployment' => 'Hedapen pribatuak',
		'require_email_confirmation' => 'Erabiltzailearen email baieztapena beharrezkoa da.',
		'submit_report_message' => 'Bidali txosten mezua',
		'timezone' => 'Ordu gunea',
		'title' => 'Gunearen ezarpenak',
		'twitter_configuration' => 'Twitterren bilaketa zehaztapenak',
		'twitter_hashtags' => 'Hashtag - komekin banandu',
	) ,
	'site_email' => array(
		'email' => 'Guneko emailaren eremuak ez du baliozko email helbidea',
		'length' => 'Gunearen email eremuak gutxienez 4 eta gehienez 64 karaktere izan behar ditu.',
	) ,
	'site_name' => array(
		'length' => 'Gune honetako izen eremuak gutxienez 3 eta gehienez 50 karaktere izan behar ditu.',
		'required' => 'Gunearen izen eremua beharrezkoa da',
	) ,
	'sms' => array(
		'title' => 'SMS Konfigurazio aukerak',
	) ,
	'twitter' => array(
		'title' => 'Twitter Konfigurazio aukerak',
	) ,
	'test_settings' => 'testaren ezarpenak',
);
