<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:18+0000
$lang = array(
	'error' => 'Hitilafu ya databesi%s',
	'table_not_found' => 'Jedwali "%s" halipatikani katika databesi. Tafadhali hakikisha akuwa unatumia toleo jipya zaidi la databesi ya Ushahidi.',
);
