<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:13+0000
$lang = array(
	'imap_stream_not_opened' => 'Mkondo wa IMAP haungefunguka',
	'unsupported_service' => 'Huduma ya barua pepe haijaegemezwa',
);
