<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:14+0000
$lang = array(
	'captcha' => array(
		'default' => 'Tafadhali ingiza kificho cha usalama kilicho sahihi.',
		'required' => 'Tafadhali ingiza kificho cha usalama.',
	) ,
	'email' => array(
		'email' => 'Sehemu ya anwani ya barua pepe inaonekana kuwa na anwani isiyo sahihi.',
		'length' => 'Ni sharti sehemu ya barua pepe iwe ya urefu wa angalau herufi 4 na isizidi herufi 64.',
		'required' => 'Sehemu ya barua pepe inahitajika iwapo kisanduku cha alama kimewekwa alama.',
	) ,
	'message' => array(
		'required' => 'Sehemu ya maoni inahitajika.',
	) ,
	'name' => array(
		'length' => 'Ni sharti sehemu ya majina iwe ya urefu wa herufi 3.',
		'required' => 'Sehemu ya majina inahitajika.',
	) ,
	'phone' => array(
		'length' => 'Sehemu ya nambari ya simu si sahihi.',
	) ,
);
