<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:14+0000
$lang = array(
	'admin_footer' => 'Ujumbe huu ulitumwa kutoka kwa tovuti yako',
	'admin_login_url' => 'Kiingilizi cha Mzimamizi',
	'admin_new_comment' => array(
		'message' => 'Oni jipya limewasilishwa katika tovuti yako ili kujibiza:',
		'subject' => 'Oni jipya',
	) ,
	'admin_new_email' => array(
		'message' => 'Ujumbe mpya wa barua pepe umewasilishwa katika tovuti yako.',
		'subject' => 'Ujumbe Mpya wa Barua pepe',
	) ,
	'admin_new_report' => array(
		'message' => 'Ripoti mpya imewasilishwa katika tovuti yako.',
		'subject' => 'Ripoti Mpya',
	) ,
	'admin_new_sms' => array(
		'message' => 'Ujumbe mpya wa simu umewasilishwa katika tovuti yako.',
		'subject' => 'Ujumbe Mpya wa Simu',
	) ,
	'member_new_alert' => array(
		'message' => 'Umepokea Arifa Mpya',
		'subject' => 'Arifa Mpya!',
	) ,
	'member_new_message' => array(
		'message' => 'Umepokea Ujumbe wa Kibinafsi',
		'subject' => 'Ujumbe Mpya wa Kibinafsi',
		'footer' => 'Ili Kujibu Tafadhali Nenda Kwa: ',
	) ,
);
