<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:22+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'Ni sharti Kitambulisho Kikuu kiandikwe kwa nambari',
	) ,
	'private_to' => array(
		'required' => 'Sehemu ya Kwa inahitajika',
		'exists' => 'Mtumiaji unayejaribu kutumia ujumbe hayupo',
	) ,
	'private_subject' => array(
		'required' => 'Sehemu ya mada inahitajika.',
		'length' => 'Ni sharti mada iwe na kati ya herufi 3 na  150.',
	) ,
	'private_message' => array(
		'required' => 'Sehemu ya ujumbe inahitajika.',
	) ,
);
