<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:23+0000
$lang = array(
	'latitude' => array(
		'between' => 'Sehemu ya latitudi inaonekana kuwa na latitudi isiyo sahihi.',
		'required' => 'Sehemu ya latitudi inahitajika. Tafadhali bonyeza kwenye ramani kuashiria eneo.',
	) ,
	'level_id' => array(
		'numeric' => 'Ngazi ya Ripota inaonekana kuwa na Ngazi isiyo sahihi.',
		'required' => 'Ngazi ya Ripota inaonekana kuwa na Ngazi isiyo sahihi.',
	) ,
	'location_name' => array(
		'length' => 'Ni sharti sehemu ya eneo la majina iwe ya urefu wa angalau herufi 3 na isizidi herufi 200.',
		'required' => 'Sehemu ya eneo la jina inahitajika.',
	) ,
	'longitude' => array(
		'between' => 'Sehemu ya longitudi inaonekana kuwa na longitudi isiyo sahihi.',
		'required' => 'Sehemu ya longitudi inahitajika. Tafadhali bonyeza kwenye ramani kuashiria eneo.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Ripota Asiyekubalika',
		'required' => 'Ripota Asiyekubalika',
	) ,
);
