<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-03 06:23+0000
// PO revision date:  2013-11-02 08:15+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'Sehemu ya ruhusu fikira inaonekana si sahihi',
		'required' => 'Sehemu ya ruhusu fikira inahitajika.',
	) ,
	'allow_feed' => array(
		'between' => 'Sehemu ya ruhusu tawanyiko inaonekana si sahihi',
		'required' => 'Sehemu ya ruhusu tawanyiko inahitajika.',
	) ,
	'allow_alerts' => array(
		'between' => 'The allow alerts field does not appear to contain a valid value.',
		'required' => 'The allow alerts field is required.',
	) ,
	'allow_reports' => array(
		'between' => 'Sehemu ya ruhusu ripoti inaonekana si sahihi',
		'required' => 'Sehemu ya ruhusu ripoti inahitajika.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'Sehemu ya gawanya takwimu inaonekana si sahihi',
		'required' => 'Sehemu ya gawanya takwimu inahitajika.',
	) ,
	'api' => array(
		'default_record_limit' => 'Default number of records to be fetched per API request',
		'maximum_record_limit' => 'Maximum number of records to be fetched per API request',
		'maximum_requests_per_ip_address' => 'Maximum number of API requests per IP address',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'Sehemu ya Akismet inaonekana si sahihi',
		'length' => 'Sehemu ya Akismet inaonekana si sahihi',
	) ,
	'banner_image' => array(
		'size' => 'Tafadhali hakikisha kuwa ukubwa wa "Banner Image" ni mdogo kuliko 250 KB.',
	) ,
	'cache_pages' => array(
		'between' => 'The cache pages field is required.',
		'required' => 'The cache pages field does not appear to contain a valid value.',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'The cache pages lifetime field does not appear to contain a valid value.',
		'required' => 'The cache pages lifetime field is required.',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">this forum post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs (without "index.php" in the URL).',
		'enable_clean_url' => 'Enable Clean URLs',
		'title' => 'Clean URLs',
	) ,
	'clickatell_api' => array(
		'length' => 'Sehemu ya nambari ya Clickatell API haiezi pitisha herufi 20.',
		'required' => 'Sehemu ya nambari ya Clickatell API inahitajika.',
	) ,
	'clickatell_password' => array(
		'length' => 'Sehemu ya nywila ya Clickatell lazma iwe baina ya herufi 5 na 50.',
		'required' => 'Sehemu ya nywila ya Clickatell inahitajika.',
	) ,
	'clickatell_username' => array(
		'length' => 'Sehemu ya nambari ya jina la mtumizi wa Clickatell API haiezi pitisha herufi 20.',
		'required' => 'Sehemu ya nambari ya jina la mtumizi wa Clickatell API inahitajika.',
	) ,
	'configure_map' => 'Sanidi Ramani',
	'default_location' => 'Default Location',
	'default_map_all' => array(
		'alpha_numeric' => 'Sehemu ya rangi inaonekana si sahihi',
		'length' => 'Sehemu ya rangi lazima iwe na herufi 6.',
		'required' => 'Sehemu ya rangi inahitajika.',
	) ,
	'default_map_view' => 'Mandhari ya Ramani ya Awali',
	'default_zoom_level' => 'Zoom ya Ramani ya Awali',
	'download_city_list' => 'Pata miji kutokana na Geonames',
	'email_host' => array(
		'length' => 'Port ya Mail Server ni ndefu sana',
		'numeric' => 'Sehemu ya port ya Mail Server lazima iwe nambari.',
	) ,
	'email_password' => array(
		'length' => 'Sehemu ya nywila ya Mail Server lazma iwe baina ya herufi 5 an 50.',
		'required' => 'Sehemu ya nywila ya Mail Server inahitajika.',
	) ,
	'email_port' => array(
		'length' => 'Port ya Mail Server ni ndefu sana',
		'numeric' => 'Sehemu ya port ya Mail Server lazima iwe nambari.',
	) ,
	'email_servertype' => array(
		'length' => 'Port ya Mail Server ni ndefu sana',
		'required' => 'Sehemu ya aina ya Mail Server inahitajika.',
	) ,
	'email_username' => array(
		'length' => 'Sehemu ya jina la mtumizi wa Mail Server haiezi pitisha herufi 50.',
		'required' => 'Sehemu ya jina la mtumizi wa Mail Server inahitajika.',
	) ,
	'facebook' => array(
		'title' => 'Facebook Setup Options',
		'description' => 'To get the information below you will need to create a new Facebook application at',
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret',
	) ,
	'google_analytics' => array(
		'length' => 'Sehemu ya Google Analytics lazma iwe na Web Property ID sahihi kwa fomati ya UA-XXXXX-XX.',
	) ,
	'https' => array(
		'enable_https' => 'Enable HTTPS',
		'https_disabled' => 'This option makes Ushahidi be accessed in unsecure mode; <strong>without</strong> "https://" in the URL prefix',
		'https_enabled' => 'This option makes Ushahidi be accessed in secure mode; with <strong>https</strong> in the URL prefix',
		'title' => 'HTTPS',
	) ,
	'items_per_page' => array(
		'between' => 'Sehemu ya vipengele kwa kurasa (Uso wa tovuti) inaonekana si sahihi',
		'required' => 'Sehemu ya vipengele kwa kurasa (Uso wa tovuti) inahitajika.',
	) ,
	'items_per_page_admin' => array(
		'between' => 'Sehemu ya vipengele kwa kurasa (Meneja) inaonekana si sahihi',
		'required' => 'Sehemu ya vipengele kwa kurasa (Meneja) inahitajika.',
	) ,
	'map' => array(
		'default_location' => 'Kueka map provider ni jambo rahisi. Chagua provider, Pata API key Kutoka kwa tovuti ya provider, ubandike API key hapa',
		'zoom' => 'Kipimo cha zoom',
	) ,
	'map_provider' => array(
		'choose' => 'Chagua Map Provider',
		'enter_api' => 'Andika API Key mpya',
		'get_api' => 'Pata API Key',
		'info' => 'Kueka map provider ni jambo rahisi. Chagua provider, Pata API key Kutoka kwa tovuti ya provider, ubandike API key hapa',
		'name' => 'Map provider',
	) ,
	'map_timeline' => 'Map Timeline',
	'map_settings' => 'Vipimo vya Ramani',
	'multiple_countries' => 'Je hii Ushahidi inatumika kwenye nchi nyingi',
	'select_default_location' => 'Tafadhali chagua nchi ya awali',
	'set_location' => 'Bonyeza uburute ramani kwa eneo unayoitaka',
	'site' => array(
		'allow_clustering' => 'Kushanya repoti kwa ramani',
		'allow_comments' => 'Ruhusu watumizi kutunga fikira zao kwa kila ripoti',
		'allow_feed' => 'Weka tawanyiko la habari za RSS kwa tovuti',
		'allow_alerts' => 'Allow Users To Subscribe For Alerts',
		'allow_reports' => 'Ruhusu watumizi kutunga ripoti',
		'api_akismet' => 'Key ya Akismet',
		'banner' => 'Site Banner',
		'blocks_per_row' => 'Blocks Per Row',
		'cache_pages' => 'Cache Pages',
		'cache_pages_lifetime' => 'Cache Pages Lifetime',
		'checkins' => 'Enable Checkins',
		'copyright_statement' => 'Site Copyright Statement',
		'default_category_colors' => 'Rangi ya asili kwa jamii zote',
		'default_category_icons' => 'Default Icon For All Categories',
		'delete_banner_image' => 'Delete Banner Image',
		'delete_default_map_all_icon' => 'Delete Default Icon',
		'display_contact_page' => 'Onyesha kurasa ya  mawasiliano',
		'display_howtohelp_page' => 'Onyesha kurasa ya "Ushaidizi"',
		'email_alerts' => 'Anwani ya barua pepe ya kutanabahisha',
		'email_notice' => '<span>Ili kupata repoti na barua pepe, tafadhali sanidi vipimo vyako vya anwani yako ya barua pepe.</span>',
		'email_site' => 'Anwani ya barua pepe ya tovuti',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'Web Property ID - Formato: UA-XXXXX-XX',
		'items_per_page' => 'Vipengele kwa kila kurasa - Uso wa tovuti',
		'items_per_page_admin' => 'Vipengele kwa kila kurasa - Meneja',
		'kismet_notice' => 'Zuia spam kwa fikira kutumia <a href="http://akismet.com/" target="_blank">Akismet</a> kutoka Automattic. <BR />Unaeza pata API key ya bure kwa kujisajilisha kwa <a href="http://en.wordpress.com/api-keys/" target="_blank">akaunti ya mtumizi ya WordPress.com</a>',
		'laconica_configuration' => 'Sifa za Laconica',
		'laconica_site' => 'Tovuti ya Laconica ',
		'language' => 'Lugha ya tovuti',
		'manually_approve_users' => 'Manually Approve Users',
		'message' => 'Site Message',
		'name' => 'Jina la tovuti',
		'private_deployment' => 'Private Deployment',
		'require_email_confirmation' => 'Require User Email Confirmation',
		'submit_report_message' => 'Submit Report Message',
		'share_site_stats' => 'Shriki na takwimu za API na wengine',
		'tagline' => 'Tagline ya tovuti',
		'timezone' => 'Timezone',
		'title' => 'Vipimo vya tovuti',
		'twitter_configuration' => 'Sifa za Twitter',
		'twitter_hashtags' => 'Hashtags - Tofautisha na comma ',
	) ,
	'site_email' => array(
		'email' => 'Anwani ya barua pepe ya tovuti inaonekana si sahihi',
		'length' => 'Anwani ya barua pepe ya tovuti lazma liwe baina ya herufi 4 na 100.',
	) ,
	'site_name' => array(
		'length' => 'Jina la tovuti lazma liwe baina ya herufi 3 na 50.',
		'required' => 'Jina la tovuti linahitajika.',
	) ,
	'site_tagline' => array(
		'length' => 'Jina la tagline lazma liwe baina ya herufi 3 na 100.',
		'required' => 'Jina la tagline linahitajika.',
	) ,
	'sms' => array(
		'clickatell_api' => 'Namba yako ya Clickatell API',
		'clickatell_check_balance' => 'Pesa zilizobaki za Clickatell',
		'clickatell_load_balance' => 'Engeza Credit ya Clickatell',
		'clickatell_password' => 'Nywila yako ya Clickatell',
		'clickatell_text_1' => 'Jiunganishe na Clickatells kwa <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">kubonya hapa</a>',
		'clickatell_text_2' => 'Ingiza maarifa ya kuungana na Clickatell kwa sehemu inayofuata',
		'clickatell_username' => 'Jina la mtumizi wa akaunti yako ya Clickatell',
		'flsms_download' => 'Pakua na usakinishe FrontlineSMS',
		'flsms_text_1' => 'Andika namba za simu za Frontline SMS kwa sehemu inayofuata',
		'flsms_text_2' => 'Andika namba za simu + au mapengo kwa sehemu ifuatayo',
		'option_1' => 'Chaguo la 1: Tumia Frontline SMS',
		'option_2' => 'Chaguo la 2: Tumia SMS Gateway ya kimataifa',
		'title' => 'Vipimo vya SMS',
	) ,
	'sms_no1' => array(
		'length' => 'Sehemu ya number ya simu ya kwanza inaonekana si sahihi',
		'numeric' => 'Sehemu ya number ya simu ya kwanza lazma iwe na nambari.',
	) ,
	'sms_no2' => array(
		'length' => 'Sehemu ya number ya simu ya pili inaonekana si sahihi',
		'numeric' => 'Sehemu ya number ya simu ya pili lazma iwe na nambari.',
	) ,
	'sms_no3' => array(
		'length' => 'Sehemu ya number ya simu ya tatu inaonekana si sahihi',
		'numeric' => 'Sehemu ya number ya simu ya tatu lazma iwe na nambari.',
	) ,
	'twitter' => array(
		'title' => 'Chaguo za Usanidi wa Twitter',
	) ,
);
