<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-03-01 10:16+0000
$lang = array(
	'date' => 'Tarehe ya kuingilia',
	'date_added' => 'Tarehe ya Kuongezwa',
	'last_access' => 'Wakati wa Mwisho wa Kufikiwa',
	'sharing_color' => array(
		'length' => 'Ni sharti sehemu ya rangi iwe ya urefu wa herufi 6.',
		'required' => 'Sehemu ya rangi inahitajika.',
	) ,
	'sharing_name' => array(
		'length' => 'Inaonekana kuwa jina la Kugawiza si sahihi',
		'required' => 'Jina la Kugawiza linahitajika',
	) ,
	'sharing_url' => array(
		'exists' => 'Anwani hii ya tovuti tayari ipo',
		'length' => 'Inaonekana kuwa anwani hii ya tovuti si sahihi',
		'required' => 'Anwani ya tovuti inahitajika.',
		'url' => 'Inaonekana kuwa sehemu ya anwani ya tovuti ina anwani isiyo sahihi.',
	) ,
);
