<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-03 06:25+0000
// PO revision date:  2013-12-02 19:29+0000
$lang = array(
	'category_color' => array(
		'length' => 'O campo cor debe contar con alomenos 6 caracteres de lonxitude.',
		'required' => 'O campo cor é obrigatorio.',
	) ,
	'category_description' => array(
		'required' => 'A descripción é obrigatoria.',
	) ,
	'category_image' => array(
		'size' => 'Asegúrese de que o tamaño de súbida das imaxes estea limitado a 50KB.',
		'type' => 'O campo da imaxe semella que non contén unha imaxe válida.Os únicos formatos aceitados son .JPG, .PNG e .GIF.',
		'valid' => 'O campo da imaxe semella que non contén un ficheiro válido',
	) ,
	'category_title' => array(
		'length' => 'O título debe contar con alomenos 3 caracteres de lonxitude e non mais de 80.',
		'required' => 'O Título é obrigatorio.',
	) ,
	'parent_id' => array(
		'already_parent' => 'Non pode subcategorizar unha categoría que xa conta con subcategorías propias.',
		'exists' => 'A categoría nai non existe.',
		'numeric' => 'A categoría nai debe ser numérica.',
		'parent_trusted' => 'A categoría nai non pode ser unha categoría especial',
		'required' => 'A categoría nai é obrigatoria.',
		'same' => 'A categoría non pode ser a mesma que a categoría nai.',
		'special' => 'As categorías especiais non poden ser subcategorizadas.',
	) ,
);
