<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-03 06:25+0000
// PO revision date:  2013-12-02 20:17+0000
$lang = array(
	'config' => 'arquivo de configuración',
	'controller' => 'controlador',
	'driver' => 'driver',
	'driver_implements' => 'O driver %s para a biblioteca %s ten que implementar a interface %s',
	'driver_not_found' => 'Non se atopa o driver %s para a biblioteca %s.',
	'errors_disabled' => 'Pode ir á <a href="%s">páxina principal</a> ou  <a href="%s">tentar de novo</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Non foi posible completar a solicitude.',
	'helper' => 'asistente',
	'invalid_filetype' => 'A solicitude do tipo de arquivo .%s non é permitida na visualización do ficheiro de configuración.',
	'invalid_method' => 'Método %s inválido solicitado en %s',
	'invalid_property' => 'A propiedade %s non existe na clase %s.',
	'library' => 'biblioteca',
	'log_dir_unwritable' => 'Non se pode escribir no directorio de logs: %s',
	'model' => 'modelo',
	'no_controller' => 'Ushahidi non pode atopar un controlador para o procesamento desta solicitude: %s',
	'no_default_route' => 'Estableza unha ruta por defecto en config/routes.php',
	'page_not_found' => 'Non foi posible atopar a páxina %s solicitada.',
	'report_bug' => '<a href="%s" id="show_bugs">Informe deste atranco a Ushahidi</a></a>',
	'resource_not_found' => 'A solicitude %s, %s, non foi topada.',
	'stack_trace' => 'Rastrexo na Pila de Memoria (Stack Trace)',
	'stats_footer' => 'Cargado en {execution_time} segundos, empregando {memory_usage} de memoria. Xerado por Ushahidi v%s.',
	'text_direction' => 'ead',
	'there_can_be_only_one' => 'Só pode haber unha instancia de Ushahidi por páxina solicitada.',
	'uncaught_exception' => 'Excepción non recollida %s: %s no arquivo %s na liña %s',
	'view' => 'visualizar',
	'view_set_filename' => 'Debe seleccionar a visualización do arquivo antes de renderizalo.',
);
