<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-06 06:25+0000
// PO revision date:  2013-12-05 18:47+0000
$lang = array(
	'field_default' => array(
		'default' => 'O valor por defecto que forneceu para este campo non é válido.',
		'length' => 'O Nome do Campo ha ter alomenos 3 caracteres de lonxitude e non máis de 200.',
	) ,
	'field_height' => array(
		'between' => 'Introduza un valor entre 0 e 50 para a Altura do Campo.',
	) ,
	'field_isdate' => array(
		'between' => 'Introduciu un valor inválido para o Campo de Data.',
		'required' => 'Seleccione Sí ou Non para o Campo de Data.',
	) ,
	'field_name' => array(
		'length' => 'O Nome do Campo debe contar con alomenos 3 caracteres de lonxitude e non máis de 100.',
		'required' => 'Introduza o Nome do Campo.',
		'duplicate' => 'O nome do campo que forneceu xa existe neste mesmo formulario.Por favor, introduza outro distinto.',
	) ,
	'field_required' => array(
		'between' => 'Introduciu un valor inválido para o Campo Obrigatorio.',
		'required' => 'Seleccione Sí ou Non para o Campo Obrigatorio.',
	) ,
	'field_type' => array(
		'numeric' => 'Seleccione un Tipo de Campo válido.',
		'required' => 'Seleccione un Tipo de Campo.',
	) ,
	'field_width' => array(
		'between' => 'Introduza un valor entre 0 e 300 para a Anchura de Campo.',
	) ,
	'form_description' => array(
		'required' => 'Forneza unha Descripción do formulario.',
	) ,
	'form_id' => array(
		'default' => 'O formulario predetermiñado non se pode borrar.',
		'numeric' => 'Seleccione qué formulario engadir a ese campo',
		'required' => 'Seleccione qué formulario engadir a ese campo',
	) ,
	'form_title' => array(
		'length' => 'O nome do campo de formulario debe contar con alomenos 3 caracteres de lonxitudee non máis de 100.',
		'required' => 'Introduza o nome do formulario.',
		'exists' => 'Xa existe un formulario con ese mesmo título. Por favor, escolla outro.',
	) ,
);
