<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-07 06:25+0000
// PO revision date:  2013-12-06 21:59+0000
$lang = array(
	'akismet_cannot_connect' => 'Non se pode conectar ao conector Akismet.',
	'akismet_cannot_retrieve' => 'Non se puido obter unha resposta do Akismet.',
	'api_library_not_found' => 'Non se puido atopar a biblioteca <strong>%s</strong> para a clase <strong>%s</strong>Verifique a táboa de ruteo da API.',
	'askimet_invalid_apikey' => 'A chave da API do Akismet non é válida.',
	'clickatell_fopen_error' => 'Erro durante a execución do método fopen de envío!<br>Verifique se o PHP ten soporte para SSL e se a versión de PHP do server é mais recente que a 5.2.',
	'clickatell_message_too_long' => 'A súa mensaxe unicode é longa de máis! (Tamaño actual=',
	'clickatell_no_destination_address' => 'Especifique a/o destinataria/o (PARA)!',
	'clickatell_no_sender_address' => 'Especifique o enderezo fonte (DE)!',
	'clickatell_unicode_message_too_long' => 'A súa mensaxe unicode é longa de máis! (Tamaño actual=',
	'clickatell_unsupported_method' => 'Método de envío non soportado!',
	'invalid_api_library' => 'A biblioteca da API %s non é válida. Tódalas bibliotecas da API deben ser subclases de %s.',
	'upgrade_directory_not_deleted' => 'O directorio <code>%s</code> non se pode borrar.',
	'upgrade_extracting_error' => 'Erro na extracción: <code>%s</code>',
	'upgrade_failed' => 'Erro baixando a última versión do Ushahidi. Código de status do HTTP',
	'upgrade_file_not_copied' => 'O arquivo <code>%s</code> non pode ser copiado.',
	'upgrade_file_not_deleted' => 'O arquivo <code>%s</code> non pode ser borrado.',
	'upgrade_title' => 'Script de actualización do Ushahidi',
	'upgrade_zip_error' => 'Non se puido acabar de baixar o arquivo zip <code>%s</code> do Ushahidi.',
	'riverid_variable_not_available' => '%s non está dispoñible na clase RiverID.',
);
