<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-09 06:25+0000
// PO revision date:  2013-12-08 19:09+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Verifique que seleccionou un elemento.',
		'numeric' => 'Verifique que seleccionou un elemento.',
		'categories_required' => 'Os informes han ser categorizados denantes de seren aprobados.',
	) ,
	'action' => array(
		'permission' => 'Non ten permisos para levar a cabo esta acción.',
	) ,
	'uploadfile' => array(
		'required' => 'Debe seleccionar un arquivo para subir',
		'type' => 'O arquivo a subir ten que estar en formato .csv ou .xml',
		'valid' => 'O campo de arquivo a subir non semella conter un ficheiro válido',
	) ,
);
