<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-10 06:25+0000
// PO revision date:  2013-12-09 14:02+0000
$lang = array(
	'date' => 'Data de ingreso',
	'date_added' => 'Data da Engádega',
	'last_access' => 'Derradeiro Acceso',
	'sharing_color' => array(
		'length' => 'O campo Cor debe contar con alomenos 6 caracteres de lonxitude.',
		'required' => 'O campo Cor é obrigatorio.',
	) ,
	'sharing_name' => array(
		'length' => 'O nome para Compartillar semella non ser válido.',
		'required' => 'Un nome para Compartillar é obligatorio.',
	) ,
	'sharing_url' => array(
		'exists' => 'O URL do site xa existe.',
		'length' => 'O URL do site semella non ser válido.',
		'required' => 'O URL do site é obrigatorio.',
		'url' => 'O campo URL do Site semella no conter un URL válido.',
	) ,
);
