<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-02 10:00+0000
$lang = array(
	'captcha' => array(
		'default' => 'Wprowadź ważny kod bezpieczeństwa',
		'required' => 'Wprowadź kod bezpieczeństwa',
		'valid' => 'Nieprawidłowy kod zabezpieczający.',
	) ,
	'comment_author' => array(
		'length' => 'Pole nazwy musi zawierać co najmniej 3 znaki.',
		'required' => 'Pole nazwy musi być wypełnione.',
	) ,
	'comment_description' => array(
		'required' => 'Pole komentarza musi być wypełnione.',
	) ,
	'comment_email' => array(
		'email' => 'Pole adresu email prawdopodobnie nie zawiera ważnego adresu emailowego',
		'length' => 'Pole adresu email musi zawierać co najmniej 4 i nie więcej niż 64 znaki.',
		'required' => 'Pole adresu email musi być wypełnione, jeżeli zaznaczono pole wyboru.',
	) ,
);
