<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-02 10:01+0000
$lang = array(
	'captcha' => array(
		'default' => 'Wprowadź poprawny kod bezpieczeństwa',
		'valid' => 'Proszę wpisać prawidłowy kod zabezpieczający.',
		'required' => 'Wprowadź kod bezpieczeństwa',
	) ,
	'contact_email' => array(
		'email' => 'Pole adresu emailowego prawdopodobnie nie zawiera poprawnego adresu mailowego',
		'length' => 'Pole adresu email musi zawierać co najmniej 4 i nie więcej niż 64 znaki.',
		'required' => 'Pole adresu email musi być wypełnione, jeśeli zaznaczone zostało pole wyboru.',
	) ,
	'contact_message' => array(
		'required' => 'Pole wiadomości musi być wypećnione.',
	) ,
	'contact_name' => array(
		'length' => 'Pole nazwy musi mieć co najmniej 3 znaki.',
		'required' => 'Pole nazwy musi być wypełnione.',
	) ,
	'contact_subject' => array(
		'length' => 'Pole tematu musi zawierać co najmniej 3 znaki.',
		'required' => 'Pole tematu musi być wypełnione.',
	) ,
	'email_send' => array(
		'failed' => 'Wystąpił błąd podczas wysyłania wiadomości.',
	) ,
);
