<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-02 11:09+0000
$lang = array(
	'am' => 'przed południem',
	'friday' => array(
		'abbv' => 'Pia',
		'full' => 'Piątek',
	) ,
	'monday' => array(
		'abbv' => 'Pon',
		'full' => 'Poniedziałek',
	) ,
	'pm' => 'po południu',
	'saturday' => array(
		'abbv' => 'Sob',
		'full' => 'Sobota',
	) ,
	'sunday' => array(
		'abbv' => 'Nie',
		'full' => 'Niedziela',
	) ,
	'thursday' => array(
		'abbv' => 'Czw',
		'full' => 'Czwartek',
	) ,
	'tuesday' => array(
		'abbv' => 'Wto',
		'full' => 'Wtorek',
	) ,
	'wednesday' => array(
		'abbv' => 'Śro',
		'full' => 'Środa',
	) ,
	'january' => array(
		'abbv' => 'Sty',
		'full' => 'Styczeń',
	) ,
	'february' => array(
		'abbv' => 'Lut',
		'full' => 'Luty',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Marzec',
	) ,
	'april' => array(
		'abbv' => 'Kwi',
		'full' => 'Kwiecień',
	) ,
	'may' => array(
		'abbv' => 'Maj',
		'full' => 'Maj',
	) ,
	'june' => array(
		'abbv' => 'Cze',
		'full' => 'Czerwiec',
	) ,
	'july' => array(
		'abbv' => 'Lip',
		'full' => 'Lipiec',
	) ,
	'august' => array(
		'abbv' => 'Sie',
		'full' => 'Sierpień',
	) ,
	'september' => array(
		'abbv' => 'Wrz',
		'full' => 'Wrzesień',
	) ,
	'october' => array(
		'abbv' => 'Paź',
		'full' => 'Październik',
	) ,
	'november' => array(
		'abbv' => 'Lis',
		'full' => 'Listopad',
	) ,
	'december' => array(
		'abbv' => 'Gru',
		'full' => 'Grudzień',
	) ,
);
