<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-02 11:19+0000
$lang = array(
	'admin_footer' => 'Ta wiadomość została wysłana z serwisu',
	'admin_login_url' => 'Logowanie do panelu administracyjnego',
	'admin_new_comment' => array(
		'message' => 'Do systemu został dodany nowy komentarz, jako odpowiedź do:',
		'subject' => 'Nowy komentarz',
	) ,
	'admin_new_email' => array(
		'message' => 'Do systemu została dodana nowa wiadomość email.',
		'subject' => 'Nowa wiadomość email',
	) ,
	'admin_new_report' => array(
		'message' => 'Do systemu został dodany nowy raport.',
		'subject' => 'Nowy Raport',
	) ,
	'admin_new_sms' => array(
		'message' => 'Do systemu została dodana nowa wiadomość tekstowa SMS.',
		'subject' => 'Nowa wiadomość tekstowa',
	) ,
	'member_new_alert' => array(
		'message' => 'Otrzymano nowy alert!',
		'subject' => 'Nowy alert!',
	) ,
	'member_new_message' => array(
		'message' => 'Otrzymano nową Prywatną Wiadomość',
		'subject' => 'Nowa Prywatna Wiadomość',
		'footer' => 'Aby odpowiedzieć, odwiedź:',
	) ,
);
