<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-02 10:41+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'ID musi być liczbą',
	) ,
	'private_to' => array(
		'required' => 'Pole "Do" jest wymagane',
		'exists' => 'Użytkownik, do którego próbujesz wysłać wiadomość, nie istnieje.',
	) ,
	'private_subject' => array(
		'required' => 'Pole "Temat" jest wymagane.',
		'length' => 'Temat musi mieć co najmniej 3 i co najwyżej 150 znaków.',
	) ,
	'private_message' => array(
		'required' => 'Treść wiadomości jest wymagana.',
	) ,
);
