<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-20 06:18+0000
// PO revision date:  2013-06-19 21:44+0000
$lang = array(
	'incident_id' => array(
		'required' => 'تكاية دوثاتي بكةرةوة كة ئايتميَكت هةلَبذاردووة ',
	) ,
);
