<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-23 17:27+0000
$lang = array(
	'alert_email' => array(
		'email' => 'O campo do Email parece conter um endereço de email inválido?',
		'email_check' => 'Esse endereço de Email já se encontra registado na nossa base de dados para receber alertas nessa localização',
		'length' => 'O campo do Email deve ter entre 4 a 64 caracteres.',
		'required' => 'O campo do e-mail é obrigatório, se a opção estiver seccionada.',
	) ,
	'alert_country' => array(
		'single_country' => 'Esta função estará disponível apenas para um país. Por favor, verifique se o local do alerta se encontra circunscrito ao país %s.',
	) ,
	'alert_lat' => array(
		'between' => 'Não seleccionou uma localização válida no mapa.',
		'required' => 'Não seleccionou uma localização válida no mapa.',
	) ,
	'alert_lon' => array(
		'between' => 'Não seleccionou uma localização válida no mapa.',
		'required' => 'Não seleccionou uma localização válida no mapa.',
	) ,
	'alert_mobile' => array(
		'length' => 'O campo do Telemóvel parece não conter o número de dígitos correcto.',
		'mobile_check' => 'Esse Número de Telemóvel já se encontra registado na nossa base de dados para receber alertas nessa localização.',
		'numeric' => 'O campo do Telemóvel parece não conter um número válido. Por favor insira apenas dígitos, incluindo o número de código do país (Portugal +351).',
		'one_required' => 'Tem de inserir o seu Número de Telemóvel ou Endereço de Email.',
		'required' => 'O campo do Telemóvel é obrigatório, se a opção estiver selecionada.',
	) ,
	'alert_radius' => array(
		'in_array' => 'Não definiu um raio válido no mapa.',
		'required' => 'Não definiu o seu raio no mapa.',
	) ,
	'alert_recipient' => array(
		'required' => 'Ainda não definiu um destinatário para os alertas.',
	) ,
	'alerts_subscribed' => 'Inscreveu-se para receber alertas com as seguintes categorias',
	'code_already_verified' => 'Este código já foi verificado!',
	'code_not_found' => 'Este código de verificação não foi encontrado! Por favor confirme que tem o URL correcto.',
	'code_verified' => 'O seu código foi verificado correctamente. A partir deste momento irá receber alertas de incidentes conforme forem ocorrendo.',
	'confirm_request' => 'Para confirmar o seu pedido de alerta por favor vá a ',
	'create_more_alerts' => 'Voltar à página de Alertas para criar mais alertas',
	'email_alert_request_created' => 'O seu pedido de Alerta por Email foi criado e uma mensagem de verificação foi enviada para',
	'email_code' => 'Por favor insira abaixo o código de confirmação de Email que recebeu: ',
	'email_error_head' => 'O seu pedido de Alerta por Email NÃO FICOU registado!',
	'email_ok_head' => 'O seu pedido de Alerta por Email foi registado!',
	'error' => 'O sistema não foi capaz de processar o seu pedido de confirmação!',
	'mobile_alert_request_created' => 'O seu pedido de Alerta por Telemóvel foi criado e uma mensagem de verificação foi enviada para',
	'mobile_code' => 'Por favor, insira abaixo o código de confirmação SMS que recebeu no seu telemóvel:',
	'mobile_error_head' => 'O seu pedido de Alerta por Telemóvel NÃO FICOU registado!',
	'mobile_ok_head' => 'O seu pedido de Alerta por Telemóvel foi registado!',
	'settings_error' => 'Esta implantação não está configurada para processar alertas correctamente',
	'unsubscribe' => 'Recebeu este email porque subscreveu a recepção de alertas. Caso não pretenda receber futuros alertas vá a',
	'unsubscribed' => 'Nunca mais irá receber alertas de ',
	'unsubscribe_failed' => 'Não fomos capazes de o desinscrever. Por favor confirme que tem o URL correcto.',
	'verification_email_subject' => 'alertas - verificação',
	'verify_code' => 'Não receberá alertas nesta localização até que confirme o seu pedido.',
);
