<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-10-04 06:25+0000
// PO revision date:  2014-10-03 06:28+0000
$lang = array(
	'captcha' => array(
		'default' => 'Please enter a valid security code',
		'required' => 'Please enter the security code',
	) ,
	'email' => array(
		'email' => 'The Email field does not appear to contain a valid email address?',
		'length' => 'O campo de email deve ter pelo menos 4 caracteres e no máximo 64 caracteres.',
		'required' => 'O campo do e-mail é obrigatório, se a opção estiver selecionada.',
	) ,
	'message' => array(
		'required' => 'O campo dos comentários é obrigatório.',
	) ,
	'name' => array(
		'length' => 'O campo de nome deve ter pelo menos 3 caracteres.',
		'required' => 'O campo do nome é obrigatório.',
	) ,
	'phone' => array(
		'length' => 'O campo de telefone é obrigatório',
	) ,
);
