<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-10-04 06:25+0000
// PO revision date:  2014-10-03 06:31+0000
$lang = array(
	'reports_view' => 'Ver Relatos',
	'reports_edit' => 'Criar/Editar/Apagar Relatos',
	'reports_approve' => 'Aprovar Relatos',
	'reports_verify' => 'Verificar relatos',
	'reports_comments' => 'Gerir comentários dos relatos',
	'reports_download' => 'Download dos relatos',
	'reports_upload' => 'Upload de relatos',
	'messages' => 'Gerir mensagens',
	'messages_reporters' => 'Gerir relatores de mensagens',
	'stats' => 'Ver estatísticas',
	'manage' => 'Gerir paínel',
	'users' => 'Gerir utilizadores',
);
