<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-26 14:59+0000
$lang = array(
	'private_subject' => array(
		'required' => 'O campo "assunto" é de preenchimento obrigatório',
		'length' => 'O assunto deverá ter entre 3 e 150 carateres',
	) ,
	'private_message' => array(
		'required' => 'O campo "mensagem" é de preenchimento obrigatório',
	) ,
);
