<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-23 17:36+0000
$lang = array(
	'comments_form_error' => 'erro!',
	'data_include' => array(
		'between' => 'Please select a valid item to include in the download',
		'numeric' => 'Please select a valid item to include in the download',
	) ,
	'data_point' => array(
		'between' => 'Please select a valid type of report to download',
		'numeric' => 'Please select a valid type of report to download',
		'required' => 'Please select a valid type of report to download',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'The FROM date field does not appear to contain a valid date?',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'The am/pm field does not appear to contain a valid value?',
	) ,
	'incident_category' => array(
		'numeric' => 'The category field does not appear to contain a valid category?',
		'required' => 'O campo "Categorias" é obrigatório.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'The date field does not appear to contain a valid date?',
		'date_mmddyyyy' => 'The date field does not appear to contain a valid date?',
		'required' => 'O campo da data é obrigatório.',
	) ,
	'incident_description' => array(
		'required' => 'O campo "Descrição" é obrigatório.',
	) ,
	'incident_hour' => array(
		'between' => 'The hour field does not appear to contain a valid hour?',
		'required' => 'O campo das horas é obrigatório.',
	) ,
	'incident_information' => array(
		'alpha' => 'Please enter a valid value for Information Probability',
		'length' => 'Please enter a valid value for Information Probability',
	) ,
	'incident_minute' => array(
		'between' => 'The minute field does not appear to contain a valid value?',
		'required' => 'O campo dos minutos é obrigatório.',
	) ,
	'incident_news' => array(
		'url' => 'The news source links field does not appear to contain a valid URL?',
	) ,
	'incident_photo' => array(
		'size' => 'Please ensure that photo uploads sizes are limited to 2MB.',
		'valid' => 'The Upload Photos field does not appear to contain a valid file',
	) ,
	'incident_source' => array(
		'alpha' => 'Please enter a valid value for Source Reliability',
		'length' => 'Please enter a valid value for Source Reliability',
	) ,
	'incident_title' => array(
		'length' => 'The title field must be at least 3 and no more 200 characters long.',
		'required' => 'O campo "Título do Relatório" é obrigatório.',
	) ,
	'incident_verified' => array(
		'between' => 'Please enter a valid value for Verify This Report',
		'required' => 'Please enter a valid value for Verify This Report',
	) ,
	'incident_video' => array(
		'url' => 'The video links field does not appear to contain a valid URL?',
	) ,
	'latitude' => array(
		'between' => 'The latitude field does not appear to contain a valid latitude?',
		'required' => 'O campo da latitude é obrigatório. Por favor, clique no mapa para apontar a localização.',
	) ,
	'locale' => array(
		'exists' => 'This report already has a translation for this language',
		'locale' => 'The Original Report and the Translation have the same locale (language)',
		'required' => 'A localização é obrigatória.',
	) ,
	'location_name' => array(
		'length' => 'The location name field must be at least 3 and no more 200 characters long.',
		'required' => 'O campo "Nome da Localização" é obrigatório.',
	) ,
	'longitude' => array(
		'between' => 'The longitude field does not appear to contain a valid longitude?',
	) ,
	'person_email' => array(
		'email' => 'The email field does not appear to contain a valid email address?',
	) ,
	'person_last' => array(
		'length' => 'The last name field must be at least 3 and no more 100 characters long.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'The TO date field does not appear to contain a valid date?',
	) ,
);
