<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-08-12 14:38+0000
$lang = array(
	'date' => 'Data de inscrição',
	'date_added' => 'Data do envio',
	'last_access' => 'Último acesso',
	'sharing_color' => array(
		'length' => 'O campo cor deve ter 6 caracteres.',
		'required' => 'É necessário escolher uma cor.',
	) ,
	'sharing_name' => array(
		'length' => 'O compartilhamento parece não ter um nome válido.',
		'required' => 'É preciso ter um nome para o compartilhamento.',
	) ,
	'sharing_url' => array(
		'exists' => 'The site url already exists',
		'length' => 'A URL do site parece não ser válida.',
		'required' => 'The site url is required.',
		'url' => 'The site url field does not appear to contain a valid URL?',
	) ,
);
