<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-10-04 06:25+0000
// PO revision date:  2014-10-03 06:27+0000
$lang = array(
	'approved' => 'Aprovado',
	'categories' => 'Categorias',
	'category_impact' => 'Categoria de impacto',
	'category_impact_description' => 'This chart gives you a linear view of the reports by category over time.  Scroll from left to right to see a comparative view of the different categories. Mouse over the graph for more details',
	'choose_date_range' => 'Choose a date range',
	'countries' => 'Países',
	'country' => 'País',
	'country_breakdown' => 'Resumo de países',
	'description' => 'Hello, this is the statistics section. General description going here soon. For now, browse around using the sub category links above',
	'error' => 'Erro',
	'glossary' => 'Glossário',
	'hit_summary' => 'Resumo de visitas a site',
	'legend' => 'Lenda',
	'reports' => 'Relatos',
	'reports_categories' => 'Categories de relatos',
	'reports_statistics' => 'Estatísticas de relatos',
	'reports_status' => 'Estado de relatos',
	'time_range_1' => '1 mês',
	'time_range_2' => '3 meses',
	'time_range_3' => '6 meses ',
	'time_range_all' => 'Todos',
	'unapproved' => 'Não aprovado',
	'unique_visitors' => 'Visitantes únicos',
	'unique_visitors_description' => 'The number of individuals coming to your deployment; Unique Visitors are determined using cookies. In the case that a visitor does not have cookies enabled, they will be identified using a simple heuristic taking into account IP address, resolution, browser, plugins, OS, etc',
	'unverified' => 'Não verificado',
	'verified' => 'Verificado',
	'visitor_summary' => 'Resumo de visitantes',
	'visits' => 'Visitas',
	'visits_description' => 'A visit is a record of a unique visitor coming to the site more than 30 minutes past his/her last pageview',
);
