<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:25+0000
$lang = array(
	'captcha' => array(
		'default' => '請輸入有效的安全碼',
		'required' => '請輸入安全碼',
	) ,
	'email' => array(
		'email' => '電子信箱欄位顯示未填入有效的資料',
		'length' => '電子信箱欄位需填入4~46個字元',
		'required' => '如果已勾選，則電子信箱為必填',
	) ,
	'error' => array(
		'required' => '錯誤欄位為必填',
	) ,
	'subject' => array(
		'length' => '主題欄位需至少三個字元',
		'required' => '主題欄位為必填',
	) ,
	'yourname' => array(
		'length' => '姓名欄位至少需三個字元',
		'required' => '姓名欄位為必填.',
	) ,
);
