<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:57+0000
$lang = array(
	'error' => '數據庫錯誤: %s',
	'table_not_found' => '無法在數據庫中找到表"%s"。請確認您正在使用Ushahidi最新版本中的數據庫.',
);
