<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-01-29 06:24+0000
// PO revision date:  2014-01-28 18:27+0000
$lang = array(
	'am' => '上午',
	'friday' => array(
		'abbv' => '週五',
		'full' => '週五',
	) ,
	'monday' => array(
		'abbv' => '週一',
		'full' => '週一',
	) ,
	'pm' => '下午',
	'saturday' => array(
		'abbv' => '週六',
		'full' => '週六',
	) ,
	'sunday' => array(
		'abbv' => '週日',
		'full' => '週日',
	) ,
	'thursday' => array(
		'abbv' => '週四',
		'full' => '週四',
	) ,
	'tuesday' => array(
		'abbv' => '週二',
		'full' => '週二',
	) ,
	'wednesday' => array(
		'abbv' => '週三',
		'full' => '週三',
	) ,
	'january' => array(
		'abbv' => '1月',
		'full' => '一月',
	) ,
	'february' => array(
		'abbv' => '2月',
		'full' => '二月',
	) ,
	'march' => array(
		'abbv' => '3月',
		'full' => '三月',
	) ,
	'april' => array(
		'abbv' => '4月',
		'full' => '四月',
	) ,
	'may' => array(
		'abbv' => '5月',
		'full' => '五月',
	) ,
	'june' => array(
		'abbv' => '6月',
		'full' => '六月',
	) ,
	'july' => array(
		'abbv' => '7月',
		'full' => '七月',
	) ,
	'august' => array(
		'abbv' => '8月',
		'full' => '八月',
	) ,
	'september' => array(
		'abbv' => '9月',
		'full' => '九月',
	) ,
	'october' => array(
		'abbv' => '10月',
		'full' => '十月',
	) ,
	'november' => array(
		'abbv' => '11月',
		'full' => '十一月',
	) ,
	'december' => array(
		'abbv' => '12月',
		'full' => '十二月',
	) ,
);
