<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-01-02 06:24+0000
// PO revision date:  2014-01-01 17:01+0000
$lang = array(
	'field_default' => array(
		'default' => '之前所提供的欄位預設值為無效資料.',
		'length' => '欄位名稱不得超過200個字元',
	) ,
	'field_height' => array(
		'between' => '請輸入欄位高度值，需介於0～50',
	) ,
	'field_isdate' => array(
		'between' => '你輸入的資料不正確',
		'required' => '請確認是否新增日期欄位',
	) ,
	'field_name' => array(
		'length' => '欄位名稱需為3～100個字元',
		'required' => '請輸入欄位名稱',
		'duplicate' => '您所輸入的欄位名稱在此表格已存在, 請輸入其它的名稱',
	) ,
	'field_required' => array(
		'between' => '你輸入的資料不正確',
		'required' => '請確認是否新增欄位',
	) ,
	'field_type' => array(
		'numeric' => '請選擇一個正確的欄位類型',
		'required' => '請選擇一個欄位類型',
	) ,
	'field_width' => array(
		'between' => '請輸入欄位寬度值，需介於0～300',
	) ,
	'form_description' => array(
		'required' => '請輸入表格描述',
	) ,
	'form_id' => array(
		'default' => '預設的表格無法被刪除',
		'numeric' => '請選擇欲增加欄位的表格',
		'required' => '請選擇欲增加欄位的表格',
	) ,
	'form_title' => array(
		'length' => '表格名稱需為3~100個字元',
		'required' => '請輸入表格名稱',
		'exists' => '有此標題的表格已存在, 請選擇其它的',
	) ,
);
