<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:58+0000
$lang = array(
	'imap_stream_not_opened' => '無法開啟 IMAP stream',
	'unsupported_service' => '不支持的電子郵件服務器',
);
