<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:58+0000
$lang = array(
	'layer_color' => array(
		'length' => '顏色欄位資料必須至少為6個字元',
		'required' => '顏色欄位為必填',
	) ,
	'layer_file' => array(
		'type' => '文件地址不包含有效的文件。只接受.KMZ，.KML類型的文件',
		'valid' => '文件地址不包含有效的文件',
	) ,
	'layer_name' => array(
		'length' => '姓名欄位需為3～80個字元',
		'required' => '姓名欄位為必填',
	) ,
	'layer_url' => array(
		'atleast' => '請至少輸入KML Url 或File',
		'both' => '你無法同時使用一個KML文件和URL鏈接',
		'url' => '請輸入有效的網址，例如：http://www.ushahidi.com/layerl.kml',
	) ,
);
