<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:58+0000
$lang = array(
	'message' => '很抱歉，我們的網站目前停機維護。請在稍後再試。',
);
