<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:58+0000
$lang = array(
	'admin_footer' => '这些信息是从您的网站发出的',
	'admin_login_url' => '管理員登錄',
	'admin_new_comment' => array(
		'message' => '有新的評論,回應：',
		'subject' => '新的評論',
	) ,
	'admin_new_email' => array(
		'message' => '有新的郵件',
		'subject' => '新的郵件',
	) ,
	'admin_new_report' => array(
		'message' => '有新的事件報告',
		'subject' => '新的報告',
	) ,
	'admin_new_sms' => array(
		'message' => '有新的文本消息',
		'subject' => '新的消息',
	) ,
	'member_new_alert' => array(
		'message' => '您收到了一個事件警示',
		'subject' => '新的警示',
	) ,
	'member_new_message' => array(
		'message' => '您收到了一個私信',
		'subject' => '私信',
		'footer' => '回復請轉到 ',
	) ,
);
