<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-01-29 06:24+0000
// PO revision date:  2014-01-28 18:25+0000
$lang = array(
	'parent_id' => array(
		'numeric' => '上一層代號必須是數字',
	) ,
	'private_to' => array(
		'required' => '收件人欄位是必填的',
		'exists' => '您試著要發送訊息的對象不存在',
	) ,
	'private_subject' => array(
		'required' => '主旨欄位是必填的',
		'length' => '主旨文字數必須介於 3 到 150 字元',
	) ,
	'private_message' => array(
		'required' => '訊息欄位是必填的',
	) ,
);
