<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 02:59+0000
$lang = array(
	'latitude' => array(
		'between' => '緯度欄位資料顯示為無效',
		'required' => '緯度欄位為必填，請在地圖上點選一個位置.',
	) ,
	'level_id' => array(
		'numeric' => '報告者等級無效',
		'required' => '報告者等級無效',
	) ,
	'location_name' => array(
		'length' => '地點名稱長度為2~200個字元.',
		'required' => '地點名稱欄位為必填.',
	) ,
	'longitude' => array(
		'between' => '經度欄位資料顯示為無效',
		'required' => '經度欄位為必填，請在地圖上點選一個位置.',
	) ,
	'reporter_id' => array(
		'numeric' => '無效的報告者',
		'required' => '無效的報告者',
	) ,
);
