<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-01-09 06:24+0000
// PO revision date:  2014-01-09 00:48+0000
$lang = array(
	'incident_id' => array(
		'required' => '請確認已選擇一個項目',
		'numeric' => '請確認已選擇一個項目',
		'categories_required' => '通報必須設定分類才能夠送審',
	) ,
	'action' => array(
		'permission' => '您沒有權限執行這個操作',
	) ,
	'uploadfile' => array(
		'required' => '您必須選擇一個檔案上傳',
		'type' => '上傳的檔案必須是 .csv 或 .xml 格式',
		'valid' => '檔案上傳欄位沒有收到正確的檔案',
	) ,
);
