<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 07:03+0000
$lang = array(
	'captcha' => array(
		'default' => 'لطفاً یک کد معتبر امنیتی وارد کنید.',
		'required' => 'لطفاً کد امنیتی را وارد کنید.',
		'valid' => 'شما کد امنیتی اشتباهی را وارد کردید.',
	) ,
	'comment_author' => array(
		'length' => 'طول فیلد نام باید حداقل ۳ کاراکتر باشد.',
		'required' => 'فیلد نام باید پُر شود.',
	) ,
	'comment_description' => array(
		'required' => 'فیلد نظرات باید پُر شود.',
	) ,
	'comment_email' => array(
		'email' => 'ظاهراً یک نشانی ایمیل معتبر در بخش فیلد ایمیل وارد نشده است.',
		'length' => 'فیلد ایمیل باید حداقل ۴ و حداکثر ۶۴ کاراکتر داشته باشد.',
		'required' => 'اگر جعبه‌ی نشان‌زنی علامت دارد، فیلد ایمیل باید پُر شود.',
	) ,
);
