<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 05:41+0000
$lang = array(
	'date' => 'تاریخ',
	'feed_name' => array(
		'length' => 'فیلد نام فید باید حداقل ۳ کاراکتر و نه بیش از ۷۰ کاراکتر باشد.',
		'required' => 'لطفا نام فید را وارد کنند.',
	) ,
	'feed_url' => array(
		'required' => 'لطفا آدرس اینترنتی فید را وارد کنید.',
		'url' => 'لطفا یک آدرس اینترنتی معتبر وارد کنید. برای مثال: http://www.ushahidi.com',
	) ,
	'source' => 'منبع',
	'title' => 'عنوان',
);
