<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 06:18+0000
$lang = array(
	'imap_stream_not_opened' => 'امکان بازکردن جریان IMAP وجود ندارد.',
	'unsupported_service' => 'سرویس ایمیل پشتیبانی نمی‌شود.',
);
