<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 06:42+0000
$lang = array(
	'captcha' => array(
		'default' => 'لطفا یک کد امنیتی معتبر وارد کنید.',
		'required' => 'لطفا کد امنیتی معتبر را وارد کنید.',
	) ,
	'email' => array(
		'email' => 'ایمیل وارد شده، یک ایمیل قابل قبول به نظر نمی رسد.',
		'length' => 'فیلد ایمیل باید حداقل ۴ و حداکثر ۶۴ کاراکتر داشته باشد.',
		'required' => 'اگر جعبه‌ی نشان‌زنی علامت دارد، فیلد ایمیل باید پُر شود.',
	) ,
	'message' => array(
		'required' => 'فیلد نظرات باید پُر شود.',
	) ,
	'name' => array(
		'length' => 'طول فیلد نام باید حداقل ۳ کاراکتر باشد.',
		'required' => 'فیلد نام باید پُر شود.',
	) ,
	'phone' => array(
		'length' => 'تلفن وارد شده معتبر نمی باشد.',
	) ,
);
