<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 05:29+0000
$lang = array(
	'admin_footer' => 'این پیغام از وبسایت شما فرستاده شده است.',
	'admin_login_url' => 'ورود مدیر',
	'admin_new_comment' => array(
		'message' => 'یک نظر جدید به وبسایت شما ارسال شده است. در پاسخ به:',
		'subject' => 'نظر جدید',
	) ,
	'admin_new_email' => array(
		'message' => 'یک پیغام ایمیل به وبسایت شما ارسال شده است.',
		'subject' => 'پیغام ایمیل جدید',
	) ,
	'admin_new_report' => array(
		'message' => 'یک گزارش جدید به وبسایت شما ارسال شده است.',
		'subject' => 'گزارش جدید',
	) ,
	'admin_new_sms' => array(
		'message' => 'یک متن پیغام جدید به وبسایت شما ارسال شده است.',
		'subject' => 'متن پیغام جدید',
	) ,
	'member_new_alert' => array(
		'message' => 'شما یک هشدار جدید دریافت کرده اید.',
		'subject' => 'هشدار جدید!',
	) ,
	'member_new_message' => array(
		'message' => 'شما یک پیغام خصوصی دریافت کرده اید.',
		'subject' => 'پیغام خصوصی جدید',
		'footer' => 'جهت ارسال پاسخ لطفا به اینجا مراجعه کنید:',
	) ,
);
