<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 07:07+0000
$lang = array(
	'latitude' => array(
		'between' => 'فیلد "عرض جغرافیایی" به نظر شامل یک عرض جغرافیایی معتبر نمی باشد.',
		'required' => 'فیلد "عرض جغرافیایی" باید پر شود. لطفا جهت مشخص کردن یک مکان روی نقشه کلیک کنید.',
	) ,
	'level_id' => array(
		'numeric' => 'ظاهرا فیلد سطح گزارشگر یک سطح معتبر ندارد.',
		'required' => 'ظاهرا فیلد سطح گزارشگر یک سطح معتبر ندارد.',
	) ,
	'location_name' => array(
		'length' => 'فیلد "نام منطقه" باید حداقل ۳ و حداکثر ۲۰۰ کاراکتر باشد.',
		'required' => 'فیلد نام محل باید پُر شود. ',
	) ,
	'longitude' => array(
		'between' => 'فیلد "طول جغرافیایی" به نظر شامل یک طول جغرافیایی معتبر نمی باشد.',
		'required' => 'فیلد "طول جغرافیایی" باید پُر شود. لطفا جهت مشخص کردن یک مکان روی نقشه کلیک کنید.',
	) ,
	'reporter_id' => array(
		'numeric' => 'گزارشگر نامعتبر',
		'required' => 'گزارشگر نامعتبر',
	) ,
);
