<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 06:16+0000
$lang = array(
	'description' => array(
		'length' => 'فیلد شرح باید حداقل سه نویسه و حداکثر ۱۰۰ نویسه باشد.',
		'required' => 'فیلد شرح باید پُر شود.',
	) ,
	'name' => array(
		'alpha_numeric' => 'فیلد «نام» تنها می‌تواند شامل حروف یا اعداد باشد.',
		'length' => 'فیلد نام باید حداقل ۳ و حداکثر ۸۰ نویسه باشد',
		'nomodify' => 'نقش مدیرویژه قابل اصلاح نیست.',
		'required' => 'فیلد نام باید پُر شود.',
	) ,
	'access_level' => array(
		'numeric' => 'فیلد سطح دسترسی باید عددی بین ۰ تا ۱۰۰ باشد.',
		'required' => 'فیلد سطح دسترسی باید عددی بین ۰ تا ۱۰۰ باشد.',
	) ,
	'permissions' => array(
		'numeric' => 'فیلد مجوز باید عددی بین ۰ تا ۱۰۰ باشد.',
	) ,
);
