<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 07:56+0000
// PO revision date:  2013-03-08 08:37+0000
$lang = array(
	'approved' => 'تأیید‌ شده',
	'categories' => 'دسته‌ها',
	'category_impact' => 'میزان تاثیر دسته',
	'category_impact_description' => 'این جدول یه شما یک دید خطی از دسته های مختلف  گزارش ها در طول زمان می دهد. از چپ به راست حرکت کنید تا یک نمای تطبیقی از دسته های مختلف داشته باشید. موشواره را روی نمودار ببرید تا جزئیات بیشتری ببینید.',
	'choose_date_range' => 'بازه ی تاریخ را انتخاب کنید.',
	'countries' => 'کشور ها',
	'country' => 'کشور',
	'country_breakdown' => 'تفکیک کشور',
	'description' => 'بخش آمار به زودی دارای شرح کلی ای خواهد شد. فعلا توسط این  پیوند های  زیر دسته ای جستجو کنید.',
	'error' => 'خطا',
	'glossary' => 'واژه نامه',
	'hit_summary' => 'خلاصه نمایش',
	'legend' => 'شرح',
	'pageviews' => 'تعداد بازدید صفحه',
	'pageviews_description' => 'تعداد کل صفحاتی که مراجعه کنندگان روی سایت شما بازدید کرده اند.',
	'reports' => 'گزارش‌ها',
	'reports_categories' => 'دسته های گزارش ها',
	'reports_statistics' => 'آمار گزارش ها',
	'reports_status' => 'وضعیت گزارش ها',
	'report_punchcard' => 'پانچ کارت گزارش',
	'report_stats' => 'آمار گزارش ها',
	'stats_not_setup' => 'آمار تنظیم نشده است',
	'time_range_1' => '1 ماه',
	'time_range_2' => '3 ماه',
	'time_range_3' => '6 ماه',
	'time_range_all' => 'همه',
	'unapproved' => 'تأیید نشده',
	'unique_visitors' => 'بازدید کننده های منحصر به فرد',
	'unique_visitors_description' => 'تعداد افرادی که به گستره ی شما رجوع کرده اند. بازدید کنندگان منحصر به فرد توسط cookie ها شناسایی می شوند. بازدید کننده هایی که cookie های خود را فعال نکرده اند توسط آدرس IP ، تفکیک پذیری، جستجو گر ، پلاگین، سیستم عامل و غیره شناسایی می شوند. ',
	'unverified' => 'صحت گذاری نشده',
	'verified' => 'صحت‌گذاری‌شده',
	'visitor_summary' => 'خلاصه بازدید ها',
	'visits' => 'بازدید ها',
	'visits_description' => 'یک "بازدید" رکوردی از یک مراجعه کننده منحصر به فرد است که بیش از 30 دقیقه پس از آخرین بازدید خود به سایت مراجعه کرده است.',
);
