<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:26+0000
$lang = array(
	'category_color' => array(
		'length' => 'Цветът трябва да има 6 символа.',
		'required' => 'Цветът е задължителен.',
	) ,
	'category_description' => array(
		'required' => 'Описанието е задължително.',
	) ,
	'category_image' => array(
		'size' => 'Моля имайте предвид, че размерът на иконката трябва да е до 50KB.',
		'type' => 'Полето за иконката изглежда не съдържа валидна снимката. Поддържаните формати са .JPG, .PNG и .GIF.',
		'valid' => 'Полето за иконката изглежда не съдържа валиден файл.',
	) ,
	'category_title' => array(
		'length' => 'Заглавието трябва да е между 3 и 80 символа.',
		'required' => 'Заглавието е задължително.',
	) ,
	'parent_id' => array(
		'exists' => 'Родителската категория не съществува.',
		'numeric' => 'Родителската категория трябва да е цифра.',
		'required' => 'Родителската категория е задължителна',
		'same' => 'Категорията и родителската категория не може да са едни и същи.',
	) ,
);
