<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:35+0000
// PO revision date:  2014-05-01 12:31+0000
$lang = array(
	'captcha' => array(
		'default' => 'Моля въведете правилен код за сигурност',
		'required' => 'Моля въведете код за сигурност',
		'valid' => 'Въведен е грешен код за сигурност.',
	) ,
	'comment_author' => array(
		'length' => 'Името трябва да е с поне 3 символа.',
		'required' => 'Името е задължително.',
	) ,
	'comment_description' => array(
		'required' => 'Трябва да въведете коментар.',
	) ,
	'comment_email' => array(
		'email' => 'Email адресът не изглежда да е правилен?',
		'length' => 'Email трябва да съдържа между 4 и 64 символа.',
		'required' => 'Email полето е задължително, ако сте отбелязали отметката.',
	) ,
);
