<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:28+0000
$lang = array(
	'captcha' => array(
		'default' => 'Моля въведете правилен код за сигурност',
		'required' => 'Моля въведете код за сигурност',
	) ,
	'contact_email' => array(
		'email' => 'Email адресът не изглежда да е правилен?',
		'length' => 'Email трябва да съдържа между 4 и 64 символа.',
		'required' => 'Email полето е задължително, ако сте отбелязали отметката.',
	) ,
	'contact_message' => array(
		'required' => 'Съобщението е задължително.',
	) ,
	'contact_name' => array(
		'length' => 'Името трябва да е с поне 3 символа.',
		'required' => 'Името е задължително.',
	) ,
	'contact_subject' => array(
		'length' => 'Заглавието трябва е дълго поне 3 символа.',
		'required' => 'Заглавието е задължително.',
	) ,
);
