<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-05 12:07+0000
$lang = array(
	'field_default' => array(
		'length' => 'Полето Име трябва да е между 3 и 200 символа.',
	) ,
	'field_height' => array(
		'between' => 'Моля въведете стойност между 0 и 50 за полето Височина',
	) ,
	'field_isdate' => array(
		'between' => 'Въвели сте неправилна стойност за полето Дата',
		'required' => 'Моля изберете Да или Не за полето Дата',
	) ,
	'field_name' => array(
		'length' => 'Полето Име трябва да е между 3 и 100 символа.',
		'required' => 'Моля въведете стойност за полето Име.',
	) ,
	'field_required' => array(
		'between' => 'Въвели сте неправилна стойност за полето Изисква се',
		'required' => 'Моля изберете Да или Не за полето Изисква се',
	) ,
	'field_type' => array(
		'numeric' => 'Моля изберете валиден тип на поле.',
		'required' => 'Моля изберете тип на поле.',
	) ,
	'field_width' => array(
		'between' => 'Моля въведете стойност между 0 и 200 за полето Широчина',
	) ,
	'form_description' => array(
		'required' => 'Моля въведете описание на формуляра.',
	) ,
	'form_id' => array(
		'default' => 'Формулярът по подразбиране не може да бъде изтрит.',
		'numeric' => 'Моля изберете към кой формуляр да се добави това поле.',
		'required' => 'Моля изберете към кой формуляр да се добави това поле.',
	) ,
	'form_title' => array(
		'length' => 'Името на формуляра трябва да е между 3 и 100 символа.',
		'required' => 'Моля въведете име на формуляра.',
	) ,
);
