<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Моля въведете правилен код за сигурност',
		'required' => 'Моля въведете код за сигурност',
	) ,
	'contact_email' => array(
		'email' => 'Email адресът не изглежда да е правилен?',
		'required' => 'Моля задайте правилен email адрес.',
	) ,
	'contact_message' => array(
		'required' => 'Полето за съобщения трябва да съдържа нещо.',
	) ,
	'contact_subject' => array(
		'length' => 'Заглавието трябва да е поне 3 символа.',
		'required' => 'Заглавието е задължително.',
	) ,
);
