<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:45+0000
$lang = array(
	'admin_footer' => 'Това съобщение е изпратено от вашия сайт',
	'admin_login_url' => 'Вход за администратори',
	'admin_new_comment' => array(
		'message' => 'Нов коментар е пуснат в отговор на:',
		'subject' => 'Нов коментар',
	) ,
	'admin_new_email' => array(
		'message' => 'Ново email съобщение е пуснато на сайта.',
		'subject' => 'Ново email съобщение',
	) ,
	'admin_new_report' => array(
		'message' => 'Нов сигнал е пуснат на сайта.',
		'subject' => 'Нов сигнал',
	) ,
	'admin_new_sms' => array(
		'message' => 'Нов SMS е пуснат на сайта.',
		'subject' => 'Нов SMS',
	) ,
);
