<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:49+0000
$lang = array(
	'description' => array(
		'length' => 'Полето с описание трябва да е между 3 и 100 символа',
		'required' => 'Полето с описание се изисква.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Полето за името трябва да съдържа само букви и цифри.',
		'length' => 'Полето за името трябва да е между 2 и 30 символа.',
		'nomodify' => 'Ролята на Супер Администратор не може да бъде променяна.',
		'required' => 'Полето за името се изисква.',
	) ,
);
