<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-13 06:05+0000
$lang = array(
	'email' => array(
		'email' => 'Emailkaad gelisay sax ma aha',
		'exists' => 'Waan ka xunnahay, Emailkan horay ayaa account loogu sameeyay',
		'length' => 'Emailkaagu waa inuu ka kooban yahay ugu yaraan afar xaraf, ugu badnaanna 64 xaraf',
		'required' => 'Email waa lagama maarmaan',
	) ,
	'name' => array(
		'length' => 'Magaca oo dhamaystiran waa inuu ka kooban yahay ugu yaraan saddex xaraf, ugu badnaanna 100 xaraf',
		'required' => 'Magaca oo dhamaystiran ayaa loo baahan yahay',
		'standard_text' => 'Magacaaga (Username) waxaa ku jira xuruuf aan la oggolayn',
	) ,
	'password' => array(
		'length' => 'Waa inuu password-ku yahay ugu yaraan 5 xaraf, ugu badnaanna 16 xaraf',
		'matches' => 'Fadlan geli Password isku mida labada god ee loogu talagalay passwordka',
		'required' => 'Password ayaa loo baahan yahay',
	) ,
	'password_confirm' => array(
		'matches' => 'Waa inay password-yadu is leeyihiin',
	) ,
	'resetemail' => array(
		'email' => 'Emailkaad gelisay sax ma aha',
		'invalid' => 'Waan ka xunnahay, ma hayno Emailkaaga',
		'required' => 'Email ayaa loo baahan yahay',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Hannaanka xuruuftu sax ma aha',
		'length' => 'Xuruuftu waa inay ka kooban tahay ugu yaraan 5 xaraf ugu badnaanna 30 xaraf',
		'required' => 'Waa inaad qeexdaa ugu yaraan hal heer',
		'values' => 'Waa inaad doorataa heerka ADMIN amaba heerka USER',
	) ,
	'username' => array(
		'admin' => 'Heerka User ADMIN-ka waxba lagama beddeli karo',
		'exists' => 'waan ka xunnahay, magaca Username-kan horay ayaa loo qaatay',
		'length' => 'Magaca Username-ku waa inuu ka kooban yahay ugu yaraan 2 xaraf ugu badnaanna 16 xaraf',
		'required' => 'Username ayaa loo baahan yahay',
		'superadmin' => 'Heerka super admin role waxba lagama beddeli karo',
	) ,
);
