<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:33+0000
$lang = array(
	'am' => 'a.m. (Waqtiga u dhexeeya saqda dhexe ilaa 12:00 duhurkii)',
	'friday' => array(
		'abbv' => 'Jimce',
		'full' => 'Jimce',
	) ,
	'monday' => array(
		'abbv' => 'Isniin',
		'full' => 'Isniin',
	) ,
	'pm' => 'p.m. (Duhur kaddib)',
	'saturday' => array(
		'abbv' => 'Sabti',
		'full' => 'Sabti',
	) ,
	'sunday' => array(
		'abbv' => 'Axad',
		'full' => 'Axad',
	) ,
	'thursday' => array(
		'abbv' => 'Khamiis',
		'full' => 'Khamiis',
	) ,
	'tuesday' => array(
		'abbv' => 'Talaado',
		'full' => 'Talaado',
	) ,
	'wednesday' => array(
		'abbv' => 'Arbaco',
		'full' => 'Arbaco',
	) ,
);
