<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:35+0000
$lang = array(
	'date' => 'Taariikhda',
	'feed_name' => array(
		'length' => 'Magaca xogta Feed-ku waa inuu ka kooban yahay ugu yaraan 3 xaraf, ugu badnaanna 70 xaraf',
		'required' => 'Fadlan geli magaca xogta Feed-ka',
	) ,
	'feed_url' => array(
		'required' => 'Fadlan geli URL-ka xogta Feed-ka',
		'url' => 'Fadlan geli URL jira. Tusaale ahaan: http://www.ushahidi.com',
	) ,
	'source' => 'Asalka',
	'title' => 'Cinwaan',
);
