<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => 'Fadlan geli security code sax ah',
		'required' => 'Fadlan geli security code-ka',
	) ,
	'email' => array(
		'email' => 'Email-kaad gelisay sax ma aha',
		'length' => 'Emailku waa inuu ka koobnaadaa ugu yaraan 4 xaraf ugu badnaanna 64 xaraf',
		'required' => 'Email ayaa loo baahan yahay hadduu sanduuqu saxan yahay',
	) ,
	'message' => array(
		'required' => 'Faallooyin ayaa loo baahan yahay',
	) ,
	'name' => array(
		'length' => 'Magacu waa inuu ka koobnaadaa ugu yaraan 3 xaraf',
		'required' => 'Magac ayaa loo baahan yahay',
	) ,
	'phone' => array(
		'length' => 'Telefoonku ma ahan mid sax ah',
	) ,
);
