<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:49+0000
$lang = array(
	'latitude' => array(
		'between' => 'Xarriiqda loolku (latitude)sax ma aha?',
		'required' => 'Xarriiqda loolka (latitude) ayaa loo baahan yahay. Fadlan guji khariidada si aad goob u tilmaanto.',
	) ,
	'level_id' => array(
		'numeric' => 'Goobta Reporter Level-ka kuma jiro Level sax ah.',
		'required' => 'Goobta Reporter Level-ka kuma jiro Level sax ah.',
	) ,
	'location_name' => array(
		'length' => 'Magaca goobtu waa inuu ahaadaa ugu yaraan 3 xaraf, ugu badnaana 200 xaraf.',
		'required' => 'Magaca goobta ayaa loo baahan yahay.',
	) ,
	'longitude' => array(
		'between' => 'Goobta longitude-ku ma lahan longitude sax ah?',
		'required' => 'Goobta longitude ayaa loo baahan yahay.Fadlan guji khariidada si aad u tilmaantid goob.   ',
	) ,
	'reporter_id' => array(
		'numeric' => 'Soo tebiyuhu sax ma aha.',
		'required' => 'Soo tebiyuhu sax ma aha.',
	) ,
);
