<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'Taariikhda lagu daray.',
	'date_added' => 'Taariikhda lagu daray.',
	'last_access' => 'Daalacashadii ugu dambeysay.',
	'sharing_color' => array(
		'length' => 'Goobta midabku waa iney ahaataa ugu badnaan 6 xaraf.',
		'required' => 'Goobta midabka ayaa loo bahan yahay.',
	) ,
	'sharing_name' => array(
		'length' => 'Magac-wadaaggu ma ahan mid sax ah?',
		'required' => 'Magaca-wadaagga ayaa loo baahan yahay.',
	) ,
	'sharing_url' => array(
		'exists' => 'so_SO:',
		'length' => 'URL-ku maahan mid sax ah.',
		'required' => 'URL-ka bogga ayaa loo bahan yahay.',
		'url' => 'URL-ka boggu ma ahan mid sax ah.',
	) ,
);
