<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-19 22:50+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'The allow comments field does not appear to contain a valid value?',
	) ,
	'allow_feed' => array(
		'between' => 'The include feed field does not appear to contain a valid value?',
	) ,
	'allow_reports' => array(
		'between' => 'The allow reports field does not appear to contain a valid value?',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'The stat sharing field does not appear to contain a valid value?',
	) ,
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
	) ,
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
	) ,
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
	) ,
	'sms_no1' => array(
		'length' => 'The phone 1 field does not appear to contain a valid value?',
	) ,
	'sms_no2' => array(
		'length' => 'The phone 2 field is too long',
	) ,
	'sms_no3' => array(
		'length' => 'The phone 3 field is too long',
	) ,
);
