<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-17 09:35+0000
$lang = array(
	'page_title' => array(
		'required' => 'برجاء كتابة اسم الصفحة',
		'length' => 'عنوان الصفحة يجب ان يحتوى على 3 حروف على الاقل و150 حرف كحد اقصى',
	) ,
	'page_tab' => array(
		'required' => 'برجاء كتابة اسم الصفحة',
	) ,
	'page_description' => array(
		'required' => 'برجاء كتابة وصف الصفحة',
	) ,
);
