<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-05 06:26+0000
// PO revision date:  2013-09-04 14:34+0000
$lang = array();
