<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-04 05:08+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Chishanu',
		'full' => 'Chishanu',
	) ,
	'monday' => array(
		'abbv' => 'Muvhuro',
		'full' => 'Muvhuro',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Mugovera',
		'full' => 'Mugovera',
	) ,
	'sunday' => array(
		'abbv' => 'Svondo',
		'full' => 'Svondo',
	) ,
	'thursday' => array(
		'abbv' => 'China',
		'full' => 'China',
	) ,
	'tuesday' => array(
		'abbv' => 'Chipiri',
		'full' => 'Chipiri',
	) ,
	'wednesday' => array(
		'abbv' => 'Chitatu',
		'full' => 'Chitatu',
	) ,
	'january' => array(
		'abbv' => 'Ndira',
		'full' => 'Ndira',
	) ,
	'february' => array(
		'abbv' => 'Kukadzi',
		'full' => 'Kukadzi',
	) ,
	'march' => array(
		'abbv' => 'Kurume',
		'full' => 'Kurume',
	) ,
	'april' => array(
		'abbv' => 'Kubvumbi',
		'full' => 'Kubvumbi',
	) ,
	'may' => array(
		'abbv' => 'Chivabvu',
		'full' => 'Chivabvu',
	) ,
	'june' => array(
		'abbv' => 'Chukumi',
		'full' => 'Chikumi',
	) ,
	'july' => array(
		'abbv' => 'Chikunguru',
		'full' => 'Chikunguru',
	) ,
	'august' => array(
		'abbv' => 'Nyamavhuvhu',
		'full' => 'Nyamavhuvhu',
	) ,
	'september' => array(
		'abbv' => 'Gunyana',
		'full' => 'Gunyana',
	) ,
	'october' => array(
		'abbv' => ' Gumiguru',
		'full' => ' Gumiguru',
	) ,
	'november' => array(
		'abbv' => 'Mbudzi',
		'full' => 'Mbudzi',
	) ,
	'december' => array(
		'abbv' => 'Zvita',
		'full' => 'Zvita',
	) ,
);
