<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-09 01:30+0000
$lang = array(
	'sharing_name' => array(
		'required' => 'Kugova zita kunosungirwa.',
	) ,
	'sharing_url' => array(
		'required' => 'URL yesite iyi inodiikanwa',
		'url' => 'URL yesite iyi haisi chaiyo.',
	) ,
);
