<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-04 05:24+0000
$lang = array(
	'access' => 'Donho',
	'add' => 'Wedzera',
	'added_by' => 'Wedzera ne',
	'alerts' => 'Pihwa  changamudza',
	'alerts_get' => 'Pihwa  changamudza',
	'alerts_mobile_phone' => 'Foni nhumba',
	'allowed' => 'Bvumirwa',
	'and' => 'ne',
	'api' => 'API',
	'approve' => 'Bvumira	',
	'approved' => 'Abvumira	',
	'author' => 'Munyori	',
	'blog' => ' Rutarwa',
);
