<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-09 01:37+0000
$lang = array(
	'upgrade_automatic' => 'Otomatiki apugradhi',
	'upgrade_available' => 'Maapudated Aripo',
	'upgrade_continue_btn_text' => 'Enderera',
	'upgrade_db_btn_text' => 'Apugradhi',
	'upgrade_db_text_1' => 'Ndava kuapugradha database vhezheni',
	'upgrade_db_text_2' => 'kudataase vhezheni itsva',
	'upgrade_db_title' => 'Ushahidi database apugradhi',
	'upgrade_failed' => 'Apugredhi yatadza kupfuurira mberi',
	'upgrade_database' => 'Database:',
	'ushahidi_release_version' => 'Ushahidi %s',
	'beta' => 'BETA!',
	'log_file' => 'Log refaira',
);
