<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-09-16 16:26+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vă rugăm introduceți un cod de securitate valid.',
		'required' => 'Vă rugăm introduceți un cod de securitate.',
	) ,
	'email' => array(
		'email' => 'Câmpul email nu pare să conțină o adresă validă de email?',
		'length' => 'Câmpul email trebuie să fie de cel puțin 4 caractere și nu mai mult de 64 de caractere lungime.',
		'required' => 'Câmpul email este necesar dacă checkbox-ul este bifat.',
	) ,
	'error' => array(
		'required' => 'Câmpul ce conține eroarea este necesar.',
	) ,
	'subject' => array(
		'length' => 'Câmpul ce conține subiectul trebuie să fie de cel puțin 3 caractere lungime.',
		'required' => 'Câmpul subiect este necesar.',
	) ,
	'yourname' => array(
		'length' => 'Câmpul ce conține numele trebuie să fie de cel puțin 3 caractere lungime.',
		'required' => 'Câmpul ce conține numele este necesar.',
	) ,
);
