<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-06 06:10+0000
// PO revision date:  2013-01-05 13:42+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Vin',
		'full' => 'Vineri',
	) ,
	'monday' => array(
		'abbv' => 'Lun',
		'full' => 'Luni',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Sâm',
		'full' => 'Sâmbătă',
	) ,
	'sunday' => array(
		'abbv' => 'Dum',
		'full' => 'Duminică',
	) ,
	'thursday' => array(
		'abbv' => 'Joi',
		'full' => 'Joi',
	) ,
	'tuesday' => array(
		'abbv' => 'Mar',
		'full' => 'Marți',
	) ,
	'wednesday' => array(
		'abbv' => 'Mie',
		'full' => 'Miercuri',
	) ,
	'january' => array(
		'abbv' => 'Ian',
		'full' => 'Ianuarie',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Februarie',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Martie',
	) ,
	'april' => array(
		'abbv' => 'Apr',
		'full' => 'Aprilie',
	) ,
	'may' => array(
		'abbv' => 'Mai',
		'full' => 'Mai',
	) ,
	'june' => array(
		'abbv' => 'Iun',
		'full' => 'Iunie',
	) ,
	'july' => array(
		'abbv' => 'Iul',
		'full' => 'Iulie',
	) ,
	'august' => array(
		'abbv' => 'Aug',
		'full' => 'August',
	) ,
	'september' => array(
		'abbv' => 'Sep',
		'full' => 'Septembrie',
	) ,
	'october' => array(
		'abbv' => 'Oct',
		'full' => 'Octombrie',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'Noiembrie',
	) ,
	'december' => array(
		'abbv' => 'Dec',
		'full' => 'Decembrie',
	) ,
);
