<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-05 06:10+0000
// PO revision date:  2013-01-04 17:54+0000
$lang = array(
	'cURL_not_installed' => 'php5-curl nu este instalat pe acest sistem.',
);
