<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-05 06:10+0000
// PO revision date:  2013-01-04 18:16+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vă rugăm să introduceți un cod de securitate valid.',
		'required' => 'Vă rugăm să introduceți codul de securitate.',
	) ,
	'email' => array(
		'email' => 'Câmpul  de email nu pare să conțină o adresă de email validă.',
		'length' => 'Câmpul email trebuie să fie de cel puțin 4 și nu mai mult de 64 caractere lungime.',
		'required' => 'Câmpul email este necesar dacă checkbox-ul este activ.',
	) ,
	'message' => array(
		'required' => 'Câmpul de comentarii este necesar.',
	) ,
	'name' => array(
		'length' => 'Câmpul nume trebuie să fie de cel puțin 3 caractere lungime.',
		'required' => 'Câmpul de nume este necesar.',
	) ,
	'phone' => array(
		'length' => 'Câmpul de telefon este necesar.',
	) ,
);
