<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-03 06:10+0000
// PO revision date:  2013-01-02 21:40+0000
$lang = array(
	'page_title' => array(
		'required' => 'Vă rugăm introduceți un titlu de pagină.',
		'length' => 'Titlul paginii trebuie să aibă cel puțin 3 dar nu mai mult de 150 de caractere lungime.',
	) ,
	'page_tab' => array(
		'required' => 'Vă rugăm introduceți nume pentru tab-ul paginii.',
	) ,
	'page_description' => array(
		'required' => 'Vă rugăm introduceți o descriere a paginii.',
	) ,
);
