<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:10+0000
// PO revision date:  2012-08-26 04:04+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'Părinți ID trebuie să fie numeric',
	) ,
	'private_to' => array(
		'required' => 'Câmpul Către este obligatoriu',
		'exists' => 'Utilizatorul către care încerca să trimiți un mesaj nu există',
	) ,
	'private_subject' => array(
		'required' => 'Câmpul subiect este necesar',
		'length' => 'Câmpul subiect trebuie să fie între 3 și 150 de caractere',
	) ,
	'private_message' => array(
		'required' => 'Câmpul mesaj este obligatoriu',
	) ,
);
