<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-23 06:25+0000
// PO revision date:  2013-08-22 06:22+0000
$lang = array(
	'comments_form_error' => 'Eroare!',
	'country_name' => array(
		'single_country' => 'Această implementare cuprinde doar o singură țară. Vă rugăm să vă asigurați că locația alertei este în țara %s. ',
	) ,
	'custom_field' => array(
		'numeric' => 'Câmpul "%s" trebuie să fie numeric.',
		'required' => 'Câmpul "%s" este necesar.',
		'not_exist' => 'Câmpul "%s" nu exista.',
		'permission' => 'Câmpul "%s" nu poate fi editat cu contul tau.',
		'email' => 'Câmpul "%s" trebuie să contina o adresa de mail valida.',
		'phone' => 'Câmpul "%s" trebuie să contina un număr de telefon valid.',
		'date_mmddyyyy' => 'Câmpul "%s" trebuie să conțină o dată validă (MM/DD/YYYY).',
		'date_ddmmyyyy' => 'Câmpul "%s" trebuie să conțină o dată validă (DD/MM/YYYY).',
	) ,
	'data_include' => array(
		'between' => 'Vă rugăm să selectați un element valabil de inclus în download.',
		'numeric' => 'Vă rugăm să selectați un element valabil de inclus în download.',
	) ,
	'data_active' => array(
		'between' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'numeric' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'required' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
	) ,
	'data_verified' => array(
		'between' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'numeric' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
		'required' => 'Vă rugăm să selectați "Rapoarte în curs de aprobare" sau "Rapoarte aprobate" sau ambele.',
	) ,
	'data_point' => array(
		'between' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
		'numeric' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
		'required' => 'Vă rugăm să selectați un tip valid de raport pentru descărcare.',
	) ,
	'format' => array(
		'required' => 'Trebuie să selectați un format de descărcare. Selectați fie CSV sau XML.',
		'valid' => 'Vă rugăm să selectați un format valabil în care să descărcați rapoartele',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Câmpul data FROM nu pare să conțină o dată validă.',
		'range' => 'Vă rugăm să introduceți o dată validă pentru câmpul FROM. Data nu poate fi mai mare decât ziua curentă.',
	) ,
	'incident_active' => array(
		'between' => 'Vă rugăm să introduceți o valoare validă pentru Aprobă Prezentul Raport',
		'required' => 'Vă rugăm să introduceți o valoare validă pentru Aprobă Prezentul Raport',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Câmpul am/pm nu pare să conțină o valoare validă.',
	) ,
	'incident_category' => array(
		'numeric' => 'Câmpul "Categorii" nu pare să conțină o categorie validă.',
		'required' => 'Câmpul "Categorii" este necesar.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Câmpul data nu pare să conțină o dată validă.',
		'date_mmddyyyy' => 'Câmpul data nu pare să conțină o dată validă.',
		'required' => 'Câmpul data este necesar.',
	) ,
	'incident_description' => array(
		'required' => 'Câmpul "Descriere" este necesar.',
	) ,
	'incident_hour' => array(
		'between' => 'Câmpul ora nu pare să conțină o oră validă.',
		'required' => 'Câmpul oră este necesar.',
	) ,
	'incident_information' => array(
		'alpha' => 'Vă rugăm să introduceți o valoare validă pentru Probabilitatea Informațiilor.',
		'length' => 'Vă rugăm să introduceți o valoare validă pentru Probabilitatea Informațiilor.',
	) ,
	'incident_minute' => array(
		'between' => 'Câmpul minute nu pare să conțină o valoare validă.',
		'required' => 'Câmpul minut este necesar.',
	) ,
	'incident_news' => array(
		'url' => 'Câmpul ce conține link-uri cu surse de știri nu pare să conțină o adresă URL validă.',
	) ,
	'incident_photo' => array(
		'size' => 'Vă rugăm, asigurați-vă că fotografiile încărcate sunt limitate la 2MB.',
		'type' => 'Câmpul de Încărcare Fotografii nu pare să conțină o imagine validă. Formatele acceptate sunt doar. JPG,. PNG și. GIF.',
		'valid' => 'Câmpul de Încărcare Fotografii nu pare să conțină un fișier valid.',
	) ,
	'incident_source' => array(
		'alpha' => 'Vă rugăm să introduceți o valoare validă pentru Fiabilitatea Sursei.',
		'length' => 'Vă rugăm să introduceți o valoare validă pentru Fiabilitatea Sursei.',
	) ,
	'incident_title' => array(
		'length' => 'Câmpul "Titlu Raport" trebuie să aibă cel puțin 3 dar nu mai mult de 200 de caractere lungime.',
		'required' => 'Câmpul "Titlu Raport" este necesar.',
		'csrf' => 'Posibil atac CSRF. Credeți serios că vreți să creați / editați un raport?',
	) ,
	'incident_verified' => array(
		'between' => 'Vă rugăm să introduceți o valoare validă pentru câmpul Verifica acest raport.',
		'required' => 'Vă rugăm să introduceți o valoare validă pentru câmpul Verifica acest raport.',
	) ,
	'incident_video' => array(
		'url' => 'Câmpul Link-uri video nu pare să conțină o adresă URL validă.',
	) ,
	'latitude' => array(
		'between' => 'Câmpul latitudine nu pare să conțină o latitudine validă.',
		'required' => 'Câmpul latitudine este necesar. Vă rugăm să faceți clic pe harta pentru a indica o locație.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Câmpul localizare are o valoare incorectă.',
		'exists' => 'Acest raport are deja o traducere pentru această limbă.',
		'length' => 'Câmpul localizare are o valoare incorectă.',
		'locale' => 'Raportul original și traducerea au aceeași localizare (limbă).',
		'required' => 'Câmpul localizare este necesar.',
	) ,
	'location_name' => array(
		'length' => 'Câmpul "Nume Locație" trebuie să aibă cel puțin 3 dar nu mai mult de 200 de caractere lungime.',
		'required' => 'Câmpul "Nume Locație" este necesar.',
	) ,
	'longitude' => array(
		'between' => 'Câmpul longitudine nu pare să conțină o longitudine validă.',
		'required' => 'Câmpul longitudine este necesar. Vă rugăm să faceți clic pe harta pentru a indica o locație.',
	) ,
	'person_email' => array(
		'email' => 'Câmpul email nu pare să conțină o adresa de email validă.',
		'length' => 'Câmpul email trebuie să aibă cel puțin 4 dar nu mai mult de 64 de caractere lungime.',
	) ,
	'person_first' => array(
		'length' => 'Câmpul prenume  trebuie să aibă cel puțin 3 dar nu mai mult de 100 de caractere lungime.',
	) ,
	'person_last' => array(
		'length' => 'Câmpul nume trebuie să aibă cel puțin 2 dar nu mai mult de 100 de caractere lungime.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Câmpul data TO nu pare să conțină o dată validă.',
		'range' => 'Vă rugăm să introduceți o dată validă pentru câmpul TO. Data nu poate fi mai mare decât ziua curentă.',
		'range_greater' => 'Câmpul dată FROM nu poate fi mai mare decât câmpul dată TO.',
	) ,
);
