<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-04 06:10+0000
// PO revision date:  2013-01-03 21:30+0000
$lang = array(
	'description' => array(
		'length' => 'Câmpul descriere trebuie să aibă cel puțin 3 dar nu mai mult de 100 de caractere lungime.',
		'required' => 'Este necesar câmpul descriere.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Câmpul de conține numele trebuie să conțină numai litere sau numere.',
		'length' => 'Câmpul de conține numele trebuie să aibă cel puțin 2 dar nu mai mult de 30 de caractere lungime.',
		'nomodify' => 'Rolul SuperAdmin nu poate fi modificat.',
		'required' => 'Este necesar câmpul nume.',
	) ,
	'access_level' => array(
		'numeric' => 'Câmpul Access Level trebuie să fie între 0 - 100.',
		'required' => 'Câmpul Access Level trebuie să fie între 0 - 100.',
	) ,
	'permissions' => array(
		'numeric' => 'Câmpul Permissions trebuie să fie între 0 - 100.',
	) ,
);
