<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-01-05 06:10+0000
// PO revision date:  2013-01-04 16:44+0000
$lang = array(
	'approved' => 'Aprobat',
	'categories' => 'Categorii',
	'category_impact' => 'Impact Categorie',
	'category_impact_description' => 'Această diagramă vă oferă o vedere liniara a rapoartelor pe categorii de-a lungul timpului. Derulați de la stânga la dreapta pentru a vedea o imagine comparativă a diferitelor categorii. Puneți mouse-ul peste grafic pentru mai multe detalii.',
	'choose_date_range' => 'Alege un interval pentru dată.',
	'countries' => 'Țări',
	'country' => 'Țara',
	'country_breakdown' => 'Împărțire pe țări',
	'description' => 'Aceasta este secțiunea de statistici și va conține o descriere generală în curând. Pentru moment, navigați folosind link-urile de mai sus ale  subcategoriei.',
	'error' => 'Eroare',
	'glossary' => 'Glosar',
	'hit_summary' => 'Sumar Hit-uri',
	'legend' => 'Legendă',
	'pageviews' => 'Pagini vizualizate',
	'pageviews_description' => 'Numărul total de pagini pe care vizitatorii l-au văzut pe site-ul dvs.',
	'reports' => 'Rapoarte',
	'reports_categories' => 'Categorii Rapoarte',
	'reports_statistics' => 'Statistici Rapoarte',
	'reports_status' => 'Status Rapoarte',
	'report_punchcard' => 'Raport Punchcard',
	'report_stats' => 'Statistici Rapoarte',
	'stats_not_setup' => 'Statisticile nu au fost setate',
	'time_range_1' => '1 Lună',
	'time_range_2' => '3 Luni',
	'time_range_3' => '6 Luni',
	'time_range_all' => 'Tot',
	'unapproved' => 'Neaprobat',
	'unique_visitors' => 'Vizitatori unici',
	'unique_visitors_description' => 'Numărul de persoane care vin această implementare. Vizitatorii unici sunt determinați folosind cookie-urile. Vizitatorii care nu au cookie-urile activate vor fi identificați ținând cont de adresa IP, rezoluția, browser-ul, plugin-uri, sistem de operare, etc.',
	'unverified' => 'Neverificat',
	'verified' => 'Verificat',
	'visitor_summary' => 'Sumar Vizitatori',
	'visits' => 'Vizite',
	'visits_description' => 'O vizită este o înregistrare a unui vizitator unic ce revine la site în mai mult de 30 minute de la ultima vizualizare de pagină.',
);
