<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-14 06:13+0000
// PO revision date:  2013-04-13 06:48+0000
$lang = array(
	'actions' => array(
		'add_to_category' => 'Aceasta adaugă raportul la categorii adiționale. Dacă selectați Categoria 1 și raportul are deja Categoria 2, raportul va avea atunci atât Categoria 1 cât și Categoria 2.',
		'approve' => 'Aprobă un raport sau nu. Dacă va fi aprobat, aceasta va apărea în mod public.',
		'assign_badge' => 'Veți fi capabil să atribuiți o insignă utilizatorului ce face declanșarea. Alege insigna pe care i-o repartizați aici.',
		'email_body' => 'Corpul mesajului pentru emailul ce va fi trimis.',
		'email_subject' => 'Subiectul emailului ce va fi trimis.',
		'report_title' => 'Acesta este titlul implicit ce va fi adăugat la raport.',
		'verify' => 'Marchează un raport ca verificat sau nu.',
	) ,
	'default_value' => 'Separați fiecare valoare cu o virgulă, de exemplu, valoare1, valoare2.',
	'dropdown_choices' => 'Separați fiecare element cu o virgulă, de exemplu, valoare1, valoare2.',
	'private_to' => 'Începeți să scrieti lista membrilor.',
	'private_subject' => 'Subiectul mesajului privat',
	'private_message' => 'Mesaj privat',
	'profile_email' => 'Adresa dvs. de email',
	'profile_public_url' => 'Aceasta este adresa unde profilul dvs. public poate fi găsit.',
	'profile_username' => 'Numele utilizatorului nu poate fi schimbat.',
	'settings_alert_email' => 'Aceasta este adresa de email care va fi folosita pentru a trimite alerte prin e-mail.',
	'settings_allow_comments' => 'Permite utilizatorilor sa comenteze rapoartele in site-ul principal.',
	'settings_cache_pages_lifetime' => 'Setează durata de viață a cache-ului.',
	'settings_flsms_text_1' => 'Numerele de telefon prin care mesajele text sunt primite.',
	'settings_map_provider' => 'Acesta defineste care harta va fi utilizată pe site.',
);
