<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-03-27 06:25+0000
// PO revision date:  2014-03-26 18:31+0000
$lang = array(
	'email' => array(
		'email' => 'El correo introducido no es válido.',
		'exists' => 'Lo sentimos, ya existe una cuenta registrada con ese correo electrónico.',
		'length' => 'El campo de correo electrónico debe tener entre 4 y 64 caracteres.',
		'required' => 'El campo de correo electrónico es obligatorio.',
	) ,
	'name' => array(
		'length' => 'El campo de nombre debe tener una longitud entre 3 y 100 carecteres',
		'required' => 'El campo Nombre es obligatorio.',
		'standard_text' => 'El campo Usuario tiene caracteres no permitidos.',
	) ,
	'current_password' => array(
		'length' => 'La contraseña debe contener al menos 8 caracteres.',
		'login error' => 'Compruebe que a escrito correctamente el correo electrónico y la contraseña.',
		'matches' => 'Por favor, escriba la misma contraseña en los dos compos de contraseña.',
		'required' => 'La contraseña es obligatorio.',
		'alpha_dash' => 'La contraseña debe contener caracter alfabéticos, los símbolos # y @, numeros, guiones bajos y guiones.',
		'incorrect' => 'La contraseña que ha escrito es incorrecta. Vuelva a intentarlo.',
	) ,
	'new_password' => array(
		'length' => 'La contraseña debe tener al menos 8 caracteres de longitud.',
		'login error' => 'Por favor compruebe que ha introducido correctamente el correo electrónico y la contraseña.',
		'matches' => 'Por favor escribe la misma contraseña en los dos campos de contraseña.',
		'required' => 'La contraseña es obligatoria.',
		'alpha_dash' => 'La contraseña debe contener caracter alfabéticos, los símbolos # y @, numeros, guiones bajos y guiones.',
	) ,
	'password' => array(
		'default' => 'Hubo un error en el acceso.',
		'length' => 'La contraseña debe contener al menos 8 caracteres.',
		'login error' => 'Por favor compruebe que ha escrito correctamente el correo electrónico y la contraseña.',
		'matches' => 'Por favor, escribe la misma contraseña en los dos campos de contraseña.',
		'required' => 'La contraseña es obligatoria.',
		'riverid server down' => 'El servidor de acceso no está operativo. Por favor, vuelva a intentarlo.',
		'riverid' => '%s',
		'alpha_dash' => 'La contraseña debe contener caracter alfabéticos, los símbolos # y @, numeros, guiones bajos y guiones.',
	) ,
	'password_confirm' => array(
		'matches' => 'El campo de confirmación de contraseña debe coincidir con el campo de la contraseña.',
	) ,
	'resetemail' => array(
		'email' => 'El correo electrónico que has escrito no es válido.',
		'invalid' => 'Perdón, pero no tenemos tu correo electrónico.',
		'required' => 'El correo electrónico es obligatorio.',
	) ,
	'role' => array(
		'superadmin_modify' => 'Solo un superadministrador puede modificar a una superadministrador o actualizar a un usuario a administrador.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Formato de papel inválido.',
		'length' => 'El papel tiene que tener entre 5 y 30 caracteres.',
		'required' => 'Debe de definir al menos un papel.',
		'values' => 'Debe seleccionar ADMINISTRADOR o USUARIO.',
	) ,
	'token' => array(
		'invalid' => 'El token de contraseña obligatoria no es válido.',
		'required' => 'El token de contraseña olvidada es obligatorio.',
	) ,
	'username' => array(
		'admin' => 'El papel de administrador no puede ser modificado.',
		'alpha_numeric' => 'URL publica del perfil solo puede contener números y letras.',
		'exists' => 'Perdón, URL pública en uso.',
		'length' => 'La URL pública del perfil tiene que tener entre 2 y 100 caracteres de largo.',
		'login error' => 'Compruebe que a escrito correctamente la URL publica de perfil.',
		'required' => 'La URL pública de perfil es obligatoria.',
		'superadmin' => 'El papel de superadministrador no puede ser modificado.',
		'csrf' => 'Posible ataque CSRF. ¿De verdad quieres crear/editar un usuario?',
	) ,
);
