<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:23+0000
// PO revision date:  2013-07-09 20:17+0000
$lang = array(
	'captcha' => array(
		'default' => 'Introduce un código de seguridad válido.',
		'required' => 'Introduce el código de seguridad.',
		'valid' => 'El código de seguridad es incorrecto.',
	) ,
	'comment_author' => array(
		'length' => 'El campo Nombre debe contener al menos 3 caracteres.',
		'required' => 'El campo Nombre es obligatorio.',
	) ,
	'comment_description' => array(
		'required' => 'El campo Comentarios es obligatorio.',
	) ,
	'comment_email' => array(
		'email' => 'La dirección escrita en el campo Correo Electrónico es incorrecta.',
		'length' => 'El campo de correo electrónico debe tener entre 4 y 64 caracteres.',
		'required' => 'El campo de correo electrónico es obligatorio si la casilla está marcada.',
	) ,
);
