<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:23+0000
// PO revision date:  2013-07-09 20:08+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Introduce un código de seguridad válido.',
		'required' => 'Introduce el código de seguridad.',
	) ,
	'contact_email' => array(
		'email' => 'La dirección escrita en el campo Correo Electrónico es incorrecta.',
		'required' => 'Introduce una dirección de correo electrónico válida.',
	) ,
	'contact_message' => array(
		'required' => 'El campo Mensaje es obligatorio.',
	) ,
	'contact_subject' => array(
		'length' => 'El campo Asunto debe contener al menos 3 caracteres.',
		'required' => 'El campo Asunto es obligatorio.',
	) ,
);
