<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-03-28 06:25+0000
// PO revision date:  2014-03-27 15:58+0000
$lang = array(
	'reports_view' => 'Ver informes',
	'reports_edit' => 'Crear/Editar/Eliminar informes',
	'reports_approve' => 'Aprobar informes',
	'reports_verify' => 'Verificar informes',
	'reports_comments' => 'Gestionar comentarios',
	'reports_download' => 'Descargar informes',
	'reports_upload' => 'Subir informes',
	'messages' => 'Gestionar mensajes',
	'messages_reporters' => 'Gestionar mensajes de los reporteros.',
	'stats' => 'Ver estadísticas.',
	'settings' => 'Modificar los ajustes',
	'manage' => 'Gestionar el panel',
	'users' => 'Gestionar usuarios',
	'manage_roles' => 'Gestionar Roles',
	'checkin' => 'Puede comprobar',
	'checkin_admin' => 'Gestionar comprobaciones',
	'admin_ui' => 'Acceder a la interfaz de administrador.',
	'member_ui' => 'Acceder a la interfaz de miembro.',
	'delete_all_reports' => 'Borrar todos los informes.',
);
