<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-07-10 06:23+0000
// PO revision date:  2013-07-09 19:23+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'El ID debe ser numérico',
	) ,
	'private_to' => array(
		'required' => 'El campo Para es obligatorio',
		'exists' => 'El usuario al que está intentando enviar el mensaje no existe',
	) ,
	'private_subject' => array(
		'required' => 'La campo Asunto es obligatorio',
		'length' => 'El asunto debe tener entre 3 y 150 caracteres',
	) ,
	'private_message' => array(
		'required' => 'El campo Mensaje es obligatorio',
	) ,
);
