<?php
/**
 * MHI - Legal
 *
 * PHP version 5
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 * @author     Ushahidi Team <team@ushahidi.com>
 * @package    Ushahidi - http://source.ushahididev.com
 * @module     Page View
 * @copyright  Ushahidi - http://www.ushahidi.com
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 */
?>
		<div id="primary-content">
            <div class="twocol-left"><div class="content-shadow">
                <h2>Legal</h2>
                <h3>Website Terms of Use</h3>

                <p class="intro-para">PLEASE REVIEW BEFORE USING THIS WEBSITE - IF YOU DO NOT AGREE TO THESE TERMS OF USE, DO NOT USE THIS WEBSITE.</p>

				<h4>General Description</h4>

				<p>Welcome to Crowdmap. Crowdmap hosts maps created by users using the <a href="http://www.ushahidi.com">Ushahidi</a> platform (the "Services"), through our website available at <a href="http://www.crowdmap.com">http://www.crowdmap.com</a> (the "Site"). Each map displays crowdsourced location and information data generated by users.  By way of example, a user might create a map using Crowdmap and the Ushahidi platform to present location and information data about where emergency services are needed during a natural disaster.</p>

				<p>To provide the Services, we have to set out some ground rules for using the Site in this document (the "Terms"). By accessing, using, or contributing to the Services or the Site, and in consideration for the Services we provide to you, you agree to abide by the Terms.</p>

				<p>Crowdmap may change the Terms from time to time, at Crowdmap's sole discretion. Your continued use of the Site following the posting of such changes will constitute your assent to all such changes. Please periodically visit this section of the Site to review the current version of the Terms.</p>

                <h4>DISCLAIMER OF WARRANTY and LIMITATION OF LIABILITIES</h4>

				<p>THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR OTHERWISE. WITHOUT LIMITATION, WE DISCLAIM ANY AND ALL WARRANTIES REGARDING THE ACCURACY, SECURITY, RELIABILITY, TIMELINESS, AND PERFORMANCE OF ALL SERVICES ASSOCIATED WITH USE OF THE SITE. WE MAKE NO WARRANTY, EXPRESS OR IMPLIED, THAT YOUR USE OF THE SITE WILL BE UNINTERRUPTED, TIMELY, OR ERROR-FREE. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF CERTAIN WARRANTIES, SO PORTIONS OF THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU.</p>

				<p>TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, CROWDMAP WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF OR INABILITY TO USE THE SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SITE IS SOLELY AT YOUR OWN RISK. UNDER NO CIRCUMSTANCES SHALL CLOUDMAP BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, INCOME, BUSINESS OPPORTUNITIES, AND ANY OTHER INJURY REGARDLESS OF THE NATURE OF THE CLAIM OR THE FORM OF ACTION, ARISING OUT OF OR CONNECTED WITH THE SITE (INCLUDING BUT NOT LIMITED TO ITS OPERATION, ITS CONTENTS, OR THE INFORMATION OR MATERIALS CONTAINED THEREIN, OR THE USE OR INABILITY TO USE ANY OTHER SITE LINKED TO THE SITE, OR ANY CONTENT CONTAINED IN ANY SUCH SITE, OR THESE TERMS, OR THE PRIVACY POLICY APPLICABLE TO THE SITE) EVEN IF CROWDMAP, ITS SUPPLIERS, OR LICENSORS HAVE BEEN NOTIFIED OF THE POSSIBILITY OF ANY DAMAGES.</p>

				<h4>Account</h4>

				<h4>Registration</h4>

				<p>To utilize the Site and Services, or certain portions thereof, you may be required to complete a registration process and establish an account with Crowdmap (a "Crowdmap Account"). You represent and warrant that all information provided by you to Crowdmap is current, accurate, and complete, and that you will maintain the accuracy and completeness of this information on a prompt, timely basis.</p>

				<h4>Password and Security</h4>

				<p>As a registered user of the Site and Services, you may receive or establish one or more passwords. You are solely responsible for maintaining the confidentiality and security of your password(s) and Crowdmap Account(s). You understand and agree that you fully responsible for all actions and postings made from your Crowdmap Account(s), including, but not limited to, the creation of any Ushahidi maps and/or the posting of any information to such a map. Any accounts you create are not transferable. You agree to notify Crowdmap immediately if you become aware of any unauthorized use of your Crowdmap Account(s).</p>

				<h4>Termination</h4>

				<p>Crowdmap reserves the right to terminate your Crowdmap Account(s) or restrict access to your Crowdmap Account(s), or to delete any content posted through your Crowdmap Account(s), including but not limited to entire Ushahidi maps, with or without notice, for any or for no reason, and without any liability to you.</p>

				<h4>Community Participation</h4>

				<h4>Content</h4>

				<p><strong>For the purposes of this agreement, "Content" includes any posting or submission to the <a href="http://www.crowdmap.com">Crowdmap website</a>, any posting or submission made to Crowdmap via SMS or Crowdmap's twitter hashtag, and any content that Crowdmap embeds on its site at the direction of the user.</strong></p>

				<p>Content contributed to the Site should be relevant to the subject scope of Crowdmap. Content may not be illegal, obscene, defamatory, threatening, infringing of intellectual property rights, invasive of privacy or otherwise injurious or objectionable.</p>

				<p>Unacceptable Content includes, but is not limited to, the following:
					<ol>
						<li>Statements that are intended as a personal attack or are abusive, harassing, or threatening</li>
						<li>Defamatory or knowingly false statements, including, but not limited to, wrongful or misleading inclusion of persons or entities on an Ushahidi map, and any other direct or indirect statement shown to be defamatory or false</li>
						<li>Irrelevant statements, commercial solicitations, or SPAM</li>
						<li>Materials that violate the copyright, trademark, or trade secret rights of others that are not otherwise authorized by law, such as fair use</li>
					</ol>
				</p>

				<p>We will determine what is "unacceptable Content" on a case-by-case basis, in our sole and absolute discretion. We reserve the right to change these standards at any time. We also reserve the right to remove links to unacceptable off-site content at any time.</p>

				<p>Crowdmap does not pre-screen or regularly review any contributed Content, but Crowdmap has the right (though not the obligation) to remove, without notice, any content posted which Crowdmap considers, for any reason, to violate these Terms or to be outside the subject scope of the Services. Crowdmap may terminate any Crowdmap Account, with or without notice, for posting such Content.</p>

				<h4>Licenses Applicable to Contributed Content</h4>

				<p>
					<ol type="a" style="list-style-type:lower-alpha;">
						<li>By contributing Content to Crowdmap, you are granting Crowdmap a non-exclusive, royalty-free, perpetual, irrevocable, worldwide license to use that Content (which includes original video or other content hosted on a third-party server and/or site) in connection with the operation of the Site and Services, including, without limitation, the license rights to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Content, and/or to incorporate it into a collective work.</li>
						<li>By contributing Content to Crowdmap, you are also granting other users of Crowdmap a non-exclusive, royalty-free, perpetual, irrevocable, worldwide license to use that Content without limitation.</li>
					</ol>
				</p>

				<h4>User Representations and Warranties</h4>

				<p>By posting any Content, including embedded video content hosted on third-party servers and/or sites, you represent and warrant that:</p>
				<p>
					<ol type="a" style="list-style-type:lower-alpha;">
						<li>you have all right, title, and interest to such posted Content, including but not limited to any consent, authorization, release, clearance or license from any third party (such as, but not limited to, any release related to rights of privacy or publicity) necessary for you to provide, post, upload, input or submit the content; or</li>
						<li>that such Content is in the public domain or that your use of such Content constitutes fair use.</li>
					</ol>
				</p>

				<p>You further represent and warrant that posting such Content does not violate or constitute the infringement of any patent, copyright, trademark, trade secret, right of privacy, right of publicity, moral rights, or other intellectual property right recognized by any applicable jurisdiction of any person or entity, or otherwise constitute the breach of any agreement with any other person or entity. You further represent and warrant that you are who you say you are, that you have not submitted fictitious, false or inaccurate information about yourself, and that all information contained in the posted content is true and your own work or work you are authorized to submit, and that the posted Content does not contain any threatening, harassing, libelous, false, defamatory, offensive, obscene, or pornographic, material, or other material that would violate any other applicable law or regulation. You agree that you will not knowingly and with intent to defraud provide material and misleading information. You represent and warrant that any and all Content that you supply does not violate the Terms or any applicable law.</p>

				<h4>Browsing</h4>

				<p>You understand that material made available by Crowdmap is a product of a community effort and does not necessarily represent the views of Crowdmap. Crowdmap assumes no responsibility for the accuracy, suitability, or completeness of any content provided.</p>

				<h4>Linking</h4>

				<p>You understand that Crowdmap does not and cannot review all material made available through websites linked or linking to any part of the Site. You also understand that no such linking implies in any way that Crowdmap endorses or is affiliated with any third-party website. You agree that Crowdmap bears no responsibility or liability for any content accessed or harm caused from any third-party website.</p>

				<h4>Acts Against the Site/Services</h4>

				<p>You shall not attempt or engage in potentially harmful acts that are directed against the Site or Services including, without limitation, the following:</p>

				<p>
					<ol type="a" style="list-style-type:lower-alpha;">
						<li>Using the Site or Services in contravention of any other agreement to which you are a party, including without limitation any employment agreement to which you may be a party;</li>
						<li>causing, allowing, or assisting any other person to use your Crowdmap Account(s) or impersonate you, or logging onto a server or Crowdmap Account(s) that you are not authorized to access;</li>
						<li>forging user names, manipulating identifiers, or otherwise impersonating any other person or misrepresenting your identity or affiliation with any person or entity;</li>
						<li>emulating or faking Site or Service visits or usage;</li>
						<li>causing, allowing or assisting machines, bots, or automated services to access or use the Site or Services without the express written permission of the Crowdmap;</li>
						<li>tampering, disrupting or otherwise interfering or attempting to interfere with the operation, functionality, or the security of the Site or Services, including, but not limited to, introducing viruses, worms, software, Trojan horses or other similar harmful code into the Site or Services, or attempting to probe, scan or test the vulnerability of the Site or any associated system or network, or breach any security, authentication or material usage rules or measures, or overloading, "flooding," "spamming," "mail bombing," "pinging" or "crashing" the Site;</li>
						<li>harvesting or collecting email addresses or other contact information of other users or clients from the Site by electronic or other means;</li>
						<li>reverse engineering, decompiling, disassembling, deciphering, or otherwise attempting to derive the source code for any underlying intellectual property used to provide the Site or Services;</li>
						<li>engaging in "framing," "mirroring," or otherwise simulating the appearance or function of the Site; and</li>
						<li>forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting.</li>
					</ol>
				</p>

				<p>We reserve the right to reclaim user names on behalf of businesses or individuals that hold legal claim or trademark on those user names. Accounts using business names and/or logos to mislead others will be permanently suspended.</p>

				<p>Violations of system or network security may result in civil or criminal liability. You agree that it is your responsibility to install anti-virus software and related protections against viruses, Trojan horses, worms, time bombs, cancelbots, or other computer programming routines or engines that are intended to damage, destroy, disrupt, or otherwise impair a computer's functionality or operation.</p>

				<h4>Parental Notice</h4>

				<p>Pursuant to 47 U.S.C. Section 230(d) as amended, Crowdmap hereby notifies you that parental control protections (such as computer hardware, software, or filter services) are commercially available that may assist you in limiting access to material that is harmful to minors. Information identifying current providers of such protection is available on the Internet (e.g., <a href="http://en.wikipedia.org/wiki/List_of_content-control_software">http://en.wikipedia.org/wiki/List_of_content-control_software</a>).</p>

				<h4>Copyright Complaints</h4>

				<p>If you are a copyright owner and you believe that your copyrighted materials have been used in a way that constitutes copyright infringement, please see our <a href="http://crowdmap.com/mhi/legal/dmca">DMCA Notice Policy</a>.</p>

				<h4>Indemnities</h4>

				<p>You acknowledge and agree to indemnify and hold Crowdmap and Ushahidi, their affiliates, officers, employees and agents, harmless, including costs and attorneys' fees, from any claim or demand made by any third party due to or arising out of your use of the Site or Services, your violation of these Terms, or the infringement by you or made under your Crowdmap Account(s), of any intellectual property or other right of any person or entity.</p>

				<h4>Modifications</h4>

				<p>Crowdmap reserves the right to change, at any time, at our sole discretion, the Terms under which these Services are offered. You are responsible for regularly reviewing the Terms. Your continued use of the Site and Services constitutes your agreement to all such Terms.</p>

				<h4>Termination of Service</h4>

				<p>Crowdmap disclaims all responsibility and liability for the availability, timeliness, security or reliability of the Services or Site, or any software provided through the Site. Crowdmap reserves the right to modify, suspend, or discontinue the Services or access to the Site without any notice at any time and without any liability to you.</p>

				<h4>Scope of Terms</h4>

				<p>The Terms apply to use of and contribution to the Site and any account provided therefore. Crowdmap may operate additional projects or services which require separate or additional terms. Such different terms are made available through the individual project or service and are not addressed further herein.</h4>

				<h4>No Waiver of Terms</h4>

				<p>Failure of Crowdmap to exercise or enforce any right or provision of these Terms shall not be deemed a waiver of such right or provision in that or any other instance.</p>

				<h4>Governing Law and Entire Agreement</h4>

				<p>These Terms are governed by the laws of the State of Florida, without regard to the rules of conflict of law that may cause the laws of another jurisdiction to apply. You agree to the sole and exclusive jurisdiction and venue of the federal or state courts serving Orange County in the State of Florida in the event of any dispute of any kind arising from or relating to the Site or Services, or your use or review of it. The Terms constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. If for any reason a court of competent jurisdiction finds any provision or portion of these Terms to be unenforceable, the remainder of the Terms will continue in full force and effect.</p>

			</div></div>
            <div class="twocol-right">
				<!-- right nav -->
				<div class="side-bar-module rounded shadow">
					<h4>Legal</h4>
					<div class="side-bar-content">
						<ul class="sub-nav-links">
							<li><a href="<?php echo url::site(); ?>mhi/legal">Terms of Use</a></li>
							<li><a href="<?php echo url::site(); ?>mhi/legal/dmca">Digital Millennium Copyright Act Policy</a></li>
							<li><a href="<?php echo url::site(); ?>mhi/legal/privacy">Privacy Notice</a></li>
						</ul>
					</div>
				</div>
				<!-- / right nav -->
            </div>
            <div style="clear:both;"></div>
        </div>