<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-07 06:26+0000
// PO revision date:  2013-09-06 15:16+0000
$lang = array(
	'captcha' => array(
		'default' => 'Vui lòng điền vào mã an ninh hợp lệ.',
		'required' => 'Vui lòng điền vào mã an ninh.',
	) ,
	'email' => array(
		'email' => 'Phần thông tin về địa chỉ email không chứa địa chỉ email hợp lệ?',
		'length' => 'Phần khung thông tin email phải chứa ít nhất 4 ký tự và tối đa 64 ký tự về độ dài.',
		'required' => 'lĩnh vực email được yêu cầu nếu phần lựa chọn được đánh dấu.',
	) ,
	'error' => array(
		'required' => 'lĩnh vực lỗi nhất thiết phải có.',
	) ,
	'subject' => array(
		'length' => 'lĩnh vực chủ đề phải có ít nhất 3 kí tự độ dài.',
		'required' => 'lĩnh vực chủ đề nhất thiết phải có.',
	) ,
	'yourname' => array(
		'length' => 'lĩnh vực tên phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'lĩnh vực tên nhất thiết phải có.',
	) ,
);
