<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-06 06:26+0000
// PO revision date:  2013-09-05 16:59+0000
$lang = array(
	'config' => 'tập tin cấu hình',
	'controller' => 'trình điều khiển',
	'driver' => 'chương trình điều khiển',
	'driver_implements' => 'chương trình điều khiển %s cho phần thư viện %s phải mang tính hoàn thiện cho phần giao diện %s.',
	'driver_not_found' => 'Không tìm thấy chương trình điều khiển %s sử dụng cho thư viện %s.',
	'errors_disabled' => 'Bạn có thể truy cập vào <a href="%s">trang chủ</a> hoặc <a href="%s">thử lại</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Không thể hoàn thành yêu cầu',
	'helper' => 'trình giúp đỡ',
	'invalid_filetype' => 'Loại tập tin được yêu cầu, .%s, không được phép xuất hiện trong phần xem tập tin cấu hình của bạn.',
	'invalid_method' => 'Phương thức %s không hợp lệ được gọi trong %s',
	'invalid_property' => 'Thuộc tính %s không tồn tại trong class %s.',
	'library' => 'thư viện',
	'log_dir_unwritable' => 'Thư mục chứa tập tin nhật trình không thể ghi được dữ liệu: %s',
	'model' => 'mô hình',
	'no_controller' => 'Ushahidi không thể xác định được trình điều khiển để xử lý yêu cầu này: %s',
	'no_default_route' => 'Xin vui lòng thiết đặt route mặc định trong phần config/routes.php',
	'page_not_found' => 'Trang mà bạn yêu cầu, %s, không được tìm thấy.',
	'report_bug' => '<a href="%s" id="show_bugs">Gửi báo cáo về vấn đề này đến Ushahidi</a>',
	'resource_not_found' => 'Phần yêu cầu %s, %s, không được tìm thấy.',
	'stack_trace' => 'Stack Trace',
	'stats_footer' => 'Đã tải trong vòng {execution_time} giây, sử dụng {memory_usage} bộ nhớ. Được tạo bởi Ushahidi v%s.',
	'text_direction' => 'ltr',
	'there_can_be_only_one' => 'Chỉ có duy nhất một yêu cầu được thực hiện cho mỗi tiến trình trong mỗi trang.',
	'uncaught_exception' => 'Uncaught %s: %s trong tập tin %s trên dòng %s',
	'view' => 'xem',
	'view_set_filename' => 'Bạn phải thiết lập xem tên tập tin trước khi gọi phần render.',
);
