<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-07 06:26+0000
// PO revision date:  2013-09-06 15:33+0000
$lang = array(
	'date' => 'NGÀY THÁNG',
	'feed_name' => array(
		'length' => 'Phần khung thông tin tên feed phải có ít nhất 3 ký tự 
			tối đa 70 ký tự về độ dài.',
		'required' => 'hãy nhập tên của nguồn cung cấp dữ liệu.',
	) ,
	'feed_url' => array(
		'required' => 'hãy nhập đường dẫn liên kết của nguồn cung cấp dữ liệu.',
		'url' => 'Vui lòng điền vào đường dẫn hợp lệ, ví dụ: http://www.ushahidi.com',
	) ,
	'source' => 'NGUỒN',
	'title' => 'Tiêu đề',
);
