<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-07 06:26+0000
// PO revision date:  2013-09-06 15:44+0000
$lang = array(
	'field_default' => array(
		'default' => 'Giá trị mặc định bạn đã cung cấp cho lĩnh vực này là không hợp lệ.',
		'length' => 'lĩnh vực tên phải có ít nhất 3 ký tự hoặc tối đa 200 ký tự về độ dài.',
	) ,
	'field_height' => array(
		'between' => 'xin hãy nhập giá trị 0 đến 50 cho lĩnh vực chiều cao.',
	) ,
	'field_isdate' => array(
		'between' => 'bạn đã nhập một giá trị không hợp lệ cho lĩnh vực ngày.',
		'required' => 'Xin vui lòng chọn Đồng Ý hoặc Không Đồng Ý cho phần khung thông tin ngày tháng.',
	) ,
	'field_name' => array(
		'length' => 'lĩnh vực tên phải có ít nhất 3 ký tự hoặc tối đa 100 ký tự về độ dài.',
		'required' => 'xin vui lòng nhập lĩnh vực tên.',
		'duplicate' => 'Phần khung thông tin về tên mà bạn vừa điền vào đã có trong mẫu đơn này. Vui lòng điền vào một phần khác.',
	) ,
	'field_required' => array(
		'between' => 'bạn đã nhập một giá trị không hợp lệ cho lĩnh vực được yêu cầu.',
		'required' => 'Xin vui lòng chọn Đồng Ý hoặc Không Đồng Ý cho phần khung thông tin được yêu cầu.',
	) ,
	'field_type' => array(
		'numeric' => 'xin vui lòng chọn một loại lĩnh vực hợp lệ.',
		'required' => 'Xin vui lòng chọn một loại lĩnh vực.',
	) ,
	'field_width' => array(
		'between' => 'Xin điền vào giá trị của khung thông tin về độ rộng trong khoảng 0 đến 300.',
	) ,
	'form_description' => array(
		'required' => 'Xin điền vào mô tả về mẫu đơn.',
	) ,
	'form_id' => array(
		'default' => 'Không thể xóa mẫu đơn mặc định.',
		'numeric' => 'Xin vui lòng chọn mẫu đơn để thêm vào khung thông tin này vào.',
		'required' => 'Xin vui lòng chọn mẫu đơn để thêm vào khung thông tin này vào.',
	) ,
	'form_title' => array(
		'length' => 'Phần khung thông tin tên của mẫu đơn phải có ít nhất 3 ký tự và tối đa 100 ký tự về độ dài.',
		'required' => 'Vui lòng điền vào tên của mẫu đơn.',
		'exists' => 'Một mẫu đơn với tiêu đề như thế đã tồn tại. Vui lòng chọn một phần khác.',
	) ,
);
