<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-07 06:26+0000
// PO revision date:  2013-09-06 17:49+0000
$lang = array(
	'captcha' => array(
		'default' => 'xin vui lòng nhập mã an ninh hợp lệ.',
		'required' => 'xin vui lòng nhập mã an ninh.',
	) ,
	'email' => array(
		'email' => 'Phần khung thông tin email dường như chứa địa chỉ email không hợp lệ.',
		'length' => 'Phần thông tin email phải chứa ít nhất 4 và không được nhiều hơn 64 ký tự.',
		'required' => 'Phần thông tin email được yêu cầu nếu phần lựa chọn được chọn.',
	) ,
	'message' => array(
		'required' => 'Phần khung thông tin về bình luận không được để trống.',
	) ,
	'name' => array(
		'length' => 'Phần khung thông tin tên phải chứa ít nhất 3 ký tự về độ dài.',
		'required' => 'Phần khung thông tin tên không được để trống.',
	) ,
	'phone' => array(
		'length' => 'Phần khung thông tin về số điện thoại không hợp lệ.',
	) ,
);
