<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-07 06:26+0000
// PO revision date:  2013-09-06 17:41+0000
$lang = array(
	'admin_footer' => 'Tin nhắn này đã được gửi từ website của bạn.',
	'admin_login_url' => 'Đăng nhập dạng Quản Trị Viên',
	'admin_new_comment' => array(
		'message' => 'một bình luận mới đã được gửi tới website của bạn trả lời về:',
		'subject' => 'Bình luận mới',
	) ,
	'admin_new_email' => array(
		'message' => 'Một tin nhắn mới dạng email đã được gửi đến website của bạn.',
		'subject' => 'Tin nhắn email mới',
	) ,
	'admin_new_report' => array(
		'message' => 'Một báo cáo mới đã được gửi đến website của bạn.',
		'subject' => 'Báo cáo mới',
	) ,
	'admin_new_sms' => array(
		'message' => 'Một tin nhắn mới đã được gửi đến website của bạn.',
		'subject' => 'văn bản tin nhắn mới',
	) ,
	'member_new_alert' => array(
		'message' => 'Bạn đã nhận được một cảnh báo mới',
		'subject' => 'Cảnh báo mới!',
	) ,
	'member_new_message' => array(
		'message' => 'Bạn đã nhận được một tin nhắn riêng mới',
		'subject' => 'Tạo mới tin nhắn riêng',
		'footer' => 'Để trả lời vui lòng truy cập:',
	) ,
);
