<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-06 06:26+0000
// PO revision date:  2013-09-05 07:12+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'Chỉ số gốc phải ở dạng số',
	) ,
	'private_to' => array(
		'required' => 'lĩnh vực về đối tượng nhận được yêu cầu.',
		'exists' => 'Người dùng mà bạn đang muốn gửi tin nhắn không tồn tại',
	) ,
	'private_subject' => array(
		'required' => 'lĩnh vực chủ đề được yêu cầu.',
		'length' => 'Chủ đề phải có trong khoảng3 ký tự và 150 ký tự',
	) ,
	'private_message' => array(
		'required' => 'lĩnh vực tin nhắn được yêu cầu.',
	) ,
);
