<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-09-06 06:26+0000
// PO revision date:  2013-09-05 16:24+0000
$lang = array(
	'date' => 'Ngày chuyển vào',
	'date_added' => 'Đã thêm ngày tháng',
	'last_access' => 'Lần truy cập gần đây nhất',
	'sharing_color' => array(
		'length' => 'lĩnh vực màu sắc phải chứa 6 ký tự về độ dài.',
		'required' => 'lĩnh vực màu sắc phải có.',
	) ,
	'sharing_name' => array(
		'length' => 'Phần tên Chia Sẻ hình như không hợp lệ.',
		'required' => 'Phần tên Chia Sẻ phải có.',
	) ,
	'sharing_url' => array(
		'exists' => 'Liên kết đường dẫn của trang đã tồn tại.',
		'length' => 'Liên kết đường dẫn của trang không hợp lệ.',
		'required' => 'Phần liên kết đường dẫn của trang phải có.',
		'url' => 'Phần liên kết đường dẫn của trang không chứa đường dẫn hợp lệ.',
	) ,
);
