<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-04-29 06:22+0000
// PO revision date:  2012-08-15 05:43+0000
$lang = array();
