<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-13 06:05+0000
$lang = array(
	'email' => array(
		'email' => 'El correu electrònic entrat no sembla una adreça vàlida.',
		'exists' => 'Ho sentim, ja existeix un compte d`usuari per aquesta adreça de correu electrònic.',
		'length' => 'El camp Correu Electrònci ha de tenir entre 4 i 64 caracters.',
		'required' => 'El camp Correu Electrònic és obligatori.',
	) ,
	'name' => array(
		'length' => 'El camp Nom ha de tenir entre 3 i 100 caracters.',
		'required' => 'El camp Nom és obligatori.',
		'standard_text' => 'El Camp Nom d`Usuari conté caracters no permesos.',
	) ,
	'current_password' => array(
		'length' => 'El camp Password ha de tenir 8 caracters com a mínim.',
		'login error' => 'Si us plau, reviseu que heu entrat correctament el correu electrònic i el password.',
		'matches' => 'Si us plau, poseu el mateix password als dos camps de Password.',
		'required' => 'El camp Password és obligatori.',
		'alpha_dash' => 'El camp Password només pot contenir caracters alfanumérics, els símbols # i @, números, subratllats i guions',
		'incorrect' => 'El password que heu entrat és incorrecte. Si us plau, prove-ho altra cop.',
	) ,
	'new_password' => array(
		'length' => 'El camp Password ha de tenir 8 caracters com a mínim.',
		'login error' => 'Si us plau, reviseu que heu entrat correctament el correu electrònic i el password.',
		'matches' => 'Si us plau, poseu el mateix password als dos camps de Password.',
		'required' => 'El camp Password és obligatori.',
		'alpha_dash' => 'El camp Password només pot contenir caracters alfanumérics, els símbols # i @, números, subratllats i guions',
	) ,
	'password' => array(
		'default' => 'Hi ha hagut un error intentant entrar.',
		'length' => 'El camp Password ha de tenir 8 caracters com a mínim.',
		'login error' => 'Si us plau, reviseu que heu entrat correctament el correu electrònic i el password.',
		'matches' => 'Si us plau, poseu el mateix password als dos camps de Password.',
		'required' => 'El camp Password és obligatori.',
		'riverid server down' => 'El servidor d`autenticació està caigut. Si us plau, prove-ho més tard.',
		'alpha_dash' => 'El camp Password només pot contenir caracters alfanumérics, els símbols # i @, números, subratllats i guions',
	) ,
	'password_confirm' => array(
		'matches' => 'El camp de Confirmació de Password ha de coincidir amb el camp Password.',
	) ,
	'resetemail' => array(
		'email' => 'El correu electrònic que heu posat no sembla una adreça de correu electrònic vàlida.',
		'invalid' => 'Perdoneu, no tenim la seva adreça de correu electrònic',
		'required' => 'El camp Correu Electrònic és obligatori.',
	) ,
	'role' => array(
		'superadmin_modify' => 'Només un superadmininstrador pot modificar un superadministrador o promocionar un usuari a administrador.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Format de rol invàlid.',
		'length' => 'El camp Rol ha de tenir entre 5 i 30 caracters.',
		'required' => 'Cal definir un rol com a mínim.',
		'values' => 'Heu de sel.leccionar el rol ADMIN o USUARI.',
	) ,
	'username' => array(
		'admin' => 'El rol de l`usuari admin no es pot modificar.',
		'alpha_numeric' => 'El nom d`usuari només pot tenir lletres i números.',
		'exists' => 'Perdoneu, aquest usuari ja està en ús.',
		'length' => 'El camp Nom d`Usuari ha de tenir entre 2 i 100 caracters.',
		'login error' => 'Si us plau, reviseu que heu posat correctament el nom d`usuari.',
		'required' => 'El camp Nom d`Usuari és obligatori.',
		'superadmin' => 'El rol de l`usuari superadministrador no es pot modificar.',
		'csrf' => 'Possible atac CSRF. Segur que volieu crear / editar un usuari?',
	) ,
);
