<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 01:17+0000
$lang = array(
	'captcha' => array(
		'default' => 'Si us plau, entreu un codi de seguretat vàlid',
		'required' => 'Si us plau, entreu el codi de seguretat',
	) ,
	'email' => array(
		'email' => 'El camp Correu Electrònic no conté una adreça vàlida',
		'length' => 'El camp Correu Electrònic ha de tenir entre 4 i 64 caracters.',
		'required' => 'Cal omplenar el camp Correu Electrònic si el checkbox està sel.leccionat.',
	) ,
	'error' => array(
		'required' => 'El camp Error és obligatori.',
	) ,
	'subject' => array(
		'length' => 'El camp Assumpte ha de ser, pel cap baix, de 3 caracters.',
		'required' => 'El camp Assumpte és obligatori.',
	) ,
	'yourname' => array(
		'length' => 'El camp Nom ha de ser, pel cap baix, de 3 caracters.',
		'required' => 'El camp Nom és obligatori.',
	) ,
);
