<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 15:54+0000
$lang = array(
	'captcha' => array(
		'default' => 'Si us plau, entreu un codi de seguretat vàlid',
		'valid' => 'Si us plau, introduïu un codi de seguretat vàlid.',
		'required' => 'Si us plau, entreu el codi de seguretat',
	) ,
	'contact_email' => array(
		'email' => 'El camp Email no sembla contenir una adreça vàlida de correu electrònic.',
		'length' => 'El camp de correu electrònic ha de tenir entre 4 i 64 caràcters.',
		'required' => 'El camp Email és obligatori si la casella està marcada.',
	) ,
	'contact_message' => array(
		'required' => 'El camp Missatge és obligatori.',
	) ,
	'contact_name' => array(
		'length' => 'El camp Nom ha de tenir, pel cap baix, 3 caracters.',
		'required' => 'El camp Nom és obligatori.',
	) ,
	'contact_subject' => array(
		'length' => 'El camp Assumpte ha de tenir, pel cap baix, 3 caracters.',
		'required' => 'El camp Assumpte és obligatori.',
	) ,
	'email_send' => array(
		'failed' => 'S\'ha produït un error en enviar el missatge.',
	) ,
);
