<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 15:51+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Div',
		'full' => 'Divendres',
	) ,
	'monday' => array(
		'abbv' => 'Dil',
		'full' => 'Dilluns',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Dis',
		'full' => 'Dissabte',
	) ,
	'sunday' => array(
		'abbv' => 'Diu',
		'full' => 'Diumenge',
	) ,
	'thursday' => array(
		'abbv' => 'Dij',
		'full' => 'Dijous',
	) ,
	'tuesday' => array(
		'abbv' => 'Dim',
		'full' => 'Dimarts',
	) ,
	'wednesday' => array(
		'abbv' => 'Dix',
		'full' => 'Dimecres',
	) ,
	'january' => array(
		'abbv' => 'Gen',
		'full' => 'Gener',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Febrer',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Març',
	) ,
	'april' => array(
		'abbv' => 'Abr',
		'full' => 'Abril',
	) ,
	'may' => array(
		'abbv' => 'Mai',
		'full' => 'Maig',
	) ,
	'june' => array(
		'abbv' => 'Jun',
		'full' => 'Juny',
	) ,
	'july' => array(
		'abbv' => 'Jul',
		'full' => 'Juliol',
	) ,
	'august' => array(
		'abbv' => 'Ago',
		'full' => 'Agost',
	) ,
	'september' => array(
		'abbv' => 'Set',
		'full' => 'Setembre',
	) ,
	'october' => array(
		'abbv' => 'Oct',
		'full' => 'Octubre',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'Novembre',
	) ,
	'december' => array(
		'abbv' => 'Des',
		'full' => 'Desembre',
	) ,
);
