<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 01:18+0000
$lang = array(
	'captcha' => array(
		'default' => 'Si us plau, entreu un codi de seguretat vàlid',
		'required' => 'Si us plau, entreu el codi de seguretat',
	) ,
	'email' => array(
		'email' => 'El camp Correu Electrònic sembla tenir una adreça invàlida',
		'length' => 'El camp Correu Electrònic ha de tenir entre 4 i 64 caracters.',
		'required' => 'El camp Correu Electrònic és obligatori si el checkbox està sel.leccionat.',
	) ,
	'message' => array(
		'required' => 'El camp Missatge és obligatori.',
	) ,
	'name' => array(
		'length' => 'El camp Nom ha de tenir, pel cap baix, 3 caracters.',
		'required' => 'El camp Nom és obligatori.',
	) ,
	'phone' => array(
		'length' => 'El camp Telèfon no és vàlid.',
	) ,
);
