<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-20 16:38+0000
$lang = array(
	'reports_view' => 'Veure Informes',
	'reports_edit' => 'Crear/Editar/Esborrar Informes',
	'reports_approve' => 'Aprovar Informes',
	'reports_verify' => 'Verificar Informes',
	'reports_comments' => 'Gestionar els comentaris dels Informes',
	'reports_download' => 'Descarregar Informes',
	'reports_upload' => 'Pujar Informes',
	'messages' => 'Gestionar Missatges',
	'messages_reporters' => 'Gestionar reporters de Missatges',
	'stats' => 'Veure Estadístiques',
	'settings' => 'Modificació de la Configuració',
	'manage' => 'Gestionar el Panell',
	'users' => 'Gestionar Usuaris',
	'manage_roles' => 'Gestionar Rols',
	'checkin' => 'Pot registrar-se',
	'checkin_admin' => 'Gestionar Registres',
	'admin_ui' => 'Accés a la interfície d\'usuari Admin.',
	'member_ui' => 'Accés a la interfície d\'usuari Membres.',
);
