<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-27 06:06+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Si us plau, comproveu que heu marcat un punt',
		'numeric' => 'Si us plau, comproveu que heu marcat un punt',
		'categories_required' => 'Els informes han de ser classificats abans que puguin ser aprovats',
	) ,
	'action' => array(
		'permission' => 'No teniu permís per realitzar aquesta acció',
	) ,
);
