<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-04-14 06:14+0000
// PO revision date:  2013-04-13 06:14+0000
$lang = array(
	'allow_comments' => array(
		'between' => 'El camp Comentaris Permessos no sembla tenir un valor vàlid',
		'required' => 'El camp Comentaris Permesos és obligatori.',
	) ,
	'allow_feed' => array(
		'between' => 'El camp Incloure Feed no sembla tenir un valor vàlid',
		'required' => 'El camp Incloure Feed és obligatori.',
	) ,
	'allow_alerts' => array(
		'between' => 'El camp Alertes Permesses no sembla tenir un valor vàlid',
		'required' => 'El camp Alertes Permesses és obligatori.',
	) ,
	'allow_reports' => array(
		'between' => 'El camp Informes Permessos no sembla tenir un valor vàlid',
		'required' => 'El camp Informes Permessos és obligatori.',
	) ,
	'allow_stat_sharing' => array(
		'between' => 'El camp Estadístiques Compartides no sembla tenir un valor vàlid',
		'required' => 'El camp Estadístiques Compartides és obligatori.',
	) ,
	'api' => array(
		'default_record_limit' => 'Núm. de registres per defecte a retornar per petició a l`API',
		'maximum_record_limit' => 'Núm. de registres màxim a retornars per petició a l`API',
		'maximum_requests_per_ip_address' => 'Núm. màxim de peticions d`API per adreça IP',
	) ,
	'api_akismet' => array(
		'alpha_numeric' => 'El camp Akismet no sembla tenir un valor vàlid',
		'length' => 'El camp Akismet no sembla tenir una llargada vàlida',
	) ,
	'cache_pages' => array(
		'between' => 'El camp Pàgines Catxé no sembla tenir un valor vàlid',
		'required' => 'El camp Pàgines Catxé és obligatori.',
	) ,
	'cache_pages_lifetime' => array(
		'in_array' => 'El camp Temps de Vida de les Pàgines Catxé no sembla tenir un valor vàlid',
		'required' => 'El camp Temps de Vida de les Pàgines Catxé és obligatori.',
	) ,
	'cleanurl' => array(
		'clean_url_disabled' => 'Sembla que el seu servidor no està configurat per a suportar URLs netes. Cal que canvieu la configuració del servidor com a pas previ a acceptar URLs netes. Si voleu més informació sobre com habilitar URLs netes, consulteu aquest <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">missatge al fòrum</a> (en anglès)',
		'clean_url_enabled' => 'Aquesta opció fa que l`Ushahidi sigui accessible via URLs "netes", és a dir, sense "index.php" a l`URL.',
		'enable_clean_url' => 'Habilitar URLs netes',
		'title' => 'URLs Netes',
	) ,
	'clickatell_api' => array(
		'length' => 'El camp Número de l`API Clickatell no pot ser de més de 20 caracters.',
		'required' => 'El camp número de l`API Clickatell és obligatori.',
	) ,
	'clickatell_password' => array(
		'length' => 'El camp Password de l`API Clickatell ha de tenir entre 5 i 50 caracters.',
		'required' => 'El camp password de l`API Clickatell és obligatori.',
	) ,
	'clickatell_username' => array(
		'length' => 'El camp Nom d`Usuari de l`API Clickatell no pot ser de més de 50 caracters.',
		'required' => 'El camp nom d`usuari de l`API Clickatell és obligatori.',
	) ,
	'configure_map' => 'Configureu Mapa',
	'default_location' => 'Ubicació Predeterminada',
	'default_map_all' => array(
		'alpha_numeric' => 'El camp Color del Feed no sembla tenir un valor vàlid',
		'length' => 'El camp color del feed no pot tenir més de 6 caracters.',
		'required' => 'El camp color del feed és obligatori.',
	) ,
	'default_map_view' => 'Vista de Mapa Predeterminada',
	'default_zoom_level' => 'Nivell de Zoom Predeterminat',
	'download_city_list' => 'Descarregar Llista de Ciutats des de Geonames',
	'email_host' => array(
		'length' => 'El camp Servidor de Correu és massa llarg',
		'numeric' => 'El camp Servidor de Correu només pot contenir números.',
	) ,
	'email_password' => array(
		'length' => 'El camp Password del Servidor de Corrreu ha de tenir entre 5 i 50 caracters.',
		'required' => 'El camp Password del Servidor de Corrreu és obligatori.',
	) ,
	'email_port' => array(
		'length' => 'El camp Port del Servidor de Correu és massa llarg',
		'numeric' => 'El camp Port del Servidor de Correu només pot contenir números.',
	) ,
	'email_servertype' => array(
		'length' => 'El camp Tipus de Servidor de Correu és massa llarg',
		'required' => 'El camp Tipus de Servidor de Correu és obligatori.',
	) ,
	'email_username' => array(
		'length' => 'El camp Nom d`Usuari del Servidor de Correu no pot tenir més de 50 caracters.',
		'required' => 'El camp Nom d`Usuari del Servidor de Correu és obligatori.',
	) ,
	'facebook' => array(
		'title' => 'Configuració d`opcions de Facebook',
		'description' => 'Per agafar la informació següent, necessiteu fer una nova sol.licitud de Facebook a',
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret',
	) ,
	'google_analytics' => array(
		'length' => 'El camp Google Analytics ha de contenir un Web Property ID vàlid amb el format UA-XXXXX-XX.',
	) ,
	'https' => array(
		'enable_https' => 'Habilitar HTTPS',
		'https_disabled' => 'Aquesta opció fa l`Ushahidi accessible en mode no-segur; <strong>sense https</strong>"://" al prefix de l`URL',
		'https_enabled' => 'Aquesta opció fa l`Ushahidi accessible en mode segur; <strong>amb https</strong>"://" al prefix de l`URL',
		'title' => 'HTTPS',
	) ,
	'items_per_page' => array(
		'between' => 'El camp Items per Pàgina (Frontend) sembla no contenir un valor vàlid',
		'required' => 'El camp Items per Pàgina (Frontend) és obligatori.',
	) ,
	'items_per_page_admin' => array(
		'between' => 'El camp Items per Pàgina (Admin) sembla no contenir un valor vàlid',
		'required' => 'El camp Items per Pàgina (Admin) és obligatori.',
	) ,
	'map' => array(
		'default_location' => 'Configurar el proveïdor de cartografia és un procés senzill. Seleccioneu un proveïdor, obteniu una clau API del site del proveïdor i entreu la clau de l`API',
		'zoom' => 'Nivell de Zoom',
	) ,
	'map_provider' => array(
		'choose' => 'SEscolliu un Proveïdor de Cartografia',
		'enter_api' => 'Entreu la nova Clau de l`API',
		'get_api' => 'Aconseguiu una Clau d`API',
		'info' => 'Configurar el proveïdor de cartografia és un procés senzill. Seleccioneu un proveïdor, obteniu una clau API del site del proveïdor i entreu la clau de l`API',
		'name' => 'Proveïdor de Cartografia',
	) ,
	'map_timeline' => 'Mapa Cronològic',
	'map_settings' => 'Configuració del Mapa',
	'multiple_countries' => 'Aquesta instal.lació de l`Ushahidi, ¿abasta varis països?',
	'select_default_location' => 'Si us plau, predetermineu un país',
	'set_location' => 'Cliqueu i arrossegueu el mapa per indicar la vostra localització exacta',
	'site' => array(
		'allow_clustering' => 'Permetre Agrupar Informes Reportats al Mapa',
		'allow_comments' => 'Permetre als Usuaris Enviar Comentaris als Informes Reportats',
		'allow_feed' => 'Incloure Feed RSS de Notícies al Website',
		'allow_alerts' => 'Permetre Subscripcions dels Usuaris per Alertes',
		'allow_reports' => 'Permetre als Usuaris Enviar Informes Reportats',
		'api_akismet' => 'Clau Akismet',
		'banner' => 'Banner del Site',
		'blocks_per_row' => 'Blocs Per Filera',
		'cache_pages' => 'Cache de Pàgines',
		'cache_pages_lifetime' => 'Temsp de Vida de la Catxé de Pàgines',
		'checkins' => 'Habilitar Registres',
		'copyright_statement' => 'Declaració de Copyright del Site',
		'default_category_colors' => 'Color Predeterminat Per Totes Les Categories',
		'default_category_icons' => 'Icona predeterminada per a totes les Categories',
		'delete_banner_image' => 'Esborrar Imatge del Banner',
		'delete_default_map_all_icon' => 'Esborrar Icona Predeterminada',
		'display_contact_page' => 'Mostrar Pàgina de Contacte',
		'display_howtohelp_page' => 'Mostrar Pàgina de "Com Ajudar"',
		'email_alerts' => 'Adreça de Correu Electrònic per a les Alertes',
		'email_notice' => '<span>Per tal de poder rebre informes reportats per correu electrònic, si us plkau, configureu el vostre compte de correu electrònic.</span>',
		'email_site' => 'Adreça de Correu Electrònic del Site',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'ID de Propietat Web - Format: UA-XXXXX-XX',
		'items_per_page' => 'Items Per Pàgina - Front End',
		'items_per_page_admin' => 'Items Per Pàgina - Admin',
		'kismet_notice' => 'Eviteu rebre correu brossa fent servir <a href="http://akismet.com/" target="_blank">Akismet</a> d`Automattic. <BR />Podeu obtenir una clau d`API gratuïta registrant un <a href="http://en.wordpress.com/api-keys/" target="_blank">compte d`usuari de WordPress.com</a>',
		'laconica_configuration' => 'Credencials de Laconica',
		'laconica_site' => 'Site de Laconica ',
		'language' => 'Idioma del Site',
		'manually_approve_users' => 'Aprovació Manual d`Usuaris',
		'message' => 'Missatge del Site',
		'name' => 'Nom del Site',
		'private_deployment' => 'Instal.lació Privada',
		'require_email_confirmation' => 'Requereix Confirmació del Correu Electrònic de l`Usuari',
		'submit_report_message' => 'Enviar Missatge d`Informe Reportat',
		'share_site_stats' => 'Habilitar Estadístiques (Enmagatzemades al servidor de l`Ushahidi)',
		'tagline' => 'Subtítol del Site',
		'timezone' => 'Zona Horària',
		'title' => 'Configuració del Site',
		'twitter_configuration' => 'Termes de Recerca a Twitter',
		'twitter_hashtags' => 'Hashtags - Separats amb comes ',
	) ,
	'site_email' => array(
		'email' => 'El camp Correu Electrònic del Site no sembla tenir un valor vàlid',
		'length' => 'El camp Correu Electrònic del Site ha de tenir entre 4 i 100 caracters.',
	) ,
	'site_name' => array(
		'length' => 'El camp Nom del Site ha de tenir entre 3 i 50 caracters.',
		'required' => 'El camp Nom del Site és obligatori.',
	) ,
	'site_tagline' => array(
		'length' => 'El camp Tagline ha de tenir entre 3 i 100 caracters.',
		'required' => 'El camp Tagline és obligatori.',
	) ,
	'sms' => array(
		'clickatell_api' => 'Clau de l`API de Clickatell',
		'clickatell_check_balance' => 'Reviseu el Saldo del Clickatell',
		'clickatell_load_balance' => 'Carregueu Saldo',
		'clickatell_password' => 'Password del Clickatell',
		'clickatell_text_1' => 'Registreu-vos al servei Clickatells <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">clicant aquí</a>',
		'clickatell_text_2' => 'Entreu les vostres dades d`accés a Clickatell a sota',
		'clickatell_username' => 'El vostre Nom d`Usuari Clickatell',
		'flsms_text_1' => 'Entreu el(s) número(s) de telèfon connectats al Frontline SMS al(s) camp(s) següent(s)',
		'flsms_text_2' => 'Entreu el número sense cap + ni guions',
		'option_1' => 'Opció 1: Fer servir el Frontline SMS',
		'option_2' => 'Opció 2: Fer servir un sistema SMS extern',
		'title' => 'Opcions de Configuració SMS',
	) ,
	'sms_no1' => array(
		'length' => 'El camp Telèfon 1 sembla no tenir un valor vàlid',
		'numeric' => 'El camp Telèfon 1 només hauria de tenir números.',
	) ,
	'sms_no2' => array(
		'length' => 'El camp Telèfon 2 és massa llarg',
		'numeric' => 'El camp Telèfon 2 només hauria de tenir números.',
	) ,
	'sms_no3' => array(
		'length' => 'El camp Telèfon 3 és massa llarg',
		'numeric' => 'El camp Telèfon 3 només hauria de tenir números.',
	) ,
);
