<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:27+0000
$lang = array(
	'category_color' => array(
		'length' => 'ფერის ველი უნდა შედგებოდეს 6 სიმბოლოსგან.',
		'required' => 'ფერის ველი სავალდებულოა.',
	) ,
	'category_description' => array(
		'required' => 'აღწერის ველი სავალდებულოა.',
	) ,
	'category_image' => array(
		'size' => 'გთხოვთ დარწმუნდეთ, რომ გამოსახულების ატვირთვის ზომები შეზღუდულია 50 კილო ბაიტამდე.',
		'type' => 'გამოსახულების ველი როგორც ჩანს არ შეიცავს დასაშვებ გამოსახულებას. დასაშვები ფორმატები არის მხოლოდ და მხოლოდ .JPG, .PNG and .GIF.',
		'valid' => 'ამოსახულების ველი როგორც ჩანს არ შეიცავს სწორ ფაილს',
	) ,
	'category_title' => array(
		'length' => 'სათაურის ველი უნდა შედგებოდეს არანაკლებ 3 და არაუმეტეს  80 სიმბოლოსგან.',
		'required' => 'სათაურის ველი სავალდებულოა.',
	) ,
	'parent_id' => array(
		'exists' => 'მწარმოებლის კატეგორია არ არსებობს.',
		'numeric' => 'მწარმოებლის კატეგორიის ველი უნდა იყოს რიცხვითი.',
		'required' => 'მწარმოებლის კატეგორიის ველი სავალდებულოა.',
		'same' => 'კატეგორია და მწარმოებლის კატეგორია შეუძლებელია იყოს ერთიდაიგივე.',
	) ,
);
