<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-05 12:07+0000
$lang = array(
	'field_default' => array(
		'length' => 'ველის სახელი უნდა შედგებოდეს არანაკლებ 3 და არაუმეტეს 200 სიმბოლოსგან.',
	) ,
	'field_height' => array(
		'between' => 'გთხოვთ შეიყვანოთ სიდიდე 0–დან 50–მდე ველის სიმაღლისთვის',
	) ,
	'field_isdate' => array(
		'between' => 'ტვენ შეიყვანეთ არასწორი სიდიდე თარიღის ველისთვის',
		'required' => 'გთხოვთ, აირჩიოთ დიახ ან არა თარიღის ველისთვის',
	) ,
	'field_name' => array(
		'length' => 'ველის სახელი უნდა შედგებოდეს არანაკლებ 3 და არაუმეტეს 100 სიმბოლოსგან.',
		'required' => 'გთხოვთ შეიყვანოთ ველის სახელი.',
	) ,
	'field_required' => array(
		'between' => 'თქვენ შეიყვანეთ არასწორი სიდიდე სავალდებულო ველისთვის',
		'required' => 'თხოვთ, აირჩიოთ დიახ ან არა სავალდებულო ველისთვის',
	) ,
	'field_type' => array(
		'numeric' => 'გთხოვთ აირჩიოთ ველის სწორი ტიპი.',
		'required' => 'გთხოვთ აირჩიოთ ველის ტიპი.',
	) ,
	'field_width' => array(
		'between' => 'გთხოვთ შეიყვანოთ სიდიდე 0–დან 300–მდე ველის სიგანისთვის',
	) ,
	'form_description' => array(
		'required' => 'გთხოვთ შეიყვანოთ ფორმაფორმის აღწერა.',
	) ,
	'form_id' => array(
		'default' => 'სტანდარტული ფორმის წასშლა სეუძლებელია.',
		'numeric' => 'გთხოვთ, მონიშნოთ რომელ ფორმას დავუმატოთ ეს ველი.',
		'required' => 'გთხოვთ, მონიშნოთ რომელ ფორმას დავუმატოთ ეს ველი.',
	) ,
	'form_title' => array(
		'length' => 'ფორმის ველის სახელი უნდა შედგებოდეს არანაკლებ 3 და არაუმეტეს 100 სიმბოლოსგან.',
		'required' => 'გთხოვთ, შეიყვანოთ ფორმის სახელი.',
	) ,
);
