<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-19 22:55+0000
$lang = array(
	'database_host_description' => 'თუ Ushahidi გაშვებული გაქვთ საკუთარ კომპიუტერზე, ეს სავარაუდოდ იქნება "localhost"–ი. თუ Ushahidi გაშვებული გაქვთ ვებ–სერვერიდან, თქვენ host ინფორმაციას მიიღებთ ვებ–ჰოსტინგ პროვაიდერისგან',
	'database_name_description' => 'მონაცემთა ბაზის სახელი, რომელშიც გსურთ  Ushahidi–ს გაშვება',
	'db_information_link' => 'უფრო მეტი ინფორმაციის მისაღებად მოინახულეთ <a href="http://wiki.ushahidi.com/doku.php?id=a_brief_word_on_databases" target="_blank">this article</a> wiki, რომელიც საუბრობს მონაცემთა ბაზების შესახებ დეტალებში',
	'default_language_description' => ' Ushahidi–სთითოეული გამოყენება მოიცავს ჩაშენებული ენის თარგმანის კომპლექტს. თქვენ ასევე შეგიძლიათ <a href="http://wiki.ushahidi.com/doku.php?id=localisation_l10n_internationlisation_i18n&s[]=language#enabling_new_languages" target="_blank">add your own</a>',
	'error_summary' => 'ქვევით არის ჩამოთვლილი შეცდომები, რომელსაც ჩვენ შევხვდით',
	'files_location_text' => 'ადგილმდებარეობა  თქვენს სერვერზე, სადაც განათავსეთ თქვენი Ushahidi ფაილები. <strong>ჩვენ ავტომატურად აღმოვაჩინეთ ეს მნიშვნელობა,გთხოვთ,დარწმუნდით, რომ ის არის სწორი.</strong> არ შეწუხდეთ თუ ველი ცარიელია, ეს ნიშნავს, რომ ushahidi დაინსტალირდა ზედა დონის დირექტორიაში',
	'google_key_description' => 'ნებისნიერს შეუძლია მიიღოს api გასაღები. <a id="api-link" href="http://code.google.com/apis/maps/signup.html" target="_blank">Get yours now</a>',
	'index' => array(
		'advanced_installation_description' => 'მიიღეთ ყველა ძირითადი მოწყობილობა დასრულებული სახით, ამ ხუთი საფეხურის მეშვეობით.  ეს მოიცავს სერვერს, რუკას, საიტის სახელსა და საკონტაქტო დეტალებს',
		'basic_installation_description' => 'მარტივი და სწრაფი. რაც გჭირდებათ ეს არის თქვენი ვებ–გვერდის საფუძველების ცნობარი და თქვენი მონაცემთა ბაზის ინფორმაცია. აირჩიე ეს უნქცია, თუ გინდა რომ მორჩე უცებ და შენშეგეძლება ყოველთვის შეცვალო ყველაფერი მოგვიანებით',
		'welcome' => 'კეთილი იყოს თქვენი მობრძანება Ushahidi–ის სერვერის ინსტალაციის პროცესში.  აირჩიეთ რომელი ტიპის ინსტალაცია გსურთ რომ გამოიყენოთ',
	) ,
	'installation_successful' => 'წარმატებით ინსტალაცია',
	'mail_server_host_description' => 'მაგალითები: mail.yourwebsite.com, imap.gmail.com, pop.gmail.com',
	'mail_server_password' => 'საფოსტო სერვერის პაროლი',
	'mail_server_password_description' => 'პაროლი, რომელსაც ჩვეულებრივ გამოიყენებთ თქვენს ელექტრონულ ფოსტაში შესაღწევად',
	'mail_server_port' => 'საფოსტო სერვერის პორტი',
	'mail_server_port_description' => 'საერთო პორტები: 25, 110, 995 (Gmail POP3 SSL), 993 (Gmail IMAP SSL)',
	'mail_server_type' => 'საფოსტო სერვერის ტიპი',
	'mail_server_type_description' => 'შეტყობინების მისვლის ინტერნეტ პროტოკოლი (IMAP) ან ფოსტის პროტოკოლი (POP). <a href="http://saturn.med.nyu.edu/it/help/email/imap/index.html" target="_blank">რა არის სხვაობა?</a>',
	'mail_server_username' => 'საფოსტო სერვერის მომხმარებლის სახელი',
	'mail_server_username_description' => 'თუ თქვენ იყენებთ Gmail–ს, Hotmail–ს, ან Yahoo Mail–ს, შეიყვანეთ ელექტრონული ფოსტის სრული მისამართი როგორც მომხმარებლის სახელი',
	'map_provider_description' => 'Ushahidi მუშაობს ისევე კარგად, როგორც ეს ოთხი პროვაიდერი: Google–ი, Bing–ი, Yahoo და OpenStreetMap–ი.  აირჩიეთ ის, რომელსაც აქვს დეტალების უმეტესობა თქვენს დარგში',
	'other_steps' => 'სხვა საფეხურები...',
	'password' => 'პაროლი',
	'password_description' => 'თქვენი მონაცემთა ბაზის პაროლი',
	'previous' => 'წინა',
	'restart_apache' => 'გთხოვთ, გადატვირთოთ თქვენი Apache სერვერი',
	'select_mail_server_ssl' => 'ჩავრთათ, თუ გამოვრთოთ SSL–ის',
	'select_mail_server_ssl_description' => 'ზოგიერთი საფოსტო სერვერი <abbr title="Secure Sockets Layer">SSL</abbr> გამოყენების ოფციას გაძლევთ კავშირის დამყარებისას.  SSL–ის გამოყენება რეკომენდირებულია, რამდენადაც ის გაძლევთ უსაფრთხოების დამატებით საფეხურს',
	'setup_sms' => 'დააყენეთ თქვენი SMS სერვერი',
	'site_email' => 'საიტის ელექტრონული ფოსტის მისამართი',
	'site_email_alerts' => 'საიტის გამაფრთხილებელი ელექტრონული ფოსტის მისამართი',
	'site_email_alerts_description' => 'როდესაც თქვენი საიტის მნახველები რეგისტრირდებიან სისტემაში ელექტრონული ფოსტით გაფრთხილების მირებისათვის, ისისნი მიიღებენ ელექტრონულ ფოსტას ამ მისამართიდან. ელექტრონული ფოსტის მისამართი არ უნდა იყოს იგივე რაც საიტის ელექტრონული მისამართი',
	'site_email_description' => 'საიტის შიგნით ელექტრონული ფოსტით განხორციელებული კომუნიკაცია ამ მისამართის მეშვეობითგ გადაიგზავნება. ',
	'site_name' => 'საიტის სახელი',
	'site_name_description' => 'თქვენი საიტის სახელი',
	'site_tagline' => 'საიტის ქვესათაური',
	'site_tagline_description' => 'თქვენი ქვესათაური',
	'summary' => array(
		'text_1' => 'Tქვემოთ მოცემული ფაილები და ფოლდერები უნდა იყოს გადაწერადი  თქვენი ვებ–სერვერის მიერ',
		'text_2' => '<p>აქ მოცემულია ინსტრუქციები ფაილის შეცვლის ნებართვისათვის:</p>
        <ul>
            <li><a href="http://www.washington.edu/computing/unix/permissions.html" target="_blank">Unix/Linux</a></li>
            <li><a href="http://support.microsoft.com/kb/308419" target="_blank">Windows</a></li>
        </ul>',
		'text_3' => 'სანამ დაიწყებთ, უნდა დარწმუნდეთ, რომ შემდეგი ფაილები და ფოლდერები არის გადაწერადითქვენი ვებ–სერვერის მიერ. ეს მოიცავს ფაილის შეცვლის ნებართვას',
		'text_4' => 'ინსტალაციის პროცესისთვის, გთხოვთ, შემდეგი მცირედი ინფორმაცია იყოს ხელმისაწვდომი',
	) ,
	'table_prefix_description' => 'როგორც წესი თქვენ არშეცვლიდით ცხრილის პრეფიქსს.თუმცა, თუ თქვენ გსურთ შეასრულოთ Ushahidi–ის მრავალჯერადი ინსტალაცია ერთი მონაცემთა ბაზიდან, ეს შეგიძლიათ გააკეთოთპრეფიქსის აქ შეცვლით',
	'title' => 'სათაური',
	'to_login' => 'სისტემაში შესასვლელად მიდით',
	'upload_data' => 'ატვირთეთ ბაზის აღწერა',
	'username' => 'მომხმარებლის სახელი',
	'username_description' => 'თქვენი მონაცემთა ბაზის მომხმარებლის სახელი',
	'use_credentials' => 'და გამოიყენეთ შემდეგი მანდატი',
	'view_site' => 'მოინახულეთ თქვენი ვებ–გვერდი',
);
