<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:42+0000
$lang = array(
	'akismet_cannot_connect' => 'შეუძლებელია akismet სერვერთან დაკავშირება',
	'akismet_cannot_retrieve' => 'Akismet–დან პასუხი ვერ იქნა მიღებული',
	'api_library_not_found' => 'The API library: <strong>%s</strong>, for the <strong>%s</strong> კლასი ვერ იქნა აღმოჩენილი. შეამოწმეთ თქვენი API დავალებების განმსაზღვრელი ცხრილი.',
	'askimet_invalid_apikey' => 'თქვენი Akismet API გასაღებიი არ არის სწორი',
	'clickatell_fopen_error' => 'შეცდომა გაგზავნის მეთოდის შესრულებაში!<br>გთხოვთ, შემოწმოთ PHP–მ თუ გახსნა SSL დახმარებადა შეამოწმეთ  PHP ვერსია თუ არის 5.2–ზე დიდი',
	'clickatell_message_too_long' => 'თქვენი unicode შეტყობინება ძალზე გრძელია! (Current lenght=',
	'clickatell_no_destination_address' => 'გთხოვთ, მიუთითეთ მიმღების მისამართი (TO)!',
	'clickatell_no_sender_address' => 'გთხოვთ, მიუთითეთ გამომავალი მისამართი (FROM)!',
	'clickatell_unicode_message_too_long' => 'თქვენი unicode შეტყობინება ძალზე გრძელია! (მიმდინარე სიგრძე=',
	'clickatell_unsupported_method' => 'მხარდაუჭერელი გაგზავნის მეთოდი!',
	'invalid_api_library' => 'API ბიბლიოთეკა %s არასწორია. All API ბიბლიოთეკები უნდა იყვნენ %s–ის ქვეკლასები',
	'upgrade_directory_not_deleted' => 'Directory <code>%s</coded> შეუძლებელია წაშლა',
	'upgrade_extracting_error' => 'შეცდომა გამოყოფისას: <code>%s</code>',
	'upgrade_failed' => 'ushabadi-s საბოლოო ვერსიის გადმოწერა ვერ მოხერხდა. HTTP სტატუს კოდი',
	'upgrade_file_not_copied' => 'File <code>%s</coded> კოპირება შეუძლებელია',
	'upgrade_file_not_deleted' => 'File <code>%s</coded> წაშლა შეუძლებელია',
	'upgrade_title' => 'Ushahidi სკრიპტის განახლება',
	'upgrade_zip_error' => 'გადმოწერილი ushahidi zip ფაილი <code>%s</code>, ჩაწერა შეუძლებელია',
);
