<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-17 07:01+0000
$lang = array(
	'date' => 'თარიღში შესვლა',
	'date_added' => 'თარიღის დამატება',
	'last_access' => 'ბოლო შესვლა',
	'sharing_color' => array(
		'length' => 'ფერის ველი უნდა შეიცავდეს მინიმუმ 6 სიმბოლოს.',
		'required' => 'ფერის ველი სავალდებულოა.',
	) ,
	'sharing_name' => array(
		'length' => 'სახელის გაზიარება მოქმედია?',
		'required' => 'სახელის გაზიარება სავალდებულოა.',
	) ,
	'sharing_url' => array(
		'exists' => 'ეს საიტი მისამართი (url) უკვე არსებობს',
		'length' => 'ეს საიტი მისამართი (url) მოქმედია?',
		'required' => 'საიტი მისამართი (url) სავალდებულოა.',
		'url' => 'ამ საიტის მისამართი (url) სწორია?',
	) ,
);
