<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-26 06:20+0000
// PO revision date:  2013-06-25 21:40+0000
$lang = array(
	'description' => array(
		'length' => 'विवरण क्षेत्र कम से कम 3 और अधिकतम 100 अक्षर का होना चाहिए ',
		'required' => 'विवरण क्षेत्र की आवश्यकता है',
	) ,
	'name' => array(
		'alpha_numeric' => 'नाम क्षेत्र में केवल अंक या अक्षर हो सकते हैं ',
		'length' => 'नाम क्षेत्र कम से कम 2 और अधिकतम 30 अक्षर का होना चाहिए ',
		'nomodify' => 'SuperAdmin भूमिका नहीं बदली जा सकती ',
		'required' => 'नाम क्षेत्र की आवश्यकता है',
	) ,
	'access_level' => array(
		'numeric' => 'Access Level क्षेत्र 0-100 के बीच का अंक  होना चाहिए ',
		'required' => 'Access Level क्षेत्र 0-100 के बीच का अंक  होना चाहिए ',
	) ,
	'permissions' => array(
		'numeric' => 'Permission Level क्षेत्र 0-100 के बीच का अंक  होना चाहिए ',
	) ,
);
