<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-30 06:22+0000
// PO revision date:  2013-06-29 11:21+0000
$lang = array(
	'config' => 'файл конфигураци',
	'controller' => 'контроллер',
	'driver' => 'драйвер',
	'driver_implements' => 'The %s driver for the %s library must implement the %s interface',
	'driver_not_found' => 'The %s driver for the %s library could not be found',
	'errors_disabled' => 'Вы можете перейти <a href="%s">на домашнюю страницу</a> или <a href="%s">пробовать снова</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Невозможно выполнить запрос',
	'helper' => 'помощник',
	'invalid_filetype' => 'The requested filetype, .%s, is not allowed in your view configuration file',
	'invalid_method' => 'Недопустимый метод %s вызова %s',
	'invalid_property' => 'Свойство %s не существует в классе %s.',
	'library' => 'библиотека',
	'log_dir_unwritable' => 'Каталог журнала не доступен для записи: %s',
	'model' => 'модель',
	'no_controller' => 'Ushahidi не смог определить контроллер для обработки этого запроса: %s',
	'no_default_route' => 'Задайте маршрут по умолчанию в config/routes.php',
	'page_not_found' => 'Запрашиваемая станица %s, не может быть найдена.',
	'report_bug' => '<a href="%s" id="show_bugs">Сообщить об этой проблеме</a>',
	'resource_not_found' => 'The requested %s, %s, could not be found',
	'stack_trace' => 'Трассировка стека',
	'stats_footer' => 'Загружено за {execution_time} секунд, используя {memory_usage} памяти. Создано Ushahidi v%s.',
	'text_direction' => 'ltr',
	'there_can_be_only_one' => 'There can be only one deployment of Ushahidi per page request',
	'uncaught_exception' => 'Неперехваченные % s: %s в файле %s на линии %s',
	'view' => 'вид',
	'view_set_filename' => 'You must set the the view filename before calling render',
);
