<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-30 06:22+0000
// PO revision date:  2013-06-29 08:36+0000
$lang = array(
	'field_default' => array(
		'default' => 'Заданное вами значение по умолчанию для поля недопустимо.',
		'length' => 'Имя поля должно быть не менее 3 и не более 200 символов.',
	) ,
	'field_height' => array(
		'between' => 'Введите значение поля от 0 до 50',
	) ,
	'field_isdate' => array(
		'between' => 'Вы выбрали неправильное значение поля "Дата"',
		'required' => 'Выберите Да или Нет',
	) ,
	'field_name' => array(
		'length' => 'Имя поля должно быть не менее 3 и не более 100 символов.',
		'required' => 'Введите имя поля.',
		'duplicate' => 'Имя поля, которое вы ввели, уже существует в этой форме. Введите другое.',
	) ,
	'field_required' => array(
		'between' => 'Вы ввели неправильное значения для обязательного поля',
		'required' => 'Выберите "Да" или "Нет" для обязательного поля',
	) ,
	'field_type' => array(
		'numeric' => 'Выберите правильный тип поля.',
		'required' => 'Выберите тип поля.',
	) ,
	'field_width' => array(
		'between' => 'Введите значение от 0 до 300 для ширины поля',
	) ,
	'form_description' => array(
		'required' => 'Введите описание формы.',
	) ,
	'form_id' => array(
		'default' => 'Форма по-умолчанию не может быть удалена.',
		'numeric' => 'Выберите, в какую форму нужно добавить данное поле.',
		'required' => 'Выберите, в какую форму нужно добавить данное поле.',
	) ,
	'form_title' => array(
		'length' => 'Длина имени формы не может быть менее 3х и более 100 символов.',
		'required' => 'Введите имя формы.',
		'exists' => 'Форма с этим именем уже существует. Выберите другое имя.',
	) ,
);
