<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-15 06:12+0000
// PO revision date:  2013-03-14 08:02+0000
$lang = array(
	'page_title' => array(
		'required' => 'Пожалуйста введите название страницы.',
		'length' => 'Заголовок страницы должен быть длиной как минимум  3 символа, но не длиннее 150.',
	) ,
	'page_tab' => array(
		'required' => 'Пожалуйста введите название закладки страницы. ',
	) ,
	'page_description' => array(
		'required' => 'Пожалуйста введите описание страницы.',
	) ,
);
