<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-30 06:22+0000
// PO revision date:  2013-06-29 12:31+0000
$lang = array(
	'latitude' => array(
		'between' => 'Введите верное значение широты',
		'required' => 'Введите широту или выберите место на карте.',
	) ,
	'level_id' => array(
		'numeric' => 'Кажется, поле Уровень Репортера содержит не правильный Уровень?',
		'required' => 'Кажется, поле Уровень Репортера содержит не правильный Уровень?',
	) ,
	'location_name' => array(
		'length' => 'Имя локации должно быть от 3 до 200 символов.',
		'required' => 'Заполните имя локации',
	) ,
	'longitude' => array(
		'between' => 'Введите верное значение долготы',
		'required' => 'Введите долготу или выберите место на карте.',
	) ,
	'reporter_id' => array(
		'numeric' => 'Неверный Репортер',
		'required' => 'Неверный Репортер',
	) ,
);
