<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-15 06:12+0000
// PO revision date:  2013-03-14 08:06+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Пожалуйста убедитесь, что вы выбрали значение. ',
		'numeric' => 'Пожалуйста убедитесь, что вы выбрали значение. ',
		'categories_required' => 'Сообщения должны быть отнесены к какой-то категории, прежде чем их можно будет подтвердить.',
	) ,
	'action' => array(
		'permission' => 'У вас нет прав доступа для указанного действия.',
	) ,
	'uploadfile' => array(
		'required' => 'Вы должны выбрать файл для загрузки',
		'type' => 'Загружаемый файл должен быть в формате .csv или .xml',
		'valid' => 'Поле для загрузки файла не содержит правильного файла',
	) ,
);
