<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-19 23:09+0000
$lang = array(
	'config' => 'konfigürasyon dosyası',
	'controller' => 'yönetici',
	'driver' => 'sürücü',
	'driver_implements' => '%s kütüphanesi (library) için olan %s sürücüsü (driver) %s arayüzünü (interface) oluşturmalıdır.',
	'driver_not_found' => '%s kütüphanesi (library) için %s sürücüsü (driver) bulunamadı.',
	'errors_disabled' => '<a href="%s">Anasayfa</a>\'ya gidebilir ya da <a href="%s">yeniden deneyebilirsiniz</a>.',
	'generic_error' => 'İstek Tamamlanamadı.',
	'helper' => 'yardımcı',
	'invalid_filetype' => 'İstenen dosya türünün (%s) konfigürasyon dosyasının içerisinde görüntülenmesine izin verilmiyor.',
	'invalid_method' => 'Geçerli olmayan yöntem %s, %s diye bilinir.',
	'invalid_property' => '%s sınıfında (class) %s özelliği (property) bulunmuyor.',
	'library' => 'kütüphane',
	'log_dir_unwritable' => 'Günlük dosyası yazılamıyor: %s',
	'no_controller' => 'Ushahidi kontrol eden dosyayı belirleyemiyor: %s ',
	'no_default_route' => 'Lütfen varsayılan dosya yolunu "config/routes.php" olarak ayarlayın. ',
	'page_not_found' => 'İstenen sayfa (%s) bulunamadı.',
	'report_bug' => '<a href="%s" id="show_bugs">Bu Sorunu Ushahidiye Bildirin</a>',
	'resource_not_found' => 'İstenen (%s) bulunamadı',
	'stack_trace' => 'Yığın Takibi',
	'stats_footer' => '{execution_time} saniyede, {memory_usage} hafıza kullanarak yüklendi. Ushahidi Tarafından Oluşturuldu v%s.',
	'there_can_be_only_one' => 'Her sayfa isteğinde, Ushahidi size sadece bir örnek gösterebilir',
	'uncaught_exception' => 'Yakalanamayan %s: %s adlı dosya içerisinde %s. satırda %s',
	'view' => 'görüntüle',
	'view_set_filename' => 'Sunum yapmadan önce dosya ismi görüntüleme kısmını ayarlamak zorundasınız',
);
