<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-23 12:15+0000
$lang = array(
	'error' => 'Veritabanı hatası: %s',
	'table_not_found' => '"%s" tablosu veritabanı içerisinde bulunamadı. Lütfen Ushahidinin şu anki versiyonu için en güncel veritabanı sürümünü kullandığınıza emin olun.',
);
