<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-23 12:06+0000
$lang = array(
	'layer_color' => array(
		'length' => 'Renk alanı en az 6 karakterden oluşmalıdır.',
		'required' => 'Renk alanı boş bırakılamaz.',
	) ,
	'layer_file' => array(
		'type' => 'Dosya uzantısı geçersiz. .KMZ, .KML uzantılı dosyalar kabul edilmektedir.',
		'valid' => 'Dosya geçersiz görünüyor.',
	) ,
	'layer_name' => array(
		'length' => 'İsim alanı en az 3, en fazla 80 karakterden oluşmalıdır.',
		'required' => 'İsim alanı boş bırakılamaz.',
	) ,
	'layer_url' => array(
		'atleast' => 'Bir KML URL\'si ya da Dosyası gereklidir',
		'both' => 'Aynı anda hem bir KML dosyasına ve bir KML URL\'sine sahip olamazsınız',
		'url' => 'Lütfen geçerli bir adres giriniz. Örn. http://www.ushahidi.com/layerl.kml',
	) ,
);
