<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => 'Lütfen geçerli bir güvenlik kodu girin',
		'required' => 'Lütfen güvenlik kodunu girin',
	) ,
	'email' => array(
		'email' => 'E-posta adresi geçersiz.',
		'length' => 'E-posta kısmı en az 4, en fazla 64 karakter uzunluğunda olmalı.',
		'required' => 'Kullanım koşullarını kabul ettiyseniz sisteme e-posta adresi girmeniz gerekir.',
	) ,
	'message' => array(
		'required' => 'Yorumlar kısmı boş bırakılamaz.',
	) ,
	'name' => array(
		'length' => 'İsim kısmı en az 3 karakterden oluşmalı.',
		'required' => 'İsim kısmı boş bırakılamaz.',
	) ,
	'phone' => array(
		'length' => 'Telefon kısmı geçerli değil.',
	) ,
);
