<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-01-31 06:22+0000
// PO revision date:  2015-01-30 12:31+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Lütfen geçerli bir güvenlik kodu giriniz.',
		'required' => 'Lütfen güvenlik kodunu giriniz.',
	) ,
	'contact_email' => array(
		'email' => 'E-posta adresi geçerli değil gibi görünüyor.',
		'required' => 'Lütfen geçerli bir e-posta adresi giriniz.',
	) ,
	'contact_message' => array(
		'required' => 'İleti alanı boş bırakılamaz.',
	) ,
	'contact_subject' => array(
		'length' => 'Başlık en az 3 karakterden oluşmalıdır.',
		'required' => 'Başlık alanı boş bırakılamaz.',
	) ,
);
