<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-01-31 06:22+0000
// PO revision date:  2015-01-30 12:32+0000
$lang = array(
	'private_subject' => array(
		'required' => 'Konu alanı boş bırakılamaz.',
	) ,
	'private_message' => array(
		'required' => 'İleti alanı boş bırakılamaz.',
	) ,
);
