<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:50+0000
$lang = array(
	'description' => array(
		'length' => 'Açıklama kısmı en az 3, en fazla 100 karakter uzunluğunda olmalıdır.',
		'required' => 'Açıklama kısmı boş bırakılamaz.',
	) ,
	'name' => array(
		'alpha_numeric' => 'İsim kısmı sadece harflerden veya rakamlardan oluşmalıdır.',
		'length' => 'İsim kısmı en az 2, en fazla 30 karaterden oluşmalıdır.',
		'nomodify' => 'SüperAdmin Ünvanı Değiştirilemez.',
		'required' => 'İsim kısmı boş bırakılamaz.',
	) ,
	'access_level' => array(
		'numeric' => 'Erişim seviyesi kısmı 0 ila 100 arası bir numara olmalıdır.',
		'required' => 'Erişim seviyesi kısmı 0 ila 100 arası bir numara olmalıdır.',
	) ,
);
