<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-21 20:13+0000
$lang = array(
	'captcha' => array(
		'default' => 'Digite um código de segurança válido.',
		'valid' => 'Por favor insira um código de segurança correto.',
		'required' => 'Digite o código de segurança.',
	) ,
	'contact_email' => array(
		'email' => 'O campo do email parece não conter um endereço de email válido.',
		'length' => 'O campo do email deve ter pelo menos 4 e no máximo 64 caracteres.',
		'required' => 'É necessário preencher o campo do email se a caixa de seleção tiver sido marcada.',
	) ,
	'contact_message' => array(
		'required' => 'É necessário preencher o campo de mensagem.',
	) ,
	'contact_name' => array(
		'length' => 'O campo nome deve ter pelo menos 3 caracteres.',
		'required' => 'É necessário preencher o campo nome.',
	) ,
	'contact_subject' => array(
		'length' => 'O campo de assunto deve ter pelo menos 3 caracteres.',
		'required' => 'É necessário preencher o campo de assunto.',
	) ,
	'email_send' => array(
		'failed' => 'Houve um erro ao enviar a sua mensagem.',
	) ,
);
