<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-21 20:59+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Sex',
		'full' => 'Sexta',
	) ,
	'monday' => array(
		'abbv' => 'Seg',
		'full' => 'Segunda',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Sáb',
		'full' => 'Sábado',
	) ,
	'sunday' => array(
		'abbv' => 'Dom',
		'full' => 'Domingo',
	) ,
	'thursday' => array(
		'abbv' => 'Qui',
		'full' => 'Quinta',
	) ,
	'tuesday' => array(
		'abbv' => 'Ter',
		'full' => 'Terça',
	) ,
	'wednesday' => array(
		'abbv' => 'Qua',
		'full' => 'Quarta',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Janeiro',
	) ,
	'february' => array(
		'abbv' => 'Fev',
		'full' => 'Fevereiro',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Março',
	) ,
	'april' => array(
		'abbv' => 'Abr',
		'full' => 'Abril',
	) ,
	'may' => array(
		'abbv' => 'Mai',
		'full' => 'Maio',
	) ,
	'june' => array(
		'abbv' => 'Jun',
		'full' => 'Junho',
	) ,
	'july' => array(
		'abbv' => 'Jul',
		'full' => 'Julho',
	) ,
	'august' => array(
		'abbv' => 'Ago',
		'full' => 'Agosto',
	) ,
	'september' => array(
		'abbv' => 'Set',
		'full' => 'Setembro',
	) ,
	'october' => array(
		'abbv' => 'Out',
		'full' => 'Outubro',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'Novembro',
	) ,
	'december' => array(
		'abbv' => 'Dez',
		'full' => 'Dezembro',
	) ,
);
