<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:34+0000
$lang = array(
	'date' => 'DATA',
	'feed_name' => array(
		'length' => 'O nome do feed deve ter pelo menos 3 e no máximo
			70 caracteres.',
		'required' => 'Digite o nome do feed.',
	) ,
	'feed_url' => array(
		'required' => 'Digite uma URL válida para o feed.',
		'url' => 'Digite uma URL válida. Ex. http://www.eleitor2010.com',
	) ,
	'source' => 'FONTE',
	'title' => 'TÍTULO',
);
