<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-21 20:39+0000
$lang = array(
	'page_title' => array(
		'required' => 'Por favor insira um título de página.',
		'length' => 'Título da página deve ser no mínimo 3 e no máximo 150 caracteres.',
	) ,
	'page_tab' => array(
		'required' => 'Por favor insira um nome de guia da página.',
	) ,
	'page_description' => array(
		'required' => 'Por favor insira uma descrição da página.',
	) ,
);
