<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-21 20:56+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'ID pai deve ser numérico',
	) ,
	'private_to' => array(
		'required' => 'O campo Para é requerido',
		'exists' => 'O usuário a que você está tentar enviar uma mensagem não existe',
	) ,
	'private_subject' => array(
		'required' => 'O campo assunto é obrigatório',
		'length' => 'Assunto deve ter entre 3 e 150 caracteres',
	) ,
	'private_message' => array(
		'required' => 'O campo de mensagem é necessária',
	) ,
);
