<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:11+0000
// PO revision date:  2013-01-18 18:01+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Por favor, verifique se checou um item',
		'numeric' => 'Por favor, verifique se checou um item',
		'categories_required' => 'Relatos devem ser categorizados antes de poderem ser aprovados',
	) ,
	'action' => array(
		'permission' => 'Você não tem permissão para executar esta ação',
	) ,
	'uploadfile' => array(
		'required' => 'Você deve escolher um arquivo para carregar',
		'type' => 'O arquivo a carregar deve estar em formato .csv ou .xml.',
		'valid' => 'O campo de carregamento de arquivo não parece conter um arquivo válido',
	) ,
);
