<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-05 06:26+0000
// PO revision date:  2013-12-04 21:27+0000
$lang = array(
	'captcha' => array(
		'default' => 'Ange en giltig s&auml;kerhetskod',
		'required' => 'Ange s&auml;kerhetskoden',
		'valid' => 'Du angav en felaktig säkerhetskod.',
	) ,
	'comment_author' => array(
		'length' => 'Namnf&auml;ltet m&aring;ste vara minst 3 tecken.',
		'required' => 'Namnf&auml;ltet m&aring;ste fyllas i.',
	) ,
	'comment_description' => array(
		'required' => 'Kommentarsf&auml;ltet m&aring;ste fyllas i.',
	) ,
	'comment_email' => array(
		'email' => 'E-postf&auml;ltet verkar inte inneh&aring;lla en giltig e-postadress?',
		'length' => 'E-postadressen m&aring;ste vara mellan 4 och 64 tecken.',
		'required' => 'E-postf&auml;ltet m&aring;ste fyllas i om kryssrutan &auml;r markerad.',
	) ,
);
