<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-04 06:25+0000
// PO revision date:  2013-12-03 23:06+0000
$lang = array(
	'message' => 'Tyvärr ligger vår sida nere för underhåll. Prova igen om ett par minuter.',
);
