<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-04 06:25+0000
// PO revision date:  2013-12-03 23:19+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Var god ange en giltig säkerhetskod.',
		'required' => 'Var god ange säkerhetskoden.',
	) ,
	'contact_email' => array(
		'email' => 'E-postfältet verkar inte innehålla en giltig adress.',
		'required' => 'Var god ange en giltig e-postadress.',
	) ,
	'contact_message' => array(
		'required' => 'Meddelandefältet erfordras.',
	) ,
	'contact_subject' => array(
		'length' => 'Ämnesfältet måste minst innehålla 3 tecken.',
		'required' => 'Ämnesfältet erfordras.',
	) ,
);
