<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-04 06:25+0000
// PO revision date:  2013-12-03 23:12+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'Parent ID måste vare numerisk',
	) ,
	'private_to' => array(
		'required' => 'Till-fälten erfodras',
		'exists' => 'Användaren du försöker skicka meddelandet till, existerar inte',
	) ,
	'private_subject' => array(
		'required' => 'Ämnes-fältet erfordras',
		'length' => 'Ämnet måste vara mellan 3 och 150 tecken långt',
	) ,
	'private_message' => array(
		'required' => 'Meddelande-fältet erfordras',
	) ,
);
