<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-12-04 06:25+0000
// PO revision date:  2013-12-03 23:05+0000
$lang = array(
	'description' => array(
		'length' => 'Beskrivningsfältet måste vare mellan 3 och 100 tecken långt.',
		'required' => 'Beskrivningsfältet måste finnas.',
	) ,
	'name' => array(
		'alpha_numeric' => 'Namnfältet får endast bestå av bokstäver och siffror.',
		'length' => 'Namnfältet måste vara mellan 2 och 30 tecken långt.',
		'nomodify' => 'SuperAdmin Rollen Får Inte Modifieras.',
		'required' => 'Namnfält måste finnas.',
	) ,
	'access_level' => array(
		'numeric' => 'Åtkomstfältet måste vara en siffra mellan 0 och 100.',
		'required' => 'Åtkomstfältet måste vara en siffra mellan 0 och 100.',
	) ,
	'permissions' => array(
		'numeric' => 'Behörighetsfältet måste vara en siffra mellan 0 och 100.',
	) ,
);
