<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 08:12+0000
// PO revision date:  2013-01-22 10:54+0000
$lang = array(
	'approved' => 'Godk&auml;nd',
	'categories' => 'Kategorier',
	'category_impact' => 'Kategoriaktivitet',
	'category_impact_description' => 'Denna graf visar en linj&auml;r vy &ouml;ver rapporter per kategori &ouml;ver tid.  Bl&auml;ddra fr&aring;n v&auml;nster till h&ouml;ger f&ouml;r att se en j&auml;mf&ouml;rande vy f&ouml;r de olika kategorierna. Peka p&aring grafen f&ouml;r mer detaljer',
	'choose_date_range' => 'V&auml;lj datumomr&aring;de',
	'countries' => 'L&auml;nder',
	'country' => 'Land',
	'country_breakdown' => 'Nedbrytning av land',
	'description' => 'Detta &auml;r statistiksektionen. Allm&auml;n information kommer fram&ouml;ver. F&ouml;r tillf&auml;llet kan du bl&auml;ddra genom l&auml;nkarna till underkategorierna ovan',
	'error' => 'Fel',
	'glossary' => 'Ordlista',
	'hit_summary' => 'Sammanfattning tr&auml;ffar',
	'legend' => 'Teckenförklaring',
	'pageviews' => 'Sidvisningar',
	'pageviews_description' => 'Det totala antalet sidor som bes&ouml;kare har tittat p&aring p&aring din sajt',
	'reports' => 'Rapporter',
	'reports_categories' => 'Rapportkategorier',
	'reports_statistics' => 'Rapportstatistik',
	'reports_status' => 'Rapportstatus',
	'report_punchcard' => 'Rapportblad',
	'report_stats' => 'Rapportstatistik',
	'stats_not_setup' => 'Statistik &auml;r inte uppsatt',
	'time_range_1' => '1 m&aring;nad',
	'time_range_2' => '3 m&aring;nader',
	'time_range_3' => '6 m&aring;nader',
	'time_range_all' => 'Alla',
	'unapproved' => 'Icke godk&auml;nda',
	'unique_visitors' => 'Unika bes&ouml;kare',
	'unique_visitors_description' => 'Antalet bes&ouml;kare till din upps&auml;ttning; Unika bes&ouml;kare best&auml;ms genom cookies. Om en bes&ouml;kare inte har aktiverat cookies, kommer de att identifieras genom en enkel metod d&auml;r man tar h&auml;nsyn till IP adress, uppl&ouml;sning, webbl&auml;sare, plugins, operativsystem, etc',
	'unverified' => 'Ej verifierad',
	'verified' => 'Verifierad',
	'visitor_summary' => 'Sammanst&auml;llning bes&ouml;kare',
	'visits' => 'Bes&ouml;k',
	'visits_description' => 'Ett bes&ouml;k registreras f&ouml;r en unik bes&ouml;kare som &aring;terkommer till sajten efter mer &auml;n 30 minuter sedan senaste sidvisningen',
);
