<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-20 12:02+0000
$lang = array(
	'profile_email' => 'Din e-postadress',
	'profile_name' => 'Ditt fullst&auml;ndiga namn',
	'profile_notify' => 'Om du v&auml;ljer JA, s&aring f&aring;r du meddelande via e-post om nya h&auml;ndelser eller kommentarer kommer in p&aring sajten',
	'profile_password' => 'Ditt l&ouml;senord. L&auml;mna detta f&auml;lt tomt om du vill beh&aring;lla ditt nuvarande l&ouml;senord',
	'profile_username' => 'Ditt anv&auml;ndarnamn kan inte &auml;ndras',
	'settings_alert_email' => 'Denna e-postadress anv&auml;nds f&ouml;r e-postutskick av h&auml;ndelser.',
	'settings_display_contact' => 'Sl&aring;r av och p&aring kontakta-formul&auml;ret p&aring sajten.',
	'settings_locale' => 'V&auml;ljer vilket spr&aring;k som ska anv&auml;ndas p&aring sajten.',
	'settings_site_email' => 'Denna e-postadress f&aring;r rapporter och meddelande fr&aring;n kontakta-formul&auml;ret.',
	'settings_site_name' => 'Detta &auml;r namnet p&aring sajten som syns l&auml;ngst upp p&aring sidan.',
	'settings_site_tagline' => 'F&ouml;rklara med n&aring;gra f&aring ord vad sajten anv&auml;nds till.',
);
