<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-12 06:24+0000
// PO revision date:  2013-11-12 04:29+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Pia',
		'full' => 'Piatok',
	) ,
	'monday' => array(
		'abbv' => 'Pon',
		'full' => 'Pondelok',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Sob',
		'full' => 'Sobota',
	) ,
	'sunday' => array(
		'abbv' => 'Ned',
		'full' => 'Nedeľa',
	) ,
	'thursday' => array(
		'abbv' => 'Štv',
		'full' => 'Štvrtok',
	) ,
	'tuesday' => array(
		'abbv' => 'Uto',
		'full' => 'Utorok',
	) ,
	'wednesday' => array(
		'abbv' => 'Str',
		'full' => 'Streda',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Január',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Február',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Marec',
	) ,
	'april' => array(
		'abbv' => 'Apr',
		'full' => 'Apríl',
	) ,
	'may' => array(
		'abbv' => 'Máj',
		'full' => 'Máj',
	) ,
	'june' => array(
		'abbv' => 'Jún',
		'full' => 'Jún',
	) ,
	'july' => array(
		'abbv' => 'Júl',
		'full' => 'Júl',
	) ,
	'august' => array(
		'abbv' => 'Aug',
		'full' => 'August',
	) ,
	'september' => array(
		'abbv' => 'Sep',
		'full' => 'September',
	) ,
	'october' => array(
		'abbv' => 'Okt',
		'full' => 'Október',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'November',
	) ,
	'december' => array(
		'abbv' => 'Dec',
		'full' => 'December',
	) ,
);
