<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-11-14 06:24+0000
// PO revision date:  2013-11-14 02:08+0000
$lang = array(
	'admin_footer' => 'Správa bola odoslaná z vašej webstránky.',
	'admin_login_url' => 'Prihlásenie administrátora',
	'admin_new_comment' => array(
		'message' => 'Na vašej webstránke bol pridaný nový komentár v reakcii na:',
		'subject' => 'Nový komentár',
	) ,
	'admin_new_email' => array(
		'message' => 'Nová e-mailová správa bola pridaná na vašu webstránku.',
		'subject' => 'Nová e-mail správa',
	) ,
	'admin_new_report' => array(
		'message' => 'Nová udalosť bola pridaná na vašu webstránku.',
		'subject' => 'Nová udalosť',
	) ,
	'admin_new_sms' => array(
		'message' => 'Nová textová správa bola pridaná na vašu webstránku.',
		'subject' => 'Nová textová správa',
	) ,
	'member_new_alert' => array(
		'message' => 'Obdržali ste nové upozornenie',
		'subject' => 'Nové upozornenie!',
	) ,
	'member_new_message' => array(
		'message' => 'Obdržali ste novú súkromnú správu',
		'subject' => 'Nová súkromná správa',
		'footer' => 'Pre odpoveď choďte prosím do:',
	) ,
);
