<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-06-10 06:21+0000
// PO revision date:  2015-06-10 02:32+0000
$lang = array(
	'alert_email' => array(
		'email' => 'Format alamat surel yang tercantum pada kolom surel tidak valid ?',
		'email_check' => 'Alamat surel yang tercantum sudah terdaftar sebagai penerima peringatan untuk lokasi tersebut',
		'length' => 'Panjang isian alamat surel harus minimal 4 dan tidak lebih dari 64 karakter.',
		'required' => 'Jika checkbox dicentang, isian surel tidak boleh kosong',
	) ,
	'alert_country' => array(
		'single_country' => 'Cakupan penyebaran platform ini hanya dalam satu negara. Pastikan lokasi peringatan berada dalam negara %s',
	) ,
	'alert_lat' => array(
		'between' => 'Anda belum memilih lokasi yang benar pada peta',
		'required' => 'Anda belum memilih lokasi yang benar pada peta',
	) ,
	'alert_lon' => array(
		'between' => 'Anda belum memilih lokasi yang benar pada peta',
		'required' => 'Anda belum memilih lokasi yang benar pada peta',
	) ,
	'alert_mobile' => array(
		'length' => 'Jumlah karakter pada isian Telepon Seluler salah.',
		'mobile_check' => 'Nomor telpon seluler yang dicantumkan sudah terdaftar untuk menerima peringatan dari lokasi itu.',
		'numeric' => 'Nomor telepon seluler pada kolom telepon seluler salah. Mohon isi hanya dengan angka termasuk kode negara.',
		'one_required' => 'Anda harus mencantumkan nomor telepon seluler anda atau alamat surel anda',
		'required' => 'Jika kotak centang dicentang, isian telepon seluler tidak boleh kosong',
	) ,
	'alert_radius' => array(
		'in_array' => 'Anda belum menentukan radius yang benar pada peta',
		'required' => 'Anda belum menentukan radius anda pada peta',
	) ,
	'alert_recipient' => array(
		'required' => 'Anda belum menentukan penerima peringatan.',
	) ,
	'alerts_subscribed' => 'Anda telah berlangganan peringatan dengan kategori berikut ini',
	'code_already_verified' => 'Kode ini sudah pernah diverifikasi !',
	'code_not_found' => 'Kode verifikasi ini tidak ditemukan ! Mohon periksa kembali URL yang digunakan.',
	'code_verified' => 'Kode anda telah diverifikasi dengan benar. Anda akan menerima peringatan begitu ada kejadian.',
	'confirm_request' => 'Untuk mengkonfirmasikan permintaan peringatan anda, mohon lanjut ke',
	'create_more_alerts' => 'Kembali ke laman Peringatan untuk membuat peringatan baru',
	'email_alert_request_created' => 'Permintaan Peringatan melalui surel anda telah dibuat dan pesan untuk memverifikasi ini telah dikirim ke',
	'email_code' => 'Silakan masukan kode konfirmasi surel yang anda terima di bawah ini :',
	'email_error_head' => 'Permintaan Peringatan melalui surel anda BELUM tersimpan !',
	'email_ok_head' => 'Permintaan Peringatan melalui surel anda telah tersimpan!',
	'error' => 'Sistem tidak bisa memroses permintaan konfirmasi anda!',
	'mobile_alert_request_created' => 'Permintaan Peringatan melalui ponsel anda telah dibuat dan pesan untuk memverifikasi ini telah dikirim ke',
	'mobile_code' => 'Silakan masukan kode konfirmasi SMS yang anda terima di telpon seluler anda di bawah ini :',
	'mobile_error_head' => 'Permintaan Peringatan melalui ponsel anda BELUM tersimpan !',
	'mobile_ok_head' => 'Permintaan Peringatan melalui ponsel anda telah tersimpan !',
	'settings_error' => 'Instalasi ini tidak terkonfigurasi untuk memroses peringatan dengan benar',
	'unsubscribe' => 'Anda menerima surel ini karena anda telah berlangganan untuk memperoleh peringatan. Jika anda mau menghentikan pengiriman peringatan ini silakan ke',
	'unsubscribed' => 'Anda tidak lagi akan dikirimi peringatan dari',
	'unsubscribe_failed' => 'Kami gagal membatalkan permintaan penghentian berlangganan anda. Mohon pastikan URL yg anda gunakan sudah benar.',
	'verification_email_subject' => 'peringatan - verifikasi',
	'verify_code' => 'Anda tidak akan menerima peringatan dari lokasi ini sebelum anda konfirmasikan permintaan anda.',
);
