<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-05-16 06:22+0000
// PO revision date:  2015-05-15 08:49+0000
$lang = array(
	'email' => array(
		'email' => 'Alamat surel yang Anda masukkan tidak benar.',
		'exists' => 'Maaf, alamat surel ini sudah digunakan pengguna lain.',
		'length' => 'Panjang isian alamat surel setidaknya terdiri dari 4 dan tidak lebih dari 64 karakter.',
		'required' => 'Kolom isian surel wajib diisi.',
	) ,
	'name' => array(
		'length' => 'Kolom nama lengkap setidaknya 3 dan tidak lebih dari 100 karakter.',
		'required' => 'Isian nama lengkap harus diisi.',
		'standard_text' => 'Isian nama pengguna mengandung karakter yang tidak diperbolehkan.',
	) ,
	'current_password' => array(
		'length' => 'Kolom kata sandi setidaknya harus terdiri atas 8 karakter.',
		'login error' => 'Pastikan bahwa alamat surel dan kata sandi yang Anda masukkan sudah benar.',
		'matches' => 'Masukkan kata sandi yang sama ke kedua kolom kata sandi.',
		'required' => 'Kolom kata sandi wajib diisi.',
		'alpha_dash' => 'Kolom kata sandi setidaknya harus berisi karakter huruf, simbol # dan @, angka, garis bawah dan simbol -',
		'incorrect' => 'Kata sandi yang Anda masukkan salah. Silahkan coba lagi.',
	) ,
	'new_password' => array(
		'length' => 'Kolom kata sandi setidaknya harus terdiri atas 8 karakter.',
		'login error' => 'Pastikan bahwa alamat surel dan kata sandi yang Anda masukkan sudah benar.',
		'matches' => 'Masukkan kata sandi yang sama ke kedua kolom kata sandi.',
		'required' => 'Kolom kata sandi wajib diisi.',
		'alpha_dash' => 'Kolom kata sandi setidaknya harus berisi karakter huruf, simbol # dan @, angka, garis bawah dan tanda hubung',
	) ,
	'password' => array(
		'default' => 'Ada kesalahan saat mencoba login.',
		'length' => 'Kolom kata sandi setidaknya harus berisi 8 karakter.',
		'login error' => 'Pastikan Anda sudah mengisi alamat surel dan kata sandi dengan benar.',
		'matches' => 'Masukkan kata sandi yang sama dalam kedua kolom kata sandi.',
		'required' => 'Kolom kata sandi wajib diisi.',
		'riverid server down' => 'Server otentifikasi sedang mati. Coba beberapa saat lagi.',
		'riverid' => '%s',
		'alpha_dash' => 'Kolom kata sandi setidaknya harus berisi karakter huruf, simbol # dan @, angka, garis bawah dan tanda hubung',
	) ,
	'password_confirm' => array(
		'matches' => 'Kata sandi yang Anda masukkan pada kolom konfirmasi harus sama dengan isian pada kolom kata sandi.',
	) ,
	'resetemail' => array(
		'email' => 'Format alamat surel yang anda masukkan salah. ',
		'invalid' => 'Maaf, alamat surel anda tidak terdaftar',
		'required' => 'Kolom alamat surel wajib diisi.',
	) ,
	'role' => array(
		'superadmin_modify' => 'Hanya superadmin yang boleh menyunting sebuah akun superadmin atau menaikkan akses user menjadi admin.',
	) ,
	'roles' => array(
		'alpha_numeric' => 'Format peran salah.',
		'length' => 'Kolom peran setidaknya terdiri dari 5 dan tidak lebih dari 30 karakter.',
		'required' => 'Anda harus tetapkan setidaknya satu peran.',
		'values' => 'Anda harus memilih ADMIN atau PENGGUNA.',
	) ,
	'token' => array(
		'invalid' => 'Token untuk lupa kata sandi tidak benar.',
		'required' => 'Token untuk lupa kata sandi diperlukan',
	) ,
	'username' => array(
		'admin' => 'Peran admin tidak boleh disunting.',
		'alpha_numeric' => 'Tautan di profil untuk publik hanya berisi angka dan huruf.',
		'exists' => 'Maaf, tautan di profil untuk publik sudah pernah digunakan orang lain.',
		'length' => 'Tautan di profil untuk publik setidaknya terdiri atas 2 dan tidak lebih dari 100 karakter.',
		'login error' => 'Pastikan Anda telah menuliskan tautan di profil untuk publik dengan benar.',
		'required' => 'Tautan di profil untuk publik wajib diisi.',
		'superadmin' => 'Peran admin super tidak boleh disunting.',
		'csrf' => 'Ada potensi serangan CSRF. Apakah Anda yakin ingin membuat/menyunting seorang pengguna?',
	) ,
);
