<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-24 06:24+0000
// PO revision date:  2013-10-23 07:03+0000
$lang = array(
	'am' => 'AM',
	'friday' => array(
		'abbv' => 'Jum',
		'full' => 'Jumat',
	) ,
	'monday' => array(
		'abbv' => 'Sen',
		'full' => 'Senin',
	) ,
	'pm' => 'PM',
	'saturday' => array(
		'abbv' => 'Sab',
		'full' => 'Sabtu',
	) ,
	'sunday' => array(
		'abbv' => 'Ming',
		'full' => 'Minggu',
	) ,
	'thursday' => array(
		'abbv' => 'Kam',
		'full' => 'Kamis',
	) ,
	'tuesday' => array(
		'abbv' => 'Sel',
		'full' => 'Selasa',
	) ,
	'wednesday' => array(
		'abbv' => 'Rab',
		'full' => 'Rabu',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Januari',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Februari',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Maret',
	) ,
	'april' => array(
		'abbv' => 'Apr',
		'full' => 'April',
	) ,
	'may' => array(
		'abbv' => 'Mei',
		'full' => 'Mei',
	) ,
	'june' => array(
		'abbv' => 'Jun',
		'full' => 'Juni',
	) ,
	'july' => array(
		'abbv' => 'Jul',
		'full' => 'Juli',
	) ,
	'august' => array(
		'abbv' => 'Agus',
		'full' => 'Agustus',
	) ,
	'september' => array(
		'abbv' => 'Sep',
		'full' => 'September',
	) ,
	'october' => array(
		'abbv' => 'Okt',
		'full' => 'Oktober',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'November',
	) ,
	'december' => array(
		'abbv' => 'Des',
		'full' => 'Desember',
	) ,
);
