<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-05-21 06:22+0000
// PO revision date:  2015-05-20 06:58+0000
$lang = array(
	'akismet_cannot_connect' => 'Tidak bisa terhubung dengan layanan Akismet.',
	'akismet_cannot_retrieve' => 'Respon dari Akismet tidak bisa diperoleh.',
	'api_library_not_found' => 'Pustaka API: <strong>%s</strong> untuk <strong>%s</strong> tidak ditemukan. Mohon periksa tabel routing API task Anda.',
	'askimet_invalid_apikey' => 'Kunci API Akismet Anda tidak valid.',
	'clickatell_fopen_error' => 'Error terjadi pada saat melakukan metode pengiriman fopen!<br>Mohon pastikan PHP memiliki dukungan OpenAAL dan pastikan versi PHP-nya sudah lebih dari 5.2.',
	'clickatell_message_too_long' => 'Pesan unicode Anda terlalu panjang! (Panjang sekarang=',
	'clickatell_no_destination_address' => 'Mohon sertakan alamat tujuan (KEPADA)!',
	'clickatell_no_sender_address' => 'Mohon sertakan alamat pengirim (DARI)!',
	'clickatell_unicode_message_too_long' => 'Pesan unicode Anda terlalu panjang! (Panjang sekarang=',
	'clickatell_unsupported_method' => 'Metode pengiriman tidak dikenal!',
	'invalid_api_library' => 'Pustaka API %s tidak berlaku. Semua pustaka API harus merupakan subclass dari %s.',
	'upgrade_directory_not_deleted' => 'Direktori <code>%s</code> tidak bisa dihapus.',
	'upgrade_extracting_error' => 'Error pada saat melakukan ekstraksi: <code>%s</code>',
	'upgrade_failed' => 'Pengunduhan versi terbaru Ushahidi gagal. Status kode HTTP',
	'upgrade_file_not_copied' => 'Berkas <code>%s</code> tidak bisa disalin.',
	'upgrade_file_not_deleted' => 'Berkas <code>%s</code> tidak bisa dihapus.',
	'upgrade_title' => 'Skrip upgrade Ushahidi',
	'upgrade_zip_error' => 'Berkas zip Ushahidi yang diunduh <code>%s</code>, tidak bisa ditulis.',
	'riverid_variable_not_available' => '%s tidak tersedia di class RiverID.',
);
