<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-04-30 05:42+0000
$lang = array(
	'captcha' => array(
		'default' => 'Masukan kode keamanan yang benar',
		'required' => 'Masukan kode keamanan',
	) ,
	'email' => array(
		'email' => 'Kolom surel tampaknya tidak berisi alamat surel yang benar.',
		'length' => 'Panjang alamat surel minimal 4 karakter dan tidak boleh lebih dari 64 karakter',
		'required' => 'Kalau kotak centang dicentang kolom alamat surel tidak boleh dikosongkan',
	) ,
	'message' => array(
		'required' => 'Kolom komentar tidak boleh dikosongkan',
	) ,
	'name' => array(
		'length' => 'Panjang kolom nama minimal 3 karakter',
		'required' => 'Kolom nama tidak boleh dikosongkan',
	) ,
	'phone' => array(
		'length' => 'Isi kolom telpon salah.',
	) ,
);
