<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-10-28 06:23+0000
// PO revision date:  2013-10-27 10:44+0000
$lang = array(
	'contact_captcha' => array(
		'default' => 'Masukkan kode keamanan yang benar.',
		'required' => 'Masukkan kode keamanan.',
	) ,
	'contact_email' => array(
		'email' => 'Surel yang Anda masukkan tidak benar.',
		'required' => 'Pastikan alamat surel diisikan sudah benar.',
	) ,
	'contact_message' => array(
		'required' => 'Kolom pesan tidak boleh kosong.',
	) ,
	'contact_subject' => array(
		'length' => 'Panjang isi kolom subjek setidaknya 3 karakter.',
		'required' => 'Kolom subjek tidak boleh dikosongkan.',
	) ,
);
