<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-06-10 06:21+0000
// PO revision date:  2015-06-10 02:36+0000
$lang = array(
	'comments_form_error' => 'error!',
	'country_name' => array(
		'single_country' => 'Pengembangan ini hanya mencakup satu negara saja. Pastikan posisi dalam laporan masuk dalam wilayah negara %s.',
	) ,
	'custom_field' => array(
		'values' => 'Masukkan nilai pada kolom "%s" yang tepat.',
		'numeric' => 'Kolom "%s" harus berupa angka. ',
		'required' => 'Kolom "%s" wajib diisi.',
		'not_exist' => 'Kolom "%s" tidak ditemukan.',
		'permission' => 'Anda tidak diperkenankan menyunting kolom "%s".',
		'email' => 'Kolom "%s" harus berisi alamat surel yang benar.',
		'phone' => 'Kolom "%s" harus berisi nomor telepon seluler yang benar.',
		'date_mmddyyyy' => 'Kolom "%s" harus berupa tanggal dalam format yang tepat (MM/DD/YYYY).',
		'date_ddmmyyyy' => 'Kolom "%s" harus berupa tanggal dalam format yang tepat (DD/MM/YYYY).',
	) ,
	'data_include' => array(
		'between' => 'Pastikan hanya memilih bagian yang tepat untuk diunduh.',
		'numeric' => 'Pastikan hanya memilih bagian yang tepat untuk diunduh.',
	) ,
	'data_active' => array(
		'between' => 'Pilih "Laporan yang Menunggu Disetujui" atau "Laporan yang Disetujui" atau keduanya.',
		'numeric' => 'Pilih "Laporan yang Menunggu Disetujui" atau "Laporan yang Disetujui" atau keduanya.',
		'required' => 'Pilih "Laporan yang Menunggu Disetujui" atau "Laporan yang Disetujui" atau keduanya.',
	) ,
	'data_verified' => array(
		'between' => 'Pilih "Laporan yang Menunggu Diperiksa" atau "Laporan yang Sudah Diperiksa" atau keduanya.',
		'numeric' => 'Pilih "Laporan yang Menunggu Diperiksa" atau "Laporan yang Sudah Diperiksa" atau keduanya.',
		'required' => 'Pilih "Laporan yang Menunggu Diperiksa" atau "Laporan yang Sudah Diperiksa" atau keduanya.',
	) ,
	'data_point' => array(
		'between' => 'Pastikan memilih laporan yang tepat untuk diunduh.',
		'numeric' => 'Pastikan memilih laporan yang tepat untuk diunduh.',
		'required' => 'Pastikan memilih jenis laporan yang tepat untuk diunduh.',
	) ,
	'format' => array(
		'required' => 'Anda harus memilih format file untuk diunduh, bisa CSV atau XML.',
		'valid' => 'Masukkan format file yang hendak Anda unduh dalam',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Kolom SEJAK pada tanggal tidak benar.',
		'range' => 'Masukkan kolom SEJAK yang benar pada tanggal. Tidak boleh lebih dari saat ini.',
	) ,
	'incident_active' => array(
		'between' => 'Isi kolom Setujui Laporan Ini dengan benar.',
		'required' => 'Isi kolom Setujui Laporan Ini dengan benar.',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Kolom AM/PM tidak benar.',
	) ,
	'incident_category' => array(
		'numeric' => 'Kolom Kategori tidak benar.',
		'required' => 'Kolom Kategori wajib diisi.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Kolom tanggal tidak benar.',
		'date_mmddyyyy' => 'Kolom tanggal tidak benar.',
		'required' => 'Kolom tanggal wajib diisi.',
	) ,
	'incident_description' => array(
		'required' => 'Kolom keterangan wajib diisi.',
	) ,
	'incident_hour' => array(
		'between' => 'Kolom jam tidak benar.',
		'required' => 'Kolom jam wajib diisi.',
	) ,
	'incident_information' => array(
		'alpha' => 'Pastikan yang tertera dalam kolom Peluang Informasi sudah benar.',
		'length' => 'Pastikan yang tertera dalam kolom Peluang Informasi sudah benar.',
	) ,
	'incident_minute' => array(
		'between' => 'Kolom menit tidak benar.',
		'required' => 'Kolom menit wajib diisi.',
	) ,
	'incident_news' => array(
		'url' => 'Alamat pada kolom tautan sumber berita tidak benar.',
	) ,
	'incident_photo' => array(
		'size' => 'Pastikan besar foto yang diunggah tidak lebih dari 2 MB.',
		'type' => 'Isi kolom Unggah Foto tidak benar. Format yang berlaku hanya .JPG, .PNG dan .GIF.',
		'valid' => 'Isi kolom Unggah Foto tidak benar.',
	) ,
	'incident_source' => array(
		'alpha' => 'Masukkan Kehandalan Sumber yang tepat.',
		'length' => 'Masukkan Kehandalan Sumber yang tepat.',
	) ,
	'incident_title' => array(
		'length' => 'Panjang "Judul Laporan" setidaknya 3 karakter dan tidak lebih dari 200 karakter.',
		'required' => 'Kolom "Judul Laporan" wajib diisi.',
		'csrf' => 'Ada kemungkinan serangan CSRF. Apakah Anda yakin hendak membuat/menyunting laporan?',
	) ,
	'incident_verified' => array(
		'between' => 'Isi kolom "Periksa Laporan Ini" dengan tepat.',
		'required' => 'Isi kolom "Periksa Laporan Ini" dengan tepat.',
	) ,
	'incident_video' => array(
		'url' => 'Alamat tautan video tidak benar.',
	) ,
	'latitude' => array(
		'between' => 'Isi kolom Lintang salah.',
		'required' => 'Kolom Lintang wajib diisi. Klik lokasi pada peta.',
	) ,
	'locale' => array(
		'alpha_dash' => 'Kolom pengaturan lokal tidak tepat.',
		'exists' => 'Laporan ini sudah diterjemahkan dalam bahasa ini.',
		'length' => 'Kolom pengaturan lokal tidak tepat.',
		'locale' => 'Bahasa Laporan Asli dan Terjemahan memiliki bahasa (lokal) yang sama.',
		'required' => 'Kolom pengaturan lokal wajib diisi.',
	) ,
	'location_name' => array(
		'length' => 'Kolom "Nama Lokasi" setidaknya 3 karakter dan tidak lebih dari 200 karakter.',
		'required' => 'Kolom "Nama Lokasi" wajib diisi.',
	) ,
	'longitude' => array(
		'between' => 'Kolom Bujur tidak benar.',
		'required' => 'Kolom Bujur wajib diisi. Klik lokasi pada peta.',
	) ,
	'person_email' => array(
		'email' => 'Alamat surel Anda tidak benar.',
		'length' => 'Alamat surel setidaknya terdiri dari 4 karakter dan tidak lebih dari 64 karakter.',
	) ,
	'person_first' => array(
		'length' => 'Kolom nama pertama setidaknya 3 karakter dan tidak lebih dari 100 karakter.',
	) ,
	'person_last' => array(
		'length' => 'Kolom nama keluarga setidaknya 2 karakter dan tidak lebih dari 100 karakter.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Kolom SAMPAI pada tanggal tidak benar.',
		'range' => 'Masukkan kolom SAMPAI pada tanggal yang tepat. Tidak boleh melebihi hari ini.',
		'range_greater' => 'Kolom SEJAK pada rentang waktu tidak boleh melebihi kolom SAMPAI.',
	) ,
);
