<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2015-06-12 06:23+0000
// PO revision date:  2015-06-10 06:55+0000
$lang = array(
	'approved' => 'Disetujui',
	'categories' => 'Kategori',
	'category_impact' => 'Dampak Kategori',
	'category_impact_description' => 'Bagan berikut ini menampilkan gambaran linear dari laporan yang masuk berdasarkan kategori yang ada. Tarik dari kiri ke kanan untuk melihat perbandingan tampilan dari kategori yang berbeda-beda. Gerakkan kursor di atas bagan untuk informasi yang lebih detil.',
	'choose_date_range' => 'Pilih jeda tanggal.',
	'countries' => 'Negara',
	'country' => 'Negara',
	'country_breakdown' => 'Daftar Negara',
	'description' => 'Ini adalah bagian statistik dan akan diisi gambaran umum. Saat ini, masih diisi dengan sub kategori di atas.',
	'error' => 'Error',
	'glossary' => 'Glosarium',
	'hit_summary' => 'Ringkasan Kunjungan',
	'legend' => 'Legenda',
	'pageviews' => 'Pageview',
	'pageviews_description' => 'Jumlah halaman di situs Anda yang dilihat pengunjung.',
	'reports' => 'Laporan',
	'reports_categories' => 'Kategori Laporan',
	'reports_statistics' => 'Statistik Laporan',
	'reports_status' => 'Status Laporan',
	'report_punchcard' => 'Laporan Punchcard',
	'report_stats' => 'Statistik Laporan',
	'stats_not_setup' => 'Statistik Belum Diatur',
	'time_range_1' => '1 Bulan',
	'time_range_2' => '3 Bulan',
	'time_range_3' => '6 Bulan',
	'time_range_all' => 'Semua',
	'unapproved' => 'Belum disetujui',
	'unique_visitors' => 'Pengunjung Unik',
	'unique_visitors_description' => 'Jumlah orang yang mengunjungi situs Anda. Pengunjung unik direkam berdasarkan cookies. Pengunjung yang tidak menjalankan cookies akan diidentifikasi menggunakan pendataan alamat IP, resolusi, browser, plugins, sistem operasi dan sebagainya.',
	'unverified' => 'Belum Diverifikasi',
	'verified' => 'Terverifikasi',
	'visitor_summary' => 'Ringkasan Data Pengunjung',
	'visits' => 'Kunjungan',
	'visits_description' => 'Satu kali kunjungan dari pengujung unik dihitung sekali bila kunjungan dilakukan 30 menit setelah kunjungan terakhirnya.',
);
