<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-12 09:04+0000
$lang = array(
	'category_color' => array(
		'length' => 'Políčko s barvou musí mít 6 znaků',
		'required' => 'Barva je povinná položka',
	) ,
	'category_description' => array(
		'required' => 'Políčko popis je povinná položka',
	) ,
	'category_image' => array(
		'size' => 'Ujistěte se, že obrázky mají méně než 50KB.',
		'type' => 'Obrázek není ve správném formátu; nahrát je možné obrázky ve formátu .JPG, .PNG a .GIF.',
		'valid' => 'Obrázek není ve správném formátu',
	) ,
	'category_title' => array(
		'length' => 'Název musí mít ne méně než 3 a ne více než 80 znaků',
		'required' => 'Políčko název je povinná položka',
	) ,
	'parent_id' => array(
		'already_parent' => 'Nemůžete podkategorizovat kategorii s podkategorií.',
		'exists' => 'Nadřazená kategorie neexistuje.',
		'numeric' => 'Nadřazená kategorie musí být v číselném tvaru.',
		'parent_trusted' => 'Rodič kategorie nemůže být zvláštní kategorie',
		'required' => 'Políčko nadřazená kategorie je povinná položka.',
		'same' => 'Kategorie a nadřazená kategorie nemůže být stejná.',
		'special' => 'Zvláštní kategorie nelze podkategorizovat',
	) ,
);
