<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-12 08:47+0000
$lang = array(
	'config' => 'konfigurační soubor',
	'controller' => 'řadič',
	'driver' => 'ovladač',
	'driver_implements' => 'The %s driver for the %s library must implement the %s interface',
	'driver_not_found' => 'The %s driver for the %s library could not be found',
	'invalid_filetype' => 'The requested filetype, .%s, is not allowed in your view configuration file',
	'library' => 'knihovna',
	'log_dir_unwritable' => 'Adresář pro logy není zapisovatelný: %s',
	'model' => 'model',
	'no_controller' => 'Ushahidi nebyl schopen určit řadič pro zpracování tohoto požadaveku: %s',
	'no_default_route' => 'Prosím nastavte výchozí trasu do souboru config/routes.php',
	'page_not_found' => 'Stránka, kterou požadujete, %s, nemohla být nalezena.',
	'report_bug' => '<a href="%s" id="show_bugs">Oznámení tohoto problému Ushahidi</a>',
	'resource_not_found' => 'The requested %s, %s, could not be found',
	'stack_trace' => 'Zísobník trasování',
	'there_can_be_only_one' => 'There can be only one instance of Ushahidi per page request',
	'view_set_filename' => 'You must set the the view filename before calling render',
);
