<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:34+0000
$lang = array(
	'date' => 'DATUM',
	'feed_name' => array(
		'length' => 'Název informačního kanálu musí mít nejméně 3 a ne více než 70 znaků.',
		'required' => 'Vložte název informačního kanálu.',
	) ,
	'feed_url' => array(
		'required' => 'Vložte URL informačního kanálu.',
		'url' => 'Vložte platnou adresu URL, např. http://www.ushahidi.com',
	) ,
	'source' => 'ZDROJ',
	'title' => 'NÁZEV',
);
