<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-22 07:13+0000
$lang = array(
	'page_title' => array(
		'required' => 'Zadejte prosím název stránky.',
		'length' => 'Název stránky musí být nejméně 3 a ne více než 150 znaků dlouhý.',
	) ,
	'page_tab' => array(
		'required' => 'Zadejte prosím jméno tabulky stránky.',
	) ,
	'page_description' => array(
		'required' => 'Zadejte prosím popis stránky.',
	) ,
);
