<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-10-07 20:49+0000
$lang = array(
	'captcha' => array(
		'default' => 'Cuir isteach cód slándála bailí, le do thoil',
		'required' => 'Cuir isteach an Cód Slándála',
	) ,
	'email' => array(
		'email' => 'Tá an chosúlacht air nach seoladh ríomhphoist bailí atá sa réimse Ríomhphoist?',
		'length' => 'Ní mór don réimse Ríomhphoist a bheith 4 charachtar ar fhad ar a laghad agus gan a bheith níos mó ná 64 carachtar.',
		'required' => 'Tá an réimse Ríomhphoist ag teastáil má tá tic curtha sa bhosca.',
	) ,
	'message' => array(
		'required' => 'Tá an réimse nótaí tráchta ag teastáil.',
	) ,
	'name' => array(
		'length' => 'Ní mór don réimse ainm a bheith 3 charachtar ar fhad ar a laghad.',
		'required' => 'Tá an réimse ainm ag teastáil.',
	) ,
	'phone' => array(
		'length' => 'Níl an réimse fóin bailí.',
	) ,
);
