<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-08-23 06:26+0000
// PO revision date:  2013-08-22 06:22+0000
$lang = array(
	'comments_form_error' => 'earráid!',
	'data_include' => array(
		'between' => 'Roghnaigh, le do thoil, mír bhailí le cur san áireamh san íoslódáil.',
		'numeric' => 'Roghnaigh, le do thoil, mír bhailí le cur san áireamh san íoslódáil.',
	) ,
	'data_point' => array(
		'between' => 'Roghnaigh, le do thoil, cineál tuairisce bailí le híoslódáil.',
		'numeric' => 'Roghnaigh, le do thoil, cineál tuairisce bailí le híoslódáil',
		'required' => 'Roghnaigh, le do thoil, cineál tuairisce bailí le híoslódáil',
	) ,
	'from_date' => array(
		'date_mmddyyyy' => 'Tá an chosúlacht air nach dáta bailí atá sa réimse \'Ó\'?',
		'range' => 'Cuir isteach Dáta \'Ó\' bailí Ní féidir leis a bheith níos mó ná inniu.',
	) ,
	'incident_active' => array(
		'between' => 'Cuir isteach luach bailí do \'Ceadaigh An Tuairisc Seo\'',
		'required' => 'Cuir isteach luach bailí do \'Ceadaigh An Tuairisc Seo\'',
	) ,
	'incident_ampm' => array(
		'validvalues' => 'Tá an chosúlacht air nach bhfuil luach bailí sa réimse am/pm?',
	) ,
	'incident_category' => array(
		'numeric' => 'Tá an chosúlacht air nach bhfuil catagóir bhailí i réimse na catagóire?',
		'required' => 'Tá an réimse catagóire ag teastáil.',
	) ,
	'incident_date' => array(
		'date_ddmmyyyy' => 'Tá an chosúlacht air nach dáta bailí atá sa réimse dáta?',
		'date_mmddyyyy' => 'Tá an chosúlacht air nach dáta bailí atá sa réimse dáta?',
		'required' => 'Tá an réimse dáta ag teastáil.',
	) ,
	'incident_description' => array(
		'required' => 'Tá an réimse Tuairisce ag teastáil.',
	) ,
	'incident_hour' => array(
		'between' => 'Tá an chosúlacht air nach bhfuil uair bhailí i réimse uaire?',
		'required' => 'Tá réimse uaire ag teastáil.',
	) ,
	'incident_information' => array(
		'alpha' => 'Cuir isteach luach bailí do Dhóchúlacht Eolais',
		'length' => 'Cuir isteach luach bailí do Dhóchúlacht Eolais',
	) ,
	'incident_minute' => array(
		'between' => 'Tá an chosúlacht air nach bhfuil luach bailí sa réimse nóiméid?',
		'required' => 'Tá an réimse nóiméid ag teastáil.',
	) ,
	'incident_news' => array(
		'url' => 'Tá an chosúlacht air nach bhfuil URL bailí sa réimse nasc foinse nuachta?',
	) ,
	'incident_photo' => array(
		'size' => 'Déan cinnte, le do thoil, go bhfuil uasmhéid 2MB ar mhéideanna na ngrianghraf atá á n-uaslódáil.',
		'type' => 'Tá an chosúlacht air nach fís bhailí atá sa réimse uaslódála grianghraf. Is iad .JPG, .PNG agus .GIF amháin na formáidí a nglactar leo',
		'valid' => 'Tá an chosúlacht air nach bhfuil comhad bailí sa réimse uaslódála grianghraf.',
	) ,
	'incident_source' => array(
		'alpha' => 'Cuir isteach luach bailí do \'Iontaofacht Foinse\'',
		'length' => 'Cuir isteach luach bailí do \'Iontaofacht Foinse\'',
	) ,
	'incident_title' => array(
		'length' => 'Ní mór don réimse teidil a bheith 3 charachtar ar fhad ar a laghad agus gan a bheith níos mó ná 200 carachtar',
		'required' => 'Tá an réimse teidil ag teastáil.',
	) ,
	'incident_verified' => array(
		'between' => 'Cuir isteach luach bailí do \'Deimhnigh An Tuairsc Seo\'',
		'required' => 'Cuir isteach luach bailí do \'Deimhnigh An Tuairisc Seo\'',
	) ,
	'incident_video' => array(
		'url' => 'Tá an chosúlacht air nach bhfuil URL bailí sa réimse nasc físeáin?',
	) ,
	'latitude' => array(
		'between' => 'Tá an chosúlacht air nach bhfuil leithead bailí sa réimse leithid?',
		'required' => 'Tá an réimse leithid ag teastáil. Cliceáil ar an mapa chun suíomh a mharcáil',
	) ,
	'locale' => array(
		'alpha_dash' => 'Tá luach mícheart sa réimse logchaighdeáin. ',
		'exists' => 'Tá aistriúchán don tuairisc seo don teanga seo cheana féin',
		'length' => 'Tá luach mícheart sa réimse logchaighdeáin. ',
		'locale' => 'Tá an logchaighdeán (Teanga) céanna ag an buntuairisc agus ag an aistriúchán.',
		'required' => 'Tá an logchaighdeán ag teastáil.',
	) ,
	'location_name' => array(
		'length' => 'Ní mór do réimse ainm an tsuímh a bheith 3 charachtar ar fhad ar a laghad agus gan a bheith níos mó na 200 carachtar.',
		'required' => 'Tá ainm an tsuímh ag teastáil.',
	) ,
	'longitude' => array(
		'between' => 'Tá an chosúlacht air nach bhfuil fad bailí sa réimse faid?',
		'required' => 'Tá an réimse faid ag teastáil. Cliceáil ar an mapa chun suíomh a mharcáil',
	) ,
	'person_email' => array(
		'email' => 'Tá an chosúlacht air nach seoladh ríomhphoist bailí atá sa réimse ríomhphoist?',
		'length' => 'Ní mór don réimse ríomhphoist a bheith 4 charachtar ar fhad ar a laghad agus gan a bheith níos mó ná 64 carachtar.',
	) ,
	'person_first' => array(
		'length' => 'Ní mór don réimse céadainm a bheith 3 charachtar ar fhad ar a laghad agus gan a bheith níos mó ná 100 carachtar.',
	) ,
	'person_last' => array(
		'length' => 'Ní mór don réimse sloinne a bheith 2 charachtar ar fhad ar a laghad agus gan a bheith níos mó ná 100 carachtar.',
	) ,
	'to_date' => array(
		'date_mmddyyyy' => 'Tá an chosúlacht air nach dáta bailí atá sa réimse \'GO\'?',
		'range' => 'Cuir isteach Dáta \'GO\' bailí. Ní féidir leis a bheith níos mó ná inniu.',
		'range_greater' => 'Ní féidir an dáta \'Ó\' a bheith níos mó ná an dáta \'GO\'.',
	) ,
);
