<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-08-11 09:25+0000
$lang = array(
	'captcha' => array(
		'default' => 'กรุณาใส่รหัสรักษาความปลอดภัยที่ถูกต้อง',
		'valid' => 'กรุณาใส่รหัสรักษาความปลอดภัยที่ถูกต้อง',
		'required' => 'กรุณาใส่รหัสรักษาความปลอดภัย',
	) ,
	'contact_email' => array(
		'email' => 'ช่องอีเมล์ไม่ปรากฏอีเมล์ที่ถูกต้อง',
		'length' => 'ช่องอีเมล์ต้องมีอย่างน้อย 4 และไม่เกิน 64 ตัวอักษร',
		'required' => 'จำเป็นต้องใส่อีเมล์ถ้าช่องทำเครื่องหมายได้ทำการเช็คถูก',
	) ,
	'contact_message' => array(
		'required' => 'จำเป็นต้องใส่ข้อความ',
	) ,
	'contact_name' => array(
		'length' => 'ช่องสำหรับชื่อต้องมีอย่างน้อย 3 ตัวอักษร',
		'required' => 'จำเป็นต้องใส่ชื่อ',
	) ,
	'contact_subject' => array(
		'length' => 'ช่องสำหรับหัวข้อต้องมีอย่างน้อย 3 ตัวอักษร',
		'required' => 'จำเป็นต้องใส่หัวข้อ',
	) ,
	'email_send' => array(
		'failed' => 'มีข้อผิดพลาดในการส่งข้อความของคุณ',
	) ,
);
