<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-08-24 05:11+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'ศุกร์',
		'full' => 'วันศุกร์',
	) ,
	'monday' => array(
		'abbv' => 'จันทร์',
		'full' => 'วันจันทร์',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'เสาร์',
		'full' => 'วันเสาร์',
	) ,
	'sunday' => array(
		'abbv' => 'อาทิตย์',
		'full' => 'วันอาทิตย์',
	) ,
	'thursday' => array(
		'abbv' => 'พฤหัสบดี',
		'full' => 'วันพฤหัสบดี',
	) ,
	'tuesday' => array(
		'abbv' => 'อังคาร',
		'full' => 'วันอังคาร',
	) ,
	'wednesday' => array(
		'abbv' => 'พุธ',
		'full' => 'วันพุธ',
	) ,
	'january' => array(
		'abbv' => 'ม.ค.',
		'full' => 'มกราคม',
	) ,
	'february' => array(
		'abbv' => 'ก.พ.',
		'full' => 'กุมภาพันธ์',
	) ,
	'march' => array(
		'abbv' => 'มี.ค.',
		'full' => 'มีนาคม',
	) ,
	'april' => array(
		'abbv' => 'เม.ย.',
		'full' => 'เมษายน',
	) ,
	'may' => array(
		'abbv' => 'พ.ค.',
		'full' => 'พฤษภาคม',
	) ,
	'june' => array(
		'abbv' => 'มิ.ย.',
		'full' => 'มิถุนายน',
	) ,
	'july' => array(
		'abbv' => 'ก.ค.',
		'full' => 'กรกฎาคม',
	) ,
	'august' => array(
		'abbv' => 'ส.ค.',
		'full' => 'สิงหาคม',
	) ,
	'september' => array(
		'abbv' => 'ก.ย.',
		'full' => 'กันยายน',
	) ,
	'october' => array(
		'abbv' => 'ต.ค.',
		'full' => 'ตุลาคม',
	) ,
	'november' => array(
		'abbv' => 'พ.ย.',
		'full' => 'พฤศจิกายน',
	) ,
	'december' => array(
		'abbv' => 'ธ.ค.',
		'full' => 'ธันวาคม',
	) ,
);
