<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-03 04:19+0000
$lang = array(
	'parent_id' => array(
		'numeric' => 'ID หลักจะต้องเป็นตัวเลข',
	) ,
	'private_to' => array(
		'required' => 'ต้องป้อนข้อมูลในฟิล์ด To',
		'exists' => 'ผู้ใช้ที่คุณกำลังส่งข้อความถึงไม่ปรากฏชื่อในฐานข้อมูล',
	) ,
	'private_subject' => array(
		'required' => 'ต้องป้อนข้อมูลในฟิล์ดหัวข้อ',
		'length' => 'หัวข้อต้องมีความยาวระหว่าง 3 ตัวอักษร ถึง 150 ตัวอักษร',
	) ,
	'private_message' => array(
		'required' => 'ต้องป้อนข้อมูลในฟิล์ดข้อความ',
	) ,
);
