<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-03 05:12+0000
$lang = array(
	'latitude' => array(
		'between' => 'ช่องละติจูดไม่ปรากฏละติจูดที่ถูกต้อง',
		'required' => 'จำเป็นต้องใส่ละติจูด กรุณาคลิกบนแผนที่เพื่อระบุตำแหน่ง',
	) ,
	'level_id' => array(
		'numeric' => 'ช่องระดับผู้รายงานไม่ปรากฏระดับที่ถูกต้อง',
		'required' => 'ช่องระดับผู้รายงานข่าวไม่ปรากฏระดับที่ถูกต้อง',
	) ,
	'location_name' => array(
		'length' => 'ชื่อที่ตั้งจะต้องมีอย่างน้อย 3 และไม่เกิน 200 ตัวอักษร',
		'required' => 'จำเป็นต้องใส่ชื่อที่ตั้ง',
	) ,
	'longitude' => array(
		'between' => 'ช่องลองจิจูดไม่ปรากฏลองจิจูดที่ถูกต้อง',
		'required' => 'จำเป็นต้องใส่ลองจิจูด กรุณาคลิกบนแผนที่เพื่อระบุตำแหน่ง',
	) ,
	'reporter_id' => array(
		'numeric' => 'ผู้รายงานไม่ถูกต้อง',
		'required' => 'ผู้รายงานไม่ถูกต้อง',
	) ,
);
