<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-09-27 05:34+0000
// PO revision date:  2014-09-03 05:18+0000
$lang = array(
	'incident_id' => array(
		'required' => 'โปรดตรวจสอบว่าคุณได้ทำการเช็ครายการ',
		'numeric' => 'โปรดตรวจสอบว่าคุณได้ทำการเช็ครายการ',
		'categories_required' => 'รายงานต้องมีการจัดหมวดหมู่ก่อนที่จะสามารถได้รับการอนุมัติ',
	) ,
	'action' => array(
		'permission' => 'คุณไม่ได้รับอนุญาตให้ดำเนินการนี้',
	) ,
	'uploadfile' => array(
		'required' => 'คุณต้องเลือกไฟล์ที่จะอัปโหลด',
		'type' => 'อัพโหลดไฟล์ต้องอยู่ในรูปแบบ .csv หรือ .xml ',
		'valid' => 'ช่องอัปโหลดไฟล์มีไฟล์ที่ไม่ถูกต้อง',
	) ,
);
