<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-08-15 04:40+0000
$lang = array(
	'email' => array(
		'email' => 'è,ò,ù,à',
		'exists' => 'è,ò,ù,à',
		'length' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
	) ,
	'name' => array(
		'length' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
		'standard_text' => 'è,ò,ù,à',
	) ,
	'password' => array(
		'length' => 'è,ò,ù,à',
		'matches' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
	) ,
	'password_confirm' => array(
		'matches' => 'è,ò,ù,à',
	) ,
	'resetemail' => array(
		'email' => 'è,ò,ù,à',
		'invalid' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
	) ,
	'roles' => array(
		'alpha_numeric' => 'è,ò,ù,à',
		'length' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
		'values' => 'è,ò,ù,à',
	) ,
	'username' => array(
		'admin' => 'è,ò,ù,à',
		'exists' => 'è,ò,ù,à',
		'length' => 'è,ò,ù,à',
		'required' => 'è,ò,ù,à',
		'superadmin' => 'è,ò,ù,à',
	) ,
);
