<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-22 13:05+0000
$lang = array(
	'date' => 'Date',
	'feed_name' => array(
		'length' => 'Le nom du fil doit comporter entre 3 et 70 caractères.',
		'required' => 'Entrez le nom du fil.',
	) ,
	'feed_url' => array(
		'required' => 'Veuillez entrer l\'URL du fil.',
		'url' => 'Veuillez entrer un URL valide. Ex: http://www.ushahidi.com',
	) ,
	'source' => 'Source',
	'title' => 'Titre',
);
