<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-09-22 14:37+0000
$lang = array(
	'layer_color' => array(
		'length' => 'Le champ de couleur doit être de 6 caractères.',
		'required' => 'Le champ de couleur est nécessaire.',
	) ,
	'layer_file' => array(
		'type' => 'Le champ fichier ne semble pas contenir un fichier valide. Les formats reconnus sont seulement. KMZ et. KML.',
		'valid' => 'Le champ fichier ne semble pas contenir un fichier valide',
	) ,
	'layer_name' => array(
		'length' => 'Le champ nom doit avoir au moins 3 caractères et pas plus de 80 de long.',
		'required' => 'Le champ nom est nécessaire.',
	) ,
	'layer_url' => array(
		'atleast' => 'Entrer KML, URL ou un fichier est nécessaire.',
		'both' => 'Vous ne pouvez pas avoir à la fois un fichier KML et une URL.',
		'url' => 'Veuillez entrer une URL valide, par exemple http://www.ushahidi.com/layerl.kml',
	) ,
);
