<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-11-02 15:04+0000
$lang = array(
	'akismet_cannot_connect' => 'Impossible de se connecter au serveur Akismet.',
	'akismet_cannot_retrieve' => 'La réponse de Akismet n\\\'a pas pu être récupérée.',
	'api_library_not_found' => 'La bibliothèque API : <strong>%s</strong> pour la classe <strong>%s</strong> n\\\'a pu être trouvée. Veuillez vérifier votre tâche API de table de routage.',
	'askimet_invalid_apikey' => 'Votre clé API Akismet n\\\'est pas valide.',
	'clickatell_fopen_error' => 'Erreur lors de l\\\'exécution de la méthode d\\\'envoi fopen!<br> Veuillez vérifier si PHP a le support OpenSSL et si la version de PHP est supérieur à 5.2.',
	'clickatell_message_too_long' => 'Votre message unicode est trop long ! (Longueur actuelle=',
	'clickatell_no_destination_address' => 'Veuillez indiquer une adresse de destination (A)!',
	'clickatell_no_sender_address' => 'Veuillez spécifier l\\\'adresse source (DE)!',
	'clickatell_unicode_message_too_long' => 'Votre message unicode est trop long ! (Longueur actuelle=',
	'clickatell_unsupported_method' => 'Méthode d\\\'envoi non pris en charge !',
	'invalid_api_library' => 'La bibliothèque API %s est invalide. Toutes les bibliothèques d\\\'API doit être sous-classes de %s.',
	'upgrade_directory_not_deleted' => 'Le répertoire <code>%s</coded> ne peut pas être supprimé.',
	'upgrade_extracting_error' => 'Erreur lors de l\\\'extraction : <code>%s</code>',
	'upgrade_failed' => 'Le téléchargement de la dernière version d\\Ushahidi a échoué. Code d\\\'état HTTP',
	'upgrade_file_not_copied' => 'Le fichier <code>%s</coded> n\\\'a pas pu être copié.',
	'upgrade_file_not_deleted' => 'Le fichier <code>%s</coded> ne peut pas être supprimé.',
	'upgrade_title' => 'Script de mise à jour d\\\'Ushahidi',
	'upgrade_zip_error' => 'Le fichier zip téléchargé d\\\'Ushahidi <code>%s</code>, ne peut pas être écrit.',
	'riverid_variable_not_available' => '%s n\\\'est pas disponible dans la classe RiverID.',
);
