<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-09 06:11+0000
// PO revision date:  2012-07-12 21:43+0000
$lang = array(
	'captcha' => array(
		'default' => 'Veuillez taper un code de sécurité valide',
		'required' => 'Veuillez taper le code de sécurité',
	) ,
	'email' => array(
		'email' => 'Adress email invalide',
		'length' => 'L\'adresse email doit comporter entre 4 et 64 caractères.',
		'required' => 'Une adresse email est requise si la case est cochée.',
	) ,
	'message' => array(
		'required' => 'Veuillez entrer un commentaire.',
	) ,
	'name' => array(
		'length' => 'Le nom doit comporter plus de 3 caractères.',
		'required' => 'Veuillez indiquer un nom.',
	) ,
	'phone' => array(
		'length' => 'Numéro de téléphone invalide.',
	) ,
);
