<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2014-02-04 06:25+0000
// PO revision date:  2014-02-03 21:03+0000
$lang = array(
	'reports_view' => 'Voir les rapports',
	'reports_edit' => 'Créer/Modifier/Supprimer des rapports',
	'reports_approve' => 'Approuver les rapports',
	'reports_verify' => 'Vérifier les rapports',
	'reports_comments' => 'Gérer les commentaires des rapports',
	'reports_download' => 'Téléchargez les rapports',
	'reports_upload' => 'Envoyer les rapports',
	'messages' => 'Gérer les messages',
	'messages_reporters' => 'Gérer les messages des reporters',
	'stats' => 'Voir les stats',
	'settings' => 'Modifier les paramètres',
	'manage' => 'Gérer le panel',
	'users' => 'Gérer les utilisateurs',
	'manage_roles' => 'Gérer les rôles',
	'checkin' => 'Pouvez vérifier',
	'checkin_admin' => 'Gérer les vérifications',
	'admin_ui' => 'Accès admin UI',
	'member_ui' => 'Accès membres UI',
	'delete_all_reports' => 'Supprimer tous les rapports',
);
