<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 20:02+0000
$lang = array(
	'config' => 'Konfigurationsfil',
	'controller' => 'Kontroller',
	'driver' => 'Driver',
	'driver_implements' => 'Denne %s driver  til %s biblioteket må implementere %s grænsefladen.',
	'driver_not_found' => '%s driveren til %s biblioteket kunne ikke findes.',
	'errors_disabled' => 'Du kan gå til <a href="%s">hjemmeside</a> eller  <a href="%s">prøv igen</a>.',
	'error_file_line' => '<tt>%s <strong>[%s]:</strong></tt>',
	'generic_error' => 'Kan ikke gennemføre forespørgslen',
	'helper' => 'Hjælper',
	'invalid_filetype' => 'Denne ønskede filtype  .%s er ikke tilladt i din vis konfigurationsfil.',
	'invalid_method' => 'Invalid metode %s med kald i %s',
	'library' => 'bibliotek',
	'view' => 'Kig',
);
