<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 20:11+0000
$lang = array(
	'error' => 'Database fejl: %s',
	'table_not_found' => 'Tabel "%s" kan ikke findes i databasen. Vær sikker på at du bruger den seneste version af databasen for denne version af Ushadidi.',
);
