<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 19:36+0000
$lang = array(
	'am' => 'am',
	'friday' => array(
		'abbv' => 'Fre',
		'full' => 'Fredag',
	) ,
	'monday' => array(
		'abbv' => 'Man',
		'full' => 'Mandag',
	) ,
	'pm' => 'pm',
	'saturday' => array(
		'abbv' => 'Lør',
		'full' => 'Lørdag',
	) ,
	'sunday' => array(
		'abbv' => 'Søn',
		'full' => 'Søndag',
	) ,
	'thursday' => array(
		'abbv' => 'Tor',
		'full' => 'Torsdag',
	) ,
	'tuesday' => array(
		'abbv' => 'Tir',
		'full' => 'Tirsdag',
	) ,
	'wednesday' => array(
		'abbv' => 'Ons',
		'full' => 'Onsdag',
	) ,
	'january' => array(
		'abbv' => 'Jan',
		'full' => 'Januar',
	) ,
	'february' => array(
		'abbv' => 'Feb',
		'full' => 'Februar',
	) ,
	'march' => array(
		'abbv' => 'Mar',
		'full' => 'Marts',
	) ,
	'april' => array(
		'abbv' => 'Apr',
		'full' => 'April',
	) ,
	'may' => array(
		'abbv' => 'Maj',
		'full' => 'Maj',
	) ,
	'june' => array(
		'abbv' => 'Jun',
		'full' => 'Juni',
	) ,
	'july' => array(
		'abbv' => 'Jul',
		'full' => 'Juli',
	) ,
	'august' => array(
		'abbv' => 'Aug',
		'full' => 'August',
	) ,
	'september' => array(
		'abbv' => 'Sep',
		'full' => 'September',
	) ,
	'october' => array(
		'abbv' => 'Okt',
		'full' => 'Oktober',
	) ,
	'november' => array(
		'abbv' => 'Nov',
		'full' => 'November',
	) ,
	'december' => array(
		'abbv' => 'Dec',
		'full' => 'December',
	) ,
);
