<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 14:41+0000
$lang = array(
	'incident_id' => array(
		'required' => 'Verificere lige om du har afkrydset en post',
	) ,
	'action' => array(
		'permission' => 'Du har ikke tilladelse til at udføre denne handling',
	) ,
	'uploadfile' => array(
		'required' => 'Du skal vælge en fil for at oploade',
		'type' => 'En fil skal være af typen .csv eller .xml format for at kunne oploades.',
		'valid' => 'Fil-oploadet feltet ser ikke ud til at indeholde en valid fil',
	) ,
);
