<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 14:54+0000
$lang = array(
	'approved' => 'Godkendt',
	'categories' => 'Kategorier',
	'countries' => 'Lande',
	'country' => 'Land',
	'error' => 'Fejl',
	'pageviews' => 'Sidevisninger',
	'reports' => 'Rapporter',
	'reports_categories' => 'Rapport kategorier',
	'time_range_1' => '1 måned',
	'time_range_2' => '3 måneder',
	'time_range_3' => '6 måneder',
	'time_range_all' => 'Alle',
	'visits' => 'Antal besøg',
);
