<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-06-28 06:21+0000
// PO revision date:  2013-06-27 20:26+0000
$lang = array(
	'upgrade' => array(
		'between' => 'Ugyldig input data. Det kan kun være et 0 for Nej eller 1 for Ja.',
	) ,
	'upgrade_automatic' => 'Automatisk opgradering',
	'upgrade_available' => 'Tilgængelige opdateringer',
	'upgrade_continue_btn_text' => 'Fortsæt',
	'upgrade_db_btn_text' => 'Opgrader',
	'upgrade_db_text_1' => 'Så jeg vil nu opgradere din database fra version',
	'upgrade_db_text_2' => 'til den nyeste database version',
	'upgrade_db_text_3' => 'Klik på "Opgrader" knappen og slap helt roligt af mens jeg laver lidt magi.',
	'upgrade_manual' => 'Manuelt opgradering',
	'upgrade_ftp_username' => 'FTP brugernavn:',
	'upgrade_status_info' => 'Du har den seneste udgave af Ushahidi.',
	'upgrade_status_info_2' => 'Du behøver ikke at opgradere.',
	'upgrade_db_version' => 'Database version: %d',
	'upgrade_database' => 'Database:',
	'ushahidi_release_version' => 'Ushahidi %s',
	'beta' => 'BETA!',
	'download' => 'Downloader den seneste version af Ushahidi...',
	'log_file' => 'Logfil',
	'failed_downloading' => 'Mislykket downloading.',
	'failed_unpacking' => 'Mislykket udpakning.',
	'backup_failed' => 'Mislykket backup af database.',
	'dbupgrade_success' => 'Succes med database opgraderingen. ',
	'deleting_files' => 'Sletter downloades filer...',
);
